### ISSUE TITLE
plugin does not work at all

### ISSUE THREAD

**Issue by marianney** [stcr/subscribe-to-comments-reloaded#101]
Hi I had 'Send email only on Reply to My Comment' by Yasir installed originally and could not get it to work. Then I deactivated it and installed 'Subscribe to Comments Reloaded.' To my surprise, it saved all my users who are all activated for comments with a 'Y'. 

I cannot get either plugin to work. When I leave a test comment, i never get an email to confirm subscription. When I click to manage subscriptions, I then do get an email, but when i click the link, the page is blank with your plugin. With the other plugin, I at least get a page with a form.

My permalink is correct as i am able to fill in my email address and receive the email to go manage. 

When I reply to my test comment, I do not get any notifications either. I have tried to read through the support, but either the answers don't make any sense to me ( i am not a developer) or they don't work. 

Please help! I'm about to just install Disqus and i hate Disqus but I don't know what else to do. :(

**Comment by Reedyseth** [comment]
Hello @marianney ,

The last update came with a few bugs that unfortunately I haven'b been able to fix because of my schedule.

Just to start. Can you share the URL of your page?

**Comment by marianney** [comment]
Thank you for replying so quickly despite your schedule, I know how it is. 

Here is my last comment: http://designyourownblog.com/blog-design/learn-easy-html-code-css/how-to-edit-css-in-your-blog/ 

And the manage page is here: http://designyourownblog.com/uncategorized/comment-subscriptions

I did delete the other plugin and it seemed to help a little, however on my manage page, I can't change the action. It defaults to "suspend" but they still all say Y even if i try to change to R. 

I am still not receiving emails.

**Comment by Reedyseth** [comment]
@marianney I don't see the plugin enable, only the mailchimp form. if you have access to your FTP files please install the version 150207 version.

1. Download the version 150207 from here https://downloads.wordpress.org/plugin/subscribe-to-comments-reloaded.150207.zip
2. Deactivate the StCR plugin.
3. Upload the downloaded plugin.
4. Activate the plugin.

Post the results.

**Comment by Reedyseth** [comment]
This temporal solution is until I get the bugs on the latest version fix.

**Comment by marianney** [comment]
Thank you so much!  And i'm sorry, i did accidentally forget to reactivate the plugin yesterday which is why you did not see it. I have installed the zip file and am testing it now.

**Comment by marianney** [comment]
It works!! Thanks so much for your help. I appreciate your time even though you're very busy. I will be adding this to my recommended plugins post/ebook i'm writing. :)

**Comment by Reedyseth** [comment]
> It works!! Thanks so much for your help.

Cool, thank you for the confirmation.
