### ISSUE TITLE
Can't Manage subscription

### ISSUE THREAD

**Issue by Reedyseth** [stcr/subscribe-to-comments-reloaded#102]
Referencing this issue on WP https://wordpress.org/support/topic/cant-unsubscribe-from-comments?replies=13#post-7059497.

Created by @Adrienne

I have a commenter who is complaining that she can't unscubscribe from the comments.

This is her complaint:

"I've tried three times now to stop the email notifications but can't. I am directed to a page that says Manager Subscriptions. After I fill out my name, it sends me to a page where I can update my subscriptions, but when it processes it, I'm sent back to the original page, and the darn process keeps looping, without ever unsubscribing me from the comments."

I literally gets 100's of comments on my posts so she's getting really frustrated that she can't unsubscribe. I have your latest version so everything is updated. Can you help us resolve this before I lose a trusted commenter?

Thank you,

Adrienne

**Comment by Reedyseth** [comment]
The SRE key was not the same as the one generated by the manage page, see https://github.com/stcr/subscribe-to-comments-reloaded/blob/150422/subscribe-to-comments-reloaded/subscribe-to-comments-reloaded.php#L498

**Comment by Reedyseth** [comment]
The fix of this bug is here ba7cdc92394cd29401e718622fcff5a17f1d3879

**Comment by lucashall** [comment]
Hi there,

I'm not sure if this is related, but here we go:

When my subscribers click on unsubscribe, they get taken to a page that says "You have requested to manage your subscriptions to the articles on Landlordology. Follow this link to access your personal page:"  ... except there is no link to the personal page, and no way to manage subscriptions.

However, when I (logged in as an WP Admin) click on the same unsubscribe link (from their email that they forwarded), I'm able to manage their subscription.  I've noticed that I will get the same error if I'm not logged in to wordpress, or try to open it in a private/incognito window.

A sample link that produces this error is: https://www.landlordology.com/comment-subscriptions/?sre=1ab66452ab55a80a83c934dcac74a947&srk=1a89255e2456d032af255a6fe667b69b?utm_source=notifications&utm_medium=subscription-emails&utm_campaign=unsubscribe

Here's a screenshot: 
![image](https://cloud.githubusercontent.com/assets/6332983/8315464/cd8e1e9e-19a5-11e5-8a67-0c9f0cb6e71b.jpg)

I'm using plugin version 150611, and WP version 4.1.5
