### ISSUE TITLE
Bug Report: Users can't unsubscribe

### ISSUE THREAD

**Issue by timpritlove** [stcr/subscribe-to-comments-reloaded#104]
I am using (always) the latest version of Subscribe To Comments Reloaded and my users regularly report that they can't unsubscribe from the comment stream.

The user interface provides no helpful feedback. It all looks as if the user was taken from the list but the comments keep coming.

Manually removing the user from the list in the backend works without problem.

Any hint on what to look at what could cause this problem?

**Comment by Reedyseth** [comment]
Hey @timpritlove thank you for reporting it. I just answer in the WordPress support page. This here will be much better.

To me it looks like that there is an error trigger on the background but not display. If you could get the error from the php error file on your host it would be very helpful.

Also to mention an upcoming feature that will allow the users to unsubscribe with one click.

**Comment by timpritlove** [comment]
Indeed: there is something to be found. I include all error messages that directly relate to a single email address (which I have anonymized):

```
[Mon Jun 22 09:16:24.099497 2015] [:error] [pid 27704] [client 31.25.121.188:65459] WordPress-Datenbank-Fehler Table 'db_4567_2_jjt.wp_5_subscribe_reloaded_subscribers' doesn't exist f\xc3\xbcr Abfrage SELECT salt, subscriber_unique_id FROM wp_5_subscribe_reloaded_subscribers WHERE subscriber_email = 'foo@bar.com' von wp_new_comment, do_action('comment_post'), call_user_func_array, wp_subscribe_reloaded->new_comment_posted, wp_subscribe_reloaded->notify_user, wp_subscribe_reloaded->get_subscriber_key, referer: http://freakshow.fm/fs156-grosses-loch-alleine-reicht-nicht
[Mon Jun 22 10:37:04.479767 2015] [:error] [pid 38246] [client 62.30.150.238:56597] WordPress-Datenbank-Fehler Table 'db_4567_2_jjt.wp_5_subscribe_reloaded_subscribers' doesn't exist f\xc3\xbcr Abfrage SELECT salt, subscriber_unique_id FROM wp_5_subscribe_reloaded_subscribers WHERE subscriber_email = 'foo@bar.com' von do_action('wp_ajax_dim-comment'), call_user_func_array, wp_ajax_dim_comment, wp_set_comment_status, do_action('wp_set_comment_status'), call_user_func_array, wp_subscribe_reloaded->comment_status_changed, wp_subscribe_reloaded->notify_user, wp_subscribe_reloaded->get_subscriber_key, referer: http://freakshow.fm/wp-admin/edit-comments.php?p=8833&approved=1
[Mon Jun 22 12:01:53.745479 2015] [:error] [pid 49535] [client 62.30.150.238:59032] WordPress-Datenbank-Fehler Table 'db_4567_2_jjt.wp_5_subscribe_reloaded_subscribers' doesn't exist f\xc3\xbcr Abfrage SELECT salt, subscriber_unique_id FROM wp_5_subscribe_reloaded_subscribers WHERE subscriber_email = 'foo@bar.com' von do_action('wp_ajax_replyto-comment'), call_user_func_array, wp_ajax_replyto_comment, wp_new_comment, do_action('comment_post'), call_user_func_array, wp_subscribe_reloaded->new_comment_posted, wp_subscribe_reloaded->notify_user, wp_subscribe_reloaded->get_subscriber_key, referer: http://freakshow.fm/wp-admin/edit-comments.php?p=8833&approved=1
[Mon Jun 22 13:15:58.680889 2015] [:error] [pid 58973] [client 2001:4dd0:ff00:9656:8904:98b1:6a19:336a:65484] WordPress-Datenbank-Fehler Table 'db_4567_2_jjt.wp_5_subscribe_reloaded_subscribers' doesn't exist f\xc3\xbcr Abfrage SELECT salt, subscriber_unique_id FROM wp_5_subscribe_reloaded_subscribers WHERE subscriber_email = 'foo@bar.com' von wp_new_comment, do_action('comment_post'), call_user_func_array, wp_subscribe_reloaded->new_comment_posted, wp_subscribe_reloaded->notify_user, wp_subscribe_reloaded->get_subscriber_key, referer: http://freakshow.fm/fs156-grosses-loch-alleine-reicht-nicht
[Mon Jun 22 17:22:54.740485 2015] [:error] [pid 91031] [client 89.144.207.161:65114] WordPress-Datenbank-Fehler Table 'db_4567_2_jjt.wp_5_subscribe_reloaded_subscribers' doesn't exist f\xc3\xbcr Abfrage SELECT salt, subscriber_unique_id FROM wp_5_subscribe_reloaded_subscribers WHERE subscriber_email = 'foo@bar.com' von wp_new_comment, do_action('comment_post'), call_user_func_array, wp_subscribe_reloaded->new_comment_posted, wp_subscribe_reloaded->notify_user, wp_subscribe_reloaded->get_subscriber_key, referer: http://freakshow.fm/fs156-grosses-loch-alleine-reicht-nicht
[Mon Jun 22 18:07:10.239547 2015] [:error] [pid 97004] [client 84.114.142.63:46725] WordPress-Datenbank-Fehler Table 'db_4567_2_jjt.wp_5_subscribe_reloaded_subscribers' doesn't exist f\xc3\xbcr Abfrage SELECT salt, subscriber_unique_id FROM wp_5_subscribe_reloaded_subscribers WHERE subscriber_email = 'foo@bar.com' von wp_new_comment, do_action('comment_post'), call_user_func_array, wp_subscribe_reloaded->new_comment_posted, wp_subscribe_reloaded->notify_user, wp_subscribe_reloaded->get_subscriber_key, referer: http://freakshow.fm/fs156-grosses-loch-alleine-reicht-nicht
```

This looks like an incompatibility with WordPress multisite installations. The plugin is looking for the blog-local table `wp_5_subscribe_reloaded_subscribers` but in the database there is only a global `wp_subscribe_reloaded_subscribers` table to be found.

Is the plugin expected to work with Multisite installations at all?

**Comment by Reedyseth** [comment]
@timpritlove 
> Is the plugin expected to work with Multisite installations at all?

Yes, but for this particular error I haven't noticed. Bug added to the fix list.

**Comment by timpritlove** [comment]
Any news on this?

**Comment by Reedyseth** [comment]
Hello @timpritlove still on the list to be fix but not forgotten. I will post anything new here. Regards.

**Comment by timpritlove** [comment]
Another three months have passed and I still have to deal with frustrated users on a daily basis because of this issue. Anything you can share about your progress in this regard?

Maybe there is some kind of workaround by pruning tables or something? I am open for any recommendation.

**Comment by timpritlove** [comment]
If there won't be a fix for this, is there at least a workaround? Maybe it's all related to a corrupted database and purging them might help (even when I lose all current subscriptions)? Is there a defined way to reset the system, which database tables need to be dropped?

**Comment by Reedyseth** [comment]
Hello @timpritlove ,

I apologize for the long and delay response. I created my multisite installation and tested everything with the latest development code and everything is working like a charm. There were so many bugs and fixes including the ones on this issue. Basically there were hard code and also some function callings with error. I will be releasing the plugin update in  a couple of days and I hope you enjoy the update.

Regards.!!
