### ISSUE TITLE
Solution to solve Virtual Management Page not updating subscriptions

### ISSUE THREAD

**Issue by blitzter47** [stcr/subscribe-to-comments-reloaded#106]
Hello,
I found a little code correction making the Virtual Management Page to update successfully subscriptions after form submission. (I use Chromium 42.0.2311.90 and Firefox 38.0 in Ubuntu) It looks like the browsers interprete correctly the double-quote mark followed by a slash while there's a space between them, before the ending \</p\>, as the corrected code shown below :

For templates/user.php

line 76 : . '" /\>\<input type="hidden" name="sre" value="' . $wp_subscribe_reloaded-\>get_subscriber_key( $email ) . '" /\>\</p\>';

---------------------------------------------------
and for templates/author.php

line 77 : echo '\<p id="subscribe-reloaded-update-p"\>\<input type="submit" class="subscribe-form-button" value="' . __( 'Update subscriptions', 'subscribe-reloaded' ) . '" /\>\<input type="hidden" name="srp" value="' . intval( $post_ID ) . '" /\>\</p\>';

**Comment by Reedyseth** [comment]
@blitzter47 The slash and the end of the input it is correct when using a XHTML format, so for modern browsers that is no needed so I will get rid of the slash at the end of both inputs.

**Comment by Reedyseth** [comment]
Issue solve on commit 03fa053b4389e033137d64bc7f2c463cf99825c4.
