### ISSUE TITLE
New german translation file

### ISSUE THREAD

**Issue by maffi91** [stcr/subscribe-to-comments-reloaded#114]
Hello,

here is a better / correct german translation file :)

Download: http://www.maffert.net/subscribe-reloaded-de_DE.po

I fix this parts:

http://pastebin.com/LVLseYm5

**Comment by konus1** [comment]
Thank you. I used this as starting point for my german translation and added some more to it.
The only term, I did not use was your "Benachrichtigungseinstellungen" instead of "Benachrichtigungs Einstellungen"
The translation is now pull request #135 and I think, this issue can be closed.

**Comment by Reedyseth** [comment]
Thank you both for your contribution, I am going to merge the pull request in a different branch, but more comments on #135
