### ISSUE TITLE
Reedy's Instructions - How do I execute?

### ISSUE THREAD

**Issue by WitBlade** [stcr/subscribe-to-comments-reloaded#115]
Hey Reedy,

About a month ago you gave me some instructions but I missed them. I apologize. Can you tell me how to execute this:

'Deactivate the plugin and the run this query:

DELETE FROM wp_options WHERE option_name = 'subscribe_reloaded_data_sanitized';

Then Activate the plugin.

Just make sure that the prefix of your table is the one define on you wp-config.php file. If you did not change it then this will delete that option and the on the activation routine it will clean your StCR option of the database.'

**Comment by Reedyseth** [comment]
Hello @WitBlade,

These instrunctions are for cleaning up your database values.

Basically you run/execute this database query on your phpMyadmin or if you can connect to your database directly you run this query.

This will delete this option and then when you activate the plugin it will search for it, since it will not be available it will execute the sanitize routine and the you should have your options clean and you should be able to see the information correctly instead of html code.

**Comment by WitBlade** [comment]
I see - I am not familiar enough with phpMyadmin but I will see if I can figure it out.
Thanks

**Comment by Reedyseth** [comment]
Let get an screenshot for you, a little bit with support but I will get them.

**Comment by Reedyseth** [comment]
@WitBlade I have written a small wiki on this as I mentioned.

https://github.com/stcr/subscribe-to-comments-reloaded/wiki/Helpful-Wikis#Query-phpMyadmin

Regards.!!

**Comment by WitBlade** [comment]
Hello Reedy,

I implemented your instructions but it did not work. When I reactivated the plugin, it said it "had been sanitized to prevent the raw html from showing" but every post still has this showing through.

The DB query ran successfully. Anything that I may have done wrong?

**Comment by Reedyseth** [comment]
Can you share  a screenshot of you website or the URL. ?

**Comment by WitBlade** [comment]
URL: example:
http://alphadark.com/3-month-keyboard-challenge-month-1-pain-gain/

screenshot:

​

On Tue, Aug 4, 2015 at 1:00 PM, Israel Barragan C. <notifications@github.com
> wrote:

> Can you share a screenshot of you website or the URL. ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/stcr/subscribe-to-comments-reloaded/issues/115#issuecomment-127676223>
> .
>



-- 
Ryan Rodden
WitBlade LLC <http://witblade.com>
215-272-0348

**Comment by Reedyseth** [comment]
Can you create a temporary account so that I can dig on the plugin settings ?

use my email [reedyseth] [at] [gmail] [dot] [com]

**Comment by WitBlade** [comment]
Added - please let me know if you have any questions. my skype is rrodden_

On Tue, Aug 4, 2015 at 1:08 PM, Israel Barragan C. <notifications@github.com
> wrote:

> Can you create a temporary account so that I can dig on the plugin
> settings ?
>
> use my email [reedyseth] [at] [gmail] [dot] [com]
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/stcr/subscribe-to-comments-reloaded/issues/115#issuecomment-127677769>
> .
>



-- 
Ryan Rodden
WitBlade LLC <http://witblade.com>
215-272-0348

**Comment by Reedyseth** [comment]
Thanks, I logged in.

**Comment by Reedyseth** [comment]
OK, is done. I had click on the save options for every panel. Now is working. The weird thing is that the previous steps didn't work. There was an issue migrating from the previous version of the plugin into this. I guess your information of the database got stuck on that migration. You can go ahead and delete the WordPress account that you created

**Comment by WitBlade** [comment]
I see - well thanks for the great support. Hopefully if there is another
plugin update, this sticks.

On Tue, Aug 4, 2015 at 1:19 PM, Israel Barragan C. <notifications@github.com
> wrote:

> OK, is done. I had click on the save options for every panel. Now is
> working. The weird thing is that the previous steps didn't work. There was
> an issue migrating from the previous version of the plugin into this. I
> guess your information of the database got stuck on that migration. You can
> go ahead and delete the WordPress account that you created
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/stcr/subscribe-to-comments-reloaded/issues/115#issuecomment-127681922>
> .
>



-- 
Ryan Rodden
WitBlade LLC <http://witblade.com>
215-272-0348

**Comment by Reedyseth** [comment]
> Hopefully if there is another
> plugin update, this sticks.

It will, the next update will be much better. I have been developing many changes, if you feeling that you want to test the code I can share you the instructions.
