### ISSUE TITLE
Bug Report: <short description>

### ISSUE THREAD

**Issue by reszko** [stcr/subscribe-to-comments-reloaded#116]
Hi. When I answer a comment I receive in my email the notification of my answer together with the original comment.

I am receiving 3 messages.

1) When the visitor make a comment.
2) When I answer that comment.  Twice.

In plugin configurations page all settings seen to be correct configured. 

How can I solve this?

Thank you.

**Comment by Reedyseth** [comment]
@reszko 

This 3 messages are from StCR? I mean the same format? or also WordPress messages.

Usually on my blog when I am subscribe to the post I get the WordPress email to authorize the comment and then when I reply to that comment I get the email from StCR, can you check that your email address is not duplicated in the subscription list?

**Comment by reszko** [comment]
The first message is a StCR notifying me that a new comment was posted
Then, I answer that comment and the answer goes to me twice, with the same hour.
In the print screen attached you can see it.

9:39: Notification of a new comment
Then I go to wordpress and answer the comment
Then I receive two messages with same content at 10:47.

![print subscribe to comments](https://cloud.githubusercontent.com/assets/9325441/9115464/a2d907c4-3c35-11e5-8ccf-ea5760fee4cd.jpg)

**Comment by Reedyseth** [comment]
> 9:39: Notification of a new comment
> Then I go to wordpress and answer the comment

OK, this email is sent by WordPress.

Did you check your email on the subscriptions page to make sure that your email is not twice?

**Comment by reszko** [comment]
I went to subcriptions page and I saw my administrator email in 3 posts. I
will test now and check if the problems is solved.

All this happened after I have desinstalled the plugin and some days after
I reinstalled it again, then always when I answear a comment, I receive the
answer too.

But let's wait and see if the problem is fixed now that I removed my
adminstration email from subcriptions page. But I really don't know why
that email was there.

Thank you.
Fabio

2015-08-06 12:57 GMT-03:00 Israel Barragan C. <notifications@github.com>:

> 9:39: Notification of a new comment
> Then I go to wordpress and answer the comment
>
> OK, this email is sent by WordPress.
>
> Did you check your email on the subscriptions page to make sure that your
> email is not twice?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/stcr/subscribe-to-comments-reloaded/issues/116#issuecomment-128417921>
> .
>



-- 
*Desenvolvedor WEB? Então:*
www.dicascodeigniter.com.br

**Comment by Reedyseth** [comment]
> But I really don't know why
> that email was there.

@reszko Perhaps in on time you had the option `Subscribe authors` enable and this will subscribe you automatically.

![image](https://cloud.githubusercontent.com/assets/1228711/9116891/ff60a572-3c23-11e5-8b65-c5c593aff68f.png)

**Comment by reszko** [comment]
You were correct. That option was checked to Yes.

Thank you.

2015-08-06 13:15 GMT-03:00 Israel Barragan C. <notifications@github.com>:

> But I really don't know why
> that email was there.
>
> @reszko <https://github.com/reszko> Perhaps in on time you had the option Subscribe
> authors enable and this will subscribe you automatically.
>
> [image: image]
> <https://cloud.githubusercontent.com/assets/1228711/9116891/ff60a572-3c23-11e5-8b65-c5c593aff68f.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/stcr/subscribe-to-comments-reloaded/issues/116#issuecomment-128424139>
> .
>



-- 
*Desenvolvedor WEB? Então:*
www.dicascodeigniter.com.br

**Comment by Reedyseth** [comment]
Great to see that the issue is solve.

Regards.!!

On Thu, Aug 6, 2015 at 10:21 AM, Fábio S. Reszko <notifications@github.com>
wrote:

> You were correct. That option was checked to Yes.
>
> Thank you.
>
> 2015-08-06 13:15 GMT-03:00 Israel Barragan C. <notifications@github.com>:
>
> > But I really don't know why
> > that email was there.
> >
> > @reszko <https://github.com/reszko> Perhaps in on time you had the
> option Subscribe
> > authors enable and this will subscribe you automatically.
> >
> > [image: image]
> > <
> https://cloud.githubusercontent.com/assets/1228711/9116891/ff60a572-3c23-11e5-8b65-c5c593aff68f.png
> >
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/stcr/subscribe-to-comments-reloaded/issues/116#issuecomment-128424139
> >
> > .
> >
>
>
>
> --
> *Desenvolvedor WEB? Então:*
> www.dicascodeigniter.com.br
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/stcr/subscribe-to-comments-reloaded/issues/116#issuecomment-128425485>
> .
>



-- 

*Ing. Israel Barragán Castillo*Software Developer Department
Datasoft Engineering
Cel. +52(614) 345-5651
Web: www.datasoftengineering.com
Email: ibarragan@behstant.com
