### ISSUE TITLE
Feature: Checkbox before submit button

### ISSUE THREAD

**Issue by Reedyseth** [stcr/subscribe-to-comments-reloaded#118]
Feature reported here https://wordpress.org/support/topic/new-farsi-persian-translation-is-ready-but-it-does-not-work?replies=5 by @javad2625

Hello
OK, I signed up in Github.com, and clicked on "New Issue". Then I explained this ticket over there. I hope I have done it rightly. I am looking forward to enjoying the Persian translation. My second problem is the all-time problem of all subscription plugins. Every subscription plugin has this main issue: the checkbox should be shown above "submit" button, but it is shown below submit button. I have tested Mailpoet, Subscribe To Comments", and "Subscribe To Comments Reloaded". All of them have this same problem. I wonder why the checkbox should be below "submit" button. the "Submit" button ought to be the last element in the form, or some persons won't see it, particularly if, like myself, they are blind and they use screen reader for reading the screen. "Subscribe 2" has the option to take this checkbox above submit button, but the option does not work in my theme. Even the checkbox itself is not shown in my theme (Travelify), when I use Subscribe2, unless I manipulate the theme manually. I hope there is a workaround for STCR.

**Comment by konus1** [comment]
I agree, that the checkbox should be above the submit button.
An example how it could be done is in plugin  https://wordpress.org/plugins/mailchimp-for-wp/

**Comment by Reedyseth** [comment]
I am already working on this, I am deciding if I will do that on the side part with Javascript or doing it on the backend part with WordPress Filters.

**Comment by Reedyseth** [comment]
This commit 6a157fdeb81e322249831490bd2d17fd096e12a3 complete this requirement, although there is more to add into this feature because some user would like to have the submit button below the subscription box. You can download the latest code and test it.

**Comment by IvanRF** [comment]
> I am already working on this, I am deciding if I will do that on the side part with Javascript or doing it on the backend part with WordPress Filters.

I'm sorry I'm late on this, but I think filters are better. The javascript is executed after the page is loaded (when ready), so it could be weird for the user if it sees a checkbox appearing.

I don't know which filter WordPress provides, but is better to insert the code before loading the page.

**Comment by Reedyseth** [comment]
> I'm sorry I'm late on this, but I think filters are better. The javascript is executed after the page is loaded (when ready), so it could be weird for the user if it sees a checkbox appearing.
> 
> I don't know which filter WordPress provides, but is better to insert the code before loading the page.

I was aware of this, I tried to use filters but as for another issue regarding JetPack using iframes it  will clash, to prevent the users to see the checkbox there is a CSS class that hide the checkbox form before it execute Javascript. This will work until I discover the filters way.

**Comment by konus1** [comment]
I don't know if this change of Wordpress 4.4 comments will affect the new layout. 
http://wptavern.com/wordpress-4-4-to-possibly-rearrange-fields-to-the-comment-form

**Comment by Reedyseth** [comment]
> I don't know if this change of Wordpress 4.4 comments will affect the new layout. 
> http://wptavern.com/wordpress-4-4-to-possibly-rearrange-fields-to-the-comment-form

Since this issue #118 current change is perform on the client side with jQuery this will not affect, although I am going to be aware of this since the plan is to switch from jQuery to WordPress filters. Thank you for the note.

**Comment by Reedyseth** [comment]
This commit https://github.com/stcr/subscribe-to-comments-reloaded/commit/51dee2e50370d53aef1bc9ae89d2b69895cf526e complete the request about the Checkbox position.

As for the issue I will close it and then merge this changes with the master branch once is fully tested by the community.
