### ISSUE TITLE
Date i18n

### ISSUE THREAD

**Issue by IvanRF** [stcr/subscribe-to-comments-reloaded#119]
Great plugin!
I found that in the "Manage subscriptions" page the date is not showing with i18n.
I think this is located in templates/user.php, line 63.
`$a_subscription->dt` should be using `date_i18n()`

**Comment by IvanRF** [comment]
An opinion about that page: I think the status for each post should be explicit. The first time I saw that page, (in a quick look) I found difficult to understand why there was a 'Y' or 'R' and then I saw the Legend.
Maybe for an end user, it is easier if the actual status 'All comments' or 'Replies only' is written there.

**Comment by Reedyseth** [comment]
> ) I found difficult to understand why there was a 'Y' or 'R' and then I saw the Legend.
> Maybe for an end user, it is easier if the actual status 'All comments' or 'Replies only' is written there.

Yes to me that sounds also better and it will change in a future release. 

> I found that in the "Manage subscriptions" page the date is not showing with i18n.
> I think this is located in templates/user.php, line 63.
> $a_subscription->dt should be using date_i18n()

I will take a look on this. Thank you for reporting.

**Comment by IvanRF** [comment]
I sent the fix for the date. If you prefer another formatting, here is the [documentation](https://codex.wordpress.org/Formatting_Date_and_Time).

**Comment by Reedyseth** [comment]
Another user mention the possibility to remove the date from the Management Page. How relevant is the day for you ?

**Comment by IvanRF** [comment]
Maybe when you have several subscriptions, the first data to show should be the name of the post. Then, 'All comments' or 'Replies only'. As I said, I found difficult to understand why there was a 'Y' or 'R' and I prefer to remove the Legend.

The date could be at the end or could be removed.

I searched for examples. This is how CNET shows subscriptions:
![23-9-2015 5-21-36 p- m-](https://cloud.githubusercontent.com/assets/6751650/10057728/184262c8-6218-11e5-9db1-a81bbf375c95.png)

**Comment by Reedyseth** [comment]
> As I said, I found difficult to understand why there was a 'Y' or 'R' and I prefer to remove the Legend.

Agree, This has no change on the Upcoming releases.

**Comment by IvanRF** [comment]
Regarding the user page, I think it would be better to remove the actions Suspend and Activate, and I would avoid having to select an action and then press the update button.

Like CNET, it's better to have directly a button with the action. In our case,
- Unsubscribe
- Subscribe
- Subscribe only to replies

**Comment by IvanRF** [comment]
So, the user only selects posts and press the button with the action he prefers

**Comment by Reedyseth** [comment]
I have unify both request into one ticket, I will be using that for further actions like commits, etc.

See #142.

**Comment by Reedyseth** [comment]
Request merged https://github.com/stcr/subscribe-to-comments-reloaded/commit/b07198380a133c36697b0d6348ede01b3116ea98
