### ISSUE TITLE
Mail messages localization

### ISSUE THREAD

**Issue by IvanRF** [stcr/subscribe-to-comments-reloaded#120]
I was able to use this plugin with multiple languages in the frontend by using WPML. However, the language used in a mail message is always the same, it is equal to the language set in WordPress.

Is there any way to make the language for the mail equal to the language from the post associated to the comment/email?

If I change WordPress language, mail messages are correctly localized in that language. So, I think it will be easy to implement this feature. It only needs to get the language from the post instead than from WordPress.

**Comment by IvanRF** [comment]
I have developed the solution for this issue. Which branch should I fork? master or pre_release?

**Comment by Reedyseth** [comment]
@IvanRF use the pre_release branch, since the newer code is there. Thank you for dropping some lines of code :)

**Comment by IvanRF** [comment]
notify_user() is now called confirmation_email()?

**Comment by Reedyseth** [comment]
> notify_user() is now called confirmation_email()?

No, the function has not change the name.

**Comment by IvanRF** [comment]
I couldn't find the function, it was in wp_subscribe_reloaded.php :)

**Comment by IvanRF** [comment]
I just pull the changes. I added support for WPML in notify_user(), but I don't know if the send more mails. Maybe confirmation_email()?
If you use get_option() for the content of other mails, you need to add my code in those functions too.
I debug it and WPML uses the default language in get_option(), that's why a call to $sitepress->switch_lang($language); is needed before the calls to get_option().

**Comment by IvanRF** [comment]
I tested my changes with English and Spanish and works fine.
I also added `subscribe_reloaded_from_name` and `subscribe_reloaded_manager_page` to `wpml-config.xml`, since names may differ (like mine Ivan / Iván) and pages too (/en/comment-subscriptions/ or /es/comment-subscriptions/).

**Comment by Reedyseth** [comment]
> I tested my changes with English and Spanish and works fine.
> I also added subscribe_reloaded_from_name and subscribe_reloaded_manager_page to wpml-config.xml, since names may differ (like mine Ivan / Iván) and pages too (/en/comment-subscriptions/ or /es/comment-subscriptions/).

Cool, let me look at the changes.

**Comment by IvanRF** [comment]
I just found that `subscribe_reloaded_manager_page` is not working

**Comment by IvanRF** [comment]
The translation for the mail works. However, only the link in options `/en/comment-subscriptions/` is showing a page. `/es/comment-subscriptions/` is returning a 404 error.

**Comment by Reedyseth** [comment]
> The translation for the mail works. However, only the link in options /en/comment-subscriptions/ is showing a page. /es/comment-subscriptions/ is returning a 404 error.

This is because the Management Page is bind to a single URL which you define on the options.

**Comment by IvanRF** [comment]
I'm closing this, we continue here [#133](https://github.com/stcr/subscribe-to-comments-reloaded/issues/133).
