### ISSUE TITLE
Subscribe Authors doesn't work with custom post types

### ISSUE THREAD

**Issue by nedkeller** [stcr/subscribe-to-comments-reloaded#126]
Selecting the option Subscribe Owners is working fine with regular old posts, but doesn't seem to send comment notifications to authors of custom post types.

**Comment by Reedyseth** [comment]
Hello @nedkeller This was reported before, for now StCR is not validating the Post Type and this will be a feature in one of the incoming updates,thank you for reporting it.

**Comment by nedkeller** [comment]
Thanks for the quick reply. For now, I've fixed the problem by adding a line to the code.

after this line (line 166 in Version 150820):
 add_action( 'publish_post', array( &$this, 'subscribe_post_author' ) );
I have added this line:
add_action( 'publish_mycustomposttype', array( &$this, 'subscribe_post_author' ) );

Obviously, this will break as soon as you update the  plugin, but it's working for now.

**Comment by Reedyseth** [comment]
> after this line (line 166 in Version 150820):
> add_action( 'publish_post', array( &$this, 'subscribe_post_author' ) );
> I have added this line:
> add_action( 'publish_mycustomposttype', array( &$this, 'subscribe_post_author' ) );

@nedkeller Correct, What I would do is to retrieve a list of custom post types and hook the subscribe_post_author.

**Comment by nedkeller** [comment]
Thanks for the suggestion. I'll look into that.

**Comment by nedkeller** [comment]
Instead of adding to your code, I was able to add the following to the code that creates my custom post type:

// hook into Subscribe To Comments Reloaded plugin
// cause author of custom post type to receive notification of comment	
add_action ( 'publish_message', 'aso_notify_message_author' );	
	function aso_notify_message_author($ID) {
		global $wp_subscribe_reloaded;
		$wp_subscribe_reloaded->subscribe_post_author( $ID );
	}

**Comment by Reedyseth** [comment]
> Instead of adding to your code, I was able to add the following to the code that creates my custom post type:
> 
> // hook into Subscribe To Comments Reloaded plugin
> // cause author of custom post type to receive notification of comment
> 
> add_action ( 'publish_message', 'aso_notify_message_author' );
> 
> function aso_notify_message_author($ID) {
> global $wp_subscribe_reloaded;
> $wp_subscribe_reloaded->subscribe_post_author( $ID );
> }

Sweet, I still add the code on the plugin since every user might have a different Custom Post Type.

**Comment by Reedyseth** [comment]
@nedkeller 

This commit fullfil this request dd3bb95.

I will release the code on this friday **26-Aug-2016**

Make sure to update your code before installing the new update to avoid double subscription.
