### ISSUE TITLE
Mail messages cache

### ISSUE THREAD

**Issue by IvanRF** [stcr/subscribe-to-comments-reloaded#128]
Hi Israel, I solved the messages localization with WPML but now I'm having another issue with other plugin. I use W3 Total Cache and somehow the message content is being cached. Thus, if an Spanish message is cached first, then messages that should be in English are in Spanish.
This is caused by the calls to `get_option()`. For example:
`get_option( 'subscribe_reloaded_notification_content', '' )`

I've read about this options caching issue, and someone solved it by using `no` for `autoload` in the `add_option`. It is [mentioned in the reference](https://codex.wordpress.org/Function_Reference/add_option#Parameters) too. However, I modified my database and set `no` for `subscribe_reloaded_notification_subject` and `subscribe_reloaded_notification_content` but the caching continued. I also used `no` in your `add_option` calls, then deactivate the plugin and re activate, but nothing solved this.

I opened a [thread in W3 Total Cache](https://wordpress.org/support/topic/object-cache-and-i18n-issue), but for now I had no answers. Do you use W3 Total Cache?

Since you have more knowledge about WordPress plugins than me, maybe you know how to solve this 😃

**Comment by Reedyseth** [comment]
> I've read about this options caching issue, and someone solved it by using no for autoload in the add_option. It is mentioned in the reference too. However, I modified my database and set no for subscribe_reloaded_notification_subject and subscribe_reloaded_notification_content but the caching continued. I also used no in your add_option calls, then deactivate the plugin and re activate, but nothing solved this.

For me this looks that everything is OK with the `no` option (autoload) But since WP already cache that no matter how many times you deactivate and activate the option will remain there.

Can you clear the cache with the option on W3 Total Cache and share the results ?

**Comment by IvanRF** [comment]
> Can you clear the cache with the option on W3 Total Cache and share the results ?

I already tested that, and that's is why I said "if an Spanish message is cached first". In other words, the first language that is cached after calling `get_option()` is the one that is maintained in the subsequent calls.

As a test, with a cleared cache, I added a call to `get_option('subscribe_reloaded_notification_subject')` before switching the language (`switch_lang()`). As my default language is Spanish, the mail notification had the subject in Spanish and the content in English. In other words, it didn't matter that I switched the language, the second call to `get_option('subscribe_reloaded_notification_subject')` took the cached message in Spanish instead of English.

I really don't know which plugin is to blame, I have an important mix there 😃.

**Comment by IvanRF** [comment]
This was caused by a bug in WPML String Translation, I'm so angry!

When `get_option` applies the filter `'option_' . $option`, the function `icl_st_translate_admin_string` in `wpml-string-translation/inc/admin-texts/wpml-admin-texts.class.php` is called. This class has an internal cache `$icl_st_cache` and there was the issue. **This cache is not taking into account that the language was changed**.

**Comment by Reedyseth** [comment]
Thank you for reporting and spending time on this, I know hard it was to get to this point and find the root of the problem. I guess this conversation will continue here #133
