### ISSUE TITLE
Bug Report: Author Re-subscribe

### ISSUE THREAD

**Issue by WnDSolutions** [stcr/subscribe-to-comments-reloaded#129]
When author unsubscribe from his post, can't subscribe again.

**Comment by WnDSolutions** [comment]
I was able to view my automatic subscription on the manage page and edit it. 
Now I can't. Any help?

**Comment by Reedyseth** [comment]
Hello @WnDSolutions I will check this behavior, in the mean time if you are the administrator of WordPress you can add your subscription manually on the plugin setting page, otherwise ask the administrator to add you by using the ID of the post and your email address.

Regards.!!

**Comment by WnDSolutions** [comment]
Thank you @Reedyseth 

I'm waiting for your answer.

**Comment by Reedyseth** [comment]
Hi @WnDSolutions.

I has been a lot since you reported this issues, the plugin development stopped for a while. There is a new update with many changes and fixes, please update.

If you need to re-open again this issues please do so.

Regards.!!
