### ISSUE TITLE
How can I delete "Subscription without comment"?

### ISSUE THREAD

**Issue by staysmoo** [stcr/subscribe-to-comments-reloaded#130]
hello,

how can I "Also possible: Subscription without comment." disable / delete?

see here:
http://www.niha-grafik.de/infografik-responsive-webdesign/

under the checkbox.

I want to give the user not have this option.

King regards,
Nicole

**Comment by Reedyseth** [comment]
@staysmoo Right now that option is not available, but you can remove the link on the comment settings and that will work.

To remove the link go to the `Comment Form` tab and on the Default Label remove the Text `Auch möglich: Abo ohne Kommentar.` Notice that `Abo ohne Kommentar` is wrap in a HTML a (anchor) tag. Just to keep things easy, just leave this text `E-Mail-Benachrichtigung bei weiteren Kommentaren.`.

![image](https://cloud.githubusercontent.com/assets/1228711/9880006/146ef982-5b87-11e5-8fa9-0617c32b2352.png)

**Comment by staysmoo** [comment]
THANK YOU! It works!

**Comment by Reedyseth** [comment]
You're Welcome !
