### ISSUE TITLE
WPML support

### ISSUE THREAD

**Issue by IvanRF** [stcr/subscribe-to-comments-reloaded#133]
I've found another bug in WPML trying to make it work right with Subscribe to comments reloaded. I sent the information to them but they replied me:

> In the case you want to make a plugin/theme compatible with WPML, please submit it at: [https://wpml.org/documentation/theme-compatibility/go-global-program/](https://wpml.org/documentation/theme-compatibility/go-global-program/).
> We have a dedicated team to work with the theme/plugin authors and resolve all compatibility problem.

Apparently, they create a demo site with your plugin and make it work. So, in order to stop spending my time with this I will appreciate if you can fill that form. They have a dedicated team to make this work. Thanks!

**Comment by Reedyseth** [comment]
Hello Ivan, a while a go they contacted me to help them with this process, I actually did, but they ask in reply if I could promote their plugin inside StCR, in that moment I coworker and I talk about the matter and rejected the publicity inside the plugin.

I will take a look at that and let you know the findings, by the way thank you for spending time on this. 

Regards.!!

**Comment by IvanRF** [comment]
Hi Israel, thanks for consider this. I agree with you, you shouldn't add publicity to them.

I just did a search inside Yoast SEO and there is no link to WPML, so maybe they changed that policy.

**Comment by Reedyseth** [comment]
A few days ago people from WPLM contacted me and said that they tested the latest code and is working. I am closing this issue but if you need to open please do so.

**Comment by yovamacua** [comment]
Hi, how can I change the language of the emails that are sent, I use wpml. I need to receive the emails in their respective language depending on where they are generated.
