### ISSUE TITLE
Confirmation link does not confirm

### ISSUE THREAD

**Issue by konus1** [stcr/subscribe-to-comments-reloaded#134]
I use the option to double check email adresses.
If a user gets an email and is asked to open the [confirm_link] he get to the managment page similar to [manager_link]
As far as I understand, the email is not confirmed yet, since there is an entry like
[  ]     2015-09-23 01:39:11 — YC — mail@domain.com

So to confirm the email-adress, my user would have to 
1. mark the linke with his email
2. choose option (x) aktivate
3. press submit Button

Is this correct?

If yes, I am afraid, that none of my users will complete this procedure, since they don't expect such a complex procedure. I think the user expectation is after clicking the confirmation link in the email, that they only get to a page like "Thank you for confirming your email!"

**Comment by Reedyseth** [comment]
Hello @konus1 , first of all thank you for subscribing to the testers mail address.

On this case when the user receive the confirmation link it should work only like you mention, by clicking the link on the email. I am going to test it in you site and let you know what I can find.

Regards.!!

**Comment by Reedyseth** [comment]
I checked you kids site an StCR is not enable, mailchimp is enable instead.

**Comment by konus1** [comment]
Thank you for your fast replay! Yes, I enabled both StCR and mailchimp-for-wp. After I know, that this is not the normal behavior, I am going to deactivate all other plugins for debugging.
I will report the result here.

**Comment by Reedyseth** [comment]
> Yes, I enabled both StCR and mailchimp-for-wp.

Yes, I just found StCR realoaded and I have post a comment.

**Comment by Reedyseth** [comment]
@konus1 The double check option worked as expected, after clicking on my link my subscription status changed, take a look:

![image](https://cloud.githubusercontent.com/assets/1228711/10039244/42662fe8-618d-11e5-9bdc-558b785b7746.png)

![image](https://cloud.githubusercontent.com/assets/1228711/10039247/4ad381ee-618d-11e5-88af-23c626aa0bb6.png)

**Comment by konus1** [comment]
Thank you for your help!
It looks like, that my problem was not an other plugin, but that I was already logged-in in Wordpress as an other user.

**Comment by Reedyseth** [comment]
> Thank you for your help!
> It looks like, that my problem was not an other plugin, but that I was already logged-in in Wordpress as an other user.

You're Welcome, glad that it helped.
