### ISSUE TITLE
Settings translation overrides WP translation

### ISSUE THREAD

**Issue by IvanRF** [stcr/subscribe-to-comments-reloaded#137]
The other day I noticed that in this plugin there is a translation for "Settings" which overrides the original WordPress translation. I removed that entry from WPML and that solved it.

Just to know, should a plugin override a translation from WordPress core?

Reedyseth said in [#123](https://github.com/stcr/subscribe-to-comments-reloaded/pull/123)
> This translation is inherited from the old code. I think that the plugin should not override the WP Core translation. So if WP is in Spanish the Settings word will translated by WordPress and StCR will be also in Spanish so there is no need to do this. Please add this into a new ticket so that I can track it down.The reference is [here](https://github.com/stcr/subscribe-to-comments-reloaded/blob/pre_release/subscribe-to-comments-reloaded/wp_subscribe_reloaded.php#L116)

**Comment by Reedyseth** [comment]
@IvanRF Thank you.

**Comment by IvanRF** [comment]
Closing this as it is suggested to always include the text domain.
See https://make.wordpress.org/polyglots/2016/01/10/if-a-plugin-has-a-string-which-is/#comment-271112

**Comment by Reedyseth** [comment]
Thank you for keeping track on this.
