### ISSUE TITLE
Load Text Domain not working

### ISSUE THREAD

**Issue by IvanRF** [stcr/subscribe-to-comments-reloaded#141]
I test pre_release on an empty site and Spanish translations were not loading. I fixed the call to `load_plugin_textdomain` based on documentation: 
https://developer.wordpress.org/plugins/internationalization/how-to-internationalize-your-plugin/

**Comment by IvanRF** [comment]
I also found calls to `load_plugin_textdomain` on /options/index.php and /utils/stcr_manage.php. **There should be only one call in the plugin**. If you can, test what happens if you remove those calls now that I added the action hook on 'plugins_loaded'

**Comment by Reedyseth** [comment]
Copy that I will give a try later on the day and let you know the findings.

**Comment by Reedyseth** [comment]
Both commits looks alright to me, I just need to test them.

**Comment by Reedyseth** [comment]
Now working in latest changes of `pre_release` branch. Merged here https://github.com/stcr/subscribe-to-comments-reloaded/commit/b07198380a133c36697b0d6348ede01b3116ea98
