### ISSUE TITLE
Add link to "No" value in comments table

### ISSUE THREAD

**Issue by IvanRF** [stcr/subscribe-to-comments-reloaded#143]
Some users make comments expecting an answer but they don't mark the checkbox to subscribe. So, I need to search them and add them at least "Reply to comments". It will be helpful to have a quick link in the "No" value for the column added in the comments table.

Also, the icon in the column header should have a tooltip

![25-9-2015 11-29-03 a- m-](https://cloud.githubusercontent.com/assets/6751650/10103177/e8362242-6378-11e5-8eba-26f659ab1091.png)

**Comment by IvanRF** [comment]
Tooltip pull request
https://github.com/IvanRF/subscribe-to-comments-reloaded/commit/8b489fd8025463302921d5fd1347137b33a8732a

**Comment by IvanRF** [comment]
I'm trying to define a link for "No". How can I populate the email and the post ID to this section?

![25-9-2015 5-44-43 p- m-](https://cloud.githubusercontent.com/assets/6751650/10111842/3ac3097e-63ad-11e5-8000-762130733b99.png)

**Comment by Reedyseth** [comment]
> How can I populate the email and the post ID to this section?

Right now the user must know the ID of the post entry which is not quite good, how someone will remember and ID of a post. I have in mind an improvement for this part.

**Comment by IvanRF** [comment]
I just tried this link, but it was added directly:

options-general.php?page=subscribe-to-comments-reloaded/options/index.php&subscribepanel=1&amp;sra=add&amp;srs=R&amp;srp=' . $comment->comment_post_ID . '&amp;sre=' . urlencode( $comment->comment_author_email ) . '

**Comment by IvanRF** [comment]
No, "edit" and "edit-subscription" needs that the entry exists. What other option for adding a new entry is available?

**Comment by IvanRF** [comment]
I think it would be nice to have something like "edit-subscription" that leads into the edit action, but for the add action. An "add-subscription" page, since using the add action directly in the link does not allow the user to select the status.

**Comment by IvanRF** [comment]
I can duplicate "edit-subscription" and code the "add-subscription" if you want?

**Comment by Reedyseth** [comment]
@IvanRF It would be better to have a Skype/Hangout call to coordinate this changes and all the others that are pending.

**Comment by IvanRF** [comment]
I just coded and tested that, it works like a charm 😃

https://github.com/IvanRF/subscribe-to-comments-reloaded/commit/de094211dc10edeb1d41931941e85e4623520e69

**Comment by Reedyseth** [comment]
Sweet, I will download it and test it.

**Comment by Reedyseth** [comment]
This feature is now on the beta code, thanks https://github.com/stcr/subscribe-to-comments-reloaded/commit/b07198380a133c36697b0d6348ede01b3116ea98
