### ISSUE TITLE
Bug Report: Can't turn off "HTMLify links in emails"

### ISSUE THREAD

**Issue by wcruz-br** [stcr/subscribe-to-comments-reloaded#146]
I turn the option off, but it still inserts &lt;a href&gt; tags in e-mails, breaking my layout. :(

Option:
![image](https://cloud.githubusercontent.com/assets/14890295/10165235/841d6a08-6694-11e5-8d27-34c74e562223.png)

E-mail:
![image](https://cloud.githubusercontent.com/assets/14890295/10165306/ec25bab0-6694-11e5-9675-503245bcd976.png)

E-mail source code:
![image](https://cloud.githubusercontent.com/assets/14890295/10165396/6dcbd0cc-6695-11e5-800a-256b94639b3b.png)

**Comment by wcruz-br** [comment]
I've just find out that it only occurs in that manage notifications e-mail. On regular notifications, it works fine:

![image](https://cloud.githubusercontent.com/assets/14890295/10165858/b550326a-6697-11e5-9f52-bcfb2324f941.png)

**Comment by Reedyseth** [comment]
Please download the pre_release version and test it

**BETA Repository:** https://github.com/stcr/subscribe-to-comments-reloaded/tree/pre_release
**BETA ZIP file:** https://github.com/stcr/subscribe-to-comments-reloaded/archive/pre_release.zip

Then keep deactivated the option `HTMLify links in emails` and then create you subscription template with the editor:

![image](https://cloud.githubusercontent.com/assets/1228711/10251112/e4994f1a-68eb-11e5-8b1c-e982f62c5996.png)
