### ISSUE TITLE
Bug Report: manage subscriptions page

### ISSUE THREAD

**Issue by wcruz-br** [stcr/subscribe-to-comments-reloaded#147]
After user sends his/her e-mail to receive the manage subscriptions page link, system shows the content that is expected only in the e-mail:

![image](https://cloud.githubusercontent.com/assets/14890295/10165545/48e49d10-6696-11e5-965d-e2e92e455e41.png)

This is confusing for the user. :/

Thanks in advance.

**Comment by Reedyseth** [comment]
@wcruz-br this Issue has been noticed and fix, it will be available on the next update, if you feel that you can't wait you can always download the beta version and also help to test the update for any bug.

**BETA Repository:** https://github.com/stcr/subscribe-to-comments-reloaded/tree/pre_release
**BETA ZIP file:** https://github.com/stcr/subscribe-to-comments-reloaded/archive/pre_release.zip
