### ISSUE TITLE
Apache Server 500 errors - memory & CPU overflows?

### ISSUE THREAD

**Issue by edelen** [stcr/subscribe-to-comments-reloaded#149]
Since the WordPress 4.3.1 update, the plugin has been spawning processes on my host's server that eventually overflow the 1 TB memory usage allocation and max out the CPU usage. This results in an Apache 500 error, which takes down the site. Log files blame the WordPress index.php file, but that's a catch-all for this problem

Almost two weeks of isolating plugins, and it comes down to this one. I disable it, and problem solved. I turn it back on, and immediately I start seeing usage rising in cpanel.

Anyone aware of this flaw? Comment subscribing is important to my site. Turning it back on is high on my list.

Will we see an update soon?

**Comment by Reedyseth** [comment]
Hello @edelen this is the first report of usage of CPU from StCR. I have some update with lots of code refactoring, I have tested this code on my own site and I don't have this kind of behavior. If you could download your site into a local enviroment and test that will be very helpful, let me know if you could do this.

Regards.!!
