### ISSUE TITLE
Modification username of user

### ISSUE THREAD

**Issue by filazza** [stcr/subscribe-to-comments-reloaded#156]
Hi,

On subscribe to comment plugin, the user can't modify their name or other informations, what can i do to fix this trouble ?

**Comment by Reedyseth** [comment]
Hello @filazza this options is not available yet, only if you are the admin you are allow to modify this information.

Regards.!!

**Comment by filazza** [comment]
Hi 

Many thanks,
But i don't find where ??

**Comment by Reedyseth** [comment]
You should find the edit button on the main tab of the plugin

![image](https://cloud.githubusercontent.com/assets/1228711/11449152/af99d050-9528-11e5-96ae-28612832e921.png)

**Comment by filazza** [comment]
Hi ,

Yes but we can just modify the email and we can’t mofify the pseudo,
(an user don’t want the pseudo is his real name)

many thanks
Phil
