### ISSUE TITLE
UI Issue with Options Menu (conflicts with WordPress Dashboard messages)

### ISSUE THREAD

**Issue by raamdev** [stcr/subscribe-to-comments-reloaded#158]
_Originally reported in https://github.com/websharks/comment-mail/issues/186#issuecomment-166928886._

There's a problem with the `<h2>` element that the StCR links are inside; they overflow onto Divs that show up underneath it (e.g., when another plugin adds a Dashboard message):

![2015-12-29_12-11-16](https://cloud.githubusercontent.com/assets/53005/12038374/8e945c7a-ae25-11e5-9fd1-5cb12f7326d7.png)

If you add `<div style="clear:both;"></div>` right after [this line](https://github.com/stcr/subscribe-to-comments-reloaded/blob/9f5b0dd26c4446fb9d6b8995b1b817a18c7e8397/subscribe-to-comments-reloaded/options/index.php#L84) (_inside_ the `<h2>` element), that will fix the problem:

![2015-12-29_12-11-52](https://cloud.githubusercontent.com/assets/53005/12038391/b2cbc1aa-ae25-11e5-9634-097599a5cc82.png)

![2015-12-29_12-15-12](https://cloud.githubusercontent.com/assets/53005/12038409/da94ea04-ae25-11e5-8ad7-c6545db99fcf.png)

**Comment by Reedyseth** [comment]
This UI issue is fixed on this commit 39907898e1441064d61e6f2128b0e580f34b45bf. 

You can download the latest changes of the pre_release branch to give it a try.
