### ISSUE TITLE
Generic Notification Message Template

### ISSUE THREAD

**Issue by Reedyseth** [stcr/subscribe-to-comments-reloaded#164]
Since there are users that don't have an Idea about how to create a Notification message it would be cool to have a button to load a generic template for none expert users. Idea generated on #161 

![image](https://cloud.githubusercontent.com/assets/1228711/12129297/dc9ae606-b3bf-11e5-86d8-bd24ca029871.png)

**Comment by raamdev** [comment]
Just an idea: The way Comment Mail does this is by allowing you to empty the field completely, and when you save the empty field it replaces it with the default template. That way if you ever mess up when editing the templates, you can simply delete everything in the box and save the options and Comment Mail will fill in the default template.

**Comment by Reedyseth** [comment]
> The way Comment Mail does this is by allowing you to empty the field completely, and when you save the empty field it replaces it with the default template.

Sounds good to me, otherwise I will have to do a lot of DOM manipulation to get it done.

**Comment by Reedyseth** [comment]
This commit fulfill the requirement dfb2163
