### ISSUE TITLE
Reuse wp_editor

### ISSUE THREAD

**Issue by IvanRF** [stcr/subscribe-to-comments-reloaded#166]
I saw that you included tinyMCE as a library. Since WordPress also uses that, wouldn't be better to use `wp_editor`?

[Here is the reference](http://codex.wordpress.org/Function_Reference/wp_editor), and some examples: [Using wp_editor](http://code.tutsplus.com/articles/quick-tip-using-wp_editor--wp-27136), [Enable editor in plugin](https://wordpress.org/support/topic/enable-wysiwyg-editor-in-plugin?replies=4).

**Comment by Reedyseth** [comment]
> Since WordPress also uses that, wouldn't be better to use wp_editor?

That was my first intention at first, but then I noticed that I can keep the tinyMCE up to date faster than WordPress. Also I can implement more plugins faster without messing too much with hooks and actions.

**Comment by IvanRF** [comment]
That's a good point.

I thought about using WP editor since I use Visual Composer for Posts/Pages. However, in this case is useless since VC needs javascripts which can't be used in mails (not everyone supports js in emails).

**Comment by Reedyseth** [comment]
Although I might use the WP Editor later in a custom post type, we'll see.
