### ISSUE TITLE
Call to undefined function subscribe_reloaded_show()

### ISSUE THREAD

**Issue by ragelt** [stcr/subscribe-to-comments-reloaded#169]
Hello,
After update to 160106 I have error.
<?php /* if (function_exists('subscribe_reloaded_show')) */ subscribe_reloaded_show(); ?>
shows:
PHP message: PHP Fatal error:  Call to undefined function subscribe_reloaded_show()

php version: 5.5.20

**Comment by Reedyseth** [comment]
Hello @ragelt ,

You have to change the calling to the function, See #159 And if you new a guide see here 
https://github.com/stcr/subscribe-to-comments-reloaded/wiki/KB#Real-Page

**Comment by ragelt** [comment]
Guide shows how to change the calling to the function in subscribe.php ($wp_subscribe_reloaded->stcr->subscribe_reloaded_manage) , I did it already,thanx.
Now I'm try to fix the calling the function subscribe_reloaded_show() in comments.php 
Help me please...  What should I add or change?

**Comment by Reedyseth** [comment]
Can you paste your code of `comments.php` here?

Or paster it here http://paste.behstant.com

**Comment by ragelt** [comment]
Okay: http://paste.behstant.com/?paste=212

**Comment by ragelt** [comment]
Any ides?

**Comment by Reedyseth** [comment]
> Any ides?

In you code that you share please replace this line

```php
<noindex><?php if (function_exists('subscribe_reloaded_show')) subscribe_reloaded_show(); ?></noindex>
```

for this
```php
<noindex><?php if ( isset($wp_subscribe_reloaded) ) $wp_subscribe_reloaded->stcr->subscribe_reloaded_show();; ?></noindex>
```
And let me know your results.

**Comment by ragelt** [comment]
Done. Error changed:
```PHP Fatal error:  Call to a member function subscribe_reloaded_show() on a non-object in```

**Comment by Reedyseth** [comment]
I see, now use this one:
```php
<noindex><?php global $wp_subscribe_reloaded; $wp_subscribe_reloaded->stcr->subscribe_reloaded_show(); ?></noindex>
```

**Comment by ragelt** [comment]
Currently there are no errors, but the subscription form is also not shown.

**Comment by Reedyseth** [comment]
What is your website ?

**Comment by ragelt** [comment]
Can I send it to you by hangouts or skype?

**Comment by Reedyseth** [comment]
sure, even better with skype, search me with **reedyseth**

**Comment by ragelt** [comment]
Did it.

**Comment by Reedyseth** [comment]
Got it !
