### ISSUE TITLE
Namespace not suport php 5.2

### ISSUE THREAD

**Issue by ntsasng** [stcr/subscribe-to-comments-reloaded#170]
Hi there.
I have issue with your plugin, can you help me?
 Parse error: syntax error, unexpected T_STRING in wp-content/plugins/subscribe-to-comments-reloaded/subscribe-to-comments-reloaded.php on line 19

**Comment by Reedyseth** [comment]
Hello @ntsasng ,

Unfortunately StCR requires PHP >= 5.4.x, you should ask your hosting company to upgrade to a newer version of PHP, at leat 5.4.X.
