### ISSUE TITLE
Issue with mails sent after upgrade

### ISSUE THREAD

**Issue by PatrickCB** [stcr/subscribe-to-comments-reloaded#171]
Hi. I updated Subscribe to comments today for my (Dutch) blog and now the mails that are sent to subscribers contain HTML although I set it to text only. I didn't touch the settings, so my conclusion is that the upgrade caused it. Please assist

**Comment by Reedyseth** [comment]
Can you copy and paste what you have on the `Notification Content` of the `Notification` panel ?

Also, what is the value of `Enable HTML emails` in your `Options` panel ?

**Comment by PatrickCB** [comment]
You mean this?

Er is een nieuwe reactie op [post_title]. Link naar de reactie: 
[comment_permalink] 
<http://www.carblogger.nl/wp-admin/[comment_permalink]>">[comment_permalink] 
<http://www.carblogger.nl/wp-admin/[comment_permalink]>">[comment_permalink] 
<http://www.carblogger.nl/wp-admin/%3Ca%20href=>">[comment_permalink] 
<http://www.carblogger.nl/wp-admin/[comment_permalink]> Auteur: 
[comment_author] Reactie: [comment_content] Permalink: [post_permalink] 
<http://www.carblogger.nl/wp-admin/[post_permalink]>">[post_permalink] 
<http://www.carblogger.nl/wp-admin/[post_permalink]>">[post_permalink] 
<http://www.carblogger.nl/wp-admin/%3Ca%20href=>">[post_permalink] 
<http://www.carblogger.nl/wp-admin/[post_permalink]> Beheer je 
abonnementen: [manager_link] 
<http://www.carblogger.nl/wp-admin/[manager_link]>">[manager_link] 
<http://www.carblogger.nl/wp-admin/[manager_link]>">[manager_link] 
<http://www.carblogger.nl/wp-admin/%3Ca%20href=>">[manager_link] 
<http://www.carblogger.nl/wp-admin/[manager_link]>

Value of 'Enable HTML emails' is set to 'off'
HTMLify links in emails was set to 'On'


Op 13-1-2016 om 20:55 schreef Israel Barragan C.:
>
> Can you copy and paste what you have on the |Notification Content| of 
> the |Notification| panel ?
>
> Also, what is the value of |Enable HTML emails| in your |Options| panel ?
>

**Comment by Reedyseth** [comment]
OK, 

First enable `Enable HTML email`, set it to **on**

HTMLify links in emails should be set to **off**

Then You have to update the links, you do this by selecting the text 

[comment_permalink]

Then on the editor clck the link icon, you should have somethin like the image below,

![image](https://cloud.githubusercontent.com/assets/1228711/12306379/a8bd3e3c-b9f6-11e5-915d-fb8e944cb480.png)

After Cleaning your links you should end up with something like this:

![image](https://cloud.githubusercontent.com/assets/1228711/12306469/353e9658-b9f7-11e5-8279-2a57d44a3b9c.png)

Also, I suggest that you erase all the content and save the options, this will bring a default template that will have a better look that the one you have, something like this:

![image](https://cloud.githubusercontent.com/assets/1228711/12306528/86462174-b9f7-11e5-9551-96b26fd64352.png)

Then replace English text for your Dutch one.

**Comment by PatrickCB** [comment]
Ok, will do. Thanks for your quick reply

**Comment by PatrickCB** [comment]
Hi, I tried what you explained, but I noticed that the notification messages are still not what they are supposed to. They look fine in Wordpress, but the actual mail doesn't.
![setup](https://cloud.githubusercontent.com/assets/16691336/12703935/a3946bc6-c84f-11e5-8672-69ca021c2426.jpg)

![mail](https://cloud.githubusercontent.com/assets/16691336/12703929/7b1878cc-c84f-11e5-8fed-fa30d515b7ea.jpg)

**Comment by Reedyseth** [comment]
To prevent the same error to happen on the following updates this issues has been fixed on the commit 56e914f
