### ISSUE TITLE
Older version...

### ISSUE THREAD

**Issue by CatherineWLT** [stcr/subscribe-to-comments-reloaded#174]
The new update messed up my website and I don't have time to play around with it. 

Could I please get a link to the older version? 

Error: Parse error: syntax error, unexpected T_STRING in...

**Comment by raamdev** [comment]
@CatherineWLT Older versions are available here: https://wordpress.org/plugins/subscribe-to-comments-reloaded/developers/

See the **Other versions** section.

**Comment by Reedyseth** [comment]
Thank you @raamdev ,

@CatherineWLT Just to clear this up, the new update relies on your PHP version >= 5.3.x So if your site still down you can connect with FTP, delete the folder **subscribe-to-comments-reloaded** and upload the older version.

This will work for you:

https://downloads.wordpress.org/plugin/subscribe-to-comments-reloaded.150611.zip

**Comment by CatherineWLT** [comment]
Thank you. As soon as it happened I deleted the folder via Fetch.
