### ISSUE TITLE
Notice button is causing confusion

### ISSUE THREAD

**Issue by Reedyseth** [stcr/subscribe-to-comments-reloaded#178]
When a notice is display the user wants to close the notices but it keeps appearing, See:

https://wordpress.org/support/topic/persistent-notification?replies=3

A suggestion is to remove the `Got it` button an just leave the close icon instead.

![image](https://cloud.githubusercontent.com/assets/1228711/12434843/961170d0-bec6-11e5-8b89-828d30537352.png)

**Comment by raamdev** [comment]
> A suggestion is to remove the Got it button an just leave the close icon instead.

If I remember correctly, the close icon did not dismiss the message permanently (the messages came back on the next refresh). The only way to get the notices to go away as expected was to click the "Got it." buttons.

So if you remove the "Got it." buttons, you'll need to make sure the code is updated to properly dismiss the notices when clicking the close button.

**Comment by Reedyseth** [comment]
> So if you remove the "Got it." buttons, you'll need to make sure the code is updated to properly dismiss the notices when clicking the close button.

Correct, I will trigger the Ajax call on that button, so I will change the class `stcr-dismiss-notice` to the close button.

https://github.com/stcr/subscribe-to-comments-reloaded/blob/master/subscribe-to-comments-reloaded/includes/js/stcr-admin.js#L11
