### ISSUE TITLE
oneclick unsubscribe wrong link

### ISSUE THREAD

**Issue by jdeanmllr** [stcr/subscribe-to-comments-reloaded#179]
when using [oneclick_link] the resolved link in the mail leads to the managing site, instead of unsubscribing directly. Can you please tell me what I'm doing wrong or fix that issue? Thank you!

**Comment by Reedyseth** [comment]
Hello @jdeanmllr Thank you for report the issue. I have confirm and replicate the issue. I will work on it !

**Comment by Reedyseth** [comment]
> when using [oneclick_link] the resolved link in the mail leads to the managing site, instead of unsubscribing directly.

@jdeanmllr I debug the code the the redirection works without any problem.

One important thing. Make sure that when you are clicking on the `One Click Unsubscribe` button that you are not login as an Admin, being logged it as an Administrator takes precedence over the `One Click Unsubscribe` link.

**Comment by jdeanmllr** [comment]
@Reedyseth Thank you very much, that solved the problem. I was logged in as an admin...

One last question: is it also possible to add an one click unsubscribe link/button directly to the site? So the user can easily unsubscribe again without having to use the managing site... Thanks in advance!

**Comment by jdeanmllr** [comment]
@Reedyseth Hi Israel, did you have time to check my last question yet? Best Dominik

**Comment by Reedyseth** [comment]
Hi @jdeanmllr So right now the one click tag in not translate into a link, but I will add that as a feature request.

![image](https://cloud.githubusercontent.com/assets/1228711/12603572/26239392-c471-11e5-84ad-0cb0ba5a3aa9.png)

**Comment by jdeanmllr** [comment]
Thank you @Reedyseth!
