### ISSUE TITLE
Bug Report: The latest upgrade scrambles the notification messages

### ISSUE THREAD

**Issue by jharries** [stcr/subscribe-to-comments-reloaded#182]
When I installed the latest upgrade it scrambled the notification messages with a lot of duplication. Here's what the standard message got changed to:

There is a new comment to [post_title]. Comment Link: [comment_permalink]">[comment_permalink] Author: [comment_author] Comment: [comment_content] Permalink: [post_permalink]">[post_permalink] Manage your subscriptions: [manager_link]">[manager_link]

Hope that helps.

I'm on WP 4.4.1 and running Thesis 2.1.9

**Comment by Reedyseth** [comment]
Hello @jharries 

If you delete all that you have on the editor and save your change you will get a default template that will fix this for you. For now this default template only applies to that field.

Regards.!!

**Comment by jharries** [comment]
Hi Reesdyseth,

I tried that but it all ends up blank except for:

There is a new comment on [post_title].

Is that all I can use for now?

I don't understand what you meant by: For now this default template only applies to that field.

**Comment by jharries** [comment]
Sorry but y our solution above does not fix it:

This is what's showing after the reset as you suggested:

There is a new comment on [post_title].

Comment link: [comment_permalink] 
Author: [comment_author]

Comment:
[comment_content]

Permalink: [post_permalink]
Manage your subscriptions | One click unsubscribe

And This is what gets sent out:

<h1>There is a new comment on A New Site for a New Year.</h1><hr><p><strong>Comment link:</strong> <a href="https://www.morganscloud.com/2016/01/12/a-new-site-for-a-new-year/comment-page-1/#comment-254229" data-mce-href="https://www.morganscloud.com/2016/01/12/a-new-site-for-a-new-year/comment-page-1/#comment-254229">https://www.morganscloud.com/2016/01/12/a-new-site-for-a-new-year/comment-page-1/#comment-254229</a> <br><strong>Author:</strong> John</p><p><strong>Comment:</strong><br>Test2 of comment subscription</p><div style="font-size: 0.8em" data-mce-style="font-size: 0.8em;"><strong>Permalink:</strong> <a href="https://www.morganscloud.com/2016/01/12/a-new-site-for-a-new-year/" data-mce-href="https://www.morganscloud.com/2016/01/12/a-new-site-for-a-new-year/">https://www.morganscloud.com/2016/01/12/a-new-site-for-a-new-year/</a><br><a href="https://www.morganscloud.com/comment-subscriptions/?sre=71d37985cd3676b3ffcc6de6b857f18a&srk=62ef1d8284f37bcfbfe7b4614575d038" data-mce-href="https://www.morganscloud.com/comment-subscriptions/?sre=71d37985cd3676b3ffcc6de6b857f18a&srk=62ef1d8284f37bcfbfe7b4614575d038">Manage your subscriptions</a> | <a href="https://www.morganscloud.com/comment-subscriptions/?sre=71d37985cd3676b3ffcc6de6b857f18a&srk=62ef1d8284f37bcfbfe7b4614575d038&sra=u&srp=24354" data-mce-href="https://www.morganscloud.com/comment-subscriptions/?sre=71d37985cd3676b3ffcc6de6b857f18a&srk=62ef1d8284f37bcfbfe7b4614575d038&sra=u&srp=24354">One click unsubscribe</a></div>

**Comment by Reedyseth** [comment]
> When I installed the latest upgrade it scrambled the notification messages with a lot of duplication.

See #171 To check how to remove the duplicated links.
