### ISSUE TITLE
 Error in the notification mail

### ISSUE THREAD

**Issue by Makway** [stcr/subscribe-to-comments-reloaded#184]
In settings: https://yadi.sk/i/NCDmO4GonnmvA
The letter at the post office is as follows: https://yadi.sk/i/0u-4TOGBnnn2y

**Comment by Reedyseth** [comment]
@Makway 

Mark, make sure to enable the `HTML emals` Settings and to disable the `HTMLify links in emails` options
![image](https://cloud.githubusercontent.com/assets/1228711/12596299/756b2e4a-c43c-11e5-8c08-ec4ebec7ae7e.png)

**Comment by Makway** [comment]
Many thanks!

**Comment by Reedyseth** [comment]
You're welcome.
