### ISSUE TITLE
Feature : Being able to add a gravatar in the comment notice

### ISSUE THREAD

**Issue by lolobu** [stcr/subscribe-to-comments-reloaded#188]
I've modified wp_subscribe_reloaded.php to be able to add a gravatar in the email notification using the shortcode [comment_gravatar]. Maybe I'll like it :-)
I attach git the patch
[patch.txt](https://github.com/stcr/subscribe-to-comments-reloaded/files/114745/patch.txt)

**Comment by Reedyseth** [comment]
@lolobu Thank you for the suggestion. Feature added.

Regards.!!
