### ISSUE TITLE
Bug report: update of email addresses

### ISSUE THREAD

**Issue by jlad26** [stcr/subscribe-to-comments-reloaded#189]
Hi mass update of email addresses causes an error, I think caused by this line in wp_subscribe_reloaded.php
`$rowsAffected = $wpdb->query(
						$wpdb->prepare("UPDATE ". $wpdb->prefix .
							"subscribe_reloaded_subscribers SET subscriber_email = %s,
							    salt = %d,
							    subscriber_unique_id = %s
				 				WHERE subscriber_email = %s",
							$_new_email, $salt, $this->generate_temp_key( $salt . $_new_email ),$_email )
					);`

Instead of `$this->generate_temp_key` I think it should be `$this->utils->generate_temp_key`

Hope that's a) right and b) useful.

Cheers
Jon

**Comment by Reedyseth** [comment]
@jlad26 Thank you for you report.

Yes there are more lose reference to some function I sometimes is hard to catch, if you tested the code you can submit a pull request, otherwise I could add the changes and push the fix.

Regards.!!

**Comment by Reedyseth** [comment]
Close on commit 838f11d84fd40b3a073b0f607fd0dd652b65e56a

Thank you.
