### ISSUE TITLE
Translation of subscribe-reloaded-fa_IR

### ISSUE THREAD

**Issue by omid020** [stcr/subscribe-to-comments-reloaded#191]
Hi!

Translation of Persian (Farsi) language is completed. Please kindly involve it in next release.

Thanks in advance.
Omid
[fa_IR.zip](https://github.com/stcr/subscribe-to-comments-reloaded/files/117438/fa_IR.zip)

**Comment by Reedyseth** [comment]
Translation Added a02ff96a84f5d6ac0b8993ab76ef8bcb553f8229
