### ISSUE TITLE
Bug Report: Plugin breaks customizer

### ISSUE THREAD

**Issue by drreen** [stcr/subscribe-to-comments-reloaded#195]
Hey guys

I identified the plugin to break the wp customizer on pages, where comments are enabled.
I am using Make Plus Theme (https://thethemefoundry.com/docs/make-docs/)

Will be happy to provide admin login to my staging

**Comment by Reedyseth** [comment]
Hello @drreen are you still having this issue?

**Comment by drreen** [comment]
I switched to postmatic at this point already

**Comment by Reedyseth** [comment]
Thank you for the confirmation !
