### ISSUE TITLE
subscription box above the submit button

### ISSUE THREAD

**Issue by lolowilla** [stcr/subscribe-to-comments-reloaded#196]
Hello,
I have been having issues with that option. When activated, the checkbox and label won't appear. After searching for a while, I realized that the js script supposed to show it again was not using the right selector : in most wordpress themes I've been working with (default wordpress templates), the submit input class is called "submit". In your script, it's called Cbutton.
On my script I changed the selector to input.submit and it works now but I don't like changing a script on a plugin since it will be broken again after the next update.
So I was just wondering why you are using that Csubmit class as a selector? is your plugin supposed to add it somewhere? or is it used in other wordpress themes? where does it come from?
thanks in advance for your reply.

**Comment by Reedyseth** [comment]
Hello @lolowilla 

> So I was just wondering why you are using that Csubmit class as a selector? is your plugin supposed to add it somewhere?

The class is incorrect, I found that some users have trouble with this, I was planning to correct the jQuery code, but as for this feature I will modify the code using WordPress this will improve the compatibility.

**Comment by Reedyseth** [comment]
WIP for this feature, also reported here https://github.com/stcr/subscribe-to-comments-reloaded/issues/220

**Comment by Reedyseth** [comment]
Hi, this is fixed by this commit https://github.com/stcr/subscribe-to-comments-reloaded/commit/8fe6929f3328fbf2fc3da9ac2df615d4953a6f8f and https://github.com/stcr/subscribe-to-comments-reloaded/commit/98d553e33f8a958a4e20800faeff16106b8864e6 and will be available on the next release.
