### ISSUE TITLE
Bug Report: <short description>

### ISSUE THREAD

**Issue by prateek1611** [stcr/subscribe-to-comments-reloaded#200]
Sir 
The mail which the commenter gets is not coming in proper way. Its the html code which is mailed to the user. I have also tried by setting it to default but that doesn't solved the problem.
example of a mail - 
There is a new comment to Appointment of Auditor - Sec 139.
Please click on this link to see the comment - <a href="<a href="<a href="http://taxadda.com/companies-act-2013/audit/appointment-of-auditor-sec-139/#comment-4519">http://taxadda.com/companies-act-2013/audit/appointment-of-auditor-sec-139/#comment-4519</a>"><a href="http://taxadda.com/companies-act-2013/audit/appointment-of-auditor-sec-139/#comment-4519">http://taxadda.com/companies-act-2013/audit/appointment-of-auditor-sec-139/#comment-4519</a></a>"><a href="<a href="http://taxadda.com/companies-act-2013/audit/appointment-of-auditor-sec-139/#comment-4519">http://taxadda.com/companies-act-2013/audit/appointment-of-auditor-sec-139/#comment-4519</a>"><a href="http://taxadda.com/companies-act-2013/audit/appointment-of-auditor-sec-139/#comment-4519">http://taxadda.com/companies-act-2013/audit/appointment-of-auditor-sec-139/#comment-4519</a></a></a>

Author: Prateek Agarwal

Permalink: <a href="<a href="<a href="http://taxadda.com/companies-act-2013/audit/appointment-of-auditor-sec-139/">http://taxadda.com/companies-act-2013/audit/appointment-of-auditor-sec-139/</a>"><a href="http://taxadda.com/companies-act-2013/audit/appointment-of-auditor-sec-139/">http://taxadda.com/companies-act-2013/audit/appointment-of-auditor-sec-139/</a></a>"><a href="<a href="http://taxadda.com/companies-act-2013/audit/appointment-of-auditor-sec-139/">http://taxadda.com/companies-act-2013/audit/appointment-of-auditor-sec-139/</a>"><a href="http://taxadda.com/companies-act-2013/audit/appointment-of-auditor-sec-139/">http://taxadda.com/companies-act-2013/audit/appointment-of-auditor-sec-139/</a></a></a>

Follow us on Facebook and GooglePlus
https://www.facebook.com/taxaddaindia
https://plus.google.com/+Taxaddaindia/

Manage your subscriptions: <a href="<a href="<a href="http://taxadda.com/comment-subscriptions/?sre=f8e58e0a9ab6c72325b5462615b1ca57&srk=4c686b796b6ed41720b4af8c7e9fabeb">http://taxadda.com/comment-subscriptions/?sre=f8e58e0a9ab6c72325b5462615b1ca57&srk=4c686b796b6ed41720b4af8c7e9fabeb</a>"><a href="http://taxadda.com/comment-subscriptions/?sre=f8e58e0a9ab6c72325b5462615b1ca57&srk=4c686b796b6ed41720b4af8c7e9fabeb">http://taxadda.com/comment-subscriptions/?sre=f8e58e0a9ab6c72325b5462615b1ca57&srk=4c686b796b6ed41720b4af8c7e9fabeb</a></a>"><a href="<a href="http://taxadda.com/comment-subscriptions/?sre=f8e58e0a9ab6c72325b5462615b1ca57&srk=4c686b796b6ed41720b4af8c7e9fabeb">http://taxadda.com/comment-subscriptions/?sre=f8e58e0a9ab6c72325b5462615b1ca57&srk=4c686b796b6ed41720b4af8c7e9fabeb</a>"><a href="http://taxadda.com/comment-subscriptions/?sre=f8e58e0a9ab6c72325b5462615b1ca57&srk=4c686b796b6ed41720b4af8c7e9fabeb">http://taxadda.com/comment-subscriptions/?sre=f8e58e0a9ab6c72325b5462615b1ca57&srk=4c686b796b6ed41720b4af8c7e9fabeb</a></a></a>

**Comment by prateek1611** [comment]
I read about the html options in options and it solved my problem.
Set "Enable HTML emails" to Yes
Set "HTMLify links in emails" to No

**Comment by Reedyseth** [comment]
I apologize for this, this links corruption is the result of a tags validation,

Basically you have to do two steps, the first one is what you describe here:



> I read about the html options in options and it solved my problem.
> Set "Enable HTML emails" to Yes
> Set "HTMLify links in emails" to No

and the second one is to recreate the template again. For this see #171

**Comment by Reedyseth** [comment]
Issue solved on this commit https://github.com/stcr/subscribe-to-comments-reloaded/commit/56e914fbcb3753448bde064b43810f5e7ba4ec26
