### ISSUE TITLE
Bug Report: Broken Management links

### ISSUE THREAD

**Issue by cdmonline** [stcr/subscribe-to-comments-reloaded#201]
http://portallas.com/blog
WP: 4.4.2
S2CR: 160115

I've recently installed S2CR. When a user posts a comment to a post, they can see the following below the POST COMMENT button:

You are subscribed to this post. **Manage** your subscriptions.You can **manage the subscriptions** of this post.

Both the **Manage** & **manage the subscriptions** links direct to a 404 page. Why is this happening and what can I do to fix it?

- CDM

**Comment by Reedyseth** [comment]
@cdmonline First of, apologize for the late response.

OK, I see the error, please make sure that you are following your permalink structure on the management page.
