### ISSUE TITLE
Bug Report: texts in the fields are not display in the localized language

### ISSUE THREAD

**Issue by numbifer** [stcr/subscribe-to-comments-reloaded#206]
Hi,
in the last version of plugin, all texts in the fields are not display in the localized language. However, the language interface is displayed in the localized language.
in previous versions, it was not so!
I attach the screenshot for explanation.
<img width="853" alt="schermata 2016-03-05 alle 18 53 34" src="https://cloud.githubusercontent.com/assets/17676710/13549359/9d6e23ee-e303-11e5-8c31-cddbc417dd89.png">
<img width="1166" alt="schermata 2016-03-05 alle 18 52 59" src="https://cloud.githubusercontent.com/assets/17676710/13549361/a3df115c-e303-11e5-823d-9a990f79df63.png">

**Comment by Reedyseth** [comment]
@numbifer What language are you using ?

**Comment by numbifer** [comment]
Hi, I use italian language.

**Comment by Reedyseth** [comment]
Thank for the information, I apologize for the late response.

**Comment by Reedyseth** [comment]
Translations reference updated in commit a02ff96a84f5d6ac0b8993ab76ef8bcb553f8229, it will be available on the next Milestone https://github.com/stcr/subscribe-to-comments-reloaded/milestone/1

**Comment by eapo** [comment]
Same problem here with the `subscribe-to-comments-reloaded-hu_HU.po` Version 200205

**Comment by BobaWebDev** [comment]
Hi @eapo 

The commit you submitted fixes the issue, correct?

**Comment by eapo** [comment]
> Hi @eapo
> 
> The commit you submitted fixes the issue, correct?

I don't think so, just completed with some important translations. I you tell me what can be the problem I try to fix it.
