### ISSUE TITLE
issues with generate key and permissions

### ISSUE THREAD

**Issue by Reedyseth** [stcr/subscribe-to-comments-reloaded#209]
Issue started here: https://wordpress.org/support/topic/subscibe-lead-to-500-code-message

**Comment by RoderikLouis** [comment]
Perfect! Last comment was:

**Comment by RoderikLouis** [comment]
Perfect! Last comment is:

Hi man,

Did it all. I seemed to work just fine but when i press "setting" i got a message saying that i have not enough rights.

The rights of this folder is 755 just like the other plugin folders.

Whats next?

Thanks for helping me out here!

**Comment by Reedyseth** [comment]
> Did it all. I seemed to work just fine but when i press "setting" i got a message saying that i have not enough rights.

Please create a screenshot for that error. I have a small clue for that but just need to make sure.

> The rights of this folder is 755 just like the other plugin folders.

There only file that will need 777 write permisions should be under the utils folder with the name log.txt but I don't recall to enable that.

What is you site URL ?

**Comment by RoderikLouis** [comment]
Hi! 

Sorry for my late reaction but i was outside Holland. To awnser your question:

1. Here is the screenshot: http://screencast.com/t/DJNliUsDA
2. www.aquariumfans.nl is the URL of my website. 

Curious how good your Dutch is ;)

Thanks again!

**Comment by RoderikLouis** [comment]
Hi!

Sorry to bother you again but i am waiting for a reply. Would be great if you can help me further.

Best regards,

Roderik

**Comment by Reedyseth** [comment]
Hi, I apologize for the late response, I just checked the subscription link an is broken, might be permalink issues, what is your current permalink structure ?

**Comment by RoderikLouis** [comment]
Hi, thanks for the reply!

This is the permalink structure: http://screencast.com/t/dBXE2WmEqM 

And a quick other question! When i give a reaction on a blog, i get redirected to a wordpress login page. In the settings, i cannot find anything to change this. I want people to go to a "thank you" page or something. Can you help me with this?

Thanks allot man!

**Comment by Reedyseth** [comment]
> This is the permalink structure: http://screencast.com/t/dBXE2WmEqM

Make sure that on the Management Page option you add the slash at the end of the page name, like this:

![image](https://cloud.githubusercontent.com/assets/1228711/14252866/6ca021a4-fa46-11e5-96ca-dab8925c32f1.png)

**Also, are you using Virtual Management Page or Manual ?**

> And a quick other question! When i give a reaction on a blog, i get redirected to a wordpress login page. In the settings, i cannot find anything to change this.

Perhaps you have the option to only logged in users are allow to comment.

![image](https://cloud.githubusercontent.com/assets/1228711/14253030/2159e8c8-fa47-11e5-8964-52a13c84e12c.png)


> I want people to go to a "thank you" page or something. Can you help me with this?

I would like to, but it is out of the scope of the plugin, for this matter I can help you here:

http://datasoftengineering.com/ and contac me here: http://datasoftengineering.com/index.php/contact-us/

**Comment by RoderikLouis** [comment]
Hi man!

Right so i understand that redirecting after comment subscription has nothing to do with your plugin. So let's leave that one. But your reaction about it helped allot. Thanks allot!

1. "Make sure that on the Management Page option you add the slash at the end of the page name".
This was already working fine when i checked the settings: http://screencast.com/t/h9osoY1DF

2. "Also, are you using Virtual Management Page or Manual?"
It is deactivated in my WP enviourement: http://screencast.com/t/s30nxRSHK6 Do I need to change anything here?

Subscription link is still broken unfortunately! 

Best regards and thanks again for the fast reply! I appreciate that. 

Roderik

**Comment by Reedyseth** [comment]
I see that you are able to enter the options without the permission issue.

Also please activate the Virtual Management page, the other option works
when you create a template.

**Comment by RoderikLouis** [comment]
Hi! 

Can you please explain both of your statements a bit? I am afraid that I don't understand what you mean. Sorry!

**Comment by Reedyseth** [comment]
Yes, 

The first statement is regarding this comment https://github.com/stcr/subscribe-to-comments-reloaded/issues/209#issuecomment-198409196 and this https://github.com/stcr/subscribe-to-comments-reloaded/issues/209#issuecomment-201218955 where you mentioned difficulties to access the StCR admin page.

As for the second one. There are to ways to display the Management Page,  one is Virtually( There is not a file with the html code ) and Manually ( where there is a template file where you trigger the subscription options on the client side).

**Comment by RoderikLouis** [comment]
Thanks man for explaining! 

So basicly i need to find this templatefile. When i add this -or something- it will automaticly trigger another subscriptionlink. One that does work? 

Thanks mate!

**Comment by RoderikLouis** [comment]
Hi! 

Would be great if you could help me with my last reaction. We really want to make a step here!

Thanks!

**Comment by Reedyseth** [comment]
Hi @RoderikLouis 


> So basicly i need to find this templatefile. When i add this -or something- it will automaticly trigger another subscriptionlink.

When you work with a template file is when you have issues displaying the management page in your theme, so if you don't have issue you can use the Virtual Management Page. So enable the Virtual Management Page in the `Management Page` options of the plugin.

**Comment by Reedyseth** [comment]
This issue was the result of a wrong settings page url see https://github.com/stcr/subscribe-to-comments-reloaded/commit/467999e11939a099f55c8d471be130e1b9ccc899
