### ISSUE TITLE
Not receiving notifications.

### ISSUE THREAD

**Issue by flaviorbianchi** [stcr/subscribe-to-comments-reloaded#210]
My commenters are not getting any comment notification no matter the status they choose, although they are receiving the link to the subscription management page when requested.
My website is hosted on GoDaddy and I'm using WP-Mail-SMTP to send emails to domains not registered by my account.

**Comment by Reedyseth** [comment]
@flaviorbianchi Sending notifications through some email helpers cause that the messages are detected as spam. Try to disable WP-Mail-SMTP and test if the messages are going through. I am working in some improvements related to email headers that will improve the trust of the emails that are sent.

**Comment by flaviorbianchi** [comment]
I'm getting the same behavior. I deactivated the WP-Mail-SMTP plugin and no notification was sent. The links to the subscription management page were received as always.
I commented with 3 different emails and choosed different subscription options for each and none of them were received neither in the spam folder.

**Comment by Reedyseth** [comment]
OK, I am working in something else, when I am done I let you know so that you can test with the latest code.

**Comment by Reedyseth** [comment]
@flaviorbianchi You can give it a shot now https://github.com/stcr/subscribe-to-comments-reloaded/archive/development.zip

**Comment by flaviorbianchi** [comment]
@Reedyseth how should I proceed to update using the files provided?
Just upload them into the directory or should I do something else?
Do you have a quick step-by-step?

**Comment by Reedyseth** [comment]
@flaviorbianchi ,

Now the update is available through your WordPress Plugin Dashboard. Just after you install it, please deactivate and activate the plugin and you are good to go.
