### ISSUE TITLE
Bug Report: Simple spelling issue.

### ISSUE THREAD

**Issue by KGIII** [stcr/subscribe-to-comments-reloaded#212]
Simple spelling mistake on the _Options_ page. It says:

> If this option is enable the **subscriptioin** box will be above the submit button in your comment form.

It is "subscription." I was going to go ahead and patch it but I figure it's such a trivial thing (it's easy to see what was intended) that you'll probably not want to bother fixing it until you are doing a new release anyhow.

http://i.imgur.com/qLJUk73.png
<img src="http://i.imgur.com/qLJUk73.png">

Other than that, I've not finished running it through the ringer yet but it looks to be a pretty good plug-in and I appreciate the work. I'll send a donation along sometime this weekend when I get a minute to go through that process and figure out what it entails. But, like I said, it's a simple/unimportant spelling error and there's no huge rush for a repair.

**Comment by Reedyseth** [comment]
> Simple spelling mistake on the Options page. It says: It is "subscription."

@KGIII Thank you for making the plugin better, that will take no more than a minute to get fix, I appreciate the feedback.

Regards.!!

**Comment by Reedyseth** [comment]
This Typo is already fixed, see https://github.com/stcr/subscribe-to-comments-reloaded/commit/e0b1e2008c0519524a0b0ebd6908f415dfb138a5#diff-4f598bc924f96f6f2eb1368f728d7b99
