### ISSUE TITLE
Language Setting

### ISSUE THREAD

**Issue by zivuch** [stcr/subscribe-to-comments-reloaded#213]
Hi

Could not set up my language ?
How could I do that or force this?

Thanks
Ziv

**Comment by Reedyseth** [comment]
Hi Ziv,

Did you create the po and mo files?

**Comment by zivuch** [comment]
Hi
The po & mo are already installed. my language is Hebrew or did I miss something?
Thanks

**Comment by Reedyseth** [comment]
can you send the the `po` file to my email so that I can verify it ? reedyseth at gmail dot com

By the way I spent some time working in  RTL languages so you will benefit with it on the next version.

**Comment by zivuch** [comment]
:)
I sent you the file
Thanks!!!

**Comment by Reedyseth** [comment]
@Ziv

One quick question, what version of StCR are you using ?

**Comment by zivuch** [comment]
I think the latest version. I downloaded it from wordpress.org.

**Comment by Reedyseth** [comment]
> I downloaded it from wordpress.org.

That will work :+1:

**Comment by zivuch** [comment]
Unfortunately it doesn't
I have tried several times :(

**Comment by Reedyseth** [comment]
I meant the information for testing.

**Comment by zivuch** [comment]
Cool  :)

**Comment by Reedyseth** [comment]
I have found issue in the translation, the last person who translated the file did not follow the WordPress standards, as soon as I correct the file I let you know.

**Comment by zivuch** [comment]
Good News 
Thanks!

**Comment by Reedyseth** [comment]
I just emailed you a new files.

**Comment by zivuch** [comment]
Thanks, it works :)
I will do a spelling check and will ad the rest that is not translated and will send it to you

**Comment by Reedyseth** [comment]
> I will do a spelling check and will ad the rest that is not translated and will send it to you

Awesome, I will contact you for the new revision since also there is some text that changed and also new text to translate.
