### ISSUE TITLE
Raw API functionality aviable?

### ISSUE THREAD

**Issue by giutae** [stcr/subscribe-to-comments-reloaded#216]
**Hi. Great plugin here. Thanks for all the effort for the wp community**

I develop my custom themes and try to avoid using plugins as much is possible. But automatize comments notification for not registered users is a very interesting feature for my website where I have to deal with a lot of comments and also very different visitors.

I installed StCR yesterday in localhost and try to use it in my custom theme.

But - as I said - I'm not using the default WP comment code for displaying the comment form and fields. I'm using all custom HTML/PHP/JS. I mean: I build my own html form, and I have my custom JS validation script that send the data to a PHP function that recieves the data via AJAX and performs the query to the core: I'm using the **wp_insert_comment();** function to achieve this. Everything is working as expected.

**But... how can I integrate StCR functionality in this custom form?** After some research I could add the html fields with this code:

`<?php global $wp_subscribe_reloaded; if (isset($wp_subscribe_reloaded)){ $wp_subscribe_reloaded->stcr->subscribe_reloaded_show(); } ?>`

This makes visible the select field and the link to the subscribe page.

But... this is not going to work, because there is no code (inside my custom theme) that can understand these stuff and send it to the core.

I supose that this plugin works fine "out-of-the-box" using the general WP comment code. But as you can see my case is a little different.

**So... does StCR have some api calls to directly add some email to the subscribe list?** I mean, something like this: stcr_add_email( $email, $post_id ); . This is not only useful for me, as well for many developers that want a flexible approach, in order to have the same functionality but different designs.

**Thanks in advance. Regards**

**Comment by Reedyseth** [comment]
Hello @giutae For adding a subscription you can use the method `add_subscription`, see

https://github.com/stcr/subscribe-to-comments-reloaded/blob/160106/subscribe-to-comments-reloaded/wp_subscribe_reloaded.php#L542
