### ISSUE TITLE
subscribers receive hundreds of emails after clicking on management link

### ISSUE THREAD

**Issue by aptharsia** [stcr/subscribe-to-comments-reloaded#217]
As above, two AOL subscribers said that after clicking the management link in one of their emails they then started receiving hundreds of management link emails, one said they came about 30 at a time. Is this a STCR issue or do I need to look elsewhere?

**Comment by aptharsia** [comment]
Ok, someone else emailed me that is a non-AOL user. It seems it's when they click on the manage link in an email to manage their subscriptions they receive hundreds of emails about managing their subscriptions. I've had to disable this plugin until this issue is looked into. HELP!

**Comment by Reedyseth** [comment]
Hi, can you share your site URL?

**Comment by aptharsia** [comment]
oldhousedreams.com

**Comment by Reedyseth** [comment]
@aptharsia Thank you for letting me know that the issue was cause by Postman SMTP.
