### ISSUE TITLE
Bug Report: https instead http links in email

### ISSUE THREAD

**Issue by richo67** [stcr/subscribe-to-comments-reloaded#218]
I am running my site on http only my admin part on https. Links generated in notification are using https which leads to error page.

**Comment by Reedyseth** [comment]
You are right, the protocol is hard coded, I will add this to the bug fix
like list. Thank you for your report.

Regards.!!

**Comment by richo67** [comment]
I wonder, any progress on this?

**Comment by Reedyseth** [comment]
Not so far, but I have added the **Bug Minor** label to keep track of it.

**Comment by Reedyseth** [comment]
@richo67 I apologize with the late response.

I had setup my development with SSL, but both links generated with HTTPS and HTTP works. What are the settings that you have in your `.htaccces` file ?

**Comment by richo67** [comment]
@Reedyseth never mind, I have totally change everything and I do not need anything. I even do not remember what was the issue. It is almost half a year,sorry. My site is now fully https no issue there anymore.

**Comment by Reedyseth** [comment]
Thank you for your response.

Regards.!!
