### ISSUE TITLE
function subscribe_reloaded_show does not exist

### ISSUE THREAD

**Issue by crowinck** [stcr/subscribe-to-comments-reloaded#219]
I've been using the suggested solution on your wordpress.org FAQ page to alter the placement of the subscribe opt in. However, it no longer appears and some investigation revealed the initial conditional checking for the function is returning false. Did you change this code with the last major update?

**Comment by Reedyseth** [comment]
The main reason is that the plugin is not finding the submit button of your comment form to do some logic, yes is the plugin error.

What is your website ?

Regards.!!

**Comment by crowinck** [comment]
mythcreants.com -  it's a custom theme, please let me know if I should update any of the theme files.

**Comment by Reedyseth** [comment]
I don't see the plugin being enable, can you make sure that it is?

**Comment by crowinck** [comment]
It is indeed enabled. I've done a plugin compatibility check and that wasn't an issue. The site is on WP Engine, which occasionally interferes with some features, but it stopped working when I ran updates, including your last major update.

**Comment by Reedyseth** [comment]
> It is indeed enabled. I've done a plugin compatibility check and that wasn't an issue.

In the background I can't see any resource loaded by the plugin. Do you use a cache plugin? can you clear it ?

**Comment by crowinck** [comment]
Yes, both WP Engine and Cloudflare caching is used. I have just purged both caches.

**Comment by Reedyseth** [comment]
> However, it no longer appears and some investigation revealed the initial conditional checking for the function is returning false.

Would you mind pointing this out? where did you see it?

Also disable the position of the checkbox.

![image](https://cloud.githubusercontent.com/assets/1228711/15129199/69c3a884-15fd-11e6-842f-db3f55380069.png)

**Comment by crowinck** [comment]
I know it's doing that because I'll altered the code on the staging clone of the site to echo whether the conditional was resulting in false or true. 
`if (function_exists('subscribe_reloaded_show')){ 
	subscribe_reloaded_show(); 
} else {
	echo 'function does not exist';
}`
StCR Box Position is already set to "no."

**Comment by Reedyseth** [comment]
ooh, I see,

Replace that code for this one:

```php
<?php global $wp_subscribe_reloaded; if (isset($wp_subscribe_reloaded)){ $wp_subscribe_reloaded->stcr->subscribe_reloaded_show(); } ?>
```

**Comment by crowinck** [comment]
That does it! Thank you. I recommend updating your FAQ tab on wordpress.org with this solution.

Are the background files loading now? Please let me know if other functions of the plugin might not be working.

**Comment by Reedyseth** [comment]
> That does it! Thank you. I recommend updating your FAQ tab on wordpress.org with this solution.

Good to hear that, yes I have updated that one but it will be available on the next update.



> Are the background files loading now? Please let me know if other functions of the plugin might not be working.

They don't because the checkbox is not yet included. In what post you have it included ?

**Comment by crowinck** [comment]
I just did it on the staging site, I'll roll out the coding changes to the live site later tonight. It's good to know that they'll load once the opt in field is present. I'll let you know if I run into other problems.

**Comment by Reedyseth** [comment]
> It's good to know that they'll load once the opt in field is present. I'll let you know if I run into other problems.

Copy that, I will keep posted.

**Comment by crowinck** [comment]
It looks like the manage subscriptions page is giving out a 500 error. Here's the old code: 
`if (isset($wp_subscribe_reloaded)){ global $posts; $posts = $wp_subscribe_reloaded->subscribe_reloaded_manage(); } `
Do you have an updated version?

**Comment by crowinck** [comment]
Also, could you consider creating some wrapper functions that you can update yourself to give theme developers a consistent code to interface with the plugin in the future?

**Comment by Reedyseth** [comment]
@crowinck 

> Do you have an updated version?

This should be what you need:
```
if (isset($wp_subscribe_reloaded)){ global $posts; $posts = $wp_subscribe_reloaded->stcr->subscribe_reloaded_manage(); }
```
Don't forget to disable the Virtual Management Page, since I think you are using a custom template file.

> Also, could you consider creating some wrapper functions that you can update yourself to give theme developers a consistent code to interface with the plugin in the future?

Great suggestion, so far I see that the user only needs to manipulate the checkbox display, do you have any other idea?

**Comment by crowinck** [comment]
Thank you, that worked.

I would just say that if you hand out any code snippets in your documentation, it's a good idea to insulate that code from future updates. It's hard to say how many people will be using them once you give them out. I see you already have one shortcode, which is a good way to wrap a function, especially since shortcodes fail gracefully if the code for them isn't present. In my case, the placement of the signup in the comment form and the code in the management page could have used a wrapper. I'll let you know if I find anything else.

Thanks for being so responsive.

**Comment by Reedyseth** [comment]
@crowinck FYI I have updated the readme information as you suggested and will be available on next release. Thank you for your comments. https://github.com/stcr/subscribe-to-comments-reloaded/commit/e3b1781480f1f96ccb4164caa6bc5c84cfdc3197#diff-9f82425cf174b914c3c17bd08e5c37ddR68
