### ISSUE TITLE
Bug Report: the subscribe to comments below the comment form not visible

### ISSUE THREAD

**Issue by realtimeparadigm** [stcr/subscribe-to-comments-reloaded#220]
I loaded the plugin and followed the settings from the Screenshots on WordPress.org plugin page. 
I cannot see the subscribe to comments below the comment form. 
I'm running WordPress 4.5.2 on the Divi Theme (Elegant Themes).

I use the plugin Sweet Captcha  a drag and drop visual to prevent spam comments. People often comment on my blog and I wanted a way to subscribe to comments.

In my css panel:  p.form-allowed-tags {display: none;} but this is to take away the tags below the post.
Thank you.

**Comment by Reedyseth** [comment]
@realtimeparadigm I apologize for that, there is a WIP for this behavior. Look to me that you enable the `StCR Box Position` to Yes, please set that to No and verify that the checkbox is visible.

**Comment by Reedyseth** [comment]
Hi, this is fixed by this commit https://github.com/stcr/subscribe-to-comments-reloaded/commit/8fe6929f3328fbf2fc3da9ac2df615d4953a6f8f and https://github.com/stcr/subscribe-to-comments-reloaded/commit/98d553e33f8a958a4e20800faeff16106b8864e6 and will be available on the next release.
