### ISSUE TITLE
[Solved] This plugin turned all of my pages into "subscription-manager" page

### ISSUE THREAD

**Issue by alichakery** [stcr/subscribe-to-comments-reloaded#222]
Hello,

When I enable this plugin it takes over all my pages for "Subscription Manager" page !!!

Would you please help me to solve this issue ?

Thank you.

**Comment by alichakery** [comment]
OHH.. this was my own fault in creating the custom notification management page.

This issue is solved ... thank you

**Comment by Reedyseth** [comment]
Hi @alichakery Good to hear that you solved it.

Regards.!!
