### ISSUE TITLE
Generate StCR Unique Key Doesn't Work

### ISSUE THREAD

**Issue by Niackery** [stcr/subscribe-to-comments-reloaded#223]
When I go to the Subscribe to Comments Reloaded Options tab, and click the red Generate button at the bottom, the page reloads blank below the tabs. If I then click on the Options tab and reload the page, the StCR Unique Key field is still the same (as in, a new key isn't generated).

**Comment by Reedyseth** [comment]
Hi @Niackery You can fix this by updating the file `options/panel5.php`

by replacing this code
```php
$unique_key = $wp_subscribe_reloaded->generate_key();
```
for this one
```php
$unique_key = $wp_subscribe_reloaded->stcr->utils->generate_key();
```

This bug is already fix and will be available for the next version.

**Comment by Niackery** [comment]
Thank you!

**Comment by Reedyseth** [comment]
FYI the fix of the bug is now on this commit https://github.com/stcr/subscribe-to-comments-reloaded/commit/7cde41a30975d2751db9d0c4971f0831cd456739. I will close the issue.

**Comment by atomGit** [comment]
what's the status with this?
in my case this problem still exists with stcr 5.3.2

**Comment by BobaWebDev** [comment]
Hi @atomGit 

Thanks for bringing this to our attention, we'll take a look at it and get that fixed.
