### ISSUE TITLE
Validation Error: Element link is missing required attribute property

### ISSUE THREAD

**Issue by metal450** [stcr/subscribe-to-comments-reloaded#224]
Running stcr 160115 (latest) on WP 4.5.2 (latest), my posts are no longer validating.  Here's a screenshot of the validator's output:

http://screencast.com/t/eff1J4slMHwl

The error is "Element link is missing required attribute property."  Disabling stcr eliminates the validation error.

**Comment by Reedyseth** [comment]
Hi @metal450 ,

Look to me that you are validating you site with xampp, I went through the original validator and that error did not show up. I got other type of errors but not the one that you mentioned.

https://validator.nu/?doc=http%3A%2F%2Fdesarrollandoweb.com.mx%2Fmysql%2Fconexion-php-mysql%2F

Regards.!!

**Comment by metal450** [comment]
> Look to me that you are validating you site with xampp

Yup, it's a local instance of the validator - but it (should be) using the exact same schema as the online version...

> I went through the original validator and that error did not show up.

The URL you're testing is http://desarrollandoweb.com.mx/mysql/conexion-php-mysql/; if I view the source of that page, there are no occurrences of "stcr" (http://screencast.com/t/YsQICxiCb). So clearly something's behaving differently beyond the validator itself.  When I view source on my site, I do get several "stcr" (http://screencast.com/t/vjJpwkZ8z7y), one of which is responsible for the error.  Perhaps a different plugin setting...?

**Comment by Reedyseth** [comment]
Alright @metal450 I got it, is just that the CSS style is being loaded inside the `<body>` tag so I will include that on the header instead, thank you for the report.

**Comment by metal450** [comment]
Great, glad it was so easy :)

**Comment by Reedyseth** [comment]
> Great, glad it was so easy :)

As a matter of fact it is not :disappointed: because the way WordPress uses to enqueue the style does not allow or have the function to put it on the header, there are some outdated solutions for this so you will have to keep this error.

This script is loaded only when you have the option `StCR Box Position` set to Yes, if you set it to No the the script will not be loaded. I recommend you to have it to No, this behavior will change in a new version and it won't need that CSS that is causing the validation to break.

**Comment by metal450** [comment]
I assume you mean the option "Enable default checkbox" under the "Comment Form" tab?  If so, changing that to "No" does restore validation...but then no "subscribe" checkbox is shown at all...

(note: it validated properly back on version 150820, from which I'm trying to update)

**Comment by Reedyseth** [comment]
I was taking about this option:

![image](https://cloud.githubusercontent.com/assets/1228711/15631620/474779a6-2530-11e6-8b01-b49efdd7d142.png)

**Comment by metal450** [comment]
That option was already set to no :/  I tried both settings, and in either case, validation fails the same way.

**Comment by Reedyseth** [comment]
Would you mind testing the development version ?

**Comment by metal450** [comment]
You mean just the current master?

Tried it; I can't get to the plugin's options anymore.  They aren't listed on the WP settings menu, and if I go to the plugin's "Settings" link from the Plugins page, it gives "You do not have sufficient permissions to access this page."

As soon as I reverted to the version from wp.org, it worked again.

**Comment by Reedyseth** [comment]
> You mean just the current master?

I meant the [development](https://github.com/stcr/subscribe-to-comments-reloaded/tree/development) one.



> Tried it; I can't get to the plugin's options anymore. They aren't listed on the WP settings menu, and if I go to the plugin's "Settings" link from the Plugins page, it gives "You do not have sufficient permissions to access this page."

I just fixed that.

**Comment by metal450** [comment]
Just tried development.  It's also giving me the error, both with "StCR Box Position" as "Yes" and as "No."

**Comment by Reedyseth** [comment]
if you go to the file `wp_subscribe_reloaded.php` line **1000** and comment 

```php
wp_enqueue_style( 'stcr-plugin-style' );
```
You are going to get rid of that.

**Comment by metal450** [comment]
Yup, that does it - thanks :)  No other negative side-effects of just removing that tho?

**Comment by Reedyseth** [comment]
> No other negative side-effects of just removing that tho?

Yes, like I said, that will be remove eventually :)

**Comment by metal450** [comment]
Sounds good - so I'll just temporarily hack my local copy, until the next official version is pushed out :)

Thanks again!

**Comment by Reedyseth** [comment]
@metal450 I have implemented the WordPress way to put the checkbox befor the submit button, would you download the development version again and give it a try ?

**Comment by metal450** [comment]
Sorry, in the midst of a very big site overhaul, won't be able to test this for awhile.  If a new version hasn't been pushed out by the time everything is stable on my end again, I'll give it a look.

**Comment by Reedyseth** [comment]
@metal450 The new version is out with this checkbox improvement. I am closing the issue but feel free to open it in case is need it.

**Comment by metal450** [comment]
Sounds good - thanks again!
