### ISSUE TITLE
554 Message not allowed - Headers are not RFC compliant

### ISSUE THREAD

**Issue by lucianop** [stcr/subscribe-to-comments-reloaded#226]
A few weeks ago, due to #215, I started using `master`. Since then, Yahoo has been rejecting all mail with the following non-delivery receipt:

    A message that you sent could not be delivered to one or more of its
    recipients. This is a permanent error. The following address(es) failed:
      <recipientemailhere>@yahoo.com.br
        host mta5.am0.yahoodns.net [66.196.118.33]
        SMTP error from remote mail server after end of data:
        554 Message not allowed - Headers are not RFC compliant[291]
    
    Action: failed
    Final-Recipient: rfc822;<recipientemailhere>@yahoo.com.br
    Status: 5.0.0
    Remote-MTA: dns; mta5.am0.yahoodns.net
    Diagnostic-Code: smtp; 554 Message not allowed - Headers are not RFC compliant[291]

After a quick investigation, it seems that it may be caused by a duplicate "subject" parameter (as described [here](https://www.yetanotherblog.com/2016/02/29/554-message-not-allowed-headers-are-not-rfc-compliant291/) and [here](https://www.howtoforge.com/community/threads/headers-are-not-rfc-compliant.68005/)). I checked the headers and the subject line was indeed duplicated.

I am not sure if this is a problem in the plugin itself, but it seems that the problem didn't happen with previous versions.

**Comment by Reedyseth** [comment]
Hi @lucianop 

You can download the version from the `development` tree where I have fixed all the headers sent by the plugin.

**Comment by lucianop** [comment]
Hello Israel,

I tried latest `development` (`467999e11939a099f55c8d471be130e1b9ccc899`), but no luck. Subject header is still sent twice and Yahoo is still unhappy.

**Comment by Reedyseth** [comment]
Oh, you are right, I totally missed that, now you can pull the development repository and test it again.

Also with this report I figured out why the notifications were not delivered to my gmail account, I was looking into that issue for weeks haha.

**Comment by lucianop** [comment]
I confirm this new version is working fine. Glad to know this fixes delivery to Gmail as well.

**Comment by Reedyseth** [comment]
> However, using this version, I can't get to the plugin config pages; they show as blank.

Sometimes the files are cached, please try to delete the cache. 

> Also, I'm getting plenty of Couldn\'t find an email with the SRE key: ( ) messages in /utils/log.txt. Not sure how these issues are related.

Sometimes some validation trigger this message and is find not having the the key value.

> Actually, I just tried subscribing to a post (without commenting), and I also get a blank page as a user. Something is very wrong.

As mentioned above, please try to clear any cache if you have it, I have not been able to replicate your issue.

**Comment by lucianop** [comment]
After some investigation, I realized the issues were indeed not related to the original issue, and edited my comment. Thanks for your answers, I appreciate it.

**Comment by Reedyseth** [comment]
> After some investigation, I realized the issues were indeed not related to the original issue, and edited my comment. Thanks for your answers, I appreciate it.

Awesome, great to hear that, thank you for the confirmation..!!
