### ISSUE TITLE
When deleting the plugin, the options are not cleared from the database

### ISSUE THREAD

**Issue by raamdev** [stcr/subscribe-to-comments-reloaded#228]
When deleting the StCR plugin, the plugin options are not being deleted (cleaned) from the database. As a result, there's no easy way to do a complete uninstall of the plugin.

Normal practice for WordPress plugins is to delete all data related to the plugin when deleting it so that the WordPress database does not get clogged with data from plugins that are no longer installed.

Related: https://github.com/stcr/subscribe-to-comments-reloaded/issues/225

**Comment by Reedyseth** [comment]
@raamdev Thank you for the feedback :+1:

**Comment by Reedyseth** [comment]
@raamdev Thank you for the suggestion, this commit commit closes this enhacement a89313b57a2ed00d6767b76efccfd52ed4fc3ea2.

**Comment by raamdev** [comment]
Cool! :-) 👍
