### ISSUE TITLE
 incompatibility ?

### ISSUE THREAD

**Issue by MuslimaChallenge** [stcr/subscribe-to-comments-reloaded#229]
Hello ,

I configured the plunning but the option to subscribe to comment does not appear.

How to know what is the problem and if this plugin is compatible or not?

Thank you

Sabah

**Comment by Reedyseth** [comment]
@MuslimaChallenge if you have this on a live site please share the URL so that I might take a look.

Regards.!!

**Comment by MuslimaChallenge** [comment]
Merci pour votre réponse ,

Voici le lien http://muslimachallenge.fr/index.php/2014/09/20/simple-slider-post/
I have another question please : How to translate the pluginns in French?

Regards !

**Comment by Reedyseth** [comment]
By the way do you have the option to move the subscription box above the submit button?

**Comment by MuslimaChallenge** [comment]
It's okay !!!

Merci :)
