### ISSUE TITLE
!important rule

### ISSUE THREAD

**Issue by side777** [stcr/subscribe-to-comments-reloaded#230]
There's an `!important` rule in stcr-plugin-style.css:

```
.hidden {
    display: none !important;
}
```

You use a very common word as class name with no other selector narrowing the rule down. Please don't do this! It affects any .hidden element, not just your's... Instead use:

```
#stcr .hidden {
    display: none !important;
}
```

or whatever name the parent element has. Or just a specific class name.

BTW: there's nothing in this file besides this single rule. Is this really worth another request to the server?

**Comment by Reedyseth** [comment]
@side777 

> You use a very common word as class name with no other selector narrowing the rule down. Please don't do this! It affects any .hidden element, not just your's... Instead use:

Thank you for the feedback !

> BTW: there's nothing in this file besides this single rule. Is this really worth another request to the server?

As for now is tiny bits what the request and response send/receive, not big issue, but since the behavior of the plugin checkbox will change I might remove that.

**Comment by Reedyseth** [comment]
@side777 

I have removed the enqueue of this style on this commit https://github.com/stcr/subscribe-to-comments-reloaded/commit/98d553e33f8a958a4e20800faeff16106b8864e6

Regards.!!

**Comment by berlindave** [comment]
I think the problem in Version 170428 on the repository described by @side777 still persists.

There's still this `!important` rule:
```
.hidden {
    display: none !important;
}
```
Unfortunately this is interferring with rules in some themes. Better it should read (referring to @side777 's proposal):
```
#stcr .hidden {
    display: none !important;
}
```
Would it be possible to fix this?
Best regards, David

**Comment by Reedyseth** [comment]
Hi @berlindave , I did not noticed that this raise again, this will remove on the next release. In the mean time you can just delete the content of the css to get rid of the problem.

**Comment by berlindave** [comment]
Sorry for anoying again, but in 170607 the problem still persists.

**Comment by Reedyseth** [comment]
Hello Guys, this problem has been taken care on the latest version (180212).

Thank you for your report.
