### ISSUE TITLE
Comment notifications not being sent

### ISSUE THREAD

**Issue by gbvaz** [stcr/subscribe-to-comments-reloaded#231]
Hi!

I've installed the plugin on my wordpress blog. I'm using Sendgrid as my email handler. I've successfully received emails for managing the comments subscriptions, but never for new comments. 

Is there anything I can do in order to solve this problem? 

Thanks!!

**Comment by Reedyseth** [comment]
@gbvaz 
Do you know if the status of the subscribers is to Active or Replies ?

**Comment by gbvaz** [comment]
@Reedyseth Is currently set to Active (Y)

**Comment by gbvaz** [comment]
I think I've found the "problem", not exactly a problem. I was testing making new comments with the same email. Then I tried  commenting with another email, and it worked :+1: 

Thanks for the help, sorry for all the trouble!

**Comment by Reedyseth** [comment]
No problem, good to hear that it is working !
