### ISSUE TITLE
Blank Page on replyging to comment

### ISSUE THREAD

**Issue by extremecarver** [stcr/subscribe-to-comments-reloaded#232]
Well I think since Wordpress 4.4 (not really sure since when exactly - it's about 3 months ago) when replying to a comment - the comment is correctly recorded - however a blank page is shown. 

This happens on the website front-end. 
On the backend - the Admin comment page instead - below the comment field - "Internal Server Error" pops up in red. reloading the page and the reply is shown.

I deactivated all other plugins - and it still happens.

This is on a root server running Ubuntu 16.04 - running an Nginx PHP 7.0 setup. I guess maybe it is kinda nginx related? However with subscribe-to-comments-reloaded deactivated everything is find.

Note - it only happens when replyging to a comment. If writing a new comment which is not a reply - everything is fine.

Just because this often causes problems - the nginx rewrite rules are set as described in the wordpress nginx tutorial:
"location / {
			try_files $uri $uri/ /index.php?$args;
        }"

Full rules:
		# We don't really need to log favicon requests
		location = /favicon.ico { access_log off; log_not_found off; }	
	
        location = /robots.txt {
                allow all;
                log_not_found off;
                access_log off;
        }
		
		location / {
			try_files $uri $uri/ /index.php?$args;
        }
					
		# Protecting s2-member-files folder and other folders
		# https://openmtbmap.org/wp-content/plugins/s2member-files/mtbeurope.exe
		location ~ /(s2member-files|invoices|backup-db) {
		deny 	all;
		gzip off;
		}	
	
	
		# Add trailing slash to */wp-admin requests.
		rewrite /wp-admin$ $scheme://$host$uri/ permanent;
		
		
		rewrite /wp-login$ $scheme://$host$uri/ permanent;
		rewrite /login$ $scheme://$host$uri/ permanent;
		location ~* /login/ { return 301 https://www.velomap.org/wp-login.php; }
		location ~* /wp-login/ { return 301 https://www.velomap.org/wp-login.php; }	
		location ^~ /wp-login.php/ { return 301 https://www.velomap.org/wp-login.php; }	
		
	
		# Caching the typical static files such as css, js, jpg, png and so forth
		# helps in telling the browser they can cache the content
		location ~* \.(ico|css|js|gif|jpe?g|png)$ {
			expires max;
			add_header Pragma public;
			add_header Cache-Control "public, must-revalidate, proxy-revalidate";
		}
	
		# Directives to send expires headers and turn off 404 error logging.
		location ~* ^.+\.(ogg|ogv|svg|svgz|eot|otf|woff|mp4|ttf|rss|atom|jpg|jpeg|gif|png|ico|zip|tgz|gz|rar|bz2|doc|xls|exe|ppt|tar|mid|midi|wav|bmp|rtf)$ {
		access_log off; log_not_found off; expires max;
		}	

		
        # pass the PHP scripts to FastCGI server listening on 127.0.0.1:9000
        #
        #location ~ \.php$ {
        #fastcgi_pass   localhost:9000;
        #include        fastcgi_params;
		#}
		# pass the PHP scripts to FastCGI server listening on 127.0.0.1:9000

        location ~ [^/]\.php(/|$) {
			fastcgi_split_path_info ^(.+?\.php)(/.*)$;
			if (!-f $document_root$fastcgi_script_name) {
			return 404;
			}       
				
			fastcgi_pass 127.0.0.1:9100;
            fastcgi_index index.php;
            # fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name; # not needed anymore
            include fastcgi.conf;
                
        }
		
 
	# We don't want to allow the browsers to see .hidden linux/unix files
	location ~ /\. { deny  all; access_log off; log_not_found off; }
	
	# Deny access to any files with a .php extension in the uploads directory
	# Works in sub-directory installs and also in multisite network
	# Keep logging the requests to parse later (or to pass to firewall utilities such as fail2ban)
	location ~* /(?:uploads|files)/.*\.php$ {
	deny all;
	}

**Comment by Reedyseth** [comment]
Hello @extremecarver I haven't test StCR on a nginx server, I will setup the environment and let you know if I can replicate your issue.

**Comment by extremecarver** [comment]
Wow - quick reply. Oh forgot to say - page is blank and url will be:
domain/wp-comments-post.php - no matter on which subpage it was written. WP permalink structure is custom - but the common: /%category%/%postname%/
So something bout the rewriting is clearly broken here. 

So if you reply to a comment on domain/category1/hellopost --> you will be redirected to domain/wp-comments-post.php and not omain/category1/hellopost/wp-comments-post.php
Then using back button and reload the reply will be showns...


Maybe also to do with this change?
https://make.wordpress.org/core/2015/09/25/changes-to-fields-output-by-comment_form-in-wordpress-4-4/

**Comment by Reedyseth** [comment]
Are you using this on a development site? Do you have URL?

**Comment by extremecarver** [comment]
I used it on all my sites:

you can try out here:
https://openmtbmap.org/test3/support/comment-page-3/#comment-15866

it looks pretty wild because it's twenty sixteen theme and no plugins but
subscribe to comments activated.

just reply to your own comment or my test comment on top. Not to some other
in order to feed them unwanted emails.

On 26 June 2016 at 16:46, Israel Barragan C. <notifications@github.com>
wrote:

> Are you using this on a development site? Do you have URL?
> On Jun 26, 2016 8:23 AM, "extremecarver (felix)" <notifications@github.com
> >
> wrote:
>
> > Wow - quick reply. Oh forgot to say - page is blank and url will be:
> > domain/wp-comments-post.php - no matter on which subpage it was written.
> > WP permalink structure is custom - but the common:
> /%category%/%postname%/
> > So something bout the rewriting is clearly broken here.
> >
> > So if you reply to a comment on domain/category1/hellopost --> you will
> be
> > redirected to domain/wp-comments-post.php and not
> > omain/category1/hellopost/wp-comments-post.php
> > Then using back button and reload the reply will be showns...
> >
> > Maybe also to do with this change?
> >
> >
> https://make.wordpress.org/core/2015/09/25/changes-to-fields-output-by-comment_form-in-wordpress-4-4/
> >
> > —
> > You are receiving this because you were assigned.
> > Reply to this email directly, view it on GitHub
> > <
> https://github.com/stcr/subscribe-to-comments-reloaded/issues/232#issuecomment-228603775
> >,
> > or mute the thread
> > <
> https://github.com/notifications/unsubscribe/ABK_pxYbxDl8kb3HSNuFj9Qu2FuEyqIVks5qPot1gaJpZM4I-j71
> >
>
> > .
> >
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/stcr/subscribe-to-comments-reloaded/issues/232#issuecomment-228604723>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAQQjFFkZOfLZNTNTk1uSpJomQ7zUbrBks5qPpDHgaJpZM4I-j71>
> .
>



-- 
Felix Hartman - Openmtbmap.org & VeloMap.org
Schusterbergweg 32/8
6020 Innsbruck
Austria - Österreich

**Comment by extremecarver** [comment]
Ups - really sorry for the trouble. I just tried out the development version - and using it the problem is gone. Should have done that before reporting.

**Comment by Reedyseth** [comment]
No problem, thank you for reporting anyways.

**Comment by nutellino1** [comment]
Hi all, I have the same problem when I reply to a comment gives me "Internal Server Error" message !

will specifically that the hosting server I have two websites, on a site works and on no.

I have disabled all plugins and activated the default theme, but the problem remains

Can someone help me ?

**Comment by extremecarver** [comment]
For me the problem was gone as soon as I switched to the development version - and then with later updates kept on working. Right now I'm on normal 160915 and it works fine.
(160115 did not work correctly for me - v160831 solved the problem ad did the intermediary dev version).

**Comment by nutellino1** [comment]
Hello @extremecarver, sorry but how do I switched to the development version?
