### ISSUE TITLE
No Subscribe link

### ISSUE THREAD

**Issue by Dysschord** [stcr/subscribe-to-comments-reloaded#234]
I have used this plugin in the past and it worked fine. I installed on my site and the link to Subscribe does not show anywhere. I did add the `<?php if (function_exists('subscribe_reloaded_show')) subscribe_reloaded_show(); ?> ` line to the comments.php but it doesn't make a difference. My theme is Iconic One. I have had to install a different subscribe plugin for now because I need this option. I hope I will be able to migrate current subscribers to Subscribe to comments reloaded. Thanks.

**Comment by Reedyseth** [comment]
Hi @Dysschord you can fix that by using this code insteadÑ

`<?php global $wp_subscribe_reloaded; if (isset($wp_subscribe_reloaded)){ $wp_subscribe_reloaded->stcr->subscribe_reloaded_show(); } ?>`

Some users have fixed this already, seeÑ

https://wordpress.org/support/topic/custom-subscribe-button-placement-no-longer-working?replies=5

Also this fixed and will be available on the next version.

Regards.!!
