### ISSUE TITLE
Comments posting is extremely slow when this plugin is enabled

### ISSUE THREAD

**Issue by Almirouse** [stcr/subscribe-to-comments-reloaded#236]
The more subscribers to a post you have, the more lag you see on new comments.

I'm talking about HUGE lags, from few seconds to more than a minute before the page refresh, if you have ten subscribers for example.

Can you fix this issue please?

For example, I guess that mails could be delievered asynchronously, after the page reloads.

**Comment by Reedyseth** [comment]
Thank you @Almirouse,

I will keep my eyes on this issue.

Regards.@@

**Comment by Almirouse** [comment]
Thank you! The fix is pretty critical because on large websites the plugin becomes totally unusable!

**Comment by Reedyseth** [comment]
I am closing this issue since is duplicated from https://github.com/stcr/subscribe-to-comments-reloaded/issues/227 and is already reported. I am taking care of this, but since this is a big change it will take a while to get it done.
