### ISSUE TITLE
404 Error on Google Webmaster Tool

### ISSUE THREAD

**Issue by Polipo2** [stcr/subscribe-to-comments-reloaded#239]
Hello, I deactivated StCr plugin because I moved to Disqus, after that I have too many 404 errors on GWT.

For example:
comment-subscriptions?srp=49139&srk=f69acae3919548a804e12af6e661f69b&sra=s
comment-subscriptions?srp=50048&srk=f69acae3919548a804e12af6e661f69b&sra=s
comment-subscriptions?srp=40160&srk=f69acae3919548a804e12af6e661f69b&sra=s

I have 4000+ 404 errors, can you help me?

**Comment by Reedyseth** [comment]
@Polipo2 
That is because google indexed your site, eventually they will disappear. There is nothing I can do on my side.

Regards.!!
