### ISSUE TITLE
delete coment form

### ISSUE THREAD

**Issue by MuslimaChallenge** [stcr/subscribe-to-comments-reloaded#240]
Hello ,

I ' like to know how to delete the comment form knew my page legal notices please .

Thank you

**Comment by Reedyseth** [comment]
Hello @MuslimaChallenge, you can search for that on the WordPress Codex.
StCR only display a chechbox with its label.

If you want to remove that chechbox you can disable the plugin or go to the
plugin options and disable the checkbox display option.

Regards.!!
