### ISSUE TITLE
bug checkbox

### ISSUE THREAD

**Issue by MuslimaChallenge** [stcr/subscribe-to-comments-reloaded#241]
Hello ,

I zeroed my bog, and when I reactivated STCL well check the cache does not appear ...

Here the setting.

Enable the checkbox by default
  Yes

Checked by default
          No

advanced membership
  Yes

Here is my website:
http://muslimachallenge.fr/2014/09/20/simple-image-post/

Can you help me please ?

Sabah

**Comment by Reedyseth** [comment]
HI @MuslimaChallenge 

DId you add a real management page in a custom template?
