### ISSUE TITLE
he-IL translation of subscribe options not appearing

### ISSUE THREAD

**Issue by igendel** [stcr/subscribe-to-comments-reloaded#246]
Hi, thanks for this great plugin!

In my blog I recently switched from default subscription type to the drop-down box. While the other plugin strings appear in Hebrew as expected, in the drop-down box itself I see the options in English - "Don't subscribe", "All", "Replies to my comments".

While not an expert, I did use Poedit to check the .po file; it already has the correct translations for these strings. I exported and uploaded the .mo, but it didn't help. 

Sincerely,

**Comment by Reedyseth** [comment]
Hello @ido,

Open your translation file with any editor and search for a string with the
value **fuzzy**. Get rid of that complete line. You have to do this on
every match so you can use the search and replace function of your editor.

Then save the file and now open it with Poedit and click on update to get
the reference. Now repeat the same steps once more. With that you should
get the translation cleansed.

Let me know how it goes.

**Comment by igendel** [comment]
That's one fast response! 

I couldn't find any instance of "fuzzy" in the entire .po file... the relevant string records seem to be something like this (of course the Hebrew font won't show up correctly here):

#: <option value='none'" . ( get_option(
#: 'subscribe_reloaded_default_subscription_type' ) === '0' ?
#: "selected='selected'" : '' ">" __( "Don't subscribe", 'subscribe-reloaded'
#: "</option> value='yes'" '1' "All", value='replies'" '2' "Replies to my
#: comments",
msgctxt "efa1fb8216b5f6d2b76c9fc617f48b38"
msgid "All"
msgstr "כל התגובות"

Thanks,

**Comment by Reedyseth** [comment]
Please send me your files and the versión that you are using, as soon as I
have a change I will check it out.

My email is reedyseth (at} Gmail [d0t) com

**Comment by Reedyseth** [comment]
Here is the translated file in case someone need it. It works for the version 160115

https://gist.github.com/Reedyseth/7cec8ed5e324b12e9e6580d22785cc8c
