### ISSUE TITLE
Bug Report: Comment form formatting broke

### ISSUE THREAD

**Issue by DavidFB1** [stcr/subscribe-to-comments-reloaded#251]
The latest update broke the formatting, placing the "manage" sentence and link right after the "Comment" label and winding down the side of the comment box. This is in Cryout Creations Mantra theme. It was formatted reasonably prior.

![subscribe-error](https://cloud.githubusercontent.com/assets/19560675/18156047/ea59bd52-6fc7-11e6-8e42-7f6f459f0de6.gif)

**Comment by Reedyseth** [comment]
Hello @DavidFB1 ,

The subscription message goes above the submit button, the form used by the them should be using the Standar wordpress rules. You will have to update your CSS styles of the form accordingly.

What is your site URL ?

**Comment by DavidFB1** [comment]
Hi Reedyseth
The site is Davidya.ca
I have the plugin disabled at the moment due to the issue.
I can add custom CSS to the theme. Can you suggest what might work?

**Comment by Reedyseth** [comment]
@DavidFB1 WIth in your site with the plugin disabled I cannot play with the CSS, I have another site with a theme with the same issue so I will give some test on it or if your theme is free I can download it and test it.

**Comment by DavidFB1** [comment]
Yes the theme is free
https://www.cryoutcreations.eu/wordpress-themes/mantra
Thanks!

**Comment by Reedyseth** [comment]
Awesome, that will Work. Thanks

**Comment by Reedyseth** [comment]
@DavidFB1 I downloaded the theme and replicate the issue, the thing is that the theme is adding some floating into the form elements, so you can fix the mess with this code:

```html
<div style="clear: both;"></div>
You are subscribed to this post. <a href="[manager_link]">Manage</a> your subscriptions.
```

![image](https://cloud.githubusercontent.com/assets/1228711/18259960/de6443f4-73a6-11e6-84d4-f6d85ca5118f.png)

**Comment by DavidFB1** [comment]
Thank you! Much appreciate the effort. 
I also added the DIV tag to Default and Author fields so it fixed it for all users. 
Thats a fix!

**Comment by Reedyseth** [comment]
> I also added the DIV tag to Default and Author fields so it fixed it for all users. 
> Thats a fix!

Awesome, great to read that eveything is working.
