### ISSUE TITLE
subscribe_link generate wrong URL

### ISSUE THREAD

**Issue by micha1848** [stcr/subscribe-to-comments-reloaded#253]
on My Page the "subscribe_link" generates the Wrong URL if the User is not loged in.
The the : is missing...
So it produced a Link like: https//......

If your logged in, it produced the right link: https://......

_Version 160831 of the Plugin and WP = 4.6._

**Comment by Reedyseth** [comment]
@micha1848 

OK, let me check that out and I will come back with more info.

**Comment by Reedyseth** [comment]
@micha1848 I went into a deep search and I could not find that issue, the url is generated by wordpress, make sure that your general settings are pointing to the correct site.

**Comment by micha1848** [comment]
@Reedyseth 
now iam realy confused.... 
If the link is set by your original Message, all is ok. If i wrote a translation and put in the Shortcode to the Linkfield, the ":" goes away.... 
After a deeper look from my site, the Proplem seems the TinyMCE. It wrote for the Shortcode the following code:
`<a href="http://[manager_link]">`

So i think it was half my mistake. Never Trust a WYSIWYG Editor ;-)

**Comment by Reedyseth** [comment]
> After a deeper look from my site, the Proplem seems the TinyMCE. It wrote for the Shortcode the following code:
> <a href="http://[manager_link]">
> 
> So i think it was half my mistake. Never Trust a WYSIWYG Editor ;-)

Yes, when you add the tag it add by default the `http://` protocol, I always click the gear icon and make sure that the tag is clean. The cooll thing in this new version is that you can switch between the Visual and Text view.

So all is good ?

**Comment by Reedyseth** [comment]
Hi @micha1848 

> After a deeper look from my site, the Proplem seems the TinyMCE. It wrote for the Shortcode the following code:
> `<a href="http://[manager_link]">`

Yes, by default when you add a link WordPress adds you the `http://` protocol, I always click the gear Icon to make sure that everything is clean. The good think is that with the new update you can switch between the Visual view and the Text view, so you have access to the HTML code.

So all is good?

**Comment by micha1848** [comment]
Sorry for late reply, i must earn some Money the last days ;-)

Yes its all ok, was a silly fault by myself.
