### ISSUE TITLE
Feature Request: Tags for Management Page message

### ISSUE THREAD

**Issue by vbdeco** [stcr/subscribe-to-comments-reloaded#254]
Hi,

Do you think it will possible to allow these tags for the Management Page message : [post_permalink] and [post_title].

It will be great for a "return to post" message at the end.

Regards... And thank you for this work !

**Comment by Reedyseth** [comment]
Yes, it is possible and this will be ready for the next release. Thank you for the suggestion.

**Comment by Reedyseth** [comment]
Instead of adding the tag I add a back to post link. Having this option enable make sense so no need to add it on the comments settings.

![image](https://cloud.githubusercontent.com/assets/1228711/25208979/466cf0aa-2535-11e7-90c0-42401ee392f5.png)
