### ISSUE TITLE
Bug Report: Subscribing without Leaving a Comment

### ISSUE THREAD

**Issue by oliverands** [stcr/subscribe-to-comments-reloaded#255]
I have just updated to v 160831. It appears that when someone tries to subscribe to comments on a post without leaving a comment, their subscription does not get saved. The whole process works (they see the confirmation page and get an email confirmation) but the email address is not saved for sending future comments.

The process works fine, though, if someone leaves a comment and requests to subscribe.

**Comment by Reedyseth** [comment]
Hi @oliverands I apologize for the inconvenience, I have spot that issue and will be releasing the update later in the day, thank you for the report.

**Comment by Reedyseth** [comment]
@oliverands I released a new version so please update.

**Comment by oliverands** [comment]
Thank you for the quick fix!

**Comment by Reedyseth** [comment]
I will be closing this issue to clean the queue, if you feel that is not yet resolve feel free to reopen it.
