### ISSUE TITLE
Lost all subscribers

### ISSUE THREAD

**Issue by daxmacrog** [stcr/subscribe-to-comments-reloaded#261]
All of my subscribers have disappeared. I believe it happened after the most recent update to the plugin.

I tried deactivating and reactivating the plugin, per the FAQ, but it still doesn't list any subscribers. If I click “view all the subscriptions,” it does not find any, although I know I had about a dozen or so.

I took a look at my wp_postmeta database table. The records are still there (meta keys that start with _stcr@_ along with their values).

I am running WordPress version 4.6.1 and Subscribe to Comments Reloaded version 160902

**Comment by Reedyseth** [comment]
Hello @daxmacrog , This is the first time that someone report something like this. To me it sounds that you have some issues with your MySQL version, what MySQL and PHP version are you using?

**Comment by daxmacrog** [comment]
Thanks @Reedyseth. MySQL 5.5 (InnoDB type and utf8mb4_unicode_ci collation) and PHP 5.6.

**Comment by Reedyseth** [comment]
@daxmacrog I just tested StCR with those versions and have no issues. What does your apache error logs says ?

**Comment by daxmacrog** [comment]
I turned on error reporting. This error was logged after attempting to leave a new comment with “Replies to my comment” selected (database name removed):

`[09-Sep-2016 14:08:06 UTC] WordPress database error Table 'database_name.wp_subscribe_reloaded_subscribers' doesn't exist for query 
			SELECT meta_id, REPLACE(meta_key, '_stcr@_', '') AS email, post_id, SUBSTRING(meta_value, 1, 19) AS dt, SUBSTRING(meta_value, 21) AS status, srs.subscriber_unique_id AS email_key
			FROM wp_postmeta
			INNER JOIN wp_subscribe_reloaded_subscribers srs ON ( REPLACE(meta_key, '_stcr@_', '') = srs.subscriber_email  )
			WHERE meta_key LIKE '\_stcr@\_%'  AND post_id = '3843' AND SUBSTRING(meta_value, 22) = 'C'
			ORDER BY dt ASC
			LIMIT 0,18446744073709551610 made by require('wp-blog-header.php'), require_once('wp-includes/template-loader.php'), include('/themes/packafoma/single.php'), comments_template, require('/themes/packafoma/comments.php'), comment_form, apply_filters('comment_form_submit_field'), stcr\wp_subscribe_reloaded->subscribe_reloaded_show, stcr\wp_subscribe_reloaded->is_user_subscribed, stcr\wp_subscribe_reloaded->get_subscriptions`

**Comment by Reedyseth** [comment]
Can you see the table `wp_subscribe_reloaded_subscribers` in your database?

**Comment by daxmacrog** [comment]
No.

**Comment by daxmacrog** [comment]
@Reedyseth That did it! My subscribers are back. Thank you. Is there anything else I should do to clean up the database?

**Comment by Reedyseth** [comment]
> Is there anything else I should do to clean up the database?

That's all. The only thing that might be corrupted is the encoding of your messages, but if you see all ok and the notifications as well then there are no other database issues.

**Comment by Gunifaz** [comment]
Hello, the same thing happened to me. The problem is that I´m not very good with programming... can someone help me, please? 
Thanks!

**Comment by Reedyseth** [comment]
> The problem is that I´m not very good with programming... can someone help me, please?

@Gunifaz Just go to your PHPMyAdmin and search for the query box. Make sure to select your WordPress database. Paste and execute the following code.

```sql
UPDATE prex_options SET option_value = 'no' WHERE option_name = 'subscribe_reloaded_subscriber_table';
```

**Comment by Gunifaz** [comment]
I will do it and I'll let you know. 
Thank you Israel!

Sent from Yahoo Mail on Android 
 
  On Thu, Sep 29, 2016 at 8:39 AM, Israel Barragan C.<notifications@github.com> wrote:   

The problem is that I´m not very good with programming... can someone help me, please?


@Gunifaz Just go to your PHPMyAdmin and search for the query box. Make sure to select your WordPress database. Paste and execute the following code.
UPDATE prex_options SET option_value = 'no' WHERE option_name = 'subscribe_reloaded_subscriber_table';
