### ISSUE TITLE
One Click Unsubscribe – Slug of the permalink instead of the real post title

### ISSUE THREAD

**Issue by Reedyseth** [stcr/subscribe-to-comments-reloaded#269]
This was Reported by [@ben69007](https://wordpress.org/support/users/ben69007/) here:

https://wordpress.org/support/topic/one-click-unsubscribe-slug-of-the-permalink-instead-of-the-real-post-title/

> Hello Reedyseth,
> 
> Update installed and operational here. Congratulations for all improvement.
> 
> I have noted couple of things, if you have time to check it out and try to reproduce.
> 
> – The [post_title] shortcode in the Content of the One Click confirmation, in the Notifications tab, shows in output the slug of the permalink instead of the real post title.
> 
> – Where can I contribute to translate new fields of this new StCR version ? I searched here is it that ? Because of new fields Management Page message, Management Email message and One Click Unsubscribe.. the FR translation (I think this is the same for other languages) gives “Permettre aux admins de s’abonner” which means “Allow to admin to subscribe” instead of One Clik Unsubscribe, and this is the same thing for the help text under the field. It doesn’t correspond to the action of this option and could mislead users. Other things need to be translated too like “Choose an action” in the dropdown menu, or “You have request to manage another email address and this is forbidden.” etc.
> Tell me where to go I will update 🙂
> 
> This new version is very smart and for now I do not have any other issue.
> 
> Best regards!

**Comment by patrickheck** [comment]
I'm having the same problem here with version 190529.
