### ISSUE TITLE
Error when subscribing

### ISSUE THREAD

**Issue by alexstine** [stcr/subscribe-to-comments-reloaded#286]
Hello,

First I was not getting emails, so I did some debugging. With all other plugins deactivated with the Twenty Sixteen theme, this is the errors I was shown when trying to subscribe.

Fatal error: Uncaught exception 'phpmailerException' with message 'Invalid address: ' in /homepublic_html/wp-includes/class-phpmailer.php:946 Stack trace: #0 /home/public_html/wp-includes/pluggable.php(352): PHPMailer->setFrom('', 'The News Triang...', false) #1 /home/public_html/wp-content/plugins/subscribe-to-comments-reloaded/utils/stcr_manage.php(157): wp_mail('example@domain.com', 'Please confirm ...', 'You have reques...', 'From: The News ...') #2 /home/public_html/wp-content/plugins/subscribe-to-comments-reloaded/templates/subscribe.php(59): stcr\stcr_manage->confirmation_email(56, 'someone@example.com') #3 /home/public_html/wp-content/plugins/subscribe-to-comments-reloaded/wp_subscribe_reloaded.php(451): include('/home/...') #4 [internal function]: stcr\wp_subscribe_reloaded->subscribe_reloaded_manage(Array, Object(WP_Query)) #5 /home/public_html/wp-includes/plugin.php(291): call_user_func_array(Array, Array) #6 /home/public_html/wp-includes/q in /home/public_html/wp-includes/class-phpmailer.php on line 946

The default emails are working fine. I checked the development version with no improvement.

Suggestions?

**Comment by tech55541** [comment]
Hello @Reedyseth

I can no longer replicate this error message, but email notifications are not being sent. User registration emails are working using the same address, and [This Plugin](https://wordpress.org/plugins/comment-mail/) is having no problems. Something wrong in the code here.

I also have SSL enabled on my site if this makes a difference.

Thanks for the great plugin, would like to start using it soon.

**Comment by IrishKnight** [comment]
Hello,

Thanks for the great job!

I'm facing exactly the same issue. Hopefully it will be resolved soon. Can't use the plugin.

**Comment by tech55541** [comment]
@IrishKnight, this request has been open for quite a while, might want to start looking for another plugin. I use this plugin and am quite satisfied with it. They have a support team that will reply to you as well.
http://comment-mail.com/
They have a free plugin and a pro version of the plugin. Really great, developers are one step away to discuss with on GitHub.

Thanks.
