### ISSUE TITLE
Bug Report: <comment notifications not displaying properly>

### ISSUE THREAD

**Issue by asideofsweet** [stcr/subscribe-to-comments-reloaded#292]
My comment notification emails from my website (http://asideofsweet.com) are showing up as the code version instead of a pretty text version (see screenshot). Any ideas on how to fix this? Thanks!

<img width="794" alt="screen shot 2016-11-01 at 1 27 27 pm" src="https://cloud.githubusercontent.com/assets/23199592/19906169/f84677d0-a036-11e6-8e41-2822db1bf98c.png">

**Comment by Reedyseth** [comment]
@asideofsweet I apologize for the late response. Please enable the HTML email option. If your issue is not resolve feel free to reopen the issue.
