### ISSUE TITLE
problem subscriber

### ISSUE THREAD

**Issue by emiliano1991** [stcr/subscribe-to-comments-reloaded#295]
hi, 

i've an issue with subscribers.
When an user subscribe to post, it's not saved on list.
the list is ever empty.

why ? 

i've just try to deletel completely the plugin and re install.

it's happen also on my server.
if i try to the same site on local works.

thanks

**Comment by Reedyseth** [comment]
Hi @emiliano1991 I apologize for the late response. Can you confirm that you don't have this bug anymore. Feel free to reopen the issue.

Regards.!!
