### ISSUE TITLE
[manager_link]

### ISSUE THREAD

**Issue by nullproblemo** [stcr/subscribe-to-comments-reloaded#296]
When a subscriber clicks on the link he got he doesn't see the management page but only this: [manager_link]

**Comment by OleksiiPieshkov** [comment]
I have nearest problem. By clicking this link I've got the empty page without any managing function. Same situation to press button int he comments "Manage your subscriptions" - will get empty page. Will be glad for advice with solution. 
P.S. Users not allowed on website in admin panel (https://lifeisfreedom.net/).

**Comment by aaron13100** [comment]
I also have this issue.
![screen shot 2016-12-18 at 9 15 11 am](https://cloud.githubusercontent.com/assets/16979849/21292362/d38233b2-c502-11e6-8676-dbfd8e8a97a1.png)

**Comment by Reedyseth** [comment]
Hello Guys, I apologize for the late response. This is because the link is not created correctly. I urge you to watch this video where I teach you how to create the links.

https://youtu.be/eFW-2NIRzBA
