### ISSUE TITLE
confirm link no longer working

### ISSUE THREAD

**Issue by ropezg** [stcr/subscribe-to-comments-reloaded#297]
Hi!

I've been using this plugin for over a year now and just today realized that something went wrong:

The confirm link is no longer working.

I tested subscription with "Replies only" and "All comments" option and also the Simple subscription checkbox, the result is the same.

So I write a comment and I receive the email:

You have requested to be notified every time a new comment is added to: <blog name - cut>
Please confirm your request by clicking on this link:

<link>

I click on the link and I go to the Manage subscriptions
All I can see is:
You have requested to manage your subscriptions to the articles on Blog name

so I am not able to confirm the subscription.

I don't understand what went wrong, I assume something went wong with the last update

any suggestions!

thanks!

**Comment by rimshot212** [comment]
I'm having this problem as well.

**Comment by Reedyseth** [comment]
Hello Guys, I apologize for not keeping track of this issue the project is out of budget and I am out of time. I will keep my hands into your issues as soon as I can. Best Regards.!!

**Comment by Merllin** [comment]
I think it's a conflict in your database, check this: [https://github.com/stcr/subscribe-to-comments-reloaded/issues/303](url)
If you will find something simillar in your error_log, you should change the collation for table wp_subscribe_reloaded_subscribers

**Comment by Merllin** [comment]
You should also check this: https://github.com/stcr/subscribe-to-comments-reloaded/issues/250#issuecomment-253162823

**Comment by martindnnetdk** [comment]
Hi
I'm also having this problem and I've tried the solutions as described in this thread however none of them worked.
Is there anything new to this matter?

**Comment by Merllin** [comment]
Check  yoursite.com/error_log and yoursite.com/wp-content/plugins/subscribe-to-comments-reloaded/utils/log.txt and post the content here.

**Comment by Reedyseth** [comment]
Issue solved on #305
