### ISSUE TITLE
Bug Report: Getting 404 page when confirming comment subscription

### ISSUE THREAD

**Issue by parker-west** [stcr/subscribe-to-comments-reloaded#300]
Hello,

My users are getting a 404 when confirming their comment subscriptions via the confirmation email that gets sent. Any idea why this might be happening?

**Comment by rimshot212** [comment]
Here is a page that you can use for testing: https://www.cardpaymentoptions.com/credit-card-processors/card-cutters/

**Comment by Merllin** [comment]
Try this: [https://github.com/stcr/subscribe-to-comments-reloaded/issues/305#issuecomment-269227173](url)
