### ISSUE TITLE
Manage subscription page not found

### ISSUE THREAD

**Issue by wyse92** [stcr/subscribe-to-comments-reloaded#305]
I’m using Subscribe To Comments Reloaded v160915 and when people click the link to see or update their subscription, they get a ‘page not found’ error. The virtual management page is activated.

It’s a new case because i didn’t had this kind of problem using previous releases.

This is a great Plugin, but i don’t know how to investigate to resolve that.

Thanks for help.

**Comment by Merllin** [comment]
Probable cause is a conflict in your database. Could you post the error log here?

**Comment by wyse92** [comment]
Hello and merry Christmas!

I suppose you mean SQL error_log ?

Thanks

**Comment by Merllin** [comment]
In /wp-content/plugins/subscribe-to-comments-reloaded//utils/stcr_manage.php, on line **124**, change **sre** with **srek**:
`$manager_link` .= ( ( strpos( $manager_link, '?' ) !== false ) ? '&' : '?' ) . "srek=" . $this->utils->get_subscriber_key( $clean_email ) . `"&srk=$subscriber_salt";`

And check your site error log if is something related to subscribe to comments
![error_log](https://cloud.githubusercontent.com/assets/450304/21484559/2f575960-cb9d-11e6-8fd7-2491f3228745.jpg)

**Comment by Reedyseth** [comment]
This issue is the same issue #329, this issue is older but they refer to the same problem.

**Comment by Reedyseth** [comment]
@Merllin Thank you for your time to share the code.
