### ISSUE TITLE
Suggestion: disable the log

### ISSUE THREAD

**Issue by xberg** [stcr/subscribe-to-comments-reloaded#312]
Hi,
Your plugin automatically generates a log file with all the commentors' email in clear text. Not great for spam. 
Can we disable this?
thanks

**Comment by Reedyseth** [comment]
Hi @xberg , I apologize for the late response.

> Can we disable this?

Yes, but on the current version this is not available. I have worked on this and the next update will contain this option to disabled it and also to deleted in case the file is large.

As a plus option I have added the option to auto purge the log in case you want to have it enable but want to keep control of the file size. This will run hourly, twice day and daily.

![loggin_options](https://behstant.com/blog/wp-content/uploads/2017/04/ScreenShot034.jpg)

**Comment by xberg** [comment]
Fantastic: thanks!
If I may suggest: I would recommend having the log off my default: once it's known by spammers that there is a log file with email addresses, they will simply spider all wordpress sites to see if they contain your plugin and then retrieve the log file with emails.

**Comment by Reedyseth** [comment]
> I would recommend having the log off my default: once it's known by spammers that there is a log file with email addresses, they will simply spider all wordpress sites to see if they contain your plugin and then retrieve the log file with emails.

Thank you for the suggestion. I have already set it up to off by default.
