### ISSUE TITLE
Bug Report: Optin option not showing up

### ISSUE THREAD

**Issue by Snixykitchen** [stcr/subscribe-to-comments-reloaded#313]
I have the plugin installed and activated but the comment opt in is not showing up - it used to work fully but as of September, it is no longer appearing on my blog. ([snixykitchen.com](url))

**Comment by Reedyseth** [comment]
@Snixykitchen I apologize for the late response. There could 2 reasons of why the subscription box is not display.

1. Your plugin them is no developed with the WordPress coding standars. On this case you can go to the options and then set to Yes the option to **StCR Position**.
2. Make sure that your theme is not applying a `display none;` attribute to the comment form label.
