### ISSUE TITLE
Bug Report: Adding Email bug

### ISSUE THREAD

**Issue by viriava** [stcr/subscribe-to-comments-reloaded#316]
Hello, when i add my email, i do not see on plugin backend. you can try here https://www.reliablepsd.com/comment-subscriptions/

http://take.ms/kP0nT is empty

maybe plugin conflicts?

i have this
http://take.ms/HL3kG
http://take.ms/Cb880

subscribe_reloaded_admin_bcc: no
subscribe_reloaded_admin_subscribe: no
subscribe_reloaded_author_label: You can <a href='[manager_link]'>manage the subscriptions</a> of this post.
subscribe_reloaded_author_text: In order to cancel or suspend one or more notifications, select the corresponding checkbox(es) and click on the button at the end of the list.
subscribe_reloaded_checkbox_html: <p class='comment-form-subscriptions'><label for='subscribe-reloaded'>[checkbox_field] <span>[checkbox_label]</span></label></p>
subscribe_reloaded_checkbox_inline_style: width:30px
subscribe_reloaded_checkbox_label: Notify me of followup comments via e-mail. You can also <a href='[subscribe_link]'>subscribe</a> without commenting.
subscribe_reloaded_checked_by_default: yes
subscribe_reloaded_checked_by_default_value: 0
subscribe_reloaded_custom_header_meta: <meta name='robots' content='noindex,nofollow'>
subscribe_reloaded_data_sanitized: yes
subscribe_reloaded_default_subscription_type: 2
subscribe_reloaded_deferred_admin_notices: a:1:{s:25:"notify_update_new_install";a:4:{s:6:"status";s:4:"read";s:7:"message";s:901:"<p><strong>Thank you for installing Subscribe to Comments Reloaded!</strong>.</p><p>If you find a bug or an issue you can report it <a href="https://github.com/stcr/subscribe-to-comments-reloaded/issues" target="_blank">here</a>.</p><p>Please consider to make a donation to support the plugin, you can donate via <a href="
https://www.paypal.com/cgi-bin/webscr?cmd=_donations&business=XF86X93FDCGYA&lc=US&item_name=Datasoft%20Engineering&item_number=DI%2dSTCR¤cy_code=USD&bn=PP%2dDonationsBF%3abtn_donate_LG%2egif%3aNonHosted" target="_blank">PayPal</a>.</p><p>Please visit the <a href="https://wordpress.org/plugins/subscribe-to-comments-reloaded/changelog/" target="_blank">Changelog</a> for detailed information on plugin changes.<a class="dismiss" href="#">Dismiss.  </a><img class="stcr-loading-animation" src="https://www.reliablepsd.com/wp-admin//images/loading.gif" alt="Working..."></p>";s:4:"type";s:7:"updated";s:5:"nonce";i:0;}}
subscribe_reloaded_double_check_content: You have requested to be notified every time a new comment is added to:
[post_permalink]

Please confirm your request by clicking on this link:
[confirm_link]
subscribe_reloaded_double_check_subject: Please confirm your subscription to [post_title]
subscribe_reloaded_enable_admin_messages: no
subscribe_reloaded_enable_advanced_subscriptions: no
subscribe_reloaded_enable_double_check: no
subscribe_reloaded_enable_html_emails: yes
subscribe_reloaded_fresh_install: no
subscribe_reloaded_from_email: hello@reliablepsd.com
subscribe_reloaded_from_name: Reliable
subscribe_reloaded_htmlify_message_links: no
subscribe_reloaded_management_content: You have requested to manage your subscriptions to the articles on [blog_name]. Please check the Subscriptions management link in your email
subscribe_reloaded_management_email_content: You have requested to manage your subscriptions to the articles on [blog_name]. Follow this link to access your personal page:
[manager_link]
subscribe_reloaded_management_subject: Manage your subscriptions on [blog_name]
subscribe_reloaded_manager_page: /comment-subscriptions/
subscribe_reloaded_manager_page_enabled: yes
subscribe_reloaded_manager_page_title: Manage subscriptions
subscribe_reloaded_notification_content: There is a new comment to [post_title].
Comment Link: [comment_permalink]
Author: [comment_author]
Comment:
[comment_content]
Permalink: [post_permalink]
Manage your subscriptions: [manager_link]
subscribe_reloaded_notification_subject: There is a new comment to [post_title]
subscribe_reloaded_notify_authors: no
subscribe_reloaded_oneclick_text: <p>Your are not longer subscribe to the post:</p>

<h3>[post_title]</h3>
<br>
subscribe_reloaded_process_trackbacks: no
subscribe_reloaded_purge_days: 30
subscribe_reloaded_reply_to: 
subscribe_reloaded_request_mgmt_link: To manage your subscriptions, please enter your email address here below. We will send you a message containing the link to access your personal management page.
subscribe_reloaded_request_mgmt_link_thankyou: Thank you for using our subscription service. Your request has been completed, and you should receive an email with the management link in a few minutes.
subscribe_reloaded_safely_uninstall: yes
subscribe_reloaded_show_subscription_box: yes
subscribe_reloaded_stcr_position: no
subscribe_reloaded_subscribe_without_commenting: You can follow the discussion on <strong>[post_title]</strong> without having to leave a comment. Cool, huh? Just enter your email address in the form here below and you're all set.
subscribe_reloaded_subscribed_label: You are subscribed to this post. <a href='[manager_link]'>Manage</a> your subscriptions.
subscribe_reloaded_subscribed_waiting_label: Your subscription to this post needs to be confirmed. <a href='[manager_link]'>Manage your subscriptions</a>.
subscribe_reloaded_subscriber_table: yes
subscribe_reloaded_subscription_confirmed: Thank you for using our subscription service. Your request has been completed. You will receive a notification email every time a new comment to this article is approved and posted by the administrator.
subscribe_reloaded_subscription_confirmed_dci: Thank you for using our subscription service. In order to confirm your request, please check your email for the verification message and follow the instructions.
subscribe_reloaded_unique_key: f673ba871b1ef8913f16af8f20189c1d
subscribe_reloaded_user_text: In order to cancel or suspend one or more notifications, select the corresponding checkbox(es) and click on the button at the end of the list. You are currently subscribed to:
subscribe_reloaded_version: 160915
subscribe_reloaded_virtual_manager_page_enabled: yes
.
.
Custom_Post_Type: post| page| attachment| revision| nav_menu_item| custom_css| customize_changeset| acf| order
Permalink_Structure: /%postname%/

**Comment by Reedyseth** [comment]
> Hello, when i add my email, i do not see on plugin backend. you can try here https://www.reliablepsd.com/comment-subscriptions/

Hi, can you share the steps that you did so that I can recreate the issue on my dev side.

Is yours the reliablepsd site?

**Comment by viriava** [comment]
Hello, i just activated plugin. 

but it works on demo server. when i clone... any ideas?

plugins and themes and hosting is same

thank you

**Comment by viriava** [comment]
yes mine website. how can i help?

**Comment by Reedyseth** [comment]
If it's working in one of your side I recommend to verify your server settings and check where is the difference. Let me know what you can do, maybe I can help you...

**Comment by viriava** [comment]
server is same... just different domains. i can pay for the support. thank you

**Comment by Reedyseth** [comment]
@viriava Please send me an email to reedyseth [at} gmail {dot] c0m

**Comment by viriava** [comment]
sent :)
