### ISSUE TITLE
Bug Report: Users not being added; Notifications not sending

### ISSUE THREAD

**Issue by thelawstudentswife** [stcr/subscribe-to-comments-reloaded#317]
Although I have installed/uninstalled, and followed all of the recommended settings, new commenters are not being added to my subscription page even when the notification box is checked (I have it set to be checked by default). They are also not being notified of responses via email. HELP!

**Comment by thelawstudentswife** [comment]
My developer resolved this by doing the following and suggested that I bring it to the developer's attention. Sending to you now!

FROM DEVELOPER:
I found there were collation errors being reported by wordpress in the sites error log:

tail -f errorlog 
WHERE meta_key LIKE '_stcr@\%' AND postid = '24285' AND SUBSTRING(meta_value, 22) = 'C'
ORDER BY dt ASC
LIMIT 0,18446744073709551610 made by require('wp-blog-header.php'), require_once('wp-includes/template-loader.php'), include('/themes/wellplated/single.php'), comments_template, require('/themes/wellplated/comments.php'), comment_form, apply_filters('comment_form_submit_field'), WP_Hook->apply_filters, call_user_func_array, stcr\wp_subscribe_reloaded->subscribe_reloaded_show, stcr\wp_subscribe_reloaded->is_user_subscribed, stcr\wp_subscribe_reloaded->get_subscriptions
[25-Jan-2017 18:09:18 UTC] WordPress database error Illegal mix of collations (utf8mb4_unicode_ci,IMPLICIT) and (utf8mb4_unicode_520_ci,IMPLICIT) for operation '=' for query 
SELECT meta_id, REPLACE(meta_key, '_stcr@', '') AS email, postid, SUBSTRING(meta_value, 1, 19) AS dt, SUBSTRING(meta_value, 21) AS status, srs.subscriber_unique_id AS email_key
FROM wrd_postmeta
INNER JOIN wrd_subscribe_reloaded_subscribers srs ON ( REPLACE(meta_key, '_stcr@', '') = srs.subscriberemail )
WHERE meta_key LIKE '_stcr@\%' AND post_id = '24285' AND SUBSTRING(meta_value, 21) LIKE '%%'
ORDER BY dt ASC
LIMIT 0,18446744073709551610 made by require('wp-blog-header.php'), require_once('wp-includes/template-loader.php'), include('/themes/wellplated/single.php'), comments_template, require('/themes/wellplated/comments.php'), comment_form, apply_filters('comment_form_submit_field'), WP_Hook->apply_filters, call_user_func_array, stcr\wp_subscribe_reloaded->subscribe_reloaded_show, stcr\wp_subscribe_reloaded->is_user_subscribed, stcr\wp_subscribe_reloaded->get_subscriptions

The key here is the collation error being reported, I changed these all to to utf8mb4_unicode_ci in wrd_subscribe_reloaded_subscribers. I then killed all php and httpd processes on the server, and restarted Apache in order to ensure all PHP processes in the future would be correctly calling the database.

**Comment by edie-etoile** [comment]
### I got this issue on a new installation.

# To any who need more instructions on how to fix: 

1. Backup your database.
2. Confirm your backup is good.
3. Open database in phpMyAdmin and click on the wpXXX_subscribe_reloaded_subscribers database table.
4. Click on Structure Tab. Notice that the "subscriber_email" and "subscriber_unique_id" columns both have a Collation of: "utf8mb4_unicode_520_ci", which needs to be changed to: "utf8mb4_unicode_ci".
5. Chick on the "Change" icon for each column and use the dropdown menu to change: "utf8mb4_unicode_520_ci" to: "utf8mb4_unicode_ci" and click "Save".
6. Test to see if that worked--it did for me. If not, restore your database from your backup.

Thanks to the Developer for this great plugin and thelawstudentswife for reporting this bug and the solution.

**Comment by peraburek** [comment]
thank you, I had the same issue, changing "subscriber_email" and "subscriber_unique_id" columns both have a Collation of: "utf8mb4_unicode_520_ci", which needs to be changed to: **"utf8mb4_unicode_ci"** helped

problem is resolved, developer should integrate this fix into future releases

**Comment by Reedyseth** [comment]
Hello Guys, thank you for your effort in solving this. The plugin never mess around with the database collation so this error raised on the newer versions of WordPress. I am doing some arrangements to sort this out in the new update. Best regards.!!

**Comment by hadasduvdy** [comment]
Hey,
I'm trying to change the subscriber_email table to "utf8mb4_unicode_ci" and receive an error message that the key length is missing. Added a screenshot:

![sqlerror](https://cloud.githubusercontent.com/assets/26297842/23742922/71eab828-04b7-11e7-81c7-dcd85abbdc17.PNG)

the "subscriber_unique_id" table was fine.

How to solve it?

Thank you,
Hadas

**Comment by hadasduvdy** [comment]
The SQL query full message:

> ALTER TABLE 'wp_subscribe_reloaded_subscribers' CHANGE 'subscriber_email' 'subscriber_email' BLOG;

these are the settings on PHPmyAdmin:
![phpmyadmin_screenshot](https://cloud.githubusercontent.com/assets/26297842/23829921/854302f8-0706-11e7-9f90-33559d0fdba5.PNG)

Thank you,
Hadas

**Comment by Reedyseth** [comment]
> The SQL query full message:
> 
> ALTER TABLE 'wp_subscribe_reloaded_subscribers' CHANGE 'subscriber_email' 'subscriber_email' BLOG;

On that query you are changing the table column type and not the collation, use this query instead:

```sql
ALTER TABLE wp_subscribe_reloaded_subscribers CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
```

**Comment by hadasduvdy** [comment]
Great, it works now!
Thank you!

**Comment by Reedyseth** [comment]
Awesome, great to hear that. Regards.!!

On Mar 12, 2017 1:04 AM, "hadasduvdy" <notifications@github.com> wrote:

Great, it works now!
Thank you!

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/stcr/subscribe-to-comments-reloaded/issues/317#issuecomment-285929058>,
or mute the thread

**Comment by Vibeque** [comment]
Hello Reedyseth, 

I have the same problem (StCR installed last week on WP 4.7.5), and wondered if you think you will have a solution to this in the near future (that doesn't involve digging into the database), as I see the last comment was in March. If it all can work well "out of the box", I will install this plugin on several of my client's sites, as the rest works perfectly :)

Many thanks!

Vibeke

**Comment by Reedyseth** [comment]
Hello guys, I am glad to inform you that the latest version of the plugin takes care of this. It check collation consistency in both your website and the plugin and fix it automatically on the background. Thanks for you contributions.

Best Regards.!!
