### ISSUE TITLE
Can't see subscribers after update

### ISSUE THREAD

**Issue by Placzek** [stcr/subscribe-to-comments-reloaded#318]
Hello,
I updated to the latest version of STCR last night and now I cannot see the thousands of subscribers I had. Please advise at your earliest convenience.

**Comment by Reedyseth** [comment]
Last time I heard about this issue was that for some reason some information was not read correctly by the plugin. On this case you need to make so changes into the database, do you have access to your database with phpMyAdmin ?

**Comment by Placzek** [comment]
Yes, I can access with phpMyAdmin. I also just realized that I am running WP version 4.7.1 and your plugin page says "Compatible up to: 4.7-alpha". Is this a problem?

**Comment by Reedyseth** [comment]
> I am running WP version 4.7.1 and your plugin page says "Compatible up to: 4.7-alpha". Is this a problem?

I haven't tested the plugin into that version, so far.

What we can do is deactivate the plugin and then execute the following query:
```sql
UPDATE wp_options SET option_value = 'no' WHERE option_name = 'subscribe_reloaded_subscriber_table';
```
then activate the plugin. This will make sure that your subscribers information is in a table need by the plugin.

Let me know how it goes.

Regards.!!

**Comment by Placzek** [comment]
Thank you for your reply. I received the following:
"MySQL said:
#1146 - Table 'b5362135186919.wp_options' doesn't exist"

**Comment by Reedyseth** [comment]
Make sure to use your correct WordPress table prefix.
