### ISSUE TITLE
Double checking not working

### ISSUE THREAD

**Issue by pedropais** [stcr/subscribe-to-comments-reloaded#319]
When using double checking for email addresses, two issues are occurring, one is a major problem, the other an annoyance:

- Major problem: the link that comes on the email address gets the user to the "Management page message", instead of the "Subscription processed" page. Therefore, the email address is not confirmed and nothing happens.
- Annoyance: althought correctly formatted `<a href="[confirm_link]">[confirm_link]</a>`, the double check email is transformed and the URL appears twice, instead of once.

**Comment by pedropais** [comment]
@Reedyseth , am I the only one having this issue?

**Comment by Reedyseth** [comment]
Hi @pedropais 

I will be trying to replicate your issue. What version of the plugin are you using?
Please send me the information of the **StCR System** menu option to my email at reedyseth {at} gmail [dot) com

**Comment by pedropais** [comment]
Hi @Reedyseth 
Thanks for your reply.
I'm using version 160915 . I'll send you the requested info right away.

**Comment by Reedyseth** [comment]
> I'm using version 160915 . I'll send you the requested info right away.

Thank you, I will review it and you know. I Will update here.

**Comment by pedropais** [comment]
Hi @Reedyseth ,

Sorry to bother, but did you get my email? Any additional info I can provide?

**Comment by Reedyseth** [comment]
Hi, I did give a quick look, but as soon as I have an opportunity I will
give a thorough look and come back to you with suggestions.

**Comment by chrisk87** [comment]
Hi,
i see you fix the line of code (#issues329) and will update in in  Next Release v170412. What is the relase date?

**Comment by Reedyseth** [comment]
> i see you fix the line of code (#issues329) and will update in in  Next Release v170412. What is the relase date?

Yes, I changed the milestone date so that I can make more validations on the fix. So the release date will be on April 28th. Although you can already download the code and test it.

https://github.com/stcr/subscribe-to-comments-reloaded/archive/master.zip
