### ISSUE TITLE
Can't install corrctly on one of my site

### ISSUE THREAD

**Issue by ZcommeZanne** [stcr/subscribe-to-comments-reloaded#322]
Hello,

I can't install correctly Events Manager on www.danselavie.fr (WP 4.7.2 with Divi) : 
![capture d ecran 2017-02-13 a 13 57 55](https://cloud.githubusercontent.com/assets/25743838/22884396/fd73c3ba-f1f4-11e6-8da8-a5d6a8750b6f.png)

I installed it correctly on www.annebeguin.com (WP 4.7.2 with Divi) : ![Uploading Capture d’écran 2017-02-13 à 13.58.18.png…]()

I already uninstalled it and reinstalled it on danselavie.fr.

Could you help me please ?
I really need it on danselavie...

Thanks a lot by advance :-)

Anne

**Comment by Reedyseth** [comment]
Hi @ZcommeZanne , this plugin is not develop for me, this is the repository for Subscribe To Comments Reloaded. I hope you find a solution to your issue.
