### ISSUE TITLE
No notification received unless the person replying is also subscribed

### ISSUE THREAD

**Issue by Acetech76** [stcr/subscribe-to-comments-reloaded#324]
Hi,

I am using stcr on my wordpress 4.5.3 installation and almost everything works as it should, however there is an issue with a subscribed member not receiving a notification when the person replying isn't subscribed themselves.

I noticed this bug was reported a couple of months ago on the wordpress forum however there have been no further updates.

Is there a known workaround for this issue please?

Thanks in advance!

Regards
Gary

EDITED: I accidentally wrote the wrong verson of wordpress (typo), I'm using 4.5.3

**Comment by Reedyseth** [comment]
Hi @Acetech76 , I am afraid to tell you that seems that you are using the first version of the plugin, this repository is for the reloaded version, I doubt that this version of plugin runs in your WordPress version.

Regards.!!

**Comment by Acetech76** [comment]
Hi @Reedyseth 

Sorry that was a typo (a bad one at that), I am using wordpress 4.5.3 and the reloaded

Thanks!

**Comment by Reedyseth** [comment]
> Sorry that was a typo (a bad one at that), I am using wordpress 4.5.3

No problem !

> however there is an issue with a subscribed member not receiving a notification when the person replying isn't subscribed themselves.
> I noticed this bug was reported a couple of months ago on the WordPress forum however there have been no further updates.

@Acetech76 Unfortunately I haven't been in the WordPress forums since a long time. Your issue make sense to me, I have replicate this issue on my dev environment and the work on the fix, I will look into this as soon as I finish a project with a customer.

**Comment by Acetech76** [comment]
Excellent news!

Will the uodate be added here or on wordpress or both (so I know where to keep an eye out)

**Comment by Reedyseth** [comment]
> Will the uodate be added here or on wordpress or both (so I know where to keep an eye out)

The update is release on WordPress, but before releasing the version in WordPress the code will be here, so if you now a bit of coding or installing plugins manually you can test it before is release to the community :smiley:

**Comment by Reedyseth** [comment]
@Acetech76 FYI this error has been fix and ready to be release on the next update.!
