### ISSUE TITLE
Can I auto fill the email address for logged in members?

### ISSUE THREAD

**Issue by Acetech76** [stcr/subscribe-to-comments-reloaded#325]
Hi,

I'm pretty impressed with stcr, however I'm wondering if there is a way to "fetch" a logged in email address to auto fill the email field in the subscription management page to save members needing to fill it in (so they can just click send)?

I did spot a "working on it" post on here however there has been no further updates from what I can see, therefore I was wondering (hoping) that there was a workaround and if someone would be kind enough to tell me how to do it?

Thanks in advance!

Regards
Gary

**Comment by Reedyseth** [comment]
Hi, Please see #324

**Comment by Acetech76** [comment]
Hi @Reedyseth 

I explained on the other post that I made a typo, I am using wordpress 4.5.3 and the reloaded plugin (the latest version from wordpress which I only installed a few days ago).

Regards

**Comment by Reedyseth** [comment]
> however I'm wondering if there is a way to "fetch" a logged in email address to auto fill the email field in the subscription management page to save members needing to fill it in (so they can just click send)?

@Acetech76 , I will look into this, this is a good request and I will be taking a look into it soon.

**Comment by Acetech76** [comment]
That would be great, I'll keep an eye out for updates

Thanks!

**Comment by Reedyseth** [comment]
@Acetech76 I have worked on this request. Just to confirm, the Auto fill is when the Users that are logged in are requesting to be subscribe without commenting correct?

**Comment by Acetech76** [comment]
Hi @Reedyseth,

It's great to hear that you've been working on this!

Yes it's for logged in users clicking to subscribe without commenting but also for logged in users clicking to manage subscriptions on posts they're subscribed to.

Thanks!

**Comment by Reedyseth** [comment]
> but also for logged in users clicking to manage subscriptions on posts they're subscribed to.

Awesome, thank you for your answer. I will add that too :+1:

**Comment by Reedyseth** [comment]
@Acetech76 Enhancement Added !
