### ISSUE TITLE
Subscribers missing ! Collation Error

### ISSUE THREAD

**Issue by ohsik** [stcr/subscribe-to-comments-reloaded#327]
Nothing shows up on the Manage subscriptions page. Search is not working either.

<img width="1364" alt="screen shot 2017-02-25 at 11 54 38 am" src="https://cloud.githubusercontent.com/assets/4256774/23334379/cec297ce-fb51-11e6-9000-af2837c155f8.png">

**Comment by Reedyseth** [comment]
Hello @ohsik,

This is because on the newest version of WordPress not it detect a conflinct between the colations.

In phpMyadmin run this query:

```sql
ALTER TABLE wprn_subscribe_reloaded_subscribers CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
```
If you don't have access to phpMyAdmin then install a WordPress plugin named Database Browse, you can run the query inside your WP Admin Page.

**Comment by Reedyseth** [comment]
Closing this issue because is already reported, See #303
