### ISSUE TITLE
Installed but not working

### ISSUE THREAD

**Issue by meijin2k** [stcr/subscribe-to-comments-reloaded#328]
I have gotten the plugin installed, but cannot get it to function. Everything on the customer facing side looks great. I leave a test comment that does get added to the system, but nothing goes to the test email account I am using. The comment is there in the backend and displays on the post.

I installed the plugin Check Email and using it works as it does show the emails can be sent from WP.

I notice that me test email account does not show up in the subscribed list for StCR. 

When I go into the comments, the far right hand column for "Subscribed" shows "No". When I click on the "No", it tried to take me to the following link which gives me the message, "Sorry, you are not allowed to access this page.".

`http://MyDomainNameHere.com/wp-admin/options-general.php?page=subscribe-to-comments-reloaded/options/index.php&subscribepanel=1&sra=add-subscription&srp=311&sre=michael%40originalwatchgeek.com`

I have made no real changes to StCR as far as settings go, using pretty much the default install configuration.

Lastly, I have the plugin Error Log Monitor installed and I seem to be getting a crap ton of error messages that look to all be related to StCR. I'll post them here if they are need or send them to whoever needs to see them.

My current configuration is as follows:

Dedicated server
CentOS/Apache
Wordpress 4.7.2
PHP 5.6.30
MySQL 5.6.35
WP Rocket 2.9.7
StCR 160915
CloudFlare (paid plan)
Sahifa 5.6.3 (theme)
No SSL (yet)

I am really excited by the functionality that StCR brings to the table and would really like to use it. If anyone can help me with whatever noob mistake I have made, I would very greatly appreciate it.

Thanks...Michael

**Comment by Reedyseth** [comment]
Hello @meijin2k thank you for reporting this. I have confirmed the bug that you reported, this is an easy fix, but it will be available until the next release.

Regards.!!
