### ISSUE TITLE
Bug Report: double-opt-in link leads to file request-managment-link.php instead of confirm.php

### ISSUE THREAD

**Issue by jnz31** [stcr/subscribe-to-comments-reloaded#329]
hi
i installed the tool and checked the option "Enable double check". this works fine, i receive the email with a subscription link. but when i click it, i get redirected to the manage subscriptions page, instead of the confirmation page. if i disable line 462&463 (`$this->utils->_is_valid_key( $key, $email ) && $this->is_user_subscribed( $post_ID, $email, 'C' ) &&`) in wp_subscribe_reloaded.php, i get the correct template, but when i lookup the subscriptions on the subscriptions management page, the status still says "unconfirmed". so i also changed in file templates/confirm.php line 10 to `$wp_subscribe_reloaded->stcr->update_subscription_status( $post_ID, $wp_subscribe_reloaded->stcr->utils->get_subscriber_email_by_key( $email ), '-C' );` (hence the get_subscriber_email_by_key)
since $email is the key here, not the email.

so i guess the problem here is the $email. in your function you handle it like it is the email, whilst it is the subscriber_unique_id..?! maybe?!

with these hacks it works properly, i see the correct template and the status changes to subscribed..

**Comment by jnz31** [comment]
so after a little bit more fiddling i now ONLY changed line 393 ’$email_by_key  = $this->utils->get_subscriber_email_by_key( $sre );’ ( $sre instead of $srek ) in file wp_subscribe_reloaded.php and all seems to work fine..

**Comment by jnz31** [comment]
orrrr. is it, that simply the $_POST key is set false in subscribe-to-comments-reploaded/utils/stcr_manage.php line 124..? instead of sre change it to srek (would make sense, wouldn't it?!), since EK would be Email Key.. muah.

**Comment by Reedyseth** [comment]
Hi @jnz31 thanks for taking the time to look into the code in such a deep way. I might check this issue during this days, I will use your information to narrow things down.

Regards.!!

**Comment by Reedyseth** [comment]
Hi @jnz31 I apologize for the late response. I manage to replicate the issue and I found the root cause. The issue was the generation of the confirmation link, I will be pushing the changes later on the day. Thanks for reporting.

Regards.!!

**Comment by Reedyseth** [comment]
https://github.com/stcr/subscribe-to-comments-reloaded/blob/master/subscribe-to-comments-reloaded/utils/stcr_manage.php#L125
