### ISSUE TITLE
Bug Report: new comment is posted does not work

### ISSUE THREAD

**Issue by sbiddo** [stcr/subscribe-to-comments-reloaded#33]
Email sent to the author of the post when a new comment is posted does not work. It sends out the default wordpress notification

http://wordpress.org/support/topic/post-author-notification-1?replies=10#post-5251560

**Comment by Reedyseth** [comment]
Although this issue is very old the ability to subscribe to Custom Post Types is now available dd3bb95864aca435b231ad4da385d078193fdb54
