### ISSUE TITLE
Bug: Undefined index RC when double option is enable.

### ISSUE THREAD

**Issue by Ysery** [stcr/subscribe-to-comments-reloaded#330]
Hello.
 When I open `wp-admin/admin.php?page=stcr_manage_subscriptions` , the log file writes this:

`PHP Notice: Undefined index: RC in …/wp-content/plugins/subscribe-to-comments-reloaded/options/panel1.php on line 191`

I think that this is something like “Unconfirmed (Неподтверждённый)” (it is not displayed)

![image](https://cloud.githubusercontent.com/assets/24987252/23897900/f6f3ea92-08bf-11e7-92bd-77c38146a740.png)

How to fix it?

Sorry for my English.

**Comment by Reedyseth** [comment]
Hi, thank for for reporting this. I will take a look as soon I finished
some pending issues.

Regards.!!
