### ISSUE TITLE
PHP Fatal error:  Call to undefined method in page-comments-subscription.php

### ISSUE THREAD

**Issue by travispflanz** [stcr/subscribe-to-comments-reloaded#336]
I get this error in my error_log every day for as long as I can remember. I am just now getting around to finding a solution. I have also posted this issue in the plugin's support forum on the WordPress repository, here - https://wordpress.org/support/topic/php-fatal-error-call-to-undefined-method-in-page-comments-subscription-php/

Please advise.

Thanks,
Travis

----------------

[11-Apr-2017 16:04:49 UTC] PHP Fatal error:  Call to undefined method stcr\stcr_subscribe_reloaded::subscribe_reloaded_manage() in /home/webroot/public_html/wp-content/themes/theme1250/page-comments-subscription.php on line 3

**Comment by Reedyseth** [comment]
Hi @travispflanz , This is regarding a method that cannot be find in that context.

Can you paste the code in you template file?

**Comment by travispflanz** [comment]
Uhh... Nevermind. I didn't actually open the file. It appears that a line of code was pasted in the wrong spot. I think someone who was helping me out made a mistake.

**Comment by Reedyseth** [comment]
> Nevermind. I didn't actually open the file. It appears that a line of code was pasted in the wrong spot. I think someone who was helping me out made a mistake.

No problem,thank you for the confirmation.  Regards.!!
