### ISSUE TITLE
Wrong Default Email

### ISSUE THREAD

**Issue by RichardUUU** [stcr/subscribe-to-comments-reloaded#338]
For both the “manage your subscriptions” form and “subscribe without commenting” form, the default email address that pops up is wrong. The email does exist on the computer, but it is not who is logged into wordpress. 

Where does this default come from, and how can I change it? Or, how can I simply turn off having a default pop up?

Ultimately it would be awesome if you could detect the email of logged in users and eliminate the step of entering an email altogether, so we would go straight from "Manage your subscriptions" to the actual management page.

StCR Version 160915 / WordPress 4.7.3

**Comment by Reedyseth** [comment]
Hi @RichardUUU 



> Where does this default come from, and how can I change it? Or, how can I simply turn off having a default pop up?

You can change the sender email address on the options, see the screen below.

![image](https://cloud.githubusercontent.com/assets/1228711/25031753/60bf3b46-208c-11e7-99de-53a1bcde51aa.png)

If you do not set the email address the it will take the default email from the admin wordpress. Right now the plugin uses the default WordPress email function, this lead sometimes to get the notification sent to the spam folder, this issue will be fix on the future when I add the SMTP option.



> Ultimately it would be awesome if you could detect the email of logged in users and eliminate the step of entering an email altogether, so we would go straight from "Manage your subscriptions" to the actual management page.

This will be something that I will get working pretty soon. Stay posted on the update message.

**Comment by RichardUUU** [comment]
There is a misunderstanding. I have filled in the sender email, but this is different. 

My logged-in user (not administrator) clicks on: 
        "Or: subscribe without commenting."

A new page says: "You can follow the discussion on (post name) without needing to leave a comment. Just enter your email address."

Below that is an email field, with a suggested email filled in. It is not the user's email. It is not the sender's email. It is not the administrator's email. It is another email on the computer which has absolutely nothing to do with WordPress. How can I stop that email from showing up?

Thanks, Richard

**Comment by Reedyseth** [comment]
Would you mind sharing a screenshot ?

**Comment by RichardUUU** [comment]
Here it is. I have anonymized the email address. 

![image](https://cloud.githubusercontent.com/assets/14031396/25033581/449fcba8-20ad-11e7-842d-4e4cb82db9cd.png)

**Comment by Reedyseth** [comment]
OK, there is no way that I can replicate the issue, you will have to share your website url so that I can go and run my tests by creating a subscription like any other user will do.

**Comment by RichardUUU** [comment]
Sure. Try it at https://www.freedomite.com/

**Comment by Reedyseth** [comment]
I think you have a cache problem because I just open a post and no email is on the email input area. I registered into the site and No issue has been raised. Please make sure to clean your your browser cache and if you have a Caching plugin do the same as well.
