### ISSUE TITLE
Confusing Menu

### ISSUE THREAD

**Issue by RichardUUU** [stcr/subscribe-to-comments-reloaded#339]
On the management form, below the list of subscribed emails, you have two options: 
Select all Invert selection

It would be much more clear that these are two separate options if there were a separator between them. Maybe a | or just more space would do.

Cheers, Richard

**Comment by Reedyseth** [comment]
> It would be much more clear that these are two separate options if there were a separator between them. Maybe a | or just more space would do.

@RichardUUU This make sense to me. I will work on that and let you know.

**Comment by RichardUUU** [comment]
Thanks very much.

**Comment by Reedyseth** [comment]
Issue fixed.

![image](https://cloud.githubusercontent.com/assets/1228711/25209015/7a72abe2-2535-11e7-8612-4a4a6ba708ae.png)
