### ISSUE TITLE
Font Awesome Use?

### ISSUE THREAD

**Issue by mwaterhouse** [stcr/subscribe-to-comments-reloaded#344]
Hi
I notice font-awesome was added at the last update. But it's being output on both the admin and the user side. I couldn't see anywhere it was being used on the user side - so was that intentional for a future update?
If intended - it's a lot of overhead (30k css + some big font files) to output a few icons so could an option to turn icons off be included?
Thanks.

**Comment by Reedyseth** [comment]
Hello @mwaterhouse , it is used on the management page to style the sorting links and also to use the back arrow.
It is not my intention to remove the Font awesome CSS, but I will add an option to disable it in case someone want to. This will be added on the next reléase.

**Comment by mwaterhouse** [comment]
OK, cool. Admin only is not a problem. But at the moment it's being output in both register_admin_scripts() AND register_plugin_scripts() - which means all site visitors download the code even though it's not used outside of admin :-)

**Comment by Reedyseth** [comment]
Hi, this was also reported here: https://wordpress.org/support/topic/font-awesome-loading-twice/#post-9192060

Update is coming with the fix.

**Comment by Reedyseth** [comment]
Option already available:

![image](https://user-images.githubusercontent.com/1228711/34279956-6ed10e0c-e671-11e7-9282-9839f6b79085.png)
