### ISSUE TITLE
Not very good

### ISSUE THREAD

**Issue by Ysery** [stcr/subscribe-to-comments-reloaded#346]
If js is disabled, then any text entered into the e-mail form is stored in the database

![sn1](https://cloud.githubusercontent.com/assets/24987252/25772175/c020e1b4-326d-11e7-9751-8811856d9c72.PNG)

We open **81** articles

![sn2](https://cloud.githubusercontent.com/assets/24987252/25772174/c01fe4bc-326d-11e7-9e10-3c0f3b2ac7c3.PNG)

Sorry for my English

**Comment by Reedyseth** [comment]
@Ysery Does this happen on the Admin Options or the Management Page ?

**Comment by Ysery** [comment]
**Reedyseth**
It's not visible here _wp-admin/admin.php?page=stcr_manage_subscriptions_

But here you can already see _wp-admin/admin.php?page=stcr_manage_subscriptions&srf=post_id&srt=equals&srv=81_

And here's another example:

![snim](https://cloud.githubusercontent.com/assets/24987252/25775056/d10ff226-32a4-11e7-9ffd-79ee7f7a7187.PNG)

There is no verification if you disable javascript, you can enter that any symbols. And even an e-mail message comes that "a new user has subscribed"

**Comment by Reedyseth** [comment]
Hello @Ysery this issue is solved and will be ready on the next update. Thank you for the report.

Regards.!!
