### ISSUE TITLE
Unable to add subscription

### ISSUE THREAD

**Issue by kaplunkiigirl** [stcr/subscribe-to-comments-reloaded#349]
Hi,

I have StCR installed on one of my sites and it's working perfectly, but I've just installed it on another site and for some unknown reason it's unable to add subscriptions.

I've tried subscribing through the front end, and also using the manual addition in the back end, and neither is being successfully recorded in the list of subscriptions.

I've turned on logging, but I'm not sure where to find the logs. It sounds like a database communication issue, but I'm not sure where to look next to figure out what the problem is.

Any idea what might be going on and what I can do to get it working?

Thanks,

Nikki

**Comment by Reedyseth** [comment]
Hello @kaplunkiigirl , are you running your website on a VPS  or a shared server?

**Comment by kaplunkiigirl** [comment]
On a shared server. I have another site on the same server using the plugin that works perfectly.

**Comment by Reedyseth** [comment]
@kaplunkiigirl , this issue was related with a Database table that the plugin creates, this issue was on version 170428, but it has been fixed on version 170607. Are you using the last version in your fresh install ?

**Comment by kaplunkiigirl** [comment]
I have version 170607 installed, but I haven't yet tried uninstalling and reinstalling the plugin. Do you recommend this?

**Comment by kaplunkiigirl** [comment]
Yep, uninstalling and reinstalling (with a non-safe uninstall) did the trick. Thanks for pointing me in the right direction. All working now!

**Comment by Reedyseth** [comment]
yes, just make sure that you have the option *Safely Uninstall* enable so that you can keep your subscribers.

![image](https://user-images.githubusercontent.com/1228711/27470344-b50b9306-57b0-11e7-84ad-0e08fafd6ecd.png)

so just delete the plugin and then install it again.

**Comment by Reedyseth** [comment]
> Yep, uninstalling and reinstalling (with a non-safe uninstall) did the trick. Thanks for pointing me in the right direction. All working now!

Amazing. Great to hear that everything is working. Just FYI. The **Safe Uninstall** help you to keep the subscribers untouched.

**Comment by kaplunkiigirl** [comment]
I did the unsafe unsubscribe on purpose, because when I did a safe uninstall the problem wasn't fixed, and I assumed that was because the database tables weren't being properly recreated on the reinstall. But due to the bug, I didn't have any subscribers anyway (although I did lose all of my settings each time!)
