### ISSUE TITLE
Double Opt-In problems for Subscription of more than one post

### ISSUE THREAD

**Issue by chrisk87** [stcr/subscribe-to-comments-reloaded#350]
If i want as user to subscribe a second post, i got the message that i already are subscribed.  I got no mail to confirm my subscription. But i check the status of the subscription in the admin wordpress console. The status goes directly to confirmed without any double check. 

Why is the Double Opt-In check only active for the first comment subscription? I need the double opt-in check for each new post comment subscription.

**Comment by Reedyseth** [comment]
Hi @chrisk87 I apologize for the late response. This I have take care of this issue and it will be ready on the next update. Thank you for your report.

Regards.!!
