### ISSUE TITLE
sql error on upgrade script

### ISSUE THREAD

**Issue by nickaccent** [stcr/subscribe-to-comments-reloaded#352]
stcr_upgrade.php line 208, missing space before FROM and missing % sign in LIKE declaration, 

currently:
. "FROM wp_postmeta WHERE meta_key LIKE '_stcr@_%'"

should be:

. " FROM wp_postmeta WHERE meta_key LIKE '%_stcr@_%'"

**Comment by Reedyseth** [comment]
Hi @nickaccent Great catch I will update the code with that space.

Regards.!!

**Comment by nickaccent** [comment]
Please also note the missing the % from before the phrase 'stcr@%' in the original string.

Thanks

**Comment by Reedyseth** [comment]
@nickaccent This function is deprecated on the plugin and will be remove on the next update.

Thanks for catching up that issue though.

**Comment by Reedyseth** [comment]
Issue related #273 & #343

**Comment by Reedyseth** [comment]
This issue is fix on commit 226ce9db5dca0a3a763a0ec19f3ba0632ba7aac0
