### ISSUE TITLE
Support - need help with /?page_id=999999

### ISSUE THREAD

**Issue by terrizgit** [stcr/subscribe-to-comments-reloaded#358]
I have a persistent problem with my management page, /manage-comment-subscriptions/ redirecting to 	https://www.solo-e.com/https:/www.solo-e.com/?page_id=9999999/. For a long time I couldn't figure out where it was coming from, until I happened on the StCR setup pages. The management URL was set correctly to /manage-comment-subscriptions/, so I looked into your instructions more fully.

My permalink structure is /%category%/%postname%/, but since this is a page, it doesn't have a category...

I attempted to dummy up the /manage-comment-subscriptions page to match the permalink, by adding a dummy page /manage-comments/ and then setting the comments page to have the dummy page as a parent /manage-comments/manage-comment-subscriptions/. Now I get this error:  

Fatal error: Call to undefined method stcr\stcr_subscribe_reloaded::subscribe_reloaded_manage() in /home/soloentr/public_html/blog/wp-content/themes/responsive-childtheme-master/commentsubscribe.php on line 51

Please help! Thanks,
Terri Z

**Comment by Reedyseth** [comment]
Hi @terrizgit , you are almost there. The issue here is that calling the functino `subscribe_reloaded_manage()` change a a bit. Use it like this:

```php
<?php 
/* Template Name: Subscribe To Comments */
if (isset($wp_subscribe_reloaded)){ global $posts; $posts = $wp_subscribe_reloaded->stcr->subscribe_reloaded_manage(); } 
?>
```
Check the wiki: https://github.com/stcr/subscribe-to-comments-reloaded/wiki/KB#Real-Page

Regards.!!

**Comment by terrizgit** [comment]
Whew! Thank you, that worked! :)

Peace,
Terri Z

**Comment by Reedyseth** [comment]
> Whew! Thank you, that worked! :)

Amazing, great to hear that. :+1:
