### ISSUE TITLE
STCR CSS/JS optimization

### ISSUE THREAD

**Issue by thegulshankumar** [stcr/subscribe-to-comments-reloaded#360]
Hi,

As we activate STCR plugin, it loads its assets on all pages including the homepage. 
To have light-weight experience for our visitors Below elements should be loaded only if the comment is open on any post.

```
<link rel='stylesheet' id='stcr-plugin-style-css'  href='http://anxious-dingo.w4.poopy.life/wp-content/plugins/subscribe-to-comments-reloaded/includes/css/stcr-plugin-style.css?ver=4.8' type='text/css' media='all' />
<link rel='stylesheet' id='stcr-font-awesome-css'  href='http://anxious-dingo.w4.poopy.life/wp-content/plugins/subscribe-to-comments-reloaded/includes/css/font-awesome.min.css?ver=4.8' type='text/css' media='all' />
<script type='text/javascript' src='http://anxious-dingo.w4.poopy.life/wp-content/plugins/subscribe-to-comments-reloaded/includes/js/stcr-plugin.js?ver=4.8'></script>
```

One more thing, when I activate Shortcodes plugin and this plugin also. I don't know both plugin load same Font-awesome CSS. If there is any workaround to load only one time, it would be best. 

Ref: [Forum](https://wordpress.org/support/topic/a-kind-request/)

Thanks & Regards,
Gulshan

**Comment by Reedyseth** [comment]
Hello @thegulshankumar , on the latest version of the plugin there is an option to stop loading Font-Awesome for this kind of troubles, You just disable that option on the **Options** menu:

![image](https://user-images.githubusercontent.com/1228711/34279543-b5147334-e66e-11e7-9110-d03ec838d61a.png)

The CSS file will not be included on the following versions. As for the JS file right now it will stay they way it is until I find some time to work on it and include it only when is needed and embedded.

Regards.!!

**Comment by thegulshankumar** [comment]
Yes, I can see. Thanks for the kind response.

**Comment by Reedyseth** [comment]
Thanks to you for submitting  the request.

**Comment by Reedyseth** [comment]
Hi @thegulshankumar The optimization of the plugins is completed, it will be available on the next update.
