### ISSUE TITLE
CSS file slows down site load

### ISSUE THREAD

**Issue by cookieandkate** [stcr/subscribe-to-comments-reloaded#361]
Hi, thank you so much for your help with this issue. I'm making a GitHub request per your request. From Wordpress.org:

Hello! Thank you so much for this plugin. I have one little issue with it—it loads render-blocking CSS above-the-fold in the file contentstcr-plugin-style.css.

The only content in that file is .hidden{display:none!important;} and it doesn’t appear to be used with my settings. Is there a better way to implement that code, and/or would it be possible for you to omit that file from future versions so our sites all load as quickly as possible? Thank you!

Viewing 1 replies (of 1 total)
Plugin AuthorReedyseth (@reedyseth)
1 day, 3 hours ago
Hi @cookieandkate, yes it is possible to remove the inclusion of that CSS. I will manage to use the hidden option instead. Just to keep track of the improvement, would you mind open a GitHub issue please?

https://github.com/stcr/subscribe-to-comments-reloaded/issues

Regards.!!

**Comment by Reedyseth** [comment]
Hello @cookieandkate, thank you for taking the time to create the issue here, I will take care of it.

Regards.!!

**Comment by Reedyseth** [comment]
Hello @cookieandkate , I have fix this issue and it will be available on the next release.

For reference you can take a look a this 736ac60, also I am in the process of creating a screen cast to help the users to install the latest code provided here on GitHub so that you don't have to wait until the WordPress update is available.

Regards.!!

**Comment by cookieandkate** [comment]
Thank you, Israel! I really appreciate it.

Kathryne Taylor
http://cookieandkate.com
Facebook <http://facebook.com/cookieandkate> - Instagram
<http://instagram.com/cookieandkate> - Pinterest
<http://pinterest.com/cookieandkate> - Twitter
<http://twitter.com/cookieandkate>
*My cookbook, Love Real Food
<https://www.amazon.com/Love-Real-Food-Feel-Good-Vegetarian/dp/1623367417//ref=as_li_ss_tl?ie=UTF8&linkCode=ll1&tag=cooandkatcb-20&linkId=aef09b59265b7f5698b84fe831b4641a&appview=gmail&usersession=289977>,
is now available!*

**Comment by Reedyseth** [comment]
Here is a video where you can watch the instruction to use the latest code in your site:

https://youtu.be/uQwkBciyFGY
