### ISSUE TITLE
Optimisation JS and CSS

### ISSUE THREAD

**Issue by Ysery** [stcr/subscribe-to-comments-reloaded#363]
I propose to split the file "stcr-plugin.js":
Connect the script "Move-the-Subscription-box.js" on the pages with entries and only when the corresponding option is activated in the settings.
And the other scripts "other-scripts.js" (Validate the email address, Select all subscriptions, Deselect all subscriptions) should be connected only on the comments management page.

CSS font-awesome.min.css the style is removed altogether, replacing the icons from the font with the usual graphic elements.

Sorry for my English.

**Comment by Reedyseth** [comment]
Hello @Ysery I will work in something to improve this scripts. Same as #360

**Comment by Reedyseth** [comment]
Hi @Ysery  The optimization of the plugins is completed, it will be available on the next update.
