### ISSUE TITLE
Bug Report: <Plugin Not Working With Thrive Themes>

### ISSUE THREAD

**Issue by shaikhaquif** [stcr/subscribe-to-comments-reloaded#365]
I tried activating the plugin. However, it does not work with my current theme, Focus Blog by Thrive themes.

I did try to check the option, StCR Position, however, that does not seem to solve the problem.

Below is the link to one of my blog posts
https://www.bloggingocean.com/grammarly-review/

**Comment by Reedyseth** [comment]
Hello @shaikhaquif ,

I do see the advance subscription option. What is your issue?

![image](https://user-images.githubusercontent.com/1228711/29319652-f39887a4-8191-11e7-943c-0bb5737582b8.png)

**Comment by shaikhaquif** [comment]
Yep, I got it working after reinstalling the plugin. Might have been a temporary bug. Should have dropped a message here to inform the same. Sorry about that.

Anyways, thanks a lot for the lovely plugin.

**Comment by Reedyseth** [comment]
> Might have been a temporary bug. Should have dropped a message here to inform the same. Sorry about that.

No problem, thank you for your confirmation.

Regards.!!
