### ISSUE TITLE
Bug Report: 404 error on Manage Subscriptions

### ISSUE THREAD

**Issue by artmuns** [stcr/subscribe-to-comments-reloaded#366]
Hi

Keep getting 404 error when trying to manage subscriptions. Tried creating a new page and disabling option in plugin but getting blank page. have had the plugin for years and never had a problem (I have contributed).

It may be url path but a bit confused on that setup.

Thank you for any help!

Art

**Comment by Reedyseth** [comment]
Hello @artmuns ,

Thank you for your report. Did you have the plugin running and it stopped working or this happened in a fresh install?

Also what version of WP are you running?

Regards.!!

**Comment by Reedyseth** [comment]
I just checked the latest version of the plugin and the manage subscription page works. Looks to me that you have an error setting up the management page.

Could you please send me the information on the System Information box? You will find it on the *StCR System* menu option. Send it to my email reedyseth {at) gmail [dot| com

![image](https://user-images.githubusercontent.com/1228711/28951806-81789638-788a-11e7-8040-dc01af28ab91.png)

**Comment by artmuns** [comment]
Thanks for the reply. I have had this plugin installed for a while and has always worked just fine. It's working okay now except a subscriber can't unsubscribe as they get a 404 error. I'm on WP 4.8 and I think the Manage Subscriptions page broke on that update. Just sent you an e-mail. 

Thanks again!

**Comment by artmuns** [comment]
Hey, I just discovered it's the plugin "Widgets On Pages" that's causing the 404 Error. I will contact the developer.

**Comment by Reedyseth** [comment]
@artmuns So now you have the plugin running without any issue?

**Comment by artmuns** [comment]
No, still have same issue. Fault may be with "Widgets On Pages" plugin. If you get a chance try that plugin with StCr and you will see what I mean.

**Comment by artmuns** [comment]
FYI StCR and Widgets On Pages now play nice together. Developer of Widgets On Pages has fixed the problem.

**Comment by Reedyseth** [comment]
Thank you very much for the confirmation :+1:

**Comment by berauscher** [comment]
This just saved my live! Thanks for the report of the bug fix. I had the same problem.

**Comment by stevelaube** [comment]
I'm getting complaints from people trying to unsubscribe from a comment thread. They get a 404 message when clicking the link.

**Comment by BobaWebDev** [comment]
@stevelaube Can you send over the URL to your website so I can do some tests.

**Comment by stevelaube** [comment]
www.stevelaube.com/blog




------ Original Message ------

**Comment by BobaWebDev** [comment]
Hi Steve,

Looks like the virtual page isn't working out. Can you try the following:

Create a new page, make sure the slug is the same as the the one set in WP admin > StCR > Management Page. It's **comment-subscriptions** by default. And as the content of the page add the shortcode [stcr_management_page]

Let me know once you do that so I can give it a try and see if the issue is resolved.
