### ISSUE TITLE
Can't see testimonials to approve 

### ISSUE THREAD

**Issue by kiwimee** [stcr/subscribe-to-comments-reloaded#369]
Hello !

Thank you for this great plugin!

I just have this issue here : I can't see/modify testimonials to approve, or any testimonials that have been entered by users.

Could you help me?

Thank you so much!
![capture](https://user-images.githubusercontent.com/31047398/29332814-a40693dc-8201-11e7-83ba-39cbbc55d41e.PNG)

**Comment by Reedyseth** [comment]
Hi @kiwimee , I am sorry to hear you are facing difficulties, but I am afraid that this issue is not related to the StCR plugin.
