### ISSUE TITLE
Subscriber list not showing in WP backend

### ISSUE THREAD

**Issue by mossi2137** [stcr/subscribe-to-comments-reloaded#371]
Hello! 

First of all thanks for this great plugin! Unfortunately, I seem to have an issue with the subscriber list in the backend. When I am on the "Manage subscriptions" page in my WP Admin, I do not see any subscribers. Below the "Search subcribers" box the page is just grey. However, in my database I see the table wp_subscribe_reloaded_subscribers and it has contents. Funny enough I created a staging environment recently and there I see the list of subscriptions.

Would you have any idea how to get the subscriber overview back in my live environment?

Thanks very much in advance,
Wolfgang

![grafik](https://user-images.githubusercontent.com/31434052/29810170-309bc50e-8c9f-11e7-995e-727f311b8de7.png)

**Comment by Reedyseth** [comment]
Hello @mossi2137 , this is a known issue related to database incompatibility with the StCR table. You should fix this by updating the collation of the `wp_subscribe_reloaded_subscribers` table. Use the following query update:

```sql
ALTER TABLE wp_subscribe_reloaded_subscribers CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
```

**Comment by mossi2137** [comment]
Sorry for that, I didn't find anything about this issue with the search function here. However, thanks very much for your quick response, this solved the problem perfectly.

Thanks again and have a nice evening!

**Comment by Reedyseth** [comment]
No problem. good to hear that it is working for you.

Regards.!!
