### ISSUE TITLE
Importing StC data

### ISSUE THREAD

**Issue by TonyScialdone** [stcr/subscribe-to-comments-reloaded#374]
Hello! 

I'd love to use your plugin. I have it installed, and Mark Jaquith’s Subscribe To Comments is deactivated. How can I use your "main feature" that "Imports Mark Jaquith’s Subscribe To Comments data"?

Thank you.

**Comment by Reedyseth** [comment]
Hello @TonyScialdone , I apologize for the late response. Last time I checked that plugin had conflicts with newer versions of wordpress, this is why the importing feature for that plugin does not work with my plugin. Maybe we can sort it out, please let me know.

Regards.!!
