### ISSUE TITLE
You can also subscribe without commenting issues

### ISSUE THREAD

**Issue by factualfairytale** [stcr/subscribe-to-comments-reloaded#375]
I cannot get the “You can also subscribe without commenting.” page and form to work. What am I missing?

https://factualfairytale.com/fashion-beauty/cheap-womens-clothing-amazon/

Please click the link on the comment box to view the page and form for the  “You can also subscribe without commenting.” Nothing appears

**Comment by Reedyseth** [comment]
Hello @factualfairytale, I apologize for the late response. I noticed that you changed your notification system, but when you want to return to StCR I will be glad to help you.

Regards.!!
