### ISSUE TITLE
virtual management page will not display

### ISSUE THREAD

**Issue by mlgamerone** [stcr/subscribe-to-comments-reloaded#376]
**ADDENDUM**: I was able to resolve this by creating page.php. The virtual management page is now displaying properly. Sorry...should have worked on it a bit longer before posting.

Original comment:
I am creating a custom (from scratch) WordPress template and am testing it. Using StCR, only the checkbox works. I cannot get any of the subscribe or manage links to display the virtual management page. All of these links return to index.php.  My comment page is using a template page. My theme does not have (or need) page.php or single.php.

Any help to resolve this or point me in the right direction would be appreciated.

**Comment by Reedyseth** [comment]
Hello @mlgamerone, thank you for your confirmation.

Best Regards.!!
