### ISSUE TITLE
Security vulnerability

### ISSUE THREAD

**Issue by jharries** [stcr/subscribe-to-comments-reloaded#377]
I just received a warning from Gravity Scan that this plugin has a security vulnerability. 

http://www.securityfocus.com/bid/66288/

Sorry to be bearer of bad news. It's a great plugin so I hope you can get it fixed.

By the way, I would be happy to see this plugin go premium for say $20.00/year, well worth it.

Thanks
John

**Comment by jharries** [comment]
Turns out that this security warning was bogus. I bitched at Gravity Scan and they investigated and say they will remove the warning.

**Comment by Reedyseth** [comment]
Hello @jharries thanks for the info. Yes the plugin has plans to go premium to bring more fixes and other features, thanks for the suggestion.
