### ISSUE TITLE
Bug Report: <How do I edit or style the /comment-subscriptions/ page?>

### ISSUE THREAD

**Issue by cmarabate** [stcr/subscribe-to-comments-reloaded#378]
I would like to edit and/or style the following page that I created when I noticed this plugin was trying to redirect to it after clicking to manage my subscriptions...
[https://compassiondigital.com/comment-subscriptions/](https://compassiondigital.com/comment-subscriptions/)

I looked at your plugin's files and saw that it has a "Templates" folder which got me excited until I looked through each of the files inside and none of them seemed to have any of the content from the page I'm trying to edit. If it is possible, it would be ideal if I could create a directory in my theme for subscribe-to-comments-reloaded/templates/ to override the template in the plugin folder. This way the change won't get overwritten in a future update.

If that is not possible I am open to any other options you can give me.

Thanks,

Chris

**Comment by Reedyseth** [comment]
Good day @cmarabate , thank you for leaving the messages. Right now the plugin structure does not have that kind of template system. I am thinking to include it in the future, but right now the best option to style the management page is to go straight into the code.

Regards.!!

**Comment by cmarabate** [comment]
Okay, thank you.
