### ISSUE TITLE
404 on the "manage your subscriptions" page

### ISSUE THREAD

**Issue by arkid** [stcr/subscribe-to-comments-reloaded#379]
if I subscribe to a post I made a comment on, the first email I receive includes a "manage your subscriptions" link.  That takes me to my site and a 404 error. 

To clarify, the url is structured as follows:  

https://www.domainname.com/comment-subscriptions?srek=3c1d24a8da3ebb7ad6ff43fd2c25117f&srk=e9edcd3613ec0d577c4fa43b2b8dfc36

Can someone please help me troubleshoot this ?

**Comment by arkid** [comment]
@Reedyseth  Do you have any suggestions on this? I've checked old forum posts but still can't get a fix.

**Comment by Reedyseth** [comment]
Hello @arkid , on the plugin there is an option where all the settings are shown. Can you send that information into my email ? reedyseth 'at] gmail (dot] com.

![image](https://user-images.githubusercontent.com/1228711/33639179-55db1794-d9e7-11e7-874f-41d514585388.png)

**Comment by Mathilde295** [comment]
Hello @arkid I think I have the same problem, I have 404 errors. I created the post #387. How did you fix this problem ?

**Comment by Reedyseth** [comment]
@Mathilde295 I replied to you on #387 , your error is different from this one.

Regards.!!
