### ISSUE TITLE
No email sent, nothing happens

### ISSUE THREAD

**Issue by MatisseIt** [stcr/subscribe-to-comments-reloaded#380]
Hi There, 

i've seen other people had the same issue but no answers :(
I'm using my official email bruna@brunadepalo.com as "Sender" but nothing happens, so email sent.

What a shame as it sounded like a really great plugin. 

Any idea?

Thank you in advance, 

Bruna

**Comment by MatisseIt** [comment]
P.S.: that's the blog: https://brunadepalo.com/daretoshine-blog/

**Comment by Reedyseth** [comment]
Hello @MatisseIt , I apologize for the late reply.

Normally the plugin will take the email that you define on the options. Some servers does not take the plugin email headers and therefor the emails are rejected and not sent.

![image](https://user-images.githubusercontent.com/1228711/33638966-353bd312-d9e6-11e7-9e14-9edd0f1267a6.png)
On the image you can see my gmail emal address, the plugin will try to send the notification using this email, but it rely on the server to allow it to go through.

The is an option that will be available on the future to configure your email using STMP.

Regards.!!
