### ISSUE TITLE
DB table created with wrong collation

### ISSUE THREAD

**Issue by NotARobit** [stcr/subscribe-to-comments-reloaded#382]
The plugin is failing on many sql statements with the error `#1267 - Illegal mix of collations (utf8_general_ci,IMPLICIT) and (utf8_unicode_ci,IMPLICIT)`

This is because the plugin creates wp_subscribe_reloaded_subscribers with the collation of utf8_unicode_ci even though the rest of my database is a different collation. This causes sql statements like the following to fail.

`SELECT meta_id, REPLACE(meta_key, '_stcr@_', '') AS email, post_id, SUBSTRING(meta_value, 1, 19) AS dt, SUBSTRING(meta_value, 21) AS status, srs.subscriber_unique_id AS email_key
FROM wp_postmeta
INNER JOIN wp_subscribe_reloaded_subscribers srs ON ( REPLACE(meta_key, '_stcr@_', '') = srs.subscriber_email )
WHERE meta_key LIKE '\_stcr@\_%' AND SUBSTRING(meta_key, 8) LIKE '%@%'
ORDER BY dt DESC
LIMIT 0,25`

**Comment by Reedyseth** [comment]
Good day @NotARobit , my suggestion is that you change the collation of the **wp_subscribe_reloaded_subscribers** table with a query like this:

```sql
ALTER TABLE wprn_subscribe_reloaded_subscribers CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
```
Just replace the current collection for the one that you need it.

Best regards.!!

**Comment by NotARobit** [comment]
Is there a reason that you're specifying a character set? I see you're still getting tickets here and on wordpress.org for this problem.

**Comment by Reedyseth** [comment]
Hi @NotARobit I have taken care of this problem, the fix will be available on the next update or if you want to have it now you can download it from here:

https://github.com/stcr/subscribe-to-comments-reloaded/archive/development.zip
