### ISSUE TITLE
Bug Report: plugin does not send any messages

### ISSUE THREAD

**Issue by 4daria** [stcr/subscribe-to-comments-reloaded#384]
Please help me find the error. The plugin does not send any messages

**Comment by Reedyseth** [comment]
Hello @4daria , I will be glad to help you. Just please help me with more detail information about problem. Attaching a screenshot will also help.

Best Regards.!!

**Comment by 4daria** [comment]
Re: [stcr/subscribe-to-comments-reloaded] Bug Report: <short description> (#384)


Hello! Thanks!
screenshots:

https://yadi.sk/i/2pkxoeaB3QF3bT 
https://yadi.sk/i/PxYq-LKB3QF3bi 
https://yadi.sk/i/x2NBmFbP3QF3bv 
https://yadi.sk/i/gINyLHk03QF3cG 
https://yadi.sk/i/lllNsqeA3QF3cB 

Best Regards, Daria!

Вы писали 1 декабря 2017 г., 19:20:35:





Hello @4daria , I will be glad to help you. Just please help me with more detail information about problem. Attaching a screenshot will also help.
Best Regards.!!
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.





-- 
С уважением,
 Telmi                          mailto:telmi@tut.by

**Comment by Reedyseth** [comment]
Thank you for the screenshots, but they don't show any error. Please write a detail description of your error.
