### ISSUE TITLE
We are getting "Manage your subscriptions on XXXX" email so many times (more than 100).

### ISSUE THREAD

**Issue by genexweb** [stcr/subscribe-to-comments-reloaded#385]
Hi, 

We are getting "Manage your subscriptions on XXXX" email so many times (more than 100) without mail body message. 

We got this email notification from notification settings of STCR http://prntscr.com/hvhbrr

Can you please check and let us know why we are getting email so many times?

Thanks

**Comment by Reedyseth** [comment]
Hello @genexweb I have added more validation to the plugin, I noticed that the email validation was only taken care on the client side, so if you disable JS no validation is taken care. I added extra validation on the backend to prevent the submition of invalid information. You can test the development version to make sure this is not happening anymore.

https://github.com/stcr/subscribe-to-comments-reloaded/archive/development.zip
