### ISSUE TITLE
Bug Report: <short description>

### ISSUE THREAD

**Issue by petertemple** [stcr/subscribe-to-comments-reloaded#386]
Having an issue on my blog page where previous commenters are having their names and email inserted in the sign-in field, so that I get new commenter being able to not only access that info but sign in using it.

The page in question is here:http://worldcyclesinstitute.com/a-pending-top/

If I disable the plugin, the issue persists, but I have the button that keeps subscriber in that situation, so I have to assume the code is kept, as well.
![comments npage](https://user-images.githubusercontent.com/22054824/34739379-519d30d2-f539-11e7-9394-a4f8c6ae1c5b.jpg)

**Comment by Reedyseth** [comment]
Hi @petertemple , I am not getting exactly your problem, but it does not look to me an issue of the plugin. The name and email is pre fill by WordPress once a user comment on the post. If you want to clear the pre fill information please clear the cookies in your browser.

Regards.!!

**Comment by petertemple** [comment]
I’ve got the Thesis developer I’m also talking to who thinks it is a plugin problem, so I’m going with him at the moment, and we’ll see.
Thanks for your reply.
Peter

**Comment by Reedyseth** [comment]
Your're Welcome, I am glad to help.
