### ISSUE TITLE
Double opt-in issues

### ISSUE THREAD

**Issue by charlesrr** [stcr/subscribe-to-comments-reloaded#388]
Hi. I just installed this plugin.
I am using a moderation queue and I get the normal wordpress email to say a comment requires moderation immediately. Is that right?
Next, when I test the comment double opt-in link in the email notification sent to the commenter, it does not work, giving a page that says:
This page isn’t working
If the problem continues, contact the site owner.
HTTP ERROR 414

(for now, I have disabled the plugin)

**Comment by Reedyseth** [comment]
Helloe @charlesrr , thank you for asking. The moderation is is part of wordpress, there is nothing in conflict with the plugin until that part.

The Double opt-in should we working by default, but I will be glad to check the link. Can you provide your webstie URL so that I can subcribe and test it?

Regards.!!

**Comment by charlesrr** [comment]
Thanks for the swift response! For example here: https://charlesr.co.uk/how-to-add-hyperlinks-to-text-without-javascript-css-or-modifying-theme-code/ Keep up the good work - looks like a lot of great options once I can get it working :)

**Comment by Reedyseth** [comment]
I saw the error, the subscription is working but the link generated is wrong, i will take a look and let you know what I found.

Regards.!!

**Comment by charlesrr** [comment]
Hi again. I've disabled the plugin for now on the live site (switched to a more basic one), but I have moved the site to my test server. Would you like an admin user on the test site? If so what's the best email address to use while creating it please?

**Comment by Reedyseth** [comment]
Hi @charlesrr , I am going to try to replicate the issue locally, The plugin seems to work ok, the only thing not good is the link URL. If I am not able to replicate it I will contact you. My email is reedyseth [at} gmail 'd0t) com

**Comment by Reedyseth** [comment]
Unfortunately I was not able to replicate the issue locally, can you send me the dev site details to my email?

**Comment by charlesrr** [comment]
Thanks. You should have received the email asking you to set your password. Fingers crossed it's an easy fix! Let me know if there's anything else you need

**Comment by charlesrr** [comment]
Thanks for all your efforts on this. For anyone else searching, the issue was the "filter suspicious queries in URL" option in iThemes Security.

**Comment by Reedyseth** [comment]
@charlesrr , thank you for posting the solution I am glad to help sort it out.
