### ISSUE TITLE
Bug Report: The management page on the backend won't even load

### ISSUE THREAD

**Issue by jmorti** [stcr/subscribe-to-comments-reloaded#389]
It's been years since I was able to open the management page. We have over 10k signups, so I'm guessing something isn't coded right. Any chance you can can look at it and see if something could be causing the problem? Thanks!

**Comment by Reedyseth** [comment]
Hello @jmorti , yes I will be glad to take a look at your issue. Could you please add a description of your problem?

**Comment by jmorti** [comment]
The management page on the backend won't even load. I'm guessing the query
used can't handle the number of subscriptions we have? Thanks.

Jesse

**Comment by Reedyseth** [comment]
Hi @jmorti  a new version of the plugin will be out this week, I think this will resolve your issue.

**Comment by Reedyseth** [comment]
Is out !

**Comment by jmorti** [comment]
Thanks! It still takes a long time to load, but it actually loads after
waiting a few minutes.

Jesse

**Comment by Reedyseth** [comment]
Hi @jmorti I added 10K subscriptions to check the rendering of the backed and it flows smoothly.

![image](https://user-images.githubusercontent.com/1228711/36284160-e5074974-1263-11e8-9a8f-848c2db48d87.png)

There is not issue on the query retrieving the information.

**Comment by jmorti** [comment]
K thanks for fixing what you did.

Jesse

**Comment by Reedyseth** [comment]
Just check it and let me know if you run into something weird with the plugin. Feel free to re-open the issue anytime.
