### ISSUE TITLE
Incompatible with Elementor or Astra Sites Plugins ?

### ISSUE THREAD

**Issue by Naehs** [stcr/subscribe-to-comments-reloaded#391]
Hello,

First thanks for your work.
Since i'm using Elementor and Astra Sites Plugins, the custom Managment Page no longer works.

See the errors here : 
https://jsfiddle.net/Naehs/zerc5j0h/

Regards,
Loïc.

**Comment by Reedyseth** [comment]
Hello @Naehs I just took a look a the code and seems that for some reason no information is not created on the backened.
What steps did you do to create the Management Page ?

**Comment by Naehs** [comment]
Hi @Reedyseth,

Somehow i followed these steps : 
https://github.com/stcr/subscribe-to-comments-reloaded/wiki/KB

When i did it with my last theme, the Management Page worked well.
I think it's since i've installed the Elementor Plugin with Astra Site Plugin and the Agency Theme.
They are actualy uncompatible, but i don't know why :D 

To reproduce my environment, you must install : 
https://fr.wordpress.org/plugins/elementor/
https://wordpress.org/plugins/astra-sites/
And choose "Astra Sites > Elementor > Agency" (https://websitedemos.net/agency-02/).

Then you should have the same errors.

Regards,
Loïc.

**Comment by Naehs** [comment]
Here is my subscribe.php
```ruby
<?php 
/* Template Name: Subscribe To Comments */
if (isset($wp_subscribe_reloaded)){ global $posts; $posts = $wp_subscribe_reloaded->stcr->subscribe_reloaded_manage(); }
?>

<?php
/**
 * The template for displaying all pages.
 *
 * This is the template that displays all pages by default.
 * Please note that this is the WordPress construct of pages
 * and that other 'pages' on your WordPress site may use a
 * different template.
 *
 * @link https://codex.wordpress.org/Template_Hierarchy
 *
 * @package Astra
 * @since 1.0.0
 */

get_header(); ?>

<?php if ( astra_page_layout() == 'left-sidebar' ) : ?>

	<?php get_sidebar(); ?>

<?php endif ?>

	<div id="primary" <?php astra_primary_class(); ?>>

		<?php astra_primary_content_top(); ?>

		<main id="main" class="site-main" role="main">

			<?php
			while ( have_posts() ) :
				the_post();
?>

				<?php get_template_part( 'template-parts/content', 'page' ); ?>

				<?php
					// If comments are open or we have at least one comment, load up the comment template.
				if ( comments_open() || get_comments_number() ) :
					comments_template();
					endif;
				?>

			<?php endwhile; ?>

		</main><!-- #main -->

		<?php astra_primary_content_bottom(); ?>

	</div><!-- #primary -->

<?php if ( astra_page_layout() == 'right-sidebar' ) : ?>

	<?php get_sidebar(); ?>

<?php endif ?>

<?php get_footer(); ?>

```

**Comment by Reedyseth** [comment]
Alright, thank you for the information, I will install both plugins to replicate the issue, once I replicate the issue it will be easier to help you.
Thank you for sharing the steps.

**Comment by Naehs** [comment]
Thanks to you ! 👍

**Comment by Reedyseth** [comment]
> And choose "Astra Sites > Elementor > Agency" (https://websitedemos.net/agency-02/).

I could not get further than here, since I have to purchase the website.

**Comment by Naehs** [comment]
Well, this theme is free.
In your Dashboard, find : Astra Sites > Elementor > Agency

**Comment by Naehs** [comment]
-	Install a new Wordpress

-	Settings > Permalinks :
	Common Settings > Post name (http://localhost/wordpress/sample-post/)
	Save Changes
	
-	Plugins > Add New :
	Subscribe To Comments Reloaded
	Install Now
	Activate
	
-	Go to :
	~\wordpress\wp-content\themes\twentyseventeen
	Copy : page.php
	To : subscribe.php
	Add :

```ruby
	<?php 
	/* Template Name: Subscribe To Comments */
	if (isset($wp_subscribe_reloaded)){ global $posts; $posts = $wp_subscribe_reloaded->stcr->subscribe_reloaded_manage(); } 
	?>
```
Save.
Result :
```ruby	
	<?php 
	/* Template Name: Subscribe To Comments */
	if (isset($wp_subscribe_reloaded)){ global $posts; $posts = $wp_subscribe_reloaded->stcr->subscribe_reloaded_manage(); } 
	?>

	<?php
	/**
	 * The template for displaying all pages
	 *
	 * This is the template that displays all pages by default.
	 * Please note that this is the WordPress construct of pages
	 * and that other 'pages' on your WordPress site may use a
	 * different template.
	 *
	 * @link https://codex.wordpress.org/Template_Hierarchy
	 *
	 * @package WordPress
	 * @subpackage Twenty_Seventeen
	 * @since 1.0
	 * @version 1.0
	 */

	get_header(); ?>

	<div class="wrap">
		<div id="primary" class="content-area">
			<main id="main" class="site-main" role="main">

				<?php
				while ( have_posts() ) : the_post();

					get_template_part( 'template-parts/page/content', 'page' );

					// If comments are open or we have at least one comment, load up the comment template.
					if ( comments_open() || get_comments_number() ) :
						comments_template();
					endif;

				endwhile; // End of the loop.
				?>

			</main><!-- #main -->
		</div><!-- #primary -->
	</div><!-- .wrap -->

	<?php get_footer();
```

-	Go to : Pages > Add new
	Title : StCR
	Template : Subscribe To Comments
	
	Publish.
	
-	Go to : StCR > Management Page
	Virtual Management Page : Disabled
	Management URL : /stcr/
	
	Save Changes
	
-	Go to the default article : My URL = http://localhost/wordpress/bonjour-tout-le-monde/
	You can manage the subscriptions of this post.
	http://localhost/wordpress/stcr/?srp=1&srk=67208dbd0448e9cd9b874f88dba131d2
	
	Result :
	It works !
	
-	Plugins > Add New :
	Elementor
	Install Now
	Activate

-	Plugins > Add New :
	Astra Starter Sites
	Install Now
	Activate

-	Go to : Appearance > Themes > Add New
	Search themes : Astra
	Install
	Activate

-	Go to : Appearance > Astra Sites
	Select "Elementor" menu on the left.
	Search Sites... : Agency
	Select the free one (Stunning Business Website)
	Install Plugins
	Import This Site
	OK
	
-	Go to : Pages > Add New
	Title : Blog
	
	Publish.
	
-	Go to : Appearance > Customize
	Then : Homepage Settings
	Posts page : Blog
	
	Publish.
	
-	Go to :
	~\wordpress\wp-content\themes\astra
	Copy : page.php
	To : subscribe.php
	Add :
	
```ruby
	<?php 
	/* Template Name: Subscribe To Comments */
	if (isset($wp_subscribe_reloaded)){ global $posts; $posts = $wp_subscribe_reloaded->stcr->subscribe_reloaded_manage(); } 
	?>
```
Save.
Result :
```ruby
	<?php 
	/* Template Name: Subscribe To Comments */
	if (isset($wp_subscribe_reloaded)){ global $posts; $posts = $wp_subscribe_reloaded->stcr->subscribe_reloaded_manage(); } 
	?>

	<?php
	/**
	 * The template for displaying all pages.
	 *
	 * This is the template that displays all pages by default.
	 * Please note that this is the WordPress construct of pages
	 * and that other 'pages' on your WordPress site may use a
	 * different template.
	 *
	 * @link https://codex.wordpress.org/Template_Hierarchy
	 *
	 * @package Astra
	 * @since 1.0.0
	 */

	get_header(); ?>

	<?php if ( astra_page_layout() == 'left-sidebar' ) : ?>

		<?php get_sidebar(); ?>

	<?php endif ?>

		<div id="primary" <?php astra_primary_class(); ?>>

			<?php astra_primary_content_top(); ?>

			<main id="main" class="site-main" role="main">

				<?php
				while ( have_posts() ) :
					the_post();
	?>

					<?php get_template_part( 'template-parts/content', 'page' ); ?>

					<?php
						// If comments are open or we have at least one comment, load up the comment template.
					if ( comments_open() || get_comments_number() ) :
						comments_template();
						endif;
					?>

				<?php endwhile; ?>

			</main><!-- #main -->

			<?php astra_primary_content_bottom(); ?>

		</div><!-- #primary -->

	<?php if ( astra_page_layout() == 'right-sidebar' ) : ?>

		<?php get_sidebar(); ?>

	<?php endif ?>

	<?php get_footer(); ?>
```

-	Go to : Pages > Add new
	Title : StCR2
	Template : Subscribe To Comments
	
	Publish.
	
-	Go to : StCR > Management Page
	Management URL : /stcr2/
	
	Save Changes.
	
-	Go to the default article : My URL = http://localhost/wordpress/bonjour-tout-le-monde/
	You can manage the subscriptions of this post.
	http://localhost/wordpress/stcr2/?srp=1&srk=67208dbd0448e9cd9b874f88dba131d2
	
	Result :
	It works...
	
Well... I will try somes things later...
:(

**Comment by Reedyseth** [comment]
@Naehs Thank for you detail steps. So in all those steps everything worked. Do you have a scenario where the plugin fails?

**Comment by Naehs** [comment]
350/5000
@Reedyseth
Unfortunately no...

Before installing Elementor Plugin and stuff, I made a copy of my wordpress and put it in a new folder.
I changed all the links and worked on it, is there any way that when you duplicate a wordpress site with a database that StCR makes that kind of mistake ?

I also uninstall and install the plugin, same errors...
Is there any way to clean all hint of StCR in the database ?

Regards,
Loïc.

**Comment by Reedyseth** [comment]
> Is there any way to clean all hint of StCR in the database ?

Hi @Naehs , yes. The next version will have an Option to reset all settings, the feature is already cooked.

![image](https://user-images.githubusercontent.com/1228711/36086577-7ec8157a-0f8a-11e8-8d63-7aaebe2e6832.png)


Still getting to replicate the issue.
