### ISSUE TITLE
Bug Report: checkmark doesn't show

### ISSUE THREAD

**Issue by schulrog** [stcr/subscribe-to-comments-reloaded#393]
hi there,
installed the plugin but the checkmark on the comment section isn't showing. am i missing something here? i do already have a checkmark to subscribe to a mailchimp list as well

**Comment by Reedyseth** [comment]
Hello @schulrog Can you please share a screenshot of you website? on the comment section. Also please the image from your options.

**Comment by schulrog** [comment]
![comment section](https://user-images.githubusercontent.com/8872947/36700525-d2e33074-1b04-11e8-985a-b58e3e8f1bf1.png)
![options](https://user-images.githubusercontent.com/8872947/36700526-d307ab8e-1b04-11e8-8140-91b927d641e6.png)

**Comment by Reedyseth** [comment]
OK, please set the **StCR Position** option to Yes and give it a try.

**Comment by schulrog** [comment]
i have tried that as well

**Comment by schulrog** [comment]
right now no. i can change it to yes

**Comment by Reedyseth** [comment]
please do it. Also it does not look like you have the plugin active

![image](https://user-images.githubusercontent.com/1228711/36703741-5640df1a-1b1a-11e8-8b57-8c6d249e2355.png)

no any portion of my plugin appear on the background.

**Comment by schulrog** [comment]
![plugin](https://user-images.githubusercontent.com/8872947/36703792-375d6c38-1b12-11e8-94e0-37493b564169.png)

it is active and i changed it to "yes"

**Comment by schulrog** [comment]
should i try deleting and reinstalling the plugin?

**Comment by Reedyseth** [comment]
> should i try deleting and reinstalling the plugin?

No, I will figure it out, now I saw the code in your website. I will check why is not displaying correctly.

**Comment by schulrog** [comment]
awesome thanks!

**Comment by Reedyseth** [comment]
Okay, no you will delete the plugin and install the one I will share with you right here, but before make sure that the **Safely Uninstall** option is set to **Yes**,if so, now you can deactivate the plugin and then delete it.

Here is the fix code that you will upload.

[subscribe-to-comments-reloaded.zip](https://github.com/stcr/subscribe-to-comments-reloaded/files/1760818/subscribe-to-comments-reloaded.zip)

**Comment by schulrog** [comment]
didn't work :(

**Comment by Reedyseth** [comment]
The **StCR Position** must be set to **Yes**.

**Comment by schulrog** [comment]
ok i changed it to yes but it's still not visible. does there have to be comment made or existing for it to show?

**Comment by Reedyseth** [comment]
I just inspected your theme and unfortunately is not following the WordPress standards this is why the subscription box is not working. I apologize but You will need a very custom code to make it work and it is beyond the free version support.

**Comment by schulrog** [comment]
ok i understand thank you

**Comment by Reedyseth** [comment]
[subscribe-to-comments-reloaded.zip](https://github.com/stcr/subscribe-to-comments-reloaded/files/1764703/subscribe-to-comments-reloaded.zip)

Updated file.

**Comment by Reedyseth** [comment]
@schulrog To improve you style view please change the following.

![image](https://user-images.githubusercontent.com/1228711/36809166-69395d52-1c84-11e8-9213-1b5db7e0c45f.png)

On the **Custom inline** option please add the following code:

```css
float: none;width: auto;position: static;margin: 0 6px 0 0;padding: 0;vertical-align: middle;display: inline-block !important;max-width: 21px;-webkit-appearance: checkbox;
```
On the **Custom HTML** Please add the following:

```html
<p class='comment-form-subscriptions'><label for='subscribe-reloaded' style='float: none; display: block; cursor: pointer; width: auto; position: static; margin: 20px 0 16px 0; '>[checkbox_field] [checkbox_label]</label></p>
```
And on the **Default label** you have to switch from the visual view to the text view, then add the following:
```html
<span>Notify me of followup comments via e-mail. You can also <a href="[subscribe_link]">subscribe</a> without commenting.</span>
```
