### ISSUE TITLE
Bug Report: <Tag issue> <Italian translation issue>

### ISSUE THREAD

**Issue by PeopleInside** [stcr/subscribe-to-comments-reloaded#397]
Hi, I installed your great plugin but found issues.
I use this plugin in an Italian Wordpress blog http://www.marcoborla.it

Italian translation on visitor side is not complete. Some parts are in English,If I try to customize in admin settings where all custom text are only in English Tags stop to work made link wrong when I test the website.

So if I try to customize message Tags are not working.
Italian translation is not complete. I have customized all text and than loosed all work as links are not working once customized.

![1](https://user-images.githubusercontent.com/5006150/36695572-ff52d762-1b41-11e8-9805-f305bf0435bd.png)

**Comment by PeopleInside** [comment]
After subscribe with an email without comment the page showed is:
![immagine senza nome](https://user-images.githubusercontent.com/5006150/36695887-d8af6110-1b42-11e8-9be3-2c205daf06c9.png)
If i try to customize this text and tags on admin side all or some links stop to work.

**Comment by Reedyseth** [comment]
Hi @PeopleInside , some translation is missing due to the lack of native Italian users using the software. And yes I noticed that some parts remain in English, but those missing parts are translatable within the plugin custom messages. Those parts that are not translated inside the plugin but using another way.

**Comment by Reedyseth** [comment]
> If i try to customize this text and tags on admin side all or some links stop to work.

Correct that part is the one I found not translated. But you do that on the admin part. I will double check though, to make sure it is working as expected.

**Comment by PeopleInside** [comment]
> but those missing parts are translatable within the plugin custom messages. 

I tried to customize all text on admin side. Links stop to work if I customize message so i am forced to not customize. :)

**Comment by PeopleInside** [comment]
The Tag issue is because field has TinyMCE editor that create issue. You should see if you can disable it for that filed. 

Thanks for your very real time support!
Have a great time!

![immagine senza nome](https://user-images.githubusercontent.com/5006150/36697962-d72b25bc-1b48-11e8-9d51-fe77f90f3cf4.png)


and thanks for this great plugin, i will soon do a great vote on Wordpress.

**Comment by Reedyseth** [comment]
Marco, I have video that talks about the links on my plugin, many users have work with it a none having issues, I recommend to watch this video regarding the links generation.

https://www.youtube.com/watch?v=eFW-2NIRzBA

I will still check the translation issue to make sure that it is working.

**Comment by Reedyseth** [comment]
Marco, just FYI, I just checked and the translation is working.

**Comment by PeopleInside** [comment]
Yes all is working fine just maybe in future will be nice to see what is translated in Italian for example, also in the admin options side not only visitor side because I cannot know what is translated and what not.

Your support was the best I can remember. You are a real time man ahaha and your plugin is awesome, without it I was not able to replace the old deprecated plugin. Thanks so much, i will sure suggest your plugin! IF I can I will be happy to try a donation!

**Comment by Reedyseth** [comment]
> in future will be nice to see what is translated in Italian for example, also in the admin options side not only visitor side because I cannot know what is translated and what not.

Marco, it is possible to translate it using you help, I will create a video to explain how you can help to translate the missing parts.

> Your support was the best I can remember. You are a real time man ahaha and your plugin is awesome, without it I was not able to replace the old deprecated plugin. Thanks so much, i will sure suggest your plugin! IF I can I will be happy to try a donation!

You're welcome, I am glad to help. I know you will donate when you are able.

Regards.!!

**Comment by PeopleInside** [comment]
Thank you, I know how to do using Wordpress function to translate plugin :) I see Italian is translated for 82 % I will try to look into it, not need the video, maybe.
Thanks!

**Comment by Reedyseth** [comment]
[subscribe-reloaded-it_IT.po.zip](https://github.com/stcr/subscribe-to-comments-reloaded/files/1763107/subscribe-reloaded-it_IT.po.zip)

Here is the file that you can use to translate it. Just use [Poedit](https://poedit.net/) to translate it.
