### ISSUE TITLE
Bug Report: comment dropdown inactive and subscribe link inoperable

### ISSUE THREAD

**Issue by schulrog** [stcr/subscribe-to-comments-reloaded#398]
hi there,

thank you so much for making it show up now but unfortunately the dropdown is non-responsive and the subscribe link is ineffective.

**Comment by schulrog** [comment]
forgot to add link to page: https://abettercleanlv.com/dangers-hiring-unlicensed-housecleaner

**Comment by Reedyseth** [comment]
Hi @schulrog thank you for the report. I will take a look at it. I will add some custom code to your other issue #393  to polish the style view

**Comment by schulrog** [comment]
PS: I downloaded the version from the wordpress plugin page. Should I use the version you sent me yesterday?

**Comment by Reedyseth** [comment]
If the current version that you have is working, please leave it like that.

**Comment by schulrog** [comment]
Do you have a pro version or only donation?

**Comment by Reedyseth** [comment]
> Do you have a pro version or only donation?

I am working on the Pro version, but since it adds a lot of complex stuff on the dev side I have not schedule a release date, but to all the users that give more than $20.00 dollars I will give it to them first so that they can test it and add feedback, and of course the Support will be included for a Year.

**Comment by schulrog** [comment]
I will donate of course and have left a 5-Star review. The support is outstanding!

It’s still unresponsive though ☹

https://abettercleanlv.com/dangers-hiring-unlicensed-housecleaner

**Comment by schulrog** [comment]
Oh by the way I manually added the code to the comments.php file and wrapped it in a div.

<div>
<?php global $wp_subscribe_reloaded; if (isset($wp_subscribe_reloaded)){ $wp_subscribe_reloaded->stcr->subscribe_reloaded_show(); } ?>
</div>

**Comment by schulrog** [comment]
If I click multiple times the drop down activates

**Comment by Reedyseth** [comment]
> I will donate of course and have left a 5-Star review. The support is outstanding!

Amazing, yes I just thank you on the WP forum. Thanks.

> It’s still unresponsive though ☹
 
Yes, responsive was easy to achieve on another Theme by just adding the Width 100% to the dropdown, but in you case is acting a little bit weird, because the original dropdown is not display. Your theme try to extract the information from the regular dropdown and is not doing it correctly, that is why the dropdown is not fully functional. Is possible to make it work, but I think it requires a little bit of custom code.

**Comment by schulrog** [comment]
I see.. and the subscribe without commenting link? --> https://abettercleanlv.com/comment-subscriptions/?srp=667&srk=ee9b6721712e1bb8a6b184ef57677da8&sra=s&srsrc=f

**Comment by Reedyseth** [comment]
> I see.. and the subscribe without commenting link? --> https://abettercleanlv.com/comment-subscriptions/?srp=667&srk=ee9b6721712e1bb8a6b184ef57677da8&sra=s&srsrc=f

Directs me to a 404 page :thinking: 

For some reason your website is removing the slash after the subscriptions word.

Can you add a screenshot of your permalink structure ?

**Comment by schulrog** [comment]
What should it be? Which slash is being omitted?

**Comment by schulrog** [comment]
There are a lot of people using this theme too. I’m surprised nobody has ever mentioned anything… or they just move to Lightweight Subscribe To Comments<https://abettercleanlv.com/wp-admin/plugin-install.php?tab=plugin-information&plugin=comment-notifier-no-spammers&TB_iframe=true&width=600&height=550> which seems to work but i really like your plugin and the functionality a lot more.

**Comment by Reedyseth** [comment]
Going to the error pages will tell us why the 404 is triggering, if its a problem with my plugin the error pages will give us more light. Right now I cannot replicate it on my dev environment, you the informatio you provide from the error pages will help.

**Comment by schulrog** [comment]
I see the problem.

It works here: https://abettercleanlv.com/comment-subscriptions/srp=667&srk=ee9b6721712e1bb8a6b184ef57677da8&sra=s&srsrc=f

The ? before the “srp” removes the slash.

**Comment by schulrog** [comment]
Not sure why the link still isn’t clickable although the code looks ok

Would it help if I gave you access to my WP backend?

**Comment by Reedyseth** [comment]
> Would it help if I gave you access to my WP backend?

Yes, that will help a LOT. I will be happy to dig a little to find out the root of the problem.

Please send me a message from here:

http://subscribe-reloaded.com/contact/

**Comment by schulrog** [comment]
What’s your email? I’ll just add you to the WP backend

**Comment by Reedyseth** [comment]
reedyseth [at] gmail (dot] com

**Comment by Reedyseth** [comment]
Okay, now is working. The problem was a database creation issue. You can go ahead and delete the account you created for me.

Regards.!!
