### ISSUE TITLE
Feature: send translated text depending on user language

### ISSUE THREAD

**Issue by obrador** [stcr/subscribe-to-comments-reloaded#399]
Hi, I would like to know if it would be possible to add a new feature to this great plugin. 

I've seen in language directory that there are the strings of notifications already translated in po files for each language, so it would be very useful to send the translated text strings when an email is sent to this subscriber. Maybe the current language should be stored in the database when a new email is subscribed to a post comments to determine it's language.

Thanks.

**Comment by Reedyseth** [comment]
Hi @obrador , Actually you an customize the message notification that you deliver to your subscribers. I could not visualize a scenario where you could use the translation since you can do that already.

Best Regards.!!

**Comment by obrador** [comment]
Hi @Reedyseth, indeed, I've seen that, but as far as I know (correct me if I'm wrong please) you can set only one language for all subscribers. I forgot to mention I run a multilanguage site, so what I ask is to send a different language notifications depending on the language set when an email is subscribed.

Best regards!!

**Comment by Reedyseth** [comment]
> I forgot to mention I run a multilanguage site, so what I ask is to send a different language notifications depending on the language set when an email is subscribed.

I see, so far looks for some kind of work to make this work. No one have ever ask something like this, at least I have to get many request to make sure the developing time is worthy. I could create a custom code for you if you are willing to hire the service.

Feel free to contact me here: http://subscribe-reloaded.com/contact/

**Comment by obrador** [comment]
Ok, I see, thank you anyway.
