### ISSUE TITLE
White font on backed, link broken & management page issues.

### ISSUE THREAD

**Issue by zsaz** [stcr/subscribe-to-comments-reloaded#406]
https://yadi.sk/d/hrlvKVYi3TsRsV
https://yadi.sk/d/5M7pVFZI3TsYiN
https://yadi.sk/d/vdQ4g_4c3TsYq5

**Comment by Reedyseth** [comment]
Hi @zsaz 


> https://yadi.sk/d/hrlvKVYi3TsRsV

The white letters is part of your backend configuration or theme. You can try to inspect the code to see what styles are overriding the original ones.



> https://yadi.sk/d/5M7pVFZI3TsYiN

Double checked the link and it is working. What version of StCR are you using ?


> https://yadi.sk/d/vdQ4g_4c3TsYq5

You have to follow your permalink structure, so in the case of `/%category%/%postname%.html` you should have somthing like `/subs/comment-subscriptions.html`

**Comment by zsaz** [comment]
> The white letters is part of your backend configuration or theme. You can try to inspect the code to see what styles are overriding the original ones.

https://yadi.sk/d/53WgDDAL3TtyZF

> Double checked the link and it is working. What version of StCR are you using ?
I have latest version. If click this link, i redirect to http://behstant.com/subscribe-reloaded/realMgnPage.php      
i see this https://yadi.sk/d/DC3RvOmT3Ttyb7

> You have to follow your permalink structure, so in the case of /%category%/%postname%.html you should have somthing like /subs/comment-subscriptions.html

i any understand. My link correct, but it's no work, if i active one of plugin Yoast SEO OR CM Answers PRO... then i get 404 error. 
BUT..... I have Yoast SEO and CM Answers PRO in other site, and they active... and StCR work correct... why?

**Comment by Reedyseth** [comment]
You are using a very old version of the plugin, please update to the newest one and give it a try.

**Comment by zsaz** [comment]
i install this plugin yesterday
I haven't update https://yadi.sk/d/HCf0__kp3Ttznu

**Comment by Reedyseth** [comment]
> I have latest version. If click this link, i redirect to http://behstant.com/subscribe-reloaded/realMgnPage.php

Well, this link was updated a long time ago, please, if you have any caching plugin clear the cache.

**Comment by zsaz** [comment]
i visited this link yesterday for the first time. 
I clear cache plugin's, but didn't help

**Comment by Reedyseth** [comment]
> i visited this link yesterday for the first time.

I saw what happened, the link is not updated on the Russian translation. Here is the correct link:

https://github.com/stcr/subscribe-to-comments-reloaded/wiki/KB#Real-Page

**Comment by zsaz** [comment]
Ok, thank you, it's helped me, but i have new issue. 
When i want change my subscription, i get very many email by every second with link for change subscription, while my site get 504 e
![2018-03-31 11-34-08 - fermilon ya ru - mozilla thunderbird](https://user-images.githubusercontent.com/10978584/38159265-72f5a4fc-34d7-11e8-883d-351c5902142c.jpg)
rror

**Comment by Reedyseth** [comment]
> Ok, thank you, it's helped me, but i have new issue.
> When i want change my subscription, i get very many email by every second with link for change subscription, while my site get 504 error

In order to keep this issue clear please create another issue for this error.
