### ISSUE TITLE
Bug Report: H1 "number of comments" in conflict with the H1 title

### ISSUE THREAD

**Issue by piettt** [stcr/subscribe-to-comments-reloaded#409]
Hello,

the **H1 for "number of comment" is in conflict with the title of the article**, which is also in H1 (see my screenshot for more understanding).

So is it possible to put a H2 or H3 for the "number of comments", or simply remove it ?

Regard.

![2018-04-09_19h37_25](https://user-images.githubusercontent.com/7397394/38513316-1a95c630-3c2e-11e8-8301-d01467964ba1.jpg)

**Comment by Reedyseth** [comment]
Hi @piettt thank you for reporting, but I afraid to tell you that this is not a StCR issue. StCR does not show you the number of comments on your comment form. This is either display by another plugin or by your theme.

Best Regards.!!
