### ISSUE TITLE
Description of the checkbox is columnar

### ISSUE THREAD

**Issue by masoud-sadeghi** [stcr/subscribe-to-comments-reloaded#421]
hi
Description of the checkbox is columnar, How to correct it horizontally?
WordPress ver  4.9.6, subscribe to comments reloaded plugin, Company Elite theme

![default](https://user-images.githubusercontent.com/39634112/40566179-c36158f4-6084-11e8-8124-d1fe3fe9c8d4.png)

**Comment by Reedyseth** [comment]
Hi @masoud-sadeghi , that is part of your theme style. You can override the theme style with inline style of the elements. You do that on the `Comment Form` panel

![image](https://user-images.githubusercontent.com/1228711/40566891-17e77cfa-6030-11e8-8fc1-5c9711fb715c.png)
I suggest you to inspect the code with the Chrome Dev Tools or the tool of your choice.

Regards.!!

**Comment by masoud-sadeghi** [comment]
Your advice was great and helpful!
Thanks a lot
<a href="http://uupload.ir/" target="_blank"><img src="http://uupload.ir/files/pwjh_فرم.png" border="0" alt="آپلود عکس" /></a>
