### ISSUE TITLE
[manager_link] issue with https

### ISSUE THREAD

**Issue by manu-p** [stcr/subscribe-to-comments-reloaded#425]
Hi, 

As mentioned [here](https://wordpress.org/support/topic/managment-subcription-links-dont-work/#post-10369195), [manager_link] doesn't work with http**s**.

The source code of the mail received to gain access to the subscription management page shows http://https://etc... instead of just https://etc...

So the web browser then tries to reach https//etc... with the colon missing between https and // ,
which obviously doesn't work. Just manually adding this colon in the URL leads to the management page.

**Comment by Reedyseth** [comment]
Hi @manu-p , thank you for the report.  I am trying to replicate your issue. Regards.!!

**Comment by Reedyseth** [comment]
@manu-p can you show me what it the information that you have on the link here?

![image](https://user-images.githubusercontent.com/1228711/41182468-0d5f5236-6b33-11e8-9f81-bad886dca7ba.png)

Link generation is correctly created by the plugin, You must have the links created like this:

![image](https://user-images.githubusercontent.com/1228711/41182499-3180f494-6b33-11e8-92a4-7a2db0effdd0.png)

**Comment by manu-p** [comment]
Thx @Reedyseth, I guess that was it : WP tends to add http:// to an URL when it's "missing", even when you type a shortcode.
