### ISSUE TITLE
I need notifications to go only to the comment author, not everyone who has commented

### ISSUE THREAD

**Issue by waloob73** [stcr/subscribe-to-comments-reloaded#427]
Looks like out the box this sends notifications to everyone who has commented, I need people to receive a notification only when there is a reply to their own comment, not anyone else's.

Can't see how to achieve this via the settings so happy to code it if you point me to the right place?

Thanks :)

**Comment by Reedyseth** [comment]
Hi @waloob73 did you manage to fix that on the settings? right now there is need to code for this. I am happy that you solved it !!

**Comment by waloob73** [comment]
Yep, found it in settings - not sure how I missed it!
