### ISSUE TITLE
Suddenly receiving admin email for every approved comment

### ISSUE THREAD

**Issue by FloridaGal** [stcr/subscribe-to-comments-reloaded#449]
Using Version 180225 with WordPress Version 4.9.8
I’m not sure if it’s the plugin or something else with WordPress itself, but thought I should start here.
A couple of days ago I began receiving an email for every comment I approve. I’ve been looking everywhere in the tabs for the plugin but can’t see a place to “deactivate” this new behavior. Maybe I just need direction to the right place?
Any thoughts or suggestions would be most welcome.
Thanks!
(Have also posted this in WP plugin forum)

**Comment by elbebass** [comment]
Also on WordPress 4.9.8 using version 190214 and experiencing the same problem. There is an option for activating this feature (now?) but it's deactivated but we still receive emails about new comments on the admin email address.

**Comment by WPKube** [comment]
Hi,

There is an option to send the emails to the administrator email as BCC.  Option is named "BCC Admin on notifications" and is located in WP admin > StCR > Options. But it is disabled by default.

Any chance you could do a screenshot of one of the emails you received, should help me figure out if it's coming from the plugin or from elsewhere.

**Comment by elbebass** [comment]
The mails are those from StCR since they contain exactly the content which the user is receiving. I also can see that the same email is sent via our SMTP service provider (they show time and subject/receiver of all sent mails). I double checked the settings and what is written to the WP options table. BCC to admin is set to false.

**Comment by elbebass** [comment]
@WPKube i did look into the code again. This function call seems odd:
https://github.com/stcr/subscribe-to-comments-reloaded/blob/master/src/wp_subscribe_reloaded.php#L346

Since it should notify the author but gathers the WordPress admin email. Also we did enable author notification emails... I will disable them and see if those admin emails won't be sent.

**Comment by BobaWebDev** [comment]
@elbebass 

That one is connected to the "Subscribe authors" option located in WP admin > StCR > Options. It's disabled by default, but perhaps something got mixed up in there. What's the value you have for "subscribe_reloaded_notify_authors" in the WP options table?

But there is an issue in that code, shouldn't cause this exact problem but that's supposed to be notifying the author, not the admin.  We'll get that fixed up. 

As for the original problem, I'll do some testing today and try to replicate that issue. If I manage to replicate it today then an update will be released today.

**Comment by WPKube** [comment]
@elbebass 

That one is connected to the "Subscribe authors" option located in WP admin > StCR > Options. It's disabled by default, but perhaps something got mixed up in there. What's the value you have for "subscribe_reloaded_notify_authors" in the WP options table?

But there is an issue in that code, shouldn't cause this exact problem but that's supposed to be notifying the author, not the admin. We'll get that fixed up.

As for the original problem, I'll do some testing today and try to replicate that issue. If I manage to replicate it today then an update will be released today.

**Comment by elbebass** [comment]
@WPKube seems to be that codeline. We had the option activated and were experiencing the problem described here. Yesterday we deactivated the option for authors and the mails to the admins stopped.

**Comment by WPKube** [comment]
@elbebass Just to confirm, that option was activated by you ( it was not active by default ), correct? Thanks for the help in figuring out the issue.

@FloridaGal Do you have the "Subscribe authors" option active?

**Comment by elbebass** [comment]
@WPKube yep we activated it after installation.

**Comment by BobaWebDev** [comment]
@elbebass @FloridaGal Was just wondering if you tried out the new version, does it fix the issue?

**Comment by elbebass** [comment]
@BobaWebDev works like a charm, thanks

**Comment by BobaWebDev** [comment]
@elbebass Great, thanks.
