### ISSUE TITLE
Suggestion re wording

### ISSUE THREAD

**Issue by padraigobeirn** [stcr/subscribe-to-comments-reloaded#451]
In the Management Subscription page the top Action in the drop-down is 'Delete'. I think this would be better if it read 'Unsubscribe' instead of 'Delete'. A list of posts with an action to 'Delete' may be misleading to new users. 'Unsubscribe' is clearer in my opinion. Just a suggestion. :-)

**Comment by Reedyseth** [comment]
Hi @padraigobeirn thank you for your suggestion. It will be available on the next version.

https://github.com/stcr/subscribe-to-comments-reloaded/commit/8b872933761009505655f7a72bcfc43c7ebd2536
