### ISSUE TITLE
wordpress adding p tags to javascript

### ISSUE THREAD

**Issue by victorburgos12** [stcr/subscribe-to-comments-reloaded#458]
On manage subscription page, there are 2 clickable links: "**Select all**" and "**invert selection**".
They are not working because Wordpress is adding `<p>` tags to the javascript inside **/plugins/subscribe-to-comments-reloaded/templates/user.php**

![image](https://user-images.githubusercontent.com/37320468/50328170-27d4cc00-04c0-11e9-8761-a73a3c157a46.png)

To fix this issue temporarily, I added `<pre>` and `</pre>` tags on lines 136 and 173.
After that, the `<p>` tags were gone and the clickable links started to work again.

![image](https://user-images.githubusercontent.com/37320468/50328108-c876bc00-04bf-11e9-887b-e394f25fe042.png)

I'm not sure if this is the best solution or if it is better to move the script to js files and use wp_enqueue.

**Comment by Reedyseth** [comment]
Hi @victorburgos12 I think this issue is not part of StCR.I have tested the latest version and tried to replicate this issue but JS is working Okay. I think that you theme is causing this behavior.
What version of WordPress are you using?

Regards.!!

**Comment by victorburgos12** [comment]
Hi Reedyseth, thanks for checking this, I'm using version 5.0.2–es_ES
The theme is Boss social learner.
Do you have any recommendation to find out if my theme is causing the problem?

**Comment by Reedyseth** [comment]
> Do you have any recommendation to find out if my theme is causing the problem?

Yes, just try to activate a different theme, if you get the StCR selection working then I will suggest to check your *Boss social learner* theme comments section to see how is outputting the information.

If is a free theme or paid? If its free can you point me out the theme URL? if its paid I can't do much.

**Comment by victorburgos12** [comment]
Thanks Reeyseth, this is a paid theme, I will contact the developer.
