### ISSUE TITLE
Post editor doesn't work after installing GDPR plugin

### ISSUE THREAD

**Issue by DanieleLudus** [stcr/subscribe-to-comments-reloaded#459]
Hello,

I've just installed the plugin and I noted that now the text editor in post page doesn't work. I try to explain the issue:
if the editor is set on Visual, I cannot shift to Text, and if the editor is set on Text I cannot shift to Visual.

I haven't this issue in the Page editor.

If I disable the GDPR plugin, the editor works.

I hope you can help me with this problem.

Best regards,
Daniele

**Comment by Reedyseth** [comment]
Hi @DanieleLudus what whas the issue?

Best Regards.!!

**Comment by DanieleLudus** [comment]
Sorry, it was an error mine.



Il giorno ven 18 gen 2019 alle ore 19:25 Israel Barragan C. <
notifications@github.com> ha scritto:
