### ISSUE TITLE
Bug Report: <html in text>

### ISSUE THREAD

**Issue by scargill** [stcr/subscribe-to-comments-reloaded#465]
I'm assuming this has to be a bug in STCR - in my blog https://tech.scargill.net - I use STCR - and when I get comments via email in Outlook - they are full of raw html.

**Comment by Reedyseth** [comment]
Hi @scargill.

Please make sure that you have the **Enable HTML emails** options set to Yes.

Regards.!!

**Comment by scargill** [comment]
Hey, thanks That worked....

**Comment by Reedyseth** [comment]
Awesome !!

**Comment by scargill** [comment]
I'm hoping that won't open up a can of worms like getting emails blocked. I'd be happy having comments going out as plain text - just not with that HTML code converted to text in the middle of everything. Surely that could not have been the intention of ticking no to HTML emails?
