### ISSUE TITLE
'Track all subscriptions' button shown twice

### ISSUE THREAD

**Issue by ilebel** [stcr/subscribe-to-comments-reloaded#467]
As you can see in the attached screenshots, the 'Track all subscriptions' button is shown twice within the plugin settings.
It seems two different functionalities have been associated by mistake to the same button.

![track all subscriptions option](https://user-images.githubusercontent.com/36996012/52179239-0ada2b00-27d8-11e9-88e8-0b8005a6e1c3.PNG)
![track all subscriptions option_1](https://user-images.githubusercontent.com/36996012/52179240-0ada2b00-27d8-11e9-851f-834cbd502aa9.PNG)
![track all subscriptions option_2](https://user-images.githubusercontent.com/36996012/52179241-0b72c180-27d8-11e9-9f72-298312f8f659.PNG)

**Comment by Reedyseth** [comment]
Hello @ilebel , Thank for catching this out. I have fix the typo and will be ready for the next update bab033a.
