### ISSUE TITLE
Recurrent typo: 'you' instead of 'your'

### ISSUE THREAD

**Issue by ilebel** [stcr/subscribe-to-comments-reloaded#468]
As you can see in the attached screenshots, there's a recurrent typo within the info boxes: 'you' instead of 'your'.
Additionally, the explanation for the 'Show StCR' button is confusing as it is not clear if it is intended to disable or enable the corresponding functionality. Please, make it clearer.

![enable font awesome option typo_you instead of your](https://user-images.githubusercontent.com/36996012/52179335-6bb63300-27d9-11e9-9f1f-a56e0d8107c1.PNG)
![show stcr option_unclear typo](https://user-images.githubusercontent.com/36996012/52179336-6c4ec980-27d9-11e9-9b97-8425f039c86f.PNG)

**Comment by Reedyseth** [comment]
Hi @ilebel Thank you for your suggestion, I have taken care of this and will be available on the next update. b0a7863
