### ISSUE TITLE
Send notifications to the right admin

### ISSUE THREAD

**Issue by nathansmind** [stcr/subscribe-to-comments-reloaded#476]
The notifications I get, are being sent to one of our admin email accounts, but I would like them to come to my email account. The other account is tied to all of our internal accounts, and everyone gets notified. This is not what we want as only one person needs to handle and respond to comments. How can I change the admin email?

**Comment by BobaWebDev** [comment]
Hi,

The update to fix that will be released today.

**Comment by nathansmind** [comment]
Wow, cool. I will keep my eyes open for it. Thanks!

**Comment by BobaWebDev** [comment]
You're welcome.

**Comment by BobaWebDev** [comment]
@nathansmind Hi Nathan, was just wondering if you tried the new update, does it fix the issue you had?

**Comment by nathansmind** [comment]
Yep, I got it updated and it is working properly now. Thank you!

**Comment by BobaWebDev** [comment]
Great, happy to hear that. You're welcome.
