### ISSUE TITLE
Subscribers management link not working

### ISSUE THREAD

**Issue by moeller79** [stcr/subscribe-to-comments-reloaded#481]
The link my subscribers receive in emails to manage their subscription takes them to a 404 page on my website.

How do I get the actual management page to work for them so they can easily manage it themselves?

Thanks,
Mikael

**Comment by BobaWebDev** [comment]
Hi Mikael,

Is only the link they receive in the email taking to a 404 or does it also happen for logged in users (you can try) when clicking to manage the subscriptions of a post (the link after the comment form)?

**Comment by moeller79** [comment]
It is both the link in the email and the manage subscription link of posts that takes them to a 404.

**Comment by BobaWebDev** [comment]
Hi Mikael,

Can you send over the URL to the website?

**Comment by moeller79** [comment]
it is: https://paidfromsurveys.com/

Thanks

**Comment by BobaWebDev** [comment]
Sorry for the wait, weekend got in the way.

I see the issue.

Can you do a quick switch to a default WP theme, try the management link/url and then reactivate the current theme. That way we can know if the conflict is related to the theme or not.

If the issue happens on the default WP theme as well, can you send over a list of plugins you are using and I'll set up the same plugins on my installation and hopefully get the issue and be able to debug it.

**Comment by moeller79** [comment]
I cannot really switch to a default WP theme. My site is mostly built with Divi and its page builder. If I change to a default theme all my formatting, buttons, setup, etc. will be lost. So that is not really an option.

Do you have another suggestion about how to find out where the issue is?

The plugins I am using are: 
All in One SEO pack
Bloom
Cookie notice
Monarch plugin
MyThemeShop connect
Official Facebook pixel
Pretty links
WP edit
WP pro review
And then, of course, the STCR

Thanks,
Mikael

**Comment by BobaWebDev** [comment]
Can you try the following:

1. Go to WP Admin > StCR > Management Page
2. Set "Virtual management page" to "No" and save changes
3. Go to WP admin > Pages > Add New and create a page called "Comment subscriptions", the permalink should be comment-subscriptions

Then try to go to https://paidfromsurveys.com/comment-subscriptions

Does it still show a 404, or does it show the page with the subscription info or perhaps empty content (but not 404)?

**Comment by moeller79** [comment]
Thanks. I have now done that.

Now it just shows an empty page. No 404 but just a blank page.

**Comment by BobaWebDev** [comment]
Just to mention that I am working on the issue. It's a bit harder since I can not replicate it but will figure it out.

**Comment by moeller79** [comment]
Thanks for the update. Appreciate it and looking forward to hearing from you again.

Thanks

**Comment by BobaWebDev** [comment]
You're welcome and thanks for your patience. 

So the solution that came to mind is using a shortcode. So instead of the "virtual page" and everything that comes with it that can go wrong we go with a simpler solution.

So on that page you created you would place `[stcr_management_page]` in the content. That will then be replaced by the plugin's content for the management page.

Do you have some experience editing code? These are the changes that make that possible https://github.com/stcr/subscribe-to-comments-reloaded/commit/d7c995e72604e2673233830cb1d848699eb896c7

It's Friday 9PM and I don't like making updates so close to the weekend, because I'm often out of town during weekends. I like to be available in case anything happens to go wrong. The new update has some bigger changes. So it will be released on Monday, there's also a few more things I need to take care of before the release.

**Comment by moeller79** [comment]
Sounds great you came up with a solution.

Do not have experience in editing code. Only use code when I get a certain code and are told exactly where to put it:-)

Do I understand you correctly that once you have made the update Monday, I will be able to include the shortcode on the page I created for the comment subscription and then it should work?

Thanks,
Mikael

**Comment by BobaWebDev** [comment]
Hi Mikael,

Just released the new update. Give it a try and let me know how it goes.

So, just put the `[stcr_management_page]` shortcode in the content of the page you created. Hopefully it works out, as mentioned I wasn't able to replicate the exact issue you are having.

**Comment by moeller79** [comment]
Now it just shows the shortcode as text on the page. Any ideas?

Thanks,
Mikael

**Comment by BobaWebDev** [comment]
If it shows it as text then it's like WordPress does not know the shortcode exists. 

Can you try adding this on the page and let me know if that shortcode does anything or it also shows as text

`[caption]test[/caption]`

Does it show only `test` or does it show the full shortcode?

**Comment by BobaWebDev** [comment]
Based on the source code of the posts you are running version 190305, that's the previous one, did you run the update?

**Comment by moeller79** [comment]
I am so sorry - was so eager to test that I did not think about updating the plugin. It looks like it is working fine now.

Thank you very much. Will go and give a donation to the plugin as thanks for all the help. I appreciate it.

**Comment by BobaWebDev** [comment]
Awesome, happy to hear that.

As for the donation, thank you but we don't accept donations at the moment. There was a donations system but that's from the previous owner of the plugin, we removed that. Instead if you can [rate the plugin on WordPress](https://wordpress.org/support/plugin/subscribe-to-comments-reloaded/reviews/#new-post) that'd be fantastic.

**Comment by moeller79** [comment]
Great. I will definitely do that. Maybe also soon write a blog post about your plugin on one of my other websites:-)

Thanks again

**Comment by BobaWebDev** [comment]
You're welcome and thank you :)
