### ISSUE TITLE
Notices

### ISSUE THREAD

**Issue by marilyn1998** [stcr/subscribe-to-comments-reloaded#482]
I am using the option BCC admin yes. I have turned off the WP settings/discussion email me when anyone leaves a comment. I am correctly receiving notifications when a comment is left. But I am also receiving notification when I reply. What settings do I need to receive notice someone left a comment but not when I reply? I am the only author on the blog as well as the admin. Thx

**Comment by BobaWebDev** [comment]
Hi,

There's no option for that but we'll make it work like that by default in the next update.

**Comment by BobaWebDev** [comment]
Hi @marilyn1998,

Released an update today, give it a try and let me know if the issue you were having is gone.

**Comment by marilyn1998** [comment]
It sure did!!! Thank you.

		
Marilyn Lesniak
Owner, Marilyn's Treats
marilyn1998@comcast.net
https://www.marilynstreats.com
						


On Mar 25, 2019, at 6:54 PM, Slobodan Kustrimovic <notifications@github.com> wrote:

Hi @marilyn1998,

Released an update today, give it a try and let me know if the issue you were having is gone.

**Comment by BobaWebDev** [comment]
Great, happy to hear that. You're welcome.
