### ISSUE TITLE
Commenters Names are Scrambled after Genesis Update

### ISSUE THREAD

**Issue by BNOTP** [stcr/subscribe-to-comments-reloaded#483]
Had a Genesis Update today and now when a reader leaves a comment on my blog post, their name shows as either the word, "Says" or some scrambled version of their name with characters and numbers. I think it may have something to do with the Genesis update. See examples of this in today's post here:  https://betweennapsontheporch.net/welcoming-spring-with-a-floral-table-setting-perfect-for-easter-or-a-garden-party/

**Comment by BobaWebDev** [comment]
Hi,

The plugin does not alter the author name. Can you run a quick test, try switching to a default WordPress theme, check if the issue still happens there and then switch back to Genesis.

If the issue does not happen on the default theme then the issue is with Genesis, if it does then let us know and we'll figure out the next steps.

**Comment by BNOTP** [comment]
I'm afraid to do that, I'm not sure if it would affect my current theme or
if I could switch back. I've never done that before. It's weird because the
names are fine in the comment section of the dashboard, they just don't
show correctly on the front of the blog. And I've never touched my code in
the Editor, so it has to have been something caused by a recent update.

Thanks
Susan Herin


Between Naps on the Porch <http://betweennapsontheporch.net/>
Subscribe to BNOTP by e-mail
<http://forms.aweber.com/form/39/2054351739.htm>
BNOTP Facebook
<http://www.facebook.com/pages/Between-Naps-on-the-Porch/176107605878>

**Comment by BobaWebDev** [comment]
Did some searching and found other Genesis users reporting the issue, so it is a Genesis related issue, not with the plugin. 

https://wordpress.org/support/topic/something-weird-has-happened-in-the-comments-section/

**Comment by BNOTP** [comment]
Wow, thank you for that! I Googled my head off last night trying to find
anything online and couldn't find anything. Thank you for finding that.
I'll quit worrying and wait for an update.
Susan

P.S. I think I've donated in the past but where can I donate for your
plugin?


Between Naps on the Porch <http://betweennapsontheporch.net/>
Subscribe to BNOTP by e-mail
<http://forms.aweber.com/form/39/2054351739.htm>
BNOTP Facebook
<http://www.facebook.com/pages/Between-Naps-on-the-Porch/176107605878>

**Comment by BobaWebDev** [comment]
You're welcome. 

Thank you for the offer. There used to be a donation link in the settings pages for the plugin, but the plugin recently got a new owner, [WPKube](https://www.wpkube.com/), and we removed the donations link.

So we do not accept donations at the moment but if you could [rate the plugin](https://wordpress.org/support/plugin/subscribe-to-comments-reloaded/reviews/#new-post) that would be perfect.

**Comment by BNOTP** [comment]
Ok, thanks!
Susan


Between Naps on the Porch <http://betweennapsontheporch.net/>
Subscribe to BNOTP by e-mail
<http://forms.aweber.com/form/39/2054351739.htm>
BNOTP Facebook
<http://www.facebook.com/pages/Between-Naps-on-the-Porch/176107605878>

**Comment by BobaWebDev** [comment]
You're welcome and thank you.
