### ISSUE TITLE
Getting 403 page when confirming comment subscription

### ISSUE THREAD

**Issue by on84** [stcr/subscribe-to-comments-reloaded#484]
Hi!
I have enabled the verification email for GDPR purposes.
But when clicking on the link in the confirmation email, a 403 error page always displays, reading this:

"You don't have permission to access /comment-subscriptions/ on this server."

I have tried with different emails and got the same message. Anf of course, users don't get confirmed.
How can I fix this? Thank you!

**Comment by on84** [comment]
Actually it seems to be caused by the security plugin, since it works when I disable all security features, which of course is not a solutioon. I could use a piece of advice about whaich security functionality migth causde the issue( apparently not the firewall). Thanks.

**Comment by BobaWebDev** [comment]
Happy to hear it's sorted out.
