### ISSUE TITLE
Subscribe to Comments Reloaded not working

### ISSUE THREAD

**Issue by kayharms** [stcr/subscribe-to-comments-reloaded#486]
I have downloaded and activated this plugin twice and am getting no results. The "replies to my comment only" selection is not showing up. Are there any hidden things somewhere else that could be preventing this? Help! I really need to help my readers get email responses from me on their comments. They don't want everyone's comments, just mine. I need this option. But I can't get it to work.
![2019-03-21](https://user-images.githubusercontent.com/48773994/54791379-e060f780-4bf6-11e9-988c-bca8cbccbf20.png)

**Comment by BobaWebDev** [comment]
I answered on the original ticket.
