### ISSUE TITLE
Documentation? and forcing a notification to a subscriber

### ISSUE THREAD

**Issue by gilles008** [stcr/subscribe-to-comments-reloaded#489]
Hi!
Thanks so much for this great plugin!

After spending time looking for documentation, I've come empty-handed. I hope you can help.

1. Is there a way to trigger a notification to a subscriber of a post? That is, a person who has commented on a post and who is subscribed to this post is not receiving notifications when replies are submitted. Can I trigger a notification to be re-sent? This would help me test and find out what the problem is.

2. In the Manage Subscriptions page: stcr_manage_subscriptions
there is an Action at the bottom but the actions are very unclear:
Activate and set to R
Suspend
Activate
Activate and set to Y, etc
Where can I find what the four options actually mean/do?

Cheers!

**Comment by BobaWebDev** [comment]
Hi,

1. The system hooks into the comment process of WordPress. When that process takes place the plugin sends out the emails to those who are subscribed. But it does not store information about every notification (would make the database quite large very fast)  so there's no way to resend a specific notification. 

The only way to test notifications would be to post a new comment. 

2. We'll update those labels to be more descriptive. "Activate and set to R" activates the subscription and sets it to notify on replies to the comment. "Activate and set to Y" does the same but sets to notify on all comments, not just direct replies. "Activate" just activates it without changing the type of subscription.  "Delete" of course deletes the subscription completely.  "Suspends" sets the status to "unconfirmed" so it's sort of like a temporary disable, it's still there so you can activate it again later.

**Comment by gilles008** [comment]
Wonderful! Thanks for your reply.
Is there documentation somewhere so I review before posting here and potentially asking questions which have already been asked or save you time?

**Comment by BobaWebDev** [comment]
You're welcome.

No documentation at the moment, most options have a ? icon, hovering over it shows more information. We will look into writing up usage documentation for the plugin.

**Comment by gilles008** [comment]
Sounds good. Thanks for getting back to me.

⁣________________________
Sent from Gilles' mobile
NEW! - AwesomeCustomerExperience.com
- Practical knowledge on the art of providing awesome customer  experiences​

**Comment by BobaWebDev** [comment]
You're welcome.
