### ISSUE TITLE
Doesn't work StCR Position

### ISSUE THREAD

**Issue by livecaiv** [stcr/subscribe-to-comments-reloaded#491]
Hello. I have an issue with StCR Position. When it's enabled the checkbox is missing at all.

**Comment by BobaWebDev** [comment]
Hi,

I think I know what happened in there, we'll release an update today.

But the option "StCR Position" option is a fallback, in case the theme is outdated and doesn't handle the comment form the usual way. I'm assuming you also tested it with the option disabled, correct?

**Comment by livecaiv** [comment]
> Hi,
> 
> I think I know what happened in there, we'll release an update today.
> 
> But the option "StCR Position" option is a fallback, in case the theme is outdated and doesn't handle the comment form the usual way. I'm assuming you also tested it with the option disabled, correct?

Yes, of course. I've checked the plugin with the option disabled, but the theme that I'm using is outdated.

**Comment by livecaiv** [comment]
Hello. What about solution to the problem?

**Comment by BobaWebDev** [comment]
Hi,

It's ready, releasing in a couple hours. Working on one last fix before releasing, but I'm waiting for some further information from the person experiencing the bug so I can properly replicate and fix. If he does not answer I'll go ahead and release the update without that fix.

**Comment by livecaiv** [comment]
What information can help you?

**Comment by BobaWebDev** [comment]
Thanks, but it's a different bug. Unrelated to this one. If I don't receive an answer from him in 2 hours I'll go ahead and submit the update.

**Comment by livecaiv** [comment]
From who? I asked you about bug with StCR Position

**Comment by BobaWebDev** [comment]
Released the update, give it a try and let me know if it works as expected.

**Comment by livecaiv** [comment]
Hello. I see that the checkbox code has appeared in the page code, but the css styles prohibiting the display have also been added.

> .stcr-hidden{display: none !important;}

**Comment by BobaWebDev** [comment]
Hi,

Try the 190411 version that we just released.

**Comment by livecaiv** [comment]
> Hi,
> 
> Try the 190412 version that we just released.

Nothing has changed :(

**Comment by BobaWebDev** [comment]
Can you send over the URL to the website?

**Comment by livecaiv** [comment]
> Can you send over the URL to the website?

https://ladavestarus.ru/novosti/prezentaciya-lady-vesty-pryamaya-translyaciya.html

**Comment by BobaWebDev** [comment]
jQuery is used to move the StCR elements in the proper place and after that show them. But jQuery is being loaded at the end of the page so when it's called by StCR code it does not exist yet. 

Can you add the following JavaScript code where the rest of the JavaScript code is. For example wp-content/themes/ladarus/js/kulik.js

`jQuery(document).ready(function($){var stcr_form=$('div.stcr-form');stcr_form.prevUntil('form').each(function(){var _this=$(this);if(_this.find(':input[type="submit"]').length){stcr_form.remove(),_this.before(stcr_form);$('div.stcr-form').removeClass('stcr-hidden');return false;}})});`

**Comment by livecaiv** [comment]
Fine! Now everything is working correctly. Thank you!

**Comment by BobaWebDev** [comment]
You're welcome, happy to hear it's sorted out.
