### ISSUE TITLE
Default Checkbox Value is not considered & German translation typo

### ISSUE THREAD

**Issue by robertharm** [stcr/subscribe-to-comments-reloaded#492]
First thanks for your great plugin - I really like how easy it is to customise.

Not sure if I found a bug though - I have these settings:
![grafik](https://user-images.githubusercontent.com/158669/55675013-87fb4c80-58bc-11e9-85ae-1e8120ac3fe8.png)

On frontend though, "Reply my comments" is selected as a result and not as expected the dropdown option "all":
![grafik](https://user-images.githubusercontent.com/158669/55675015-99445900-58bc-11e9-9f31-5a22794b4ad8.png)

I deactivated all other plugins to verify if this could be caused by a plugin conflict, did not have any effect though. 

Is this a known issue or am I missing something?

Thanks for your help!

PS: I also found German translation typo - it should not be called "Nicht abbonieren" but "Nicht abonnieren" - perhaps this could be changed with the next release too.

**Comment by robertharm** [comment]
Strange - it seems to work now, I assume the last checked option is remembered. So this ticket can be closed.
Would be great though if the German typo could be fixed.

**Comment by BobaWebDev** [comment]
Hi,

Happy to hear it works.

Thanks for letting us know about the translation issue. We'll get that fixed in the next update.

**Comment by robertharm** [comment]
thx & you´re welcome!
