### ISSUE TITLE
Update info message refuses to clear

### ISSUE THREAD

**Issue by gilles008** [stcr/subscribe-to-comments-reloaded#505]
Greetings,
After updating the plugin, the backend/dashboard displays two update notifications. It's the message from the plugin which begins with:

> Subscribe to Comments Reloaded has been updated to version 190214
> This version includes fixes.,
> If you find a bug or an issue you can report it here....

Clicking on the X in the top right removes it from the screen but it reappears when the page is reloaded. The "Dismiss" link has a spinning wheel next to it and when "Dismiss" is clicked, nothing happens. 

I tested this in both Ffox and Chrome.
Any ideas on how to acknowledge and remove these update notifications?

Cheers!

**Comment by BobaWebDev** [comment]
Hi,

Thanks for lettings us know.  Those notifications shouldn't be showing up, can you let me know which version did you use prior to updating, so I can install that version and then update, hopefully it replicates the issue.

**Comment by gilles008** [comment]
Hi, Thanks for your response. 
The two notifications we're receiving are for 190117 and 190214.
I assume it would be for the version just before those.
I look forward to hearing from you.

**Comment by BobaWebDev** [comment]
The version prior to that was version 180225 which is from February 25th 2018. Does that sound correct ( haven't made updates since then )?

**Comment by gilles008** [comment]
Hmm... I always keep this website updated. I'm only going by the dates currently reported as having been updated in the dashboard.
I've attached a screenshot. I hope this helps.
 
![image](https://user-images.githubusercontent.com/2866459/58502939-9d228800-8155-11e9-80cf-feb5b2e3ad62.png)

**Comment by BobaWebDev** [comment]
Oh, it's showing the PayPal donation links. We removed all donation links (including the ones that show in the notices) back on March 1st. 

So, this is a bit weird. I'm running some tests at the moment to try and replicate that. 

There's a planned update for tomorrow morning ( about 13 hours from now ) and a fix for this will be included. **But if it's urgent** let me know and we'll figure out some way to get rid of those notifications now.

**Comment by gilles008** [comment]
no problems at all. I can certainly wait for tomorrow :)
Thanks so much. I'll report back here if the issue persists after tomorrow's update.
Cheers!

**Comment by BobaWebDev** [comment]
You're welcome and thank you :)

**Comment by BobaWebDev** [comment]
Hi,

This isn't a fix for what caused the issue (still need to determine that) but it is going to remove them.

http://bobawebdev.com/support/stcr-fix-notice.zip

It's a plugin, so download it, head over to WP admin > Plugins. Click **Add New** then click **Upload Plugin**. Select the ZIP, install and activate.

You should see them go away immediately. Then disable and delete the plugin, the notices won't come back.

**Comment by gilles008** [comment]
Thanks! Can I simply wait for tomorrow's update?

**Comment by BobaWebDev** [comment]
You're welcome. Of course.

**Comment by gilles008** [comment]
Great. I'll do that then. I'll want to update regardless. Cheers!

**Comment by BobaWebDev** [comment]
Hi,

Just released the update. Dismissing the notices should be working fine now.

**Comment by gilles008** [comment]
Thanks a million BobaWebDev. It worked like a charm :)

**Comment by BobaWebDev** [comment]
You're welcome, happy to hear it's sorted out :)
