### ISSUE TITLE
404

### ISSUE THREAD

**Issue by jb1497** [stcr/subscribe-to-comments-reloaded#521]
Hello,

Using the latest version of WordPress and StCR along with a child version of X-theme (also latest version) i was getting 404-page when trying to edit subscriptions. I then followed the guide to create a custom management page (https://github.com/stcr/subscribe-to-comments-reloaded/wiki/KB#create-a-real-management-page)

After following the steps, i do get to the page i created however the page is blank.
It seems that "isset($wp_subscribe_reloaded)" doesn't return true as expected.

Can you help me with a fix?

**Comment by BobaWebDev** [comment]
Hi,

We'll be updating that custom management page documentation, we've made it simpler to create one.

Just create a new page, make sure the slug is the same as the the one set in WP admin > StCR > Management Page. It's **comment-subscriptions** by default. And as the content of the page add [stcr_management_page]

**Comment by jb1497** [comment]
Thanks alot for the quick reply - problem solved 😊

**Comment by BobaWebDev** [comment]
You're welcome :)
