### ISSUE TITLE
Related to checkbox

### ISSUE THREAD

**Issue by a2n6ig** [stcr/subscribe-to-comments-reloaded#523]
When I set Default Checkbox Value to "Replies to this comment" and hit the Save Changes button then Default Checkbox Value automatically updated to "All new comments". This is happening again and again.

See this video to better understand the issue: https://we.tl/t-m8MuXR47LZ

**Comment by BobaWebDev** [comment]
Hi,

We'll get that fixed. In the meantime can you try this:

- Switch “Advanced Subscription” to “Yes”
- Save changes
- Change the “Default Checkbox Value” to “Replies to this comment”
- Save changes
- Switch “Advanced Subscription” to “No”
- Save changes

**Comment by a2n6ig** [comment]
Can you please tell me about how much time it would take to fix this issue? I'm totally rely on this plugin. If you'll tell me the time or date then I would check plugin back on that date.

**Comment by BobaWebDev** [comment]
Did you try the method I mentioned in the previous message. Basically what happens is that the option doesn't update when "Advanced Subscription" is disabled. But you can enable it, change the option and disable it, the value will remain. 

It's not a fix, but it's a temporary workaround that has the same result as the fix will have. 

As for when the update will be release, it depends on the other fixes and improvements that are in the next update. And there's 20 other plugins/themes that also have ongoing maintenance and updates. Which makes things had to predict and plan for.

Might be tomorrow but might be next week. Sorry, can't say for sure.

**Comment by a2n6ig** [comment]
Yes, I followed these steps:

- Switch “Advanced Subscription” to “Yes”
- Save changes
- Change the “Default Checkbox Value” to “Replies to this comment”
- Save changes
- Switch “Advanced Subscription” to “No”
- Save changes

But when I click save changes two times after switching “Advanced Subscription” to “No” then it again switch to "All new comments"

**Comment by a2n6ig** [comment]
Yes, I followed these steps:

- Switch “Advanced Subscription” to “Yes”
- Save changes
- Change the “Default Checkbox Value” to “Replies to this comment”
- Save changes
- Switch “Advanced Subscription” to “No”
- Save changes

But when I click save changes two times after switching “Advanced Subscription” to “No” then it again switch to "All new comments"

I should not click save changes two times.

_**And yes it is working.**_

**One more thing I need to ask:**

When WordPress is sending email to users for new reply added to comment then it is landing in their SPAM folder.

Is it because I have no SMTP enabled?

Can you please tell how can I connect this plugin with SMTP?

**Comment by NEMONAUT** [comment]
I have a PR for this https://github.com/stcr/subscribe-to-comments-reloaded/pull/522
Not sure if it's passable...
