### ISSUE TITLE
"404 PAGE NOT FOUND" When Confirming Subscription via Email

### ISSUE THREAD

**Issue by Lanzilli** [stcr/subscribe-to-comments-reloaded#524]
Hello,

This is a brand new install. Best I can tell is that that [confirm_link]﻿ is not pointed at the correct place. However, before I start trying to change things around, is there a standard procedure I can follow to fix this issue?

Thank you,
Larry

**Comment by BobaWebDev** [comment]
Hi Larry,

Try the following.

Create a new page, make sure the slug is the same as the the one set in WP admin > StCR > Management Page. It's comment-subscriptions by default. And as the content of the page add the shortcode [stcr_management_page]

Publish that page and try the confirmation again.

**Comment by BobaWebDev** [comment]
You're welcome.
