### ISSUE TITLE
Posts are Skewed when Plugin is Active

### ISSUE THREAD

**Issue by Lanzilli** [stcr/subscribe-to-comments-reloaded#525]
Hi,

When Subscribe to Comments Reloaded is active my posts section looks skewed. Below are the images of active / deactive:

Active:
![image](https://user-images.githubusercontent.com/39271907/65514048-7decfa80-deaa-11e9-8241-b5a8362380c0.png)

Deactive:
![image](https://user-images.githubusercontent.com/39271907/65513963-58f88780-deaa-11e9-841c-1df68ce3c9b8.png)

Thanks!
Larry

**Comment by BobaWebDev** [comment]
Hi Larry,

There's a lot of columns in there, it's quite skewed without the plugin as well, so the one column that STCR adds just makes it worse.

At the top right you can see "Screen Options", click that and a section with checkboxes will show up. In there you can disable the columns you don't need which makes more room for the other columns.

Based on the screenshot you are not using tags, so you can disable that one.

**Comment by Lanzilli** [comment]
That worked! Thank you.

**Comment by BobaWebDev** [comment]
You're welcome.
