### ISSUE TITLE
Related to Stcr form

### ISSUE THREAD

**Issue by a2n6ig** [stcr/subscribe-to-comments-reloaded#526]
Hi,

I want to change the text from 'email' to 'Email address' here: https://bit.ly/2olXKZV

I'm also getting a problem to find the exact file in plugin editor to edit that text.

Please help me by telling the exact file location to edit that text.

I'll wait for your reply.

**Comment by BobaWebDev** [comment]
Hi,

It's localized, you can use any WP translation method you prefer. [Loco Translate](https://wordpress.org/plugins/loco-translate/) is very user friendly.

Alternatively you could change it directly in the code but keep in mind that gets overwritten on plugin update. It's templates/request-management-link.php on line 115.

**Comment by a2n6ig** [comment]
Here, it is on line 103: `$email = 'email';`

Now I have changed it to `$email = 'Email address';`

**Problem solved!!**

**Comment by BobaWebDev** [comment]
Happy to hear it's sorted out.
