### ISSUE TITLE
Related to Notifications > Notification subject

### ISSUE THREAD

**Issue by a2n6ig** [stcr/subscribe-to-comments-reloaded#527]
Hi,

In Notifications > Notification subject, I'm trying to add the tag **[post_title]** with the **Quotation mark**.

Like this: **"[post_title]"**

But when I click on the **Save changes** button at the bottom of the screen the complete tag with the quotation mark  (**"[post_title]"**) disappeared automatically.

How to solve this issue? Is there any coding way or edit file in the Plugin editor. I'm ready to do anything but please solve my problem.

**Comment by a2n6ig** [comment]
Hi,

Waiting for the reply.

**Comment by BobaWebDev** [comment]
Hi,

Sorry for the wait, weekend got in the way.

An update is being released today, that issue is fixed.

**Comment by a2n6ig** [comment]
Thank you for your reply.

But I haven't gotten any update till now. Also on the plugin page, it is showing me "Last Updated: 4 months ago" (See here: [](https://prnt.sc/pgmdnq))

Have you guys increased the date?

**Comment by BobaWebDev** [comment]
Hi,

Yeah, sorry, it's moved for Wednesday (tomorrow). We have a lot of plugins/themes and update plans conflicted a bit. It's at the top of the list for tomorrow.

**Comment by a2n6ig** [comment]
No problem :)

For this issue: [#528](url)

Please check the email that you have provided here: [https://github.com/BobaWebDev](url)

**Comment by a2n6ig** [comment]
Hi Slobodan,

Sorry for the late reply. Yes, now I can confirm that this issue has been solved.

Thank you so much :)

**Comment by BobaWebDev** [comment]
You're welcome.
