### ISSUE TITLE
Problem in Notifications > One Click Unsubscribe

### ISSUE THREAD

**Issue by a2n6ig** [stcr/subscribe-to-comments-reloaded#528]
I have tag **[post_title]** in One Click Unsubscribe option. See here: https://prnt.sc/pew4zu

But when users are clicking the unsubscribe button in the email then on the website for tag **[post_title]**, it is showing me the post slug. See here: https://prnt.sc/pew5yl

I don't know why it is showing post slug instead of post title for tag **[post_title]**.

I also checked the code and there is also tag **[post_title]** is enabled. See here: https://prnt.sc/pew8e6

Please help!!

**Comment by a2n6ig** [comment]
Hi,

Waiting for the reply.

**Comment by BobaWebDev** [comment]
Hi,

Sorry for the wait, weekend got in the way.

Just tested it out and seems to be working fine. Can you send over the URL to your website, seeing it might help me figure out what's going on.

get_the_title() is used for [post_title] so whatever WordPress passes back it is what the plugin uses so I'm not quite sure why the slug is being returned.

**Comment by BobaWebDev** [comment]
The issue will be fixed in today's update.

**Comment by a2n6ig** [comment]
Okay, Slobodan.

I'll wait for the update.

**Comment by BobaWebDev** [comment]
Hi,

Just released the update. Give it a try and let me know if the issues are resolved.

**Comment by a2n6ig** [comment]
Hi Slobodan,

Sorry for the late reply. Yes, now I can confirm that this issue has been solved.

Thank you so much :)

**Comment by BobaWebDev** [comment]
You're welcome.
