### ISSUE TITLE
Related to subscription management URL

### ISSUE THREAD

**Issue by a2n6ig** [stcr/subscribe-to-comments-reloaded#531]
By default, subscription management URL was: **mydomain.com/manage-subscriptions/**, but I have changed it to **mydomain.com/comment-subscription/**

Now when users type **mydomain.com/comment-subscription/** then it opens perfectly, but when they type **mydomain.com/comment-subscription** then it redirects to my 404 error page.

You can see in both URLs there is an only difference of **slash (/)** at the end or URL.

This problem is only occurring with this URL.

One solution is I can redirect **mydomain.com/comment-subscription** to **mydomain.com/comment-subscription/**

But I also want to know that if redirection of the URL is the only solution to this problem?

**Comment by BobaWebDev** [comment]
Hi,

Thanks for lettings us know. I'll do some tests and figure out a solution.

**Comment by a2n6ig** [comment]
Okay, I'll wait for your reply.

**Comment by BobaWebDev** [comment]
Hi @a2n6ig 

There's an update coming on Monday. One of the fixes is for this issue.

**Comment by BobaWebDev** [comment]
Hi @a2n6ig 

Just released the update that fixes the issue.

**Comment by a2n6ig** [comment]
Sorry for the very late reply.

Thanks, Slobodan :)

**Comment by BobaWebDev** [comment]
You're welcome :)
