### ISSUE TITLE
Fix line up email submit field and button on mobile

### ISSUE THREAD

**Issue by cmartini** [stcr/subscribe-to-comments-reloaded#534]
![image](https://user-images.githubusercontent.com/15214291/67411881-3bf0ca80-f5b6-11e9-8ea9-6333eb58107d.png)

Love the plugin, but is there a fix to line up the email field and submit button on mobile?

Cheers

**Comment by BobaWebDev** [comment]
Hi @cmartini 

Thanks, happy to hear you like it.

The plugin does not apply any styling for the form, it's inherited from the theme. Try adding this in WP admin > Appearance > Customize > Additional CSS:

`@media only screen and (max-width: 768px) {
    form[name="sub-form"] label {
        display: none;
    }
    form[name="sub-form"] p {
        display: flex;
    }
    form[name="sub-form"] .subscribe-form-field {
        flex-grow: 1;
        width: auto;
    }
}`

**Comment by cmartini** [comment]
Yes that works, thanks!

**Comment by BobaWebDev** [comment]
You're welcome.
