### ISSUE TITLE
Not showing form form me 

### ISSUE THREAD

**Issue by javiersaord** [stcr/subscribe-to-comments-reloaded#535]
Hi there,

I changed theme and before the plugin worked for me but it not working now.
I have form_comment() function for show comments in single.php.
I need you help me.
![pantallazo-comentarios](https://user-images.githubusercontent.com/2932285/67632011-00981980-f89e-11e9-983d-9160d4a3e124.png)
![Screenshot_2019-10-27 Opciones ‹ ❤ Mejor Entrenador Personal Online desde 2010 — WordPress](https://user-images.githubusercontent.com/2932285/67632024-21f90580-f89e-11e9-9b4e-5cb55dc2d4ec.png)

**Comment by javiersaord** [comment]
php 7
wordpress 5.2.4

**Comment by javiersaord** [comment]
Resolved!! I have display:none; in class respond-box.
But i like that form appear start the page not in end.

**Comment by javiersaord** [comment]
Ok, resolved!! 
How

**Comment by BobaWebDev** [comment]
Happy to hear it's sorted out.
