### ISSUE TITLE
Checkbox missing

### ISSUE THREAD

**Issue by luiszarza** [stcr/subscribe-to-comments-reloaded#539]
Hi, 

The checkbox on the comments box is missing. Here's blog post of the site where it should be showing: https://www.saracristinaespina.com/menorca/

Plugin version: 191028 

WordPress Version: 5.2.4
Theme: Ignition (v1.91)

Please advice on how to solve it. The issue might be coming from theme, but still some guidelines on how to solve it would be appreciated.

Thank you

**Comment by BobaWebDev** [comment]
Hi @luiszarza 

Might be the theme, some older themes handle the comment form a bit differently.  I noticed on the website of that theme author that the theme is discontinued, so it's probably an old one.

Go to WP admin > StCR > Options. You will see an option called "StCR Position" in there, switch that to "Yes" and save changes. That option is meant for those older themes.

**Comment by luiszarza** [comment]
I know it is the theme, I said it on my first comment. But could you please provide a bit more info on how to edit, maybe comments.php, so that it can handle the plugin correctly?

The StCR Position thing, I already tried it and no luck.

Thank you!

**Comment by BobaWebDev** [comment]
Hi @luiszarza 

In comments.php in the place where you want the comment form the PHP function `comment_form()` should be called.

Check the [official WordPress documentation](https://developer.wordpress.org/reference/functions/comment_form/)  for more information on usage and available parameters. There's an example code at the bottom.

**Comment by luiszarza** [comment]
Thank you man @BobaWebDev !!

Your comment was so helpful. Following your idea I was able to trick my theme to adapt it to modern WP standards. Now the plugin works perfectly with my theme.

**Comment by BobaWebDev** [comment]
You're welcome @luiszarza, happy to hear it worked out.
