### ISSUE TITLE
Related to advance subscribe to comment system

### ISSUE THREAD

**Issue by a2n6ig** [stcr/subscribe-to-comments-reloaded#541]
Hi,

I want to shift my advance subscribe to the comment option after the text.

See this screenshot for details: https://bit.ly/333IKhM

Note: I'm okay with editing in the plugin code. Just tell me what steps I need to do?

Thanks :)

**Comment by BobaWebDev** [comment]
Hi @a2n6ig 

Try adding this in WP admin > Appearance > Customize  Custom CSS:

`select#subscribe-reloaded {
    float: right;
}`

**Comment by a2n6ig** [comment]
It worked but went extreme right. I want it to start from where the sentence ends.

See this screenshot for more details: https://bit.ly/348nQ2k

**Comment by BobaWebDev** [comment]
Try adding this as well:

`p.comment-form-subscriptions { display: inline-block; overflow: hidden; }`

**Comment by a2n6ig** [comment]
I've sent you an email on the address that you've provided here: https://github.com/BobaWebDev

Please check it!!

**Comment by BobaWebDev** [comment]
Hi @a2n6ig 

The theme you use has a bit of CSS that makes every element in the comment form 100% wide, which is why the last code I sent didn't make a difference. Here's the full code you need:

`select#subscribe-reloaded { float: right; margin-left: 8px; }
p.comment-form-subscriptions { display: inline-block; overflow: hidden; width:auto; line-height: 36px; }`

That makes it look like:

![image](https://user-images.githubusercontent.com/4485586/69476379-7af28580-0dd9-11ea-8fa5-ebc30db67a09.png)

**Comment by a2n6ig** [comment]
Hi,

Sorry for the late reply. The above CSS that you've provided is working excellent for desktops and tablets.

Thank you very much for that :)

But on mobile devices, it's not looking good. Actually the options (blue in color) should start where the last word of the sentence "notified:" ends.

But it is starting in middle.

See this screenshot: https://prnt.sc/qap1y5

I have also sent you a mail on the address that you've provided here: https://github.com/BobaWebDev

**Comment by BobaWebDev** [comment]
You're welcome @a2n6ig :)

An update is coming today or tomorrow, will make some adjustments to the HTML structure in there to allow for that layout.

**Comment by BobaWebDev** [comment]
Hi @a2n6ig 

Not an update, it's actually something we can do in the options, sorry, I handle support/development for a lot of plugins/themes by the same owner, sometimes I forget which options are available.

Go to WP admin > StCR > Comment Form.

For the Custom HTML option set the following:

And remove the CSS code we added before.

**Comment by a2n6ig** [comment]
Hi,

It's okay. I can understand.

Thanks now my problem has been solved :)

**Comment by BobaWebDev** [comment]
You're welcome @a2n6ig
