### ISSUE TITLE
Comment Subscriptions page 404

### ISSUE THREAD

**Issue by chugginn** [stcr/subscribe-to-comments-reloaded#542]
By default the virtual management page returns a 404 error. Using the latest version of WordPress and X Theme. Tried re-saving permalinks and clearing site cache. I also attempted disabling the virtual page and creating one manually, following [your tutorial](https://github.com/stcr/subscribe-to-comments-reloaded/wiki/KB#create-a-real-management-page). The page is blank.

**Comment by BobaWebDev** [comment]
Hi @chugginn 

Can you try the following:

- Go to WP Admin > StCR > Management Page
- Set "Virtual management page" to "No" and save changes
- Go to WP admin > Pages > Add New and create a page called "Comment subscriptions", the permalink should be comment-subscriptions

**Comment by chugginn** [comment]
Hi @BobaWebDev - yes, I've already done this following your tutorial. The page has a header and footer but is otherwise blank.

**Comment by BobaWebDev** [comment]
Hi @chugginn 

Ok, that's good news, no 404.

Now just add [stcr_management_page] in the content area ( the regular WP content editor ) for that page.

**Comment by chugginn** [comment]
That did the trick, thanks!

**Comment by BobaWebDev** [comment]
You're welcome.
