### ISSUE TITLE
[question] spam prevention & ...

### ISSUE THREAD

**Issue by atomGit** [stcr/subscribe-to-comments-reloaded#547]
i understand that StCR uses (optionally) double opt-in, but ...

1. is there anything in place to prevent bots from spamming the form and potentially causing my IP to become blacklisted by submitting arbitrary email addresses?
2. when does the subscribers email address get added to the database - before or after they respond to the opt-in mail?
3. what happens if a subscribers email address is canceled, etc. - are mails still sent to a the non-existing address? is there any checks in place to prevent this?
4. is there any monetizing or phoning home being done in the code?

i'm becoming much more aware of the spam problem since i moved my stuff to a new host and i don't want to get the IP blacklisted

lastly, what's going on with development - the latest version in the changelog and this repo is 180212, however the WP version is 191217

**Comment by atomGit** [comment]
also, where is the privacy policy for StCR?

**Comment by BobaWebDev** [comment]
Hi @atomGit 

1) There isn't anything in place for that. Are you experiencing issues with bots on the STCR forms?

2) It's added to the database as an unconfirmed subscription when they submit the form. The subscription isn't activated until they click the link in the confirmation email.

3) There's no check in place for canceled emails.

4) There's no monetizing or phoning home being done. There might be monetizing in the future to help fund the development which will most likely be in a form of a PRO version with additional features. But there's no specific plans at the moment.

**Comment by atomGit** [comment]
> Are you experiencing issues with bots on the STCR forms?

not at the moment, but i wonder if simple a (non-google) question-answer challenge might be a good idea? i can open a new issue if you think you might have an interest in that

same with point 3...

> what happens if a subscribers email address is canceled, etc. - are mails still sent to a the non-existing address? is there any checks in place to prevent this?

my concern is having the mail server IP blacklisted - i don't know whether it's possible to 'test' a mail address before sending, but if that can be done, then i think it would be a good idea - maybe just check every address once a month or so, what do you think?

**Comment by BobaWebDev** [comment]
Perhaps 2 options where you supply the question and answer. So for example you can set the question to be "What is the sum of 4 and 5" and you set the answer to "9". That question would be shown in the form and the visitor needs to supply the correct answer.

The question can of course be anything you want. Would that work?

I'm not really sure how would we could do the check for cancelled/inactive emails. Some email providers send back an email to notify that the email was not successfully sent but we ( the plugin ) don't have access to receiving emails so we can't check that.

I'll look into it but at the moment I'm not sure how that would work out.

**Comment by atomGit** [comment]
> Perhaps 2 options where you supply the question and answer. ... Would that work?

that would be great - exactly what i had in mind - a question with a non-case sensitive answer

as for testing mail addresses, i don't know either if it's possible to get a universal response from mail servers as to the status of an address without the server actually sending a mail

i think a challenge-response in itself might go a long way toward preventing abuse by bots

thanks for considering this

**Comment by BobaWebDev** [comment]
Hi @atomGit 

Great, the challenge/response should be implemented in this week's update.

**Comment by BobaWebDev** [comment]
Hi @atomGit 

Just released the update. When you go to WP admin > StCR > Options at the bottom you'll see the options for the challenge question/answer.

**Comment by atomGit** [comment]
hi @BobaWebDev 
been busy with other things and i kind of lost my train of thought here

i swore there was an option to subscribe to comment notifications without leaving a comment - am i nuts?

also, when is the challenge/answer displayed? when i log out of the backend and dump my domain cookie and leave a new comment, the challenge is not presented

**Comment by BobaWebDev** [comment]
Hi @atomGit 

Yeah, the option for subscribing without leaving a comment is there by default. Go to WP admin > StCR > Comment Form.

Under the "Messages for your visitors" there's the textarea for "Default label". It should contain a link to the subscription page (without commenting):

`Notify me of followup comments via e-mail. You can also <a href="[subscribe_link]">subscribe</a> without commenting.`

That is actually the page where challenge/answer is being displayed. We didn't add a challenge on the comment form itself, it's added on the non-WordPress form where the visitor subscribes without commenting.

I thought that was the form you were referring to when we discussed the bot submissions issue. There's plenty of plugins to "fight" against bot submissions in the comment form itself.

**Comment by atomGit** [comment]
> Yeah, the option for subscribing without leaving a comment is there by default. 

why, indeed it is  ... the reason i didn't see it is because i removed it until the challenge/response thingy was implemented : )

thanks!

**Comment by BobaWebDev** [comment]
You're welcome :)
