### ISSUE TITLE
Compatibility issue

### ISSUE THREAD

**Issue by a2n6ig** [stcr/subscribe-to-comments-reloaded#552]
Can this plugin (STCR) is compatible to work with Thrive Comments Plugin?

**Comment by BobaWebDev** [comment]
Hi @a2n6ig 

No, sorry, it's just for the native WordPress comments system. 

But I think Thrive Comments plugin has a reply notification system in it.

**Comment by a2n6ig** [comment]
Thanks for the clarification!
