### ISSUE TITLE
Just installed - doesn't seem to function

### ISSUE THREAD

**Issue by NosillaCast** [stcr/subscribe-to-comments-reloaded#555]
I'm hoping this is just a problem of a new user, but here goes. I've installed the plugin (replacing Subscribe to Comments). I haven't changed any of the default html that creates what we see on my site. I have toggled a few of the switches to change who gets notified.

Hitting the subscribe without commenting gets a Page not Found error.  The instructions say that the /comment-subscriptions/ page does not have to exist but it has to be the same format (which I think it is) of my site.  The (non-functional) link goes here:

https://www.podfeet.com/blog/comment-subscriptions/?srp=20035&srk=5491535c6796109c48e413a7fc62a2f1&sra=s&srsrc=f

Also I set the option to send a confirmation email when subscribing, but no email gets sent.

I set the option for blog authors to be notified of comments, but no emails get sent for that either.

With pretty much none of this functioning, I suspect I'm the weak link and have missed some fundamental step. I hope it's me, not the plugin, because I'm easier to teach than a plugin is to fix.

My site is https://podfeet.com

**Comment by BobaWebDev** [comment]
Hi @NosillaCast 

As for the 404, can you try the following:

Can you try the following:

- Go to WP Admin > StCR > Management Page
- Set "Virtual management page" to "No" and save changes
- Go to WP admin > Pages > Add New and create a page called "Comment subscriptions", the permalink should be comment-subscriptions
- For the content of the page add [stcr_management_page]

Let me know if that works out.

As for the emails not being sent. install this plugin https://wordpress.org/plugins/wp-mail-logging/

It logs emails being sent out through WordPress. Then try to subscribe and check the email logs. Does an email for subscription confirmation show up in there and what status does it show?

**Comment by NosillaCast** [comment]
Thanks, @BobaWebDev.  The fix for the page worked. And now that it's working, I was able to verify with the plugin that the emails were definitely being sent.  I also discovered these emails go directly to spam for my users and me!  Now to change the text of the page telling people to check their spam folders.

Thanks for the quick help,  Allison

**Comment by NosillaCast** [comment]
I may have spoken too soon. Not sure this is a problem with the plugin, since the wp-mail-logging plugin says the mail has been sent, but emails to my .mac account never arrive and a friend of mine with her own domain doesn't get them either.  We both checked spam folder but no joy.

**Comment by BobaWebDev** [comment]
Hi @NosillaCast 

Sorry for the wait, high fever the past few days.

The plugin uses the WordPress mailing system. There might be a problem in that functionality.

Can you try this plugin https://wordpress.org/plugins/wp-test-email/

It allows you to send a test email. If it's not working out then it's not an issue caused by STCR. 

In which case try https://wordpress.org/plugins/wp-mail-smtp/ which replaces the mailing system.

**Comment by NosillaCast** [comment]
Oh gosh - that's awful.  Hope you're feeling better, a fever can make you feel so fuzzy.

I installed wp-test-email and sent emails to several domains.

This is very curious. Emails appear to be going out according to the WP Mail logging plugin you suggested, but are only received on certain domains.  I have a gmail address, and an address at my own domain that is managed by google, and emails sent all arrive safely.

However, emails sent to my Mac.com address simply never arrive, not even in the junk mail folder.  I've double checked on iCloud.com and the mail isn't there. I could understand these test mails not arriving, because some filters ban empty email bodies, but the STCR emails have more subjects and bodies, so should be allowed through.

I also had a friend try with a very unusual domain, and she never received the confirmation either, even though I can see the email in the logs.

I also tried the wp-mail-smtp plugin and started down that road but it appears I have to set up a mail server?  I started doing it with my GSuite credentials but I went too many steps where I didn't know why I was doing things to continue.  

So...any other non-fever induced ideas or experiments I can run?

Allison

**Comment by BobaWebDev** [comment]
Hi @NosillaCast 

Thanks, seems to be finally going away. Almost a full week.

As for the WP Mail SMTP, no need for those complicated options in there, keep it at the default PHP option:

![image](https://user-images.githubusercontent.com/4485586/73196968-d8d08000-4130-11ea-888f-1893d620b626.png)

But since some emails arrive and some don't, I think you'll need to contact the hosting provider and ask if their system is maybe blocking some of the emails from going out.

**Comment by NosillaCast** [comment]
Thanks Slobodan, finally had a chance to try it with php, but still no joy. I've started some questions with my hosting provider. Hopefully they'll have an answer for me!

Allison Sheridan
Podfeet Podcasts at https://podfeet.com <https://podfeet.com/>
Technology geek podcasts with an EVER so slight Apple bias!
Follow me at @podfeet <https://twitter.com/podfeet>

**Comment by BobaWebDev** [comment]
Hi @NosillaCast 

Try it out with plain text emails instead of HTML. Check out this guide https://subscribe-reloaded.com/send-plain-text-emails-instead-of-html-emails/

**Comment by NosillaCast** [comment]
That sounded promising but I just subscribed using my mac.com address after changing to text email and it didn't come through.  I then tried my gmail address again and that one came through.

Good idea though!

Allison

**Comment by BobaWebDev** [comment]
Hi @NosillaCast 

Just to make sure I understood one of the previous messages correctly, when you tried the test emails plugin ( https://wordpress.org/plugins/wp-test-email/ ) the issue was also present, correct? 

If it was then it's definitely not an issue specific to our plugin, something is blocking the emails and only the hosting provider can help there.

**Comment by NosillaCast** [comment]
Yeah - sending using wp-test-email shows under WP Mail Logging that the mail was sent but it never arrives at my Mac.com email address.

I don't see how Stcr could possibly be the cause but I sure appreciate all the time you've spent trying to help me diagnose the problem.  I learned some new tools if nothing else.

If I ever figure it out I'll be sure to let you know.

Allison

**Comment by BobaWebDev** [comment]
Hi @NosillaCast 

If you want you can try disabling StCR and then try the test emails, just to make sure it's not caused by StCR but it's very unlikely.

**Comment by NosillaCast** [comment]
Another good idea - and with StCR disabled, WP Mail SMTP sends email to my gmail address but not to my Mac.com address.

Time to pester DigitalOcean again.  Thank you SO much for all of your diagnostic help!

Allison Sheridan
Podfeet Podcasts at https://podfeet.com <https://podfeet.com/>
Technology geek podcasts with an EVER so slight Apple bias!
Follow me at @podfeet <https://twitter.com/podfeet>

**Comment by BobaWebDev** [comment]
Hi @NosillaCast 

You're welcome. I hope the issue gets resolved soon, keep me informed.

**Comment by NosillaCast** [comment]
STCR is working!!!  I took your advice and wrote to my hosting provider. DigitalOcean wrote a detailed response with all of the information I needed to fix it.  The problem appears to be that since I have my email (allison@podfeet.com) managed by Google Apps for Business, the header from domain didn't match.  I wasn't personally skilled enough to do what they said so I had assistance from my consultant web manager, and we got it working.  

Interestingly the test email plugin does not work to my Mac.com address but your plugin does, so I'm golden.

Thank you so much for your help and sticking with me on this.  Do you have a tip jar, or maybe a PayPal account where I can send you some money?  My podcast is supported purely by donations so I like to pass along the love to developers in a concrete way.

Allison

I've included the DigitalOcean response in case you ever need it for someone else:

While our Droplets are self-managed, I am happy to offer advice and brainstorm with you on this. There could be many reasons for this. To get a quick opinion on it, you can visit the link below and send an e-mail to the address that it generates you. This will give you a full report on how your email appears to recipient servers.

http://www.mail-tester.com <http://www.mail-tester.com/>

These are the most common reasons why emails are filtered to spam folders:

1. Inconsistent headers
2. PTR lookup failure / no DNS record matching PTR
3. SPF Failure
4. Content

Inconsistent headers could be something like you sending from your server but in the 'From' field it shows that it was sent from somewhere else, like Yahoo, Hotmail, etc. The 'From' field should show an address that your server should be sending as (typically your domain).

You should make sure that your server's hostname is a fully qualified domain name (example: server.mydomain.com <http://server.mydomain.com/>) and that the Droplet is named to match, so that the PTR record is set. Additionally, your DNS should have that hostname (example: server.mydomain.com <http://server.mydomain.com/>) pointing to your Droplet's IP address so that reverse lookups are consistent.

Your SPF record is a DNS record of the type 'TXT' which includes either a reference to a DNS record that points to your Droplet's IP address or the Droplet's IP address itself. For example, if I want to send mail as mydomain.com <http://mydomain.com/> and I want to send from my website, as well as a Droplet with the IP of 1.2.3.4, my SPF record might look like this:

'v=spf1 +a +ip4:1.2.3.4 ~all'

The '~all' tells the receiving mail server to basically do what it thinks is best if the mail does not match the '+a' (domain's primary A record) or the '+ip4:1.2.3.4' (the Droplet's IP address). You can also use '-all' instead which suggests to the recipient mail server that any e-mail not originating from these points should be discarded.

Finally, content. Your content can be read as spam whether you intend for it to be or not. Try sending e-mails without long signatures, images, brand names, or website names to rule out the content of your e-mails. However, keep in mind that past content can impact your future e-mails as well.

Now, it is important to note that the most common belief is that blacklists cause filtering to spam folders. In most cases, blacklisting will actually cause e-mail rejection, not filtering to spam folders. However, it is certainly a possibility, even if not a probability, that blacklistings can impact what folder your e-mails land in. You can look up blacklistings for your IP address here:

http://mxtoolbox.com/blacklists.aspx <http://mxtoolbox.com/blacklists.aspx>

Do note that not every blacklist is relevant. Recipient servers have to actually use them for them to matter. Many are not widely used, and therefore do not matter. If you question whether this is the case with a particular blacklist, feel free to ask us, we generally know which ones are important.

Swimmingly,
Alberto B.
Developer Support Engineer

**Comment by BobaWebDev** [comment]
Hi @NosillaCast 

Great, happy to hear it's working out and thanks for the detailed info, will definitely be of big help if someone else runs into that issue.

As for donations, thanks but we don't have anything set up but I saw you left a review, that's help enough, thank you.
