### ISSUE TITLE
404 error

### ISSUE THREAD

**Issue by lpcdf** [stcr/subscribe-to-comments-reloaded#556]
Hello,
The page where my blog comments' subscribers can manage their subscriptions does not exist. There is a 404 error page.
I also tried to create a new page i y WordPress "[domain]/comment-subscriptions" but it still does not show any subscriptions options.
Could you help?
Best regards

**Comment by BobaWebDev** [comment]
Hi @lpcdf 

Can you try the following:

- Go to WP Admin > StCR > Management Page
- Set "Virtual management page" to "No" and save changes
- Go to WP admin > Pages > Add New and create a page called "Comment subscriptions", the permalink should be comment-subscriptions
- For the content of the page add [stcr_management_page]

Let me know if that works out.

**Comment by HGassner** [comment]
Just recognized that I had the same issue since I've changed my theme long time ago.
Your suggestion works - thanx!

**Comment by BobaWebDev** [comment]
Happy to hear the solution works. Have a great weekend.

**Comment by cincpach** [comment]
Hi,
I implemented the above solution but it hasn't improved the 404 link. 

I see the parameters are getting added after / and I think that's what causing the 404. 

<img width="505" alt="Page_not_found_-_Tidbits-Marci_com" src="https://user-images.githubusercontent.com/71287260/93134278-ed0cc180-f6ae-11ea-8c0e-a9055393e7cb.png">

Thoughts?

**Comment by BobaWebDev** [comment]
Hi @cincpach 

Can you send over the URL to the site, it will help me figure out a bit more details.

**Comment by cincpach** [comment]
Hi!

Yes - https://tidbits-marci.com/instant-pot-potato-salad/ . Scroll down to
the bottom where the contact form is.

Thank you@
-- 

*SEO Services for Wellness Entrepreneurs*
*New SEO Strategy Intensive are here **⚡️**Info + discount here
<https://digitalbloomiq.com/seo-strategy-intensive>*
Digitally Overwhelmed Podcast: bit.ly/digitallyoverwhelmed
Website: http://www.digitalbloomiq.com/
<http://www.digitalbloomiq.com/>
Instagram: @digitalbloomiq


<https://www.instagram.com/digitalbloomiq>

**Comment by BobaWebDev** [comment]
Hi @cincpach 

Getting an arrow (503) in general for the comments subscriptions page (no GET parameters)

Can you send over screenshots of:

- The top options (before Messages) in WP admin > StCR > Management page
- The permalink option for the page that serves as the management page (WP admin > Pages and then click to edit that page, if using Gutenberg it's in the right sidebar area, if using classic editor it's just below the title field).

**Comment by cincpach** [comment]
Sorry for the super late reply.

[image: Management_Page_‹_Tidbits-Marci_com_—_WordPress.png]

[image: Edit_Page_‹_Tidbits-Marci_com_—_WordPress.png]

Thank you!

-- 

*SEO Services for Wellness Entrepreneurs*
*New SEO Strategy Intensive are here **⚡️**Info + discount here
<https://digitalbloomiq.com/seo-strategy-intensive>*
Digitally Overwhelmed Podcast: bit.ly/digitallyoverwhelmed
Website: http://www.digitalbloomiq.com/
<http://www.digitalbloomiq.com/>
Instagram: @digitalbloomiq


<https://www.instagram.com/digitalbloomiq>

**Comment by BobaWebDev** [comment]
Hi @cincpach 

I do not see the images, it's just displayed in plain text. 

![image](https://user-images.githubusercontent.com/4485586/93663444-64a06f00-fa68-11ea-88c8-ed8aaf842c6e.png)

**Comment by cincpach** [comment]
Sorry about that. 

Here they are again:

<img width="770" alt="Management_Page_‹_Tidbits-Marci_com_—_WordPress" src="https://user-images.githubusercontent.com/71287260/93771378-cd682280-fbf3-11ea-8331-9282bf780a50.png">

<img width="951" alt="Edit_Page_‹_Tidbits-Marci_com_—_WordPress" src="https://user-images.githubusercontent.com/71287260/93771386-cf31e600-fbf3-11ea-8201-f9c516efc173.png">

Thank you.

**Comment by BobaWebDev** [comment]
Hi @cincpach 

I just tested it out again and I'm no longer getting the issue, can you give it a try?

**Comment by cincpach** [comment]
Yes - it looks to be fixed now. Was it something we did? Thank you.

**Comment by BobaWebDev** [comment]
Great, happy to hear that.

It's the change that was mentioned originally but not sure why it didn't apply immediately, maybe it was because of a caching plugin.

What's important is that it works now. If the issue somehow comes back let me know.

**Comment by cincpach** [comment]
Great - thank you!
-- 

*SEO Services for Wellness Entrepreneurs*
*New SEO Strategy Intensive are here **⚡️**Info + discount here
<https://digitalbloomiq.com/seo-strategy-intensive>*
Digitally Overwhelmed Podcast: bit.ly/digitallyoverwhelmed
Website: http://www.digitalbloomiq.com/
<http://www.digitalbloomiq.com/>
Instagram: @digitalbloomiq


<https://www.instagram.com/digitalbloomiq>

**Comment by BobaWebDev** [comment]
You're welcome.
