### ISSUE TITLE
Bug Report: <short description>

### ISSUE THREAD

**Issue by cheerfulmonk** [stcr/subscribe-to-comments-reloaded#557]
Subscribe to Comments Reloaded no longer works and I don't know why or how to fix it.

**Comment by BobaWebDev** [comment]
Hi @cheerfulmonk 

Will need a bit more info. Any specific functionality not working or any other info you can share?

**Comment by cheerfulmonk** [comment]
It doesn't send emails to let people know when there are new comments.

**Comment by BobaWebDev** [comment]
Hi @cheerfulmonk 

Can you install WP Mail Logging plugin ( https://wordpress.org/plugins/wp-mail-logging/ ) and check to see if the emails get logged there and what their status is.

**Comment by cheerfulmonk** [comment]
You've been a big help.  My SMTP host had been changed, so I phoned
Hostmonster to get the new information.   Thank you!

**Comment by BobaWebDev** [comment]
You're welcome @cheerfulmonk
