### ISSUE TITLE
Non clickable hyperlink in Confirmation Mail

### ISSUE THREAD

**Issue by anirbanroy2002** [stcr/subscribe-to-comments-reloaded#562]
Hi, since the latest update I'm seeing this issue, that whenever a new user subscribes to the comments, the hyperlink that he/she receives in the e-mail is non clickable because it's just text. Although the HTML e-mail option is turned on. Also, is there any way to send confirmation emails only after the comment is approved, else not?

**Comment by BobaWebDev** [comment]
Hi @anirbanroy2002 

Does the email contain HTML code in plain text? Like this:

`<a href="http://example.com">http://example.com</a>`

Or does it just show:

`http://example.com`

Can you send over a screenshot of the "Double check message" field in WP admin > StCR > Notifications.

**Comment by anirbanroy2002** [comment]
Hi, i have attached the screenshot. As you can see, it's just text without
the blue hyperlink and without the html link tags.

**Comment by anirbanroy2002** [comment]
![Screenshot_2020-02-14-22-20-17-820_com google android gm](https://user-images.githubusercontent.com/61053751/74551037-78d33980-4f78-11ea-9895-83a770e08ee0.jpg)

**Comment by BobaWebDev** [comment]
In WP Admin > StCR > Notifications make sure the "Double check message" is set to:

`You have requested to be notified every time a new comment is added to:
<a href="[post_permalink]">[post_permalink]</a>

Please confirm your request by clicking on this link:
<a href="[confirm_link]">[confirm_link]</a>`

If the text editor for the field is set to "Visual" switch it to "Text" in order to see and change HTML code:

![image](https://user-images.githubusercontent.com/4485586/74556502-7e238a80-4f5e-11ea-8f94-f573fc973c99.png)

**Comment by anirbanroy2002** [comment]
![Screenshot_2020-02-15-01-42-53-616_com android chrome](https://user-images.githubusercontent.com/61053751/74564202-85fe2180-4f94-11ea-9009-7a75bcd46a5a.jpg)


Here as you can see in the screenshot, the code is exactly the same. But the problem still persists. This problem is occurring since the latest update. Before that, everything was smooth.

**Comment by anirbanroy2002** [comment]
Well, I noticed that when I forward the e-mail to my other email id hosted on gmail, the hyperlinks are presented correctly. So, i guess it has something to do with my email host and not with the plugin. Anyways, thanks for your help! I'm closing this issue.

**Comment by anirbanroy2002** [comment]
One last question... Could you please add the option so that the subscription confirmation mail goes to the user only if the comment is approved, otherwise not? Because you know, there are plenty of spammers who put fake email ids and I don't want my ip to get blacklisted by email clients for sending emails to random non existing ids.

**Comment by BobaWebDev** [comment]
Hi @anirbanroy2002 

Sure, added that to the to do list for next update.

**Comment by plerzelwupp** [comment]
See this post: https://github.com/stcr/subscribe-to-comments-reloaded/issues/594
you have to change the Apostrophs into quotation marks
