### ISSUE TITLE
Plugin not sending emails

### ISSUE THREAD

**Issue by jbi32042** [stcr/subscribe-to-comments-reloaded#569]
After installation upon testing the plugin when a user attempts to register to receive comment updates via email the system does not send the welcome/confirmation email. I see other users have complained of the same issue.

My WP installation is using WP Mail SMTP and Amazon SES. Email services is working properly with other plugins.

**Comment by BobaWebDev** [comment]
Hi @jbi32042 

Can you try installing the [WP Mail Logging](https://wordpress.org/plugins/wp-mail-logging/) plugin to see if it shows any errors for the email that STCR sends out.

**Comment by jbi32042** [comment]
I installed it and tested it and its showing an error:

"SMTP Error: data not accepted"

Any idea what that means?

**Comment by BobaWebDev** [comment]
Hi @jbi32042 

Sorry for the wait, weekend got in the way.

This is the info I was able to find:

For AWS users who work with Amazon SES in conjunction with PHPMailer, this error also appears when your "from" mail sender isn't a verified sender.

To add a verified sender:

- Log in to your Amazon AWS console: https://console.aws.amazon.com
- Select "Amazon SES" from your list of available AWS applications
- Select, under "Verified Senders", the "Email Addresses" --> "Verify a new email address"
- Navigate to that new sender's email, click the confirmation e-mail's link.

The sender email address can be set in WP admin > StCR > Notifications. **It's the second field.**

**Comment by jbi32042** [comment]
That fixed it, thank you so much for taking the time to point this out to
me.

**Comment by BobaWebDev** [comment]
You're welcome @jbi32042
