### ISSUE TITLE
Unsolicted emails: "Manage your subscriptions on {website name}"

### ISSUE THREAD

**Issue by foliovision** [stcr/subscribe-to-comments-reloaded#57]
Hello Reedyseth,

the "Manage your subscriptions:" link in the comment notifications is broken very often. It often won't show the Management page, but sends a "Manage your subscriptions on {website name}" email to the user, saying that the key is not valid. This happens is the &srk= key in the link URL is too old - the problem is that the link is only valid for a single day - see the generate_key() function. 

1) I don't think it needs to be dependent on the date at all, since there is salt from wp-config. I wouldn't worry about people hacking around the site trying to unsubscribing somebody.

2) I also suspect that some email anti-spam software or a bot can open the link as well and then another email is sent as well. I've see "Mediapartners-Google" user agent accessing that page. So I think that page should not automatically send another email, as that's very annoying. There could be a button to request another email instead. 

Thanks!
Martin

**Comment by Reedyseth** [comment]
@foliovision I just upload a new version with a unique key encrypted to avoid this.

Check latest Merge f06e9cdad0a1123ec96afb87c58a675641f3bc7d
