### ISSUE TITLE
StCR check box above text

### ISSUE THREAD

**Issue by kettiwil** [stcr/subscribe-to-comments-reloaded#570]
Hi, 
I'm writing because I just installed ScCR on my website (tiltedmap.com – which is currently in coming soon mode). The text next to the check box is showing up not next to the box, but below it. (As in the attached screenshot.)

I have used the plugin on my other site (kettiwilhelm.com) and it does not have this problem. 

Do you have idea what may be causing this and how to fix it? 

Thanks,
Ketti
![Screen Shot 2020-03-25 at 10 13 15 AM](https://user-images.githubusercontent.com/62659169/77553087-58a16f00-6e82-11ea-8c42-fb381fc4bfab.png)

**Comment by BobaWebDev** [comment]
Hi Ketti,

The theme has some CSS code that makes them go into separate lines. I need to see the website to check which CSS code applies so I can write CSS code that reverts it.

But I'm guessing it's **display: block;** on the checkbox, which is a bit weird. If that is the case then this would fix it (goes in WP admin > Appearance > Customize > Additional CSS ):

`input#subscribe-reloaded { display: inline-block !important; }`

**Comment by kettiwil** [comment]
Hi, 
Thanks for the suggestion. I tried it and unfortunately it didn't work. I also played around with other similar options (not that I'm an expert) and nothing made visible change. 

Any other suggestions? What do you mean by you would need to see the website? Let me know what next step you suggest. 

Thanks,
Ketti

**Comment by BobaWebDev** [comment]
Hi @kettiwil 

> What do you mean by you would need to see the website?

It's in coming soon mode so I can't see the actual website. Without the coming soon mode I could inspect the element in developer tools and see the exact CSS rules that make those go into two lines and then be able to write CSS code to fix it.

**Comment by kettiwil** [comment]
Hi, 

Okay, great. If you're able to look at it today, could you please just tell me at what time so that I can take down the coming soon page for just a very brief time? 

Otherwise, if that's not possible, I'll just reach out to you again when the site is live (since it's not a crucial problem). 

Please let me know. 

Thanks,
Ketti

**Comment by BobaWebDev** [comment]
Hi @kettiwil 

How about now?

**Comment by BobaWebDev** [comment]
@kettiwil 

Or let me know at what time (GMT/UTC timezone) you can do it and I'll make sure to be available.

**Comment by kettiwil** [comment]
Hi, I'm doing it right now – ready in two minutes! Let me know if you're still available.

**Comment by BobaWebDev** [comment]
@kettiwil 

I'm here.

**Comment by kettiwil** [comment]
Okay, it's live.

**Comment by BobaWebDev** [comment]
@kettiwil 

You can go ahead and activate the coming soon page, I loaded the page.

**Comment by kettiwil** [comment]
Okay, it's only on a post page, not the homepage – I assume you have a post up?

**Comment by BobaWebDev** [comment]
@kettiwil 

They're separate paragraphs which shouldn't be the case.

![image](https://user-images.githubusercontent.com/4485586/77765368-774c6500-703e-11ea-8bd9-95df3495548d.png)

What do you have in **WP Admin > StCR > Comment Form** for the "Custom HTML" textarea at the top?

![image](https://user-images.githubusercontent.com/4485586/77765540-ae227b00-703e-11ea-83ed-46cda9de3011.png)

**Comment by kettiwil** [comment]
I have this: 

<p class='comment-form-subscriptions'><label for='subscribe-reloaded'>[checkbox_field] [checkbox_label]</label></p>

(Which I never edited. It's just there.)

**Comment by kettiwil** [comment]
Oh, let me screenshot it so it shows up as HTML.

**Comment by kettiwil** [comment]
![Screen Shot 2020-03-27 at 9 26 49 AM](https://user-images.githubusercontent.com/62659169/77766093-30924700-700d-11ea-861e-611fec39a9c7.png)

**Comment by BobaWebDev** [comment]
Below that option is "Default Label". In the top right switch it to "Text" so all the HTML shows up, the paragraph and the inline styles should show up.

I think you copy pasted from Microsoft Word so it passed on some elements and styles from it.

**Comment by BobaWebDev** [comment]
So just delete the content in there, switch it back to Visual ( or keep it at Text ) and write the text manually. 

When copy/pasting from somewhere else into a WordPress editor it's best to switch it to "Text" so only the text itself is pasted.

**Comment by kettiwil** [comment]
No, I didn't use Microsoft Word at all, so I don't know what happened. Here's the Default Label HTML. 
![Screen Shot 2020-03-27 at 9 33 13 AM](https://user-images.githubusercontent.com/62659169/77766788-1efd6f00-700e-11ea-938a-4f2cac3d6533.png)

**Comment by BobaWebDev** [comment]
Usually happens when copy/pasting from Microsoft Word, but copy/pasting in general includes more than just the text, so best to paste while in the "Text" mode. 

Visual mode tries to preserve the styling of the content you copied so it adds additional elements and styling.

**Comment by kettiwil** [comment]
Okay, that's very good to know, thank you. 

And that worked! It's all on the same line now! Thank you very much! 

I have one more question now, which I noticed when I took it off of Coming Soon mode and opened the page in a browser where I'm not logged into the site. There was another check box, above the "Let me know when there's a response" check box, that says "Save my name, email, and website in this browser for the next time I comment." I'd like to not give that option.
Do you know if this is something that could be caused by StCR, or by something else?

**Comment by kettiwil** [comment]
As you can see here: 

![Screen Shot 2020-03-27 at 9 22 16 AM](https://user-images.githubusercontent.com/62659169/77767697-7223f180-700f-11ea-8627-fa63c771b81e.png)

**Comment by BobaWebDev** [comment]
That one is coming from WordPress, part of the GDPR changes they made. 

Simplest way is to hide it:

`.comment-form-cookies-consent { display: none }`

**Comment by kettiwil** [comment]
Got it, that worked. Thank you very much for all your help!

**Comment by BobaWebDev** [comment]
You're welcome @kettiwil
