### ISSUE TITLE
Notifications not being sent

### ISSUE THREAD

**Issue by jfmoore** [stcr/subscribe-to-comments-reloaded#573]
Hi, on our site madinamerica.com we are suddenly finding that comment notifications are not being received. I have verified this myself so it is not a spam or junk message issue. We haven't changed anything in our setup. We are using version 200205 of the plugin. Thanks in advance for any advice or help resolving this issue.

**Comment by BobaWebDev** [comment]
Hi @jfmoore 

There wasn't any changes to the mailing system recently. It's the native WordPress wp_mail functionality.

Can you install [WP Mail Logging](https://wordpress.org/plugins/wp-mail-logging/) plugin and make a comment on a post you are subscribed to. Then go to the mail log and check the status of the email.

If it doesn't show up in there then there's some bug in the plugin and we'll figure out how to proceed.

If it shows up but there's an error let me know which error it shows.

If it shows up and says it's successfully sent then it's most likely being blocked by the hosting provider for some reason in which case you need to contact the hosting provider's support about it.

**Comment by jfmoore** [comment]
Hi Slobodan, thank you for taking the time to reply. I installed the WP Mail logging plugin, subscribed and commented, but there are no emails recorded as sent and I received nothing my end. Very strange, grateful for any advice. Thanks.

**Comment by BobaWebDev** [comment]
Hi @jfmoore 

Weird. The subscription is active, correct? When you go to WP admin > StCR and check that specific subscription in the list of subscriptions the "Status" does not show as "Unconfirmed", correct?

**Comment by jfmoore** [comment]
Thank you, after investigating this seemed to be an issue with a small number of specific users. Thank you for your help.

**Comment by BobaWebDev** [comment]
You're welcome @jfmoore
