### ISSUE TITLE
Related to virtual management page

### ISSUE THREAD

**Issue by a2n6ig** [stcr/subscribe-to-comments-reloaded#577]
Where I can found the code for heading (H1) of the virtual management page, this: [https://tinyurl.com/yb2etqet](https://tinyurl.com/yb2etqet)? 

If it is in the plugin editor, here: [https://prnt.sc/s3qrs1](https://prnt.sc/s3qrs1), can you please tell me the file name and if possible the line no?

**Comment by BobaWebDev** [comment]
Hi @a2n6ig 

That's the theme's page title element. The StCR part starts from "In order to..."

Exact position to edit that in the theme files varies from theme to theme, but it all starts from page.php since that's the file that gets loaded on regular pages.

**Comment by a2n6ig** [comment]
Thanks :)

**Comment by BobaWebDev** [comment]
You're welcome :)
