### ISSUE TITLE
Confirmation mail links and "subscribe without comment" redirect to a inexistent page

### ISSUE THREAD

**Issue by Newsenergia** [stcr/subscribe-to-comments-reloaded#580]
Hi
I activate double confirmation for post comment subscription.
The link in the confirmation mail redirect to an inexistent page.
Also the link "subscribe without comment" redirect to an inexistent page

**Comment by BobaWebDev** [comment]
Hi @Newsenergia 

Can you try the following:

- Go to WP Admin > StCR > Management Page
- Set "Virtual management page" to "No" and save changes
- Go to WP admin > Pages > Add New and create a page called "Comment subscriptions", the permalink should be comment-subscriptions
- As the content of that page just add [stcr_management_page]

Then try the links again.

**Comment by Newsenergia** [comment]
Hi
It seems all working good now.
Thanks

**Comment by BobaWebDev** [comment]
You're welcome :)
