### ISSUE TITLE
404 error on clicking manage subscriptions link

### ISSUE THREAD

**Issue by jfmoore** [stcr/subscribe-to-comments-reloaded#582]
HI there. I hope you can help. On our site www.madinamerica.com we have recently updated the plugin to version 200422. Now if we click the 'subscribe' or 'manage subscriptions' link we get a 404 page does not exist error. Any advice you can give would be great, thank you.

**Comment by BobaWebDev** [comment]
Hi @jfmoore 

Can you try the following:

<ol>
<li>Go to WP Admin > StCR > Management Page</li>
<li>Set "Virtual management page" to "No" and save changes</li>
<li>Go to WP admin > Pages > Add New and create a page called "Comment subscriptions", the permalink should be comment-subscriptions</li>
<li>As the content of that page just add [stcr_management_page]</li>
</ol>

**Comment by jfmoore** [comment]
Hi there, thanks so much, that seems to have fixed the issue. Thanks for coming back so quickly.

**Comment by BobaWebDev** [comment]
You're welcome @jfmoore
