### ISSUE TITLE
No link in the notification email

### ISSUE THREAD

**Issue by DanieleLudus** [stcr/subscribe-to-comments-reloaded#583]
Hello, my readers wrote me that they didn't receive a link to manage their subscription. And, if they click to manage their subscription below comments, they receive a 404 error page.
Any suggestion?
Hope you can help me to solve the problem.

**Comment by BobaWebDev** [comment]
Hi @DanieleLudus 

Can you try the following:

1. Go to WP Admin > StCR > Management Page
2. Set "Virtual management page" to "No" and save changes
3. Go to WP admin > Pages > Add New and create a page called "Comment subscriptions", the permalink should be comment-subscriptions
4. As the content of that page just add [stcr_management_page]

**Comment by DanieleLudus** [comment]
Hello, thanks for the reply. Just done, but it doesn't work. Readers didn't receive notifications.

**Comment by BobaWebDev** [comment]
Hi @DanieleLudus 

That's for the 404 error you mentioned, check to see if that one is resolved.

As for the emails not arriving, can you install the plugin [WP Mail Logging](https://wordpress.org/plugins/wp-mail-logging/)

It logs all outgoing emails made via WP.

If an email fails to send it will show in the logs that there was an error and what it was. In which case we can figure out what's causing the issue.

If it shows as successfully sent and the readers aren't receiving the emails then it gets flagged for some reason by your hosting provider (if the email service goes through them).

Some hosting control panels have a page dedicated to that where you can see if an email got flagged and for what reason exactly.

If yours doesn't have it or you're not sure where to find it, the only approach is to contact the hosting provider and ask them to check if and why emails got flagged and were blocked.

**Comment by DanieleLudus** [comment]
Hello,

here attached the screen shot of what happened when someone subscribe my
comments:

It will appear [manager_link] and no link...

Best regards,
Daniele

Il giorno dom 3 mag 2020 alle ore 10:41 Slobodan Kustrimovic <
notifications@github.com> ha scritto:

**Comment by BobaWebDev** [comment]
Hi @DanieleLudus 

Can you send over the URL to the website, I'll try subscribing so I can see the email and the issue, should help me understand what's happening.

**Comment by DanieleLudus** [comment]
Hi, this is the url: https://pennablu.it/nuovi-autori-e-pubblicazione/  But
it happens with all of posts.


Il giorno lun 8 giu 2020 alle ore 21:31 Slobodan Kustrimovic <
notifications@github.com> ha scritto:

**Comment by BobaWebDev** [comment]
Hi @DanieleLudus 

I see the issue, can you send over a screenshot of the "Double check message" option located in WP admin > StCR > Notifications.

Switch the option to "Text" (top right) so it shows the full HTML code.

![image](https://user-images.githubusercontent.com/4485586/84124797-fd702900-aa3b-11ea-91ab-8d0bb7260342.png)

Here's an example of that:

![image](https://user-images.githubusercontent.com/4485586/84124864-0e209f00-aa3c-11ea-83b9-865b03c1ac37.png)

**Comment by DanieleLudus** [comment]
Hello, thanks for your help.

My situation is different, as per attached screenshot.

I can add the <a href..., and let you know if it will work.

Il giorno mar 9 giu 2020 alle ore 10:29 Slobodan Kustrimovic <
notifications@github.com> ha scritto:

**Comment by BobaWebDev** [comment]
Hi @DanieleLudus 

I don't see a screenshot attached in the reply, but make sure that you have that a href part, it's the link:

`<a href='[confirm_link]'>[confirm_link]</a>`

**Comment by DanieleLudus** [comment]
Hello,

I changed as you showed me in your screenshot. Here attached my previous
situation.
[image: stcr.png]

Il giorno mer 10 giu 2020 alle ore 10:35 Slobodan Kustrimovic <
notifications@github.com> ha scritto:

**Comment by BobaWebDev** [comment]
Hi @DanieleLudus 

Is that with it switched to "Text"?

If it's set as "Visual" it will show as you described since it does not show the HTML code behind it.

When it's "Text" it shows the HTML as well.

![image](https://user-images.githubusercontent.com/4485586/84361363-d8122500-abcb-11ea-9e95-f6c252a041b0.png)

**Comment by DanieleLudus** [comment]
Hi, I have this situation on text.


Il giorno gio 11 giu 2020 alle ore 10:11 Slobodan Kustrimovic <
notifications@github.com> ha scritto:

**Comment by DanieleLudus** [comment]
Hi, me again...

I modified as you suggested, I received a link in the confirmation email,
but it point to a 404 error page...

Il giorno gio 11 giu 2020 alle ore 10:19 Daniele Imperi <
daniele.imperi@gmail.com> ha scritto:

**Comment by BobaWebDev** [comment]
Hi @DanieleLudus 

Try the solution from #582

**Comment by DanieleLudus** [comment]
I just have a page called "Comment subscriptions".

Il giorno ven 12 giu 2020 alle ore 10:17 Slobodan Kustrimovic <
notifications@github.com> ha scritto:

**Comment by BobaWebDev** [comment]
Hi @DanieleLudus 

Just tried subscribing on your site and I received the confirmation email but it's still without the link. The URL is there but not linked.

![image](https://user-images.githubusercontent.com/4485586/84693591-06835d80-af48-11ea-8b4f-6d8c15fb0f86.png)

But when I copy/pasted the URL it took me the confirmation page, no 404.

Add the following code in there where the link should be:

`<a href='[confirm_link]'>[confirm_link]</a>`

But make sure to switch to the "Text" tab first so it allows you to add HTML code.

![image](https://user-images.githubusercontent.com/4485586/84693792-5530f780-af48-11ea-9893-cb132e99549d.png)

**Comment by DanieleLudus** [comment]
Hello, thanks for trying to solve the problem. I just have this situation,
as per attached screenshot:

[image: stcr.png]

Il giorno lun 15 giu 2020 alle ore 20:39 Slobodan Kustrimovic <
notifications@github.com> ha scritto:

**Comment by BobaWebDev** [comment]
Hi @DanieleLudus 

For some reason I'm unable to see the images you upload.

Can you upload to imgur.com and send over the link to it?

**Comment by DanieleLudus** [comment]
Hi, here the link: https://imgur.com/dGucLnl

Il giorno mar 16 giu 2020 alle ore 18:45 Slobodan Kustrimovic <
notifications@github.com> ha scritto:

**Comment by BobaWebDev** [comment]
Hi @DanieleLudus 

Looking a bit deeper into the email I received I see the quotes around the href parameter get turned into the encoded version which breaks the HTML.

![image](https://user-images.githubusercontent.com/4485586/84937952-d6b98e80-b0dc-11ea-945b-8ea2bc93ce1a.png)

Haven't encountered that issue before.

Can you try switching from single to double quote in that option, basically just copy/paste the following:

`Hai richiesto di ricevere notifiche a nuovi commenti pubblicati a:
<a href="[post_permalink]">[post_title]</a>

Conferma la tua iscrizione cliccando sul link:
<a href="[confirm_link]">[confirm_link]</a>`

**Comment by DanieleLudus** [comment]
Hi, thanks again for your help. Just switched to double quote.


Il giorno mer 17 giu 2020 alle ore 20:57 Slobodan Kustrimovic <
notifications@github.com> ha scritto:

**Comment by BobaWebDev** [comment]
You're welcome.

I just tested it an the links work correctly now.

**Comment by DanieleLudus** [comment]
So good news! Thanks a lot again for your kind help.
Daniele


Il giorno gio 18 giu 2020 alle ore 20:18 Slobodan Kustrimovic <
notifications@github.com> ha scritto:

**Comment by BobaWebDev** [comment]
You're welcome Daniele.
