### ISSUE TITLE
Bug Report: abo without comment

### ISSUE THREAD

**Issue by Elbgeist** [stcr/subscribe-to-comments-reloaded#589]
Hi!

If you click on Subscription without commenting, the link is incorrectly formatted. 
It is: http//https://. 
Page not reachable then, logically.
You can see mine here on blog: https://www.nicht-spurlos.de/. Unfortunately I can not find where is double http. I ask for support. Thank you very much.

Regards,

Thomas

**Comment by BobaWebDev** [comment]
Hi @Elbgeist 

In WP admin > StCR > Comment Form, you'll see the section called "Messages for your visitors" and the first option in there "Default label".

Can you make a screenshot of that option value.

Make sure to switch to the "Text" tab (top right of the option area) so it shows the HTML code. 

![image](https://user-images.githubusercontent.com/4485586/82141421-ff2c3f80-9835-11ea-9a6b-6907c5d81c0b.png)

**Comment by Elbgeist** [comment]
Hi @BobaWebDev 

That was the crucial tip. I have now found the bug. Thank you for your help! Greetings and have a nice day.

Thomas
