### ISSUE TITLE
Plugin is full of broken links?

### ISSUE THREAD

**Issue by cheapskatecook** [stcr/subscribe-to-comments-reloaded#591]
Hi, 
For some reason, all of the manage subscription links on the comment form of this plugin on my site are broken. It looks like there is no Manage Subscriptions page? The Comment Form messages for visitors has tags like [subscribe_link] and [manager_link], but they don't go anywhere, just a 404. 
I like this plugin, but how do I fix this ASAP? Now I have broken links on every blog post. Thanks!

**Comment by BobaWebDev** [comment]
Hi @cheapskatecook 

What's the full URL those links take you to?

Can you send over the URL to the website?

**Comment by cheapskatecook** [comment]
Hi, here is the full URL: https://www.cheapskatecook.com/comment-subscriptions/?srp=3119&srk=ae18d4a565092b992fbd3f55650eb9b7&sra=s&srsrc=

And here is my site: https://www.cheapskatecook.com/

Thanks!

**Comment by BobaWebDev** [comment]
Hi @cheapskatecook 

Try the solution mentione at #582

**Comment by cheapskatecook** [comment]
Looks like that fixed it. Thanks so much for your quick reply!

**Comment by BobaWebDev** [comment]
You're welcome. Happy to hear it's sorted out.
