### ISSUE TITLE
E-mails are not reaching for my subscribers. 

### ISSUE THREAD

**Issue by Aircoolerguide** [stcr/subscribe-to-comments-reloaded#592]
I installed the plugin "subscribe to comments reloaded" so that my comment subscribers can easily get notified when there is a reply to their comment on my page. But when I reply to their comment the & the reply which I do is not reaching to their mail. So, what can I do? give me a suggestion. Waiting for your response.

**Comment by BobaWebDev** [comment]
Hi @Aircoolerguide 

Can you install [WP Mail Logging](https://wordpress.org/plugins/wp-mail-logging/) plugin and make a comment on a post you are subscribed to. Then go to the mail log and check the status of the email.

If it doesn't show up in there then there's some bug in the plugin and we'll figure out how to proceed.

If it shows up but there's an error let me know which error it shows.

If it shows up and says it's successfully sent then it's most likely being blocked by the hosting provider for some reason in which case you need to contact the hosting provider's support about it.

**Comment by Aircoolerguide** [comment]
I tested again and now everything is working fine,. But I don't know why the emails weren't going that day. Anyway, thanks for the support.

**Comment by BobaWebDev** [comment]
Hi @Aircoolerguide 

You're welcome. Happy to hear it's sorted out.
