### ISSUE TITLE
"No subscriptions match your search criteria." when clicking "You can manage the subscriptions of this post."

### ISSUE THREAD

**Issue by JesseVanDis** [stcr/subscribe-to-comments-reloaded#595]
Hi, I seem not get a user subscribed to a post.

When opening a post, there is a link called "You can manage the subscriptions of this post." at the comment area. There are no buttons or other elements from the plugin there, so my intuition is that i have to click there to subscribe to the comments in that post.

However when I click there, I get send to a page telling me that there are "No subscriptions match your search criteria.". 

This only happens when the user successfully subscribes to any post at the start. Afterwards the subscription layout changes, as his data is now stored, and he cannot subscribe to any other post anymore due to the mentioned reason

Is anybody familiar with this? 

Cheers: Jesse

**Comment by JesseVanDis** [comment]
It turned out to be a layout issue on my side. Button still behaves the same but 
"There are no buttons or other elements from the plugin there"
is false. 

Sorry for not having looked into it more

**Comment by BobaWebDev** [comment]
Happy to hear it's sorted out.
