### ISSUE TITLE
Subscribe without commenting not working

### ISSUE THREAD

**Issue by trishamodi** [stcr/subscribe-to-comments-reloaded#603]
When a user presses subscribe without commenting, the page loads after a lot of time with the error message 'This page isn’t working. xxxx wesbite is currently unable to handle this request. HTTP ERROR 500. Please help resolve.
<img width="1440" alt="Screenshot 2020-08-07 at 6 31 09 PM" src="https://user-images.githubusercontent.com/69352982/89649003-b5f00700-d8dd-11ea-99f5-001718b6ef8e.png">

**Comment by BobaWebDev** [comment]
Hi @trishamodi 

Seems it happens for that URL in general (without parameters) https://trywanderingmore.com/comment-subscriptions/

Might be an issue with the virtual page approach.

Can you try the following:

1. Go to WP Admin > StCR > Management Page
2. Set "Virtual management page" to "No" and save changes
3. Go to WP admin > Pages > Add New and create a page called "Comment subscriptions", the permalink should be comment-subscriptions
4. As the content of that page just add [stcr_management_page]

**Comment by trishamodi** [comment]
This worked! Thanks a ton!

**Comment by BobaWebDev** [comment]
You're welcome @trishamodi
