### ISSUE TITLE
Subscriber can see all subscribers

### ISSUE THREAD

**Issue by hwdean** [stcr/subscribe-to-comments-reloaded#607]
When user clicks on verification link in email, all subscribers are in subscription management list

Here is and example of result from one subscriber (brooke is the recipient of email confirm)

![image](https://user-images.githubusercontent.com/69878454/90576884-37fced00-e174-11ea-9453-d48bcb47d664.png)

**Comment by hwdean** [comment]
I was thinking -- I clicked on brooke's link and I am admin. Going back to check again (unable to delete comments)

**Comment by BobaWebDev** [comment]
Hi @hwdean 

Administrators see all the subscriptions. Brooke will only see her subscription in there.
