### ISSUE TITLE
Error on [confirm_link]

### ISSUE THREAD

**Issue by EmilLamprecht** [stcr/subscribe-to-comments-reloaded#610]
Hello, I have two questions.

1. We are getting an error on every use of [confirm_link]. The URL is broken and leads users to a dead page. I cannot figure out what the anomaly is as all other links seem to work without issue. At this point I'm not even sure where to look.

2. I would like to confirm where the data is stored. Does any of our user data leave our wordpress database via StCR? I presume not, but want to be sure we're securing our user data correctly and privacy policy reflective of truth.

Thanks,
Emil

**Comment by EmilLamprecht** [comment]
Ah, I'm just seeing now that any attempt to link a [short_code] automatically ads http:// in front of the short code, which is then doubled up in propogation. I'm not sure if this means we're using short codes and link properties incorrectly or if something else is wrong.

**Comment by EmilLamprecht** [comment]
Here is the message in question. All links in this are working apart from the confirm_link 

Hey there,

You have requested to be notified every time a new reply is added to your comment on:
<a href="[post_permalink]" target="_blank" rel="noopener">[post_title]</a>

<strong>Please confirm your request by clicking on this link:</strong>
<a href="[confirm_link]" target="_blank" rel="noopener">Click Here To Confirm</a>

All our comments are personally reviewed before they are published, to ensure they meet our <a href="https://liveutifree.com/community-guidelines/">community guidelines</a>.

Thanks,

Melissa
Live UTI Free

**Comment by BobaWebDev** [comment]
Hi @EmilLamprecht 

That's odd.

What is the value of the input field for "Management URL" option in WP admin > StCR > Management Page?

![image](https://user-images.githubusercontent.com/4485586/91655172-19b9ba00-eaaf-11ea-8b07-dab12abf9b77.png)

**Comment by EmilLamprecht** [comment]
Sorry slow response, didn't get a notification for some reason. Here is a screen shot:

![image](https://user-images.githubusercontent.com/6704486/92471581-7700ea00-f1d8-11ea-857a-20bef0e2ebf1.png)

**Comment by EmilLamprecht** [comment]
Our hosting platform says everytime a call to this page is done it maxes out the memory, thus the issue. It seems like your plugin tries to lookup the entire subscription database and so now that we've hit a critical mass of subscriptions it basically just shorts out every time makes a call to this page.

**Comment by EmilLamprecht** [comment]
Is this an issue in the plugin design, or something in our implementation?

**Comment by BobaWebDev** [comment]
Hi @EmilLamprecht 

Did they say if it maxes out the PHP memory limit or if the database query takes longer than allowed?

How many subscribers do you have?

**Comment by EmilLamprecht** [comment]
PHP Memory limit maxing out:
2020/09/01 09:41:10 [error] 46557#46557: *807729 FastCGI sent in stderr: "PHP message: PHP Fatal error: Allowed memory size of 536870912 bytes exhausted (tried to allocate 20480 bytes) in /www/liveutifreecom_349/public/wp-includes/wp-db.php on line 1989" while reading response header from upstream, client: 2.152.80.69, server: liveutifree.com, request: "GET /comment-subscriptions/ HTTP/1.0", upstream: "fastcgi://unix:/var/run/php7.3-fpm-liveutifreecom.sock:", host: "liveutifree.com"
 

2020/09/01 09:40:51 [error] 46557#46557: *807710 FastCGI sent in

**Comment by EmilLamprecht** [comment]
we only have about 580 subscribers actually so far

**Comment by BobaWebDev** [comment]
Hi Emil,

That amount won't cause an issue.

Can you try the following: 

- Go to WP Admin > StCR > Management Page
- Set "Virtual management page" to "No" and save changes
- Go to WP admin > Pages > Add New and create a page called "Comment subscriptions", the permalink should be comment-subscriptions (if you did not change it in the options)
- For the content of the page add [stcr_management_page]

**Comment by BobaWebDev** [comment]
You're welcome.
