### ISSUE TITLE
Bug Report: <checkbox does not appear>

### ISSUE THREAD

**Issue by clauditorium** [stcr/subscribe-to-comments-reloaded#615]
I reported this problem years ago. It was never resolved, so I gave up. Recently I downloaded the most current version of stcr, hoping the problem had been fixed, but it hasn't. Or is it just that the theme I use doesn't work with stcr?

Here is a page from my site that shows the absence of the checkbox: http://twinpeaksreviews.com/books/

**Comment by BobaWebDev** [comment]
Hi @clauditorium 

Your theme has a piece of CSS code that hides labels in the comment form:

![image](https://user-images.githubusercontent.com/4485586/95742441-51ac4380-0c90-11eb-9d67-6029a7012e30.png)

Add the following in WP admin > Appearance > Customize > Additional CSS:

`.comment-form-subscriptions label {
    display: block;
}`

**Comment by clauditorium** [comment]
> Hi @clauditorium
> 
> Your theme has a piece of CSS code that hides labels in the comment form:
> 
> ![image](https://user-images.githubusercontent.com/4485586/95742441-51ac4380-0c90-11eb-9d67-6029a7012e30.png)
> 
> Add the following in WP admin > Appearance > Customize > Additional CSS:
> 
> `.comment-form-subscriptions label { display: block; }`

Thank you for replying! I was able to find the first three items of that path, but once I click Customize, I don't see the "Additional CSS" option. There is a tab named "Theme Options", and if I click on it, there is "Custom CSS Options". If I click on that, I find "Enter Custom CSS". Is that the same as "Additional CSS"?

**Comment by BobaWebDev** [comment]
You're welcome.
