### ISSUE TITLE
stcr add new subscription on manage subscription page doesnt work.   https://hoa-review.com/wp-admin/admin.php?page=stcr_manage_subscriptions

### ISSUE THREAD

**Issue by PatrickJohansen** [stcr/subscribe-to-comments-reloaded#616]
stcr add new subscription on manage subscription page doesnt work. https://hoa-review.com/wp-admin/admin.php?page=stcr_manage_subscriptions 5 minutes ago

**Comment by PatrickJohansen** [comment]
strc   stcr add new subscription on manage subscription page doesnt work. https://hoa-review.com/wp-admin/admin.php?page=stcr_manage_subscriptions 5 minutes ago

**Comment by BobaWebDev** [comment]
Hi,

That's the WordPress admin so I can't see the page (don't share any user/pass here, this is public). 

What are you seeing on that page, does it shown an error? Can you include a screenshot of how it looks like?

**Comment by PatrickJohansen** [comment]
![stcr new subcription pic](https://user-images.githubusercontent.com/71244636/96017509-f0ef4900-0dfe-11eb-97c4-d3f5a71d74a8.PNG)

No error, just when I hit the ADD button, nothing happens.  It doesnt add the email to the list

**Comment by PatrickJohansen** [comment]
I also just found that when I hit the "You can also subscribe without commenting."   Another tab opens but says page not found.

**Comment by BobaWebDev** [comment]
Hi @PatrickJohansen 

In the screenshot for the Post ID it says "Surfside Open Blog (726)".

The value for that field should only be the numeric post ID, that ID for that post is 726

As for "you can also subscribe..." going to a 404 page, give this a try:

- Go to WP Admin > StCR > Management Page
- Set "Virtual management page" to "No" and save changes
- Go to WP admin > Pages > Add New and create a page called "Comment subscriptions", the permalink should be comment-subscriptions
- For the content of the page add [stcr_management_page]
- Publish the page and check if it's still a 404

**Comment by PatrickJohansen** [comment]
Your instructions solved both problems.  Thanks so much!

**Comment by BobaWebDev** [comment]
You're welcome.
