### ISSUE TITLE
Bug Report: Confirm Link does not work

### ISSUE THREAD

**Issue by pforrmi** [stcr/subscribe-to-comments-reloaded#627]
Hi at all,

I like the plugin very much but since a short time the confirm link for a subscription don't work any more.
For the mail template I use the confirm link like this: <a href="[confirm_link]">[confirm_link]</a>

Also if I use it regular like [confirm_link] the result is at any time: Error 404. Not found.

Any issues known?! How can I fix that.

**Comment by BobaWebDev** [comment]
Hi @pforrmi 

The confirm link or that "comment-subscriptions" page in general?

Try the following:

- Go to WP Admin > StCR > Management Page
- Set "Virtual management page" to "No" and save changes
- Go to WP admin > Pages > Add New and create a page called "Comment subscriptions", the permalink should be "comment-subscriptions" (unless you changed that in WP admin > StCR > Management Page).
- As the content of that page just add [stcr_management_page]

**Comment by pforrmi** [comment]
No just the confirm link that you get by email don't works.

I will try your solution and give feedback asap.

**Comment by pforrmi** [comment]
That was the solution. Maybe I deleted the page by mistake.
Thanks for the quick help!

**Comment by BobaWebDev** [comment]
Happy to hear it's sorted out.
