### ISSUE TITLE
Any link with extension "/content-subscription/" leads to 404 page

### ISSUE THREAD

**Issue by grclub** [stcr/subscribe-to-comments-reloaded#630]
[ UPDATE: SEE COMMENT]

Whether it's at the front end of the site or from a user's WP Generated Email (e.g. "Manage your subscriptions" or "One click unsubscribe") leads to a 404 Page. 

I'd like for users to have these options. 

Is there a setting I need to set?

Thanks!
--Dave

NOTES: First time using the plug-in. 
![image](https://user-images.githubusercontent.com/68024928/105108677-02886280-5a78-11eb-8c8a-b5f44bee7050.png)

**Comment by grclub** [comment]
[UPDATE: when I disable all other plugins, this is NOT a problem/the links function. I'm now working on identifying which plug-in(s) is affecting it. ]

**Comment by grclub** [comment]
Resolved (Sort of): 

the LearnDash LMS plugin is causing this plugin to fail regarding these links. 

I do not have a resolution of how to make it work and keep LearnDash (and LearnDash has to stay).

**Comment by BobaWebDev** [comment]
Hi @grclub 

Can you try the following:

- Go to WP Admin > StCR > Management Page
- Set "Virtual management page" to "No" and save changes
- Go to WP admin > Pages > Add New and create a page called "Comment subscriptions", the permalink should be comment-subscriptions
- For the content of the page add [stcr_management_page]

**Comment by grclub** [comment]
Thank you for your thoughtful response. 

Right now I'm looking at a service that can provide a daily digest, so the plugin is inactive. I'll look at your solution should I move back to this plugin. From my experience with my site, it LOOKS like that would work quite well. Thanks, again. 
--Dave
