### ISSUE TITLE
Manage subscription goes to 404 page

### ISSUE THREAD

**Issue by Fjuraa** [stcr/subscribe-to-comments-reloaded#633]
Hello,

may I ask, I have the plugin set to have the manag esubsciption page go to virtual page, but it doesnt work, it instead goes to a 404 page. Would you know where the issue might be?

thank you

**Comment by BobaWebDev** [comment]
Hi,

Try this solution https://github.com/stcr/subscribe-to-comments-reloaded/issues/631#issuecomment-780056837
