### ISSUE TITLE
Bug Report: Email Notifications are not being sent after update to WP 5.6.2.

### ISSUE THREAD

**Issue by tedgeving** [stcr/subscribe-to-comments-reloaded#637]
After upgrading to WP 5.6.2. Email Notifications are not being sent when a new post is published.  Currently using a Yahoo Email account to send the mail through. Not sure it's due to the update or something with the Yahoo Mail servers.

**Comment by BobaWebDev** [comment]
Hi @tedgeving 

Can you install [WP Mail Logging](https://wordpress.org/plugins/wp-mail-logging/) plugin and run a test (to trigger a notification to be sent) and then check the mail log (WP admin > Tools > WP Mail Log) to see if that email is logged and what the status of it is.

Let me know what happens so we can figure out how to proceed.

**Comment by tedgeving** [comment]
Here you go, I don't think it is a problem with plugin.

Time:
2021-03-25 17:59:21
Host:
127.0.0.1
Receiver:
ted@iterative.consulting
Subject:
There is a new comment to Have You Seen these Tiny Twig Nests for Sweet Wows?
Message:
<html><head><title>There is a new comment to Have You Seen these Tiny Twig Nests for Sweet Wows?</title></head><body><p>There is a new comment to Have You Seen these Tiny Twig Nests for Sweet Wows?.<br /> Comment Link: https://doodlet.me/2021/03/have-you-seen-these-tiny-twig-nests-for-sweet-wows/#comment-6248<br /> Author: Jeanne Cameron Washburn<br /> Comment:<br /> Thanks. Got it!<br /> Permalink: https://doodlet.me/2021/03/have-you-seen-these-tiny-twig-nests-for-sweet-wows/<br /> Manage your subscriptions: https://doodlet.me/comment-subscriptions/?srek=5bfe6ec42ca9893b58edba3e4ade029b&srk=da4565b311c3864c9596c09b5dcb5fa7</p> </body></html>
Headers:
Content-Type: text/html; charset=UTF-8 From: "Doodle T" <doodletllc@yahoo.com> Reply-To: doodletllc@yahoo.com X-Post-Id: 22664 X-Comment-Id: 6248
Attachments:
Error:

**Comment by BobaWebDev** [comment]
Hi @tedgeving 

Since it shows up in there it means that the "request to email" is made.

And if no errors show up (based on what you sent there are no errors) then the request to email was successful.

In that case if an email does not arrive then it's most likely blocked by the email hosting provider. 

For sending the emails, try switching to a different address instead of the Yahoo one.

**Comment by tedgeving** [comment]
Thanks,
That's what I was thinking. You can go ahead and close out this ticket.

**Comment by BobaWebDev** [comment]
You're welcome.
