### ISSUE TITLE
Bug Report: Subscription emails shown in WP mail log as sent but not being received by users

### ISSUE THREAD

**Issue by jfmoore** [stcr/subscribe-to-comments-reloaded#644]
I hope you can help, on our site madinameria.com we have had a number of people reporting that they have stopped receiving comment notifications. 

We have installed WP Mail log which shows the mails being sent but they are not being received, I have verified this myself using three different email accounts, WP mail log shows and email as sent but it never arrives. 

We are using Wordpress version 5.4.5 and version 210315 of the plugin. Thanks in advance for your assistance.

**Comment by BobaWebDev** [comment]
Hi @jfmoore 

If WP Mail Log shows the entry and does not show an error for it then the most likely issue is that for some reason the hosting provider stops the email from being sent.

Do other emails from that WordPress install work fine? Like a contact form for example.

If those emails get through but the ones from our plugin don't, it's definitely blocked by the server. In which case you need to access the control panel (for the hosting) and check the "mail error logs". In case you're not sure where to find that, contact the support for the hosting, they'll help out with that.

**Comment by jfmoore** [comment]
Thank you BobaWebDev, your advice pointed us to finding a rogue plugin that was causing this issue so we are now working again as we should. Thank you so much for your help.

**Comment by BobaWebDev** [comment]
You're welcome @jfmoore, happy to hear it's sorted out.
