### ISSUE TITLE
Set all past subscribers to reply only

### ISSUE THREAD

**Issue by silverboxdev** [stcr/subscribe-to-comments-reloaded#652]
We have almost 9,000 subscribers on a site that we're working on and the system is sending out thousands of emails a day due to so many subscribers being notified. Is there a way to set all past subscribers (we can only see 1,000 in the view there) to "reply only". That would be huge. I can't find where this setting is in the Database or a setting to fix this in the WP Admin. Thanks

AD

**Comment by BobaWebDev** [comment]
Hi @silverboxdev 

This SQL query would switch them over to replies only.

`UPDATE wp_postmeta SET meta_value = REPLACE( meta_value, '|Y', '|R') WHERE meta_key LIKE '_stcr@_%'`

Before you use it, make a backup of the database just in case.

**Comment by silverboxdev** [comment]
Thank you @BobaWebDev - that was what we needed and officially fixed our issues. Thanks for the extra help there!

AD

**Comment by BobaWebDev** [comment]
You're welcome.
