### ISSUE TITLE
"Error: You entered an incorrect CAPTCHA answer"

### ISSUE THREAD

**Issue by scrybbler** [stcr/subscribe-to-comments-reloaded#655]
Getting this all the time now. No CAPTCHA is being displayed.
Tried installing reCaptcha v2 checkbox; it never displayed, same error. Tried reCaptcha v2 invisible; same error.
Turned off reCaptcha; same error.
Turned on challenge question; never displayed; same error.
Turned on StCR Position with challenge question; never displayed; same error.

**Comment by scrybbler** [comment]
Sorry, frustrated and it looks like my frustration was misdirected. Still troubleshooting but I assume this is my problem because I also have AIOWPSecurity installed.

https://gvectors.com/forum/wpdiscuz-comment-plugin-support/error-you-entered-an-incorrect-captcha-answer/

**Comment by BobaWebDev** [comment]
Hi @scrybbler 

Did the solution mentioned there work out for you?

**Comment by scrybbler** [comment]
Yes it did!
