### ISSUE TITLE
Auto responses not working

### ISSUE THREAD

**Issue by Carlos-Blanco** [stcr/subscribe-to-comments-reloaded#657]
I have been trying but the auto response don´t work.

[https://blog.saludonnet.com/que-consecuencias-tiene-la-extirpacion-de-la-vesicula-biliar/#comment-1629](https://blog.saludonnet.com/que-consecuencias-tiene-la-extirpacion-de-la-vesicula-biliar/#comment-1629)

**Comment by BobaWebDev** [comment]
Hi @Carlos-Blanco 

The subscribers don't receive an email on new comments?

Can you install the plugin [WP Mail Logging](https://wordpress.org/plugins/wp-mail-logging/), it catches all outgoing emails and their status. That way we'll know if an error occurred sending the email or if it was sent successfully but for some reason it was stopped by your server.

After the plugin is activated make a test comment to one of the subscribers and then check the mail log to see if it's in there and if it shows any errors.
