### ISSUE TITLE
Bug Report: Confirmation Emails Not Sending

### ISSUE THREAD

**Issue by TugT4G** [stcr/subscribe-to-comments-reloaded#659]
Hi,

I found out that a confirmation email is not sending to the user's email so I tried it myself.

Two separate times I signed up to comments on two different posts and I never received an email. I then manually approved them and commented on the same posts and there still was no email.

How do I go about fixing this?

Thanks and regards,

Tug

**Comment by TugT4G** [comment]
So I found out that it has to do with something about WP Rocket. Cloudflare doesn't seem to inflict any issues. Sorry about that.

I excluded the manage-subscriptions page from WP Rocket's cache and it works fine now.

**Comment by BobaWebDev** [comment]
Happy to hear it's sorted out.
