### ISSUE TITLE
Management page doesn't work with Genesis

### ISSUE THREAD

**Issue by jmorti** [stcr/subscribe-to-comments-reloaded#668]
So, the virtual management page broke on my site and the static page is not compatible with Genesis. Any ideas? Thanks.

**Comment by BobaWebDev** [comment]
Hi @jmorti 

I tried out the static page approach with Genesis and it's working fine. You have `[stcr_management_page]` shortcode added in the content for that page, correct? What do you see when you visit the page?

**Comment by jmorti** [comment]
The instructions provided online didn't say anything about the shortcode. I
got it to work after figuring that out but you might want to add it to the
documentioan.
