### ISSUE TITLE
Subscribers miscount and not receiving email 

### ISSUE THREAD

**Issue by a3vd** [stcr/subscribe-to-comments-reloaded#669]
I have a strange issue with subcribers , when i query the database i get  a total of 638 users which are subcribed 
and in the backend there are only 376 user subrscribed :-(

The qry i used is SELECT * FROM wp_postmeta WHERE meta_key LIKE '\_stcr@\_%'   results are 638 users (and yes all with a Y )

Attached screenshot of the backend and the result of the QRY
![stcr](https://user-images.githubusercontent.com/29863575/140326280-ad2e80d6-f771-448d-89cd-f13c2269303f.jpg)
![stcr1](https://user-images.githubusercontent.com/29863575/140326284-a81fd82b-8dc9-4a2b-9778-cc1a3127a2fa.jpg)

**Comment by BobaWebDev** [comment]
Hi @a3vd 

How many do show up in the system information?

![image](https://user-images.githubusercontent.com/4485586/140380334-3a83edc7-76cb-407b-85cc-bf793e149dae.png)

The first part under "System Information" shows amount of subscribers and amount of subscriptions. 

It's basically the same query as the one you used but just to be sure, how much does it show there?

**Comment by a3vd** [comment]
![image](https://user-images.githubusercontent.com/29863575/140393106-9a77b5d6-9502-43c5-b79c-7d6b5c0097b6.png)

**Comment by a3vd** [comment]
Problem is solved my mistake, through a QRY i assigned users to the posts but i forgot to assign the "new" users to the subscribe_reloaded_subscribers my fault sry

**Comment by BobaWebDev** [comment]
Yeah, seemed a bit odd with 49 subsribers and 600+ subscriptions :) Happy
to hear it's sorted out.
