### ISSUE TITLE
PHP Errors, Warnings and Notices disappear into black hole when plugin is active

### ISSUE THREAD

**Issue by JakeQZ** [stcr/subscribe-to-comments-reloaded#675]
See https://wordpress.org/support/topic/trigger_error-does-not-work-when-plugin-active/

This is a serious bug.  It means that any website errors or issues will go unnoticed.

The problem seems to be that the custom logging of errors is controlled by an option, but that the custom error handler (*replacing* the default) is set up regardless of the value of this option.  When asked to log an error it checks the value of the option (default: disabled) and then does nothing.

**Comment by JakeQZ** [comment]
Having commented-out `set_error_handler( array( $this, 'exceptions_error_handler' ) )` in `stcr_utils::__construct()`, I now see there are several other warnings and notices I need to look into that I had no idea about :(

**Comment by BobaWebDev** [comment]
Hi @JakeQZ 

I'm sorry for the inconvenience.

Thank you for bringing it to our attention. We'll release an update ASAP to get rid of that, it's not even needed, should have removed that when the plugin was acquired.

**Comment by JakeQZ** [comment]
> We'll release an update ASAP to get rid of that

Just seen there's a new release which appears to resolve the issue.  I'm impressed by the quick turn-around!
