### ISSUE TITLE
Manage Subscriptions page link leads to 404

### ISSUE THREAD

**Issue by afloodtpv** [stcr/subscribe-to-comments-reloaded#681]
Hi there,

I've noticed that the subscription management page on my site has a 'Manage Subscriptions' link that then leads to a 404, leaving readers unable to unsubscribe from a post. This is the page:

https://thepeskyvegan.com/comment-subscriptions/

I'm pretty sure everything was working fine up until now, so I'm not sure why it's now an issue. As you can understand, it's a bit of a problem if readers wanting to unsubscribe from future comments on posts keep getting emails about new ones!

Do you know what might be causing this?

Thanks,
Alistair

**Comment by BobaWebDev** [comment]
Hi @afloodtpv 

Try the following:

- Go to WP Admin > StCR > Management Page
- Set “Virtual management page” to “No” and save changes
- Go to WP admin > Pages > Add New and create a page called Comment subscriptions, the permalink should be comment-subscriptions
- For the content of the page add [stcr_management_page]

**Comment by afloodtpv** [comment]
Thanks so much, seems to be working fine now!

**Comment by BobaWebDev** [comment]
You're welcome.
