### ISSUE TITLE
Notification email going to spam

### ISSUE THREAD

**Issue by sajidch7890** [stcr/subscribe-to-comments-reloaded#686]
when subscribers get notification about reply on their comment, the mail is going to spam folder. though i already setup Wpmail smtp by Gmail.

**Comment by BobaWebDev** [comment]
Hi @sajidch7890 

Can you send over the URL to the site, I'll give it a try and see if the notification I receive gives me any idea as to why it might end up in spam.

**Comment by BobaWebDev** [comment]
I left a comment on one of the posts, approve it and then can you just make some reply to it so I receive a notification about it.

**Comment by BobaWebDev** [comment]
I got a notification of a new comment, but it did not go to spam.

Do your notifications go to spam?

**Comment by BobaWebDev** [comment]
Got the new notification as well. Happy to hear it's working fine now.
