### ISSUE TITLE
Bug Report: <The page to admin subscription doesn't work and throws 404 error>

### ISSUE THREAD

**Issue by antimatterES** [stcr/subscribe-to-comments-reloaded#690]
Hi there,
The page to admin subscription doesn't work and throws 404 error.
It was working when I installed the plugin several years ago, but not sure when started to fail.
I did not change nothing in the configuration, so I understand it was something that happen when I update the plugin.
Could you be kind to help me on this?

Thanks in advance!

**Comment by mebishalnapit** [comment]
Could you follow the instructions as stated over here: https://github.com/stcr/subscribe-to-comments-reloaded/issues/681 and see if it helps you out as well?

**Comment by antimatterES** [comment]
Hi Bishal,
It seems the solution solved my issue as well.
Thank you so much!

*Alberto Quintero*
Koala Studios
c/ Roger-25-27, 2ºB
08028 Barcelona
+34 686 96 13 13
+34 935 417 803

------------------------------------------------------------------------------------------------------------------------------------------
