### ISSUE TITLE
Check box not appearing on front end

### ISSUE THREAD

**Issue by RLSDev** [stcr/subscribe-to-comments-reloaded#694]
I tried adding this to CSS but not helping. I am using a staging site, but that shouldn't be an issue, should it? 

label[for=subscribe-reloaded] {
display:block !important;
}

Also, all my members log in as the same user on my website. I need for them to be able to subscribe with their own email, even if they are logged in as my membership user. The option to add name and email disappear once they are logged in as the membership user. Is there a solution?

Thanks for advisement.

Robin

**Comment by mebishalnapit** [comment]
If you want to do so then, please visit `Appearance -> StCR -> Manage subscriptions` section from your WordPress dashboard. There you will find the button labelled as `Add New Subscription`. Now, click on this button and fill the required options there. After this process is done, those new emails added will be subscribed to the required posts/pages of your liking.

**Comment by RLSDev** [comment]
Thank you, but the checkbox does not appear  can you advise?

**Comment by mebishalnapit** [comment]
Is the checkbox option not appearing to those users only who are the post authors? If it is the case then, could you visit `Appearance -> StCR -> Options` section and then, enable `Subscribe authors` option from there and see if this helps you to resolve the issue?

**Comment by mebishalnapit** [comment]
Also, please check if `Show StCR checkbox / dropdown` is enabled or not in `Appearance -> StCR -> Options` section options page. If it is not enabled then, can you enable it and see if that helps?

**Comment by RLSDev** [comment]
Thanks for the help! Okay now the checkbox appears. My issue is that my posts that need to have comment subscriptions are all behind 1 general login/user. Each person has to login with that one/single account in order to even see the posts. So they are already logged in. at that point the subscription gets set for that general account/user. I need them to be able to subscribe by supplying a different email (not the one they are logged in as). If they are logged in already, the cannot subscribe using a different/custom email. Is there a way to enable that behavior?

Thanks again!

Robin

**Comment by RLSDev** [comment]
In other words, I need the subscription to work like this, even if the user is logged into the one general member account. We don’t have user accounts for every single member, but they all log in using the one account order  to even see the posts that we need subscriptions for. The non-logged in public cannot see these posts and comments are not enabled on posts on the non-logged/public front end:

**Comment by BobaWebDev** [comment]
Hi @RLSDev 

Unfortunately that is not possible at the moment, multiple people using the same WordPress account is not a typical scenario. We'll see what can be done, it involves a larger amount of work to make that possible but it's not something that would benefit a larger amount of the users (I think this is the first time this scenario was mentioned) so I can't promise anything at this point. Sorry.
