### ISSUE TITLE
Subscribe and Manage Links going to 404

### ISSUE THREAD

**Issue by northee** [stcr/subscribe-to-comments-reloaded#697]
If I click "subscribe" it takes me to a 404 page. If I'm logged in and click "manage" it also takes me to a 404 page.

**Comment by mebishalnapit** [comment]
Could you follow the instructions as stated over here: https://github.com/stcr/subscribe-to-comments-reloaded/issues/681 and see if it helps you out as well?

**Comment by BobaWebDev** [comment]
Hi @northee 

The update released today should fix that problem. Can you give it a try and let us what happens?

**Comment by northee** [comment]
I followed the instructions And it worked.

**Comment by northee** [comment]
Update: there was a plugin update today, I updated the plugin and now the end of all my posts have this;

```
Warning: in_array() expects parameter 2 to be array, bool given in /home/customer/www/outdoordogworld.com/public_html/wp-content/plugins/subscribe-to-comments-reloaded/wp_subscribe_reloaded.php on line 1540

Warning: array_flip() expects parameter 1 to be array, bool given in /home/customer/www/outdoordogworld.com/public_html/wp-content/plugins/subscribe-to-comments-reloaded/wp_subscribe_reloaded.php on line 1544

Warning: in_array() expects parameter 2 to be array, null given in /home/customer/www/outdoordogworld.com/public_html/wp-content/plugins/subscribe-to-comments-reloaded/wp_subscribe_reloaded.php on line 1547
```
I've disabled the plugin for now.

Any help would be appreciated.

**Comment by mebishalnapit** [comment]
Can you visit `StCR -> Options` section and just save the changes and see if that helps you to resolve this issue?

**Comment by demcorp** [comment]
The workaround worker for me. Thanks.

**Comment by northee** [comment]
That appears to have worked. In addition I've gone back to using a virtual management page, is that correct?

**Comment by mebishalnapit** [comment]
@northee If you are using the latest version of the plugin then, yes, you can use the virtual page for the comments subscription management in your site.
