### ISSUE TITLE
Breaks html validation to due unescaped ampersand

### ISSUE THREAD

**Issue by Reedyseth** [stcr/subscribe-to-comments-reloaded#70]
> @justin_k
> 
> This plugin inserts a link for non-logged-in-users like:
> 
> subscribe without commenting.
> 
> Because it doesn't escape the ampersand, this breaks html validation: http://screencast.com/t/1wI2S5iYBwQ
> 
> I'm using the latest version (140515).

Reported here: https://wordpress.org/support/topic/breaks-html-validation-to-due-unescaped-ampersand?replies=8

**Comment by Reedyseth** [comment]
@justin_k

There was a fix for this issue, option was not decode correctly, the fix is here on this commit 92294e44a0b5a4bd0246689eedb3844ecda7d2b2. Now you only need to update you database Author Label Option, since there is already garbase store into your option value you first need to clean it up.

To complete this go to the options that is causing issuesm, on this case I will use Author label on the `Comment Form` tab.

![002](https://cloud.githubusercontent.com/assets/1228711/5967398/d41af83e-a7c9-11e4-9f95-ce1e2de05036.png)

1. Just the value.
2. Save an empty value.
3. After your changes are saved paste your copied value.
4. Save again.

Now you Manage subscription script should work, if not please let me know.

**Comment by metal450** [comment]
No, that didn't fix it.  Also, you can see from the screenshot I provided that the issue would be with the default label, not the author label (the validation service would never be able to see the author label). 

Following your instructions for the default label (saving blank, then re-saving original) also did not fix it.

**Comment by Reedyseth** [comment]
> No, that didn't fix it. Also, you can see from the screenshot I provided that the issue would be with the default label, not the author label (the validation service would never be able to see the author label).
> 
> Following your instructions for the default label (saving blank, then re-saving original) also did not fix it.

Alright, then I will take a look later on the day.

**Comment by Reedyseth** [comment]
I have the fix committed fef4bfa17b8de0dd9b9f76963b24a3accf9be66c and it will be ready on WordPress on the next release, on the meantime you can download the changes to your site and validate on W3.

**Comment by metal450** [comment]
Confirmed: It seems to be fixed :)

**Comment by peterolle** [comment]
Cut, save blank, paste and save again fixed it for me.

**Comment by Reedyseth** [comment]
By the way guys, con the next update this wil be done automatically so that you don't have to do this again.
