### ISSUE TITLE
Bug Report: Latest Update Issue

### ISSUE THREAD

**Issue by ThisHealthyKitchen** [stcr/subscribe-to-comments-reloaded#703]
I updated the plugin yesterday and my website layout didn’t look right. Every post looked zoomed out and words and images were cut off the page. Once I disabled this plugin, it fixed the layout immediately.

I looked in the WordPress logs and found this error, can you please take a look?

[03-May-2022 12:53:33 UTC] PHP Fatal error:  Uncaught TypeError: in_array(): Argument #2 ($haystack) must be of type array, bool given in /var/www/html/wp-content/plugins/subscribe-to-comments-reloaded/wp_subscribe_reloaded.php:1540
Stack trace:
#0 /var/www/html/wp-content/plugins/subscribe-to-comments-reloaded/wp_subscribe_reloaded.php(1540): in_array()
#1 /var/www/html/wp-includes/class-wp-hook.php(309): stcr\wp_subscribe_reloaded->subscribe_reloaded_show()
#2 /var/www/html/wp-includes/plugin.php(189): WP_Hook->apply_filters()
#3 /var/www/html/wp-includes/comment-template.php(2722): apply_filters()
#4 /var/www/html/wp-content/themes/genesis/lib/structure/comments.php(470): comment_form()
#5 /var/www/html/wp-includes/class-wp-hook.php(307): genesis_do_comment_form()
#6 /var/www/html/wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters()
#7 /var/www/html/wp-includes/plugin.php(474): WP_Hook->do_action()
#8 /var/www/html/wp-content/themes/genesis/lib/structure/comments.php(96): do_action()
#9 /var/www/html/wp-includes/class-wp-hook.php(307): genesis_do_comments()
#10 /var/www/html/wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters()
#11 /var/www/html/wp-includes/plugin.php(474): WP_Hook->do_action()
#12 /var/www/html/wp-content/themes/genesis/comments.php(36): do_action()
#13 /var/www/html/wp-includes/comment-template.php(1556): require('...')
#14 /var/www/html/wp-content/themes/genesis/lib/structure/comments.php(33): comments_template()
#15 /var/www/html/wp-includes/class-wp-hook.php(307): genesis_get_comments_template()
#16 /var/www/html/wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters()
#17 /var/www/html/wp-includes/plugin.php(474): WP_Hook->do_action()
#18 /var/www/html/wp-content/themes/genesis/lib/structure/loops.php(154): do_action()
#19 /var/www/html/wp-content/themes/genesis/lib/structure/loops.php(38): genesis_standard_loop()
#20 /var/www/html/wp-includes/class-wp-hook.php(307): genesis_do_loop()
#21 /var/www/html/wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters()
#22 /var/www/html/wp-includes/plugin.php(474): WP_Hook->do_action()
#23 /var/www/html/wp-content/themes/genesis/lib/framework.php(66): do_action()
#24 /var/www/html/wp-content/themes/genesis/single.php(15): genesis()
#25 /var/www/html/wp-includes/template-loader.php(106): include('...')
#26 /var/www/html/wp-blog-header.php(19): require_once('...')
#27 /var/www/html/index.php(17): require('...')
#28 {main}
  thrown in /var/www/html/wp-content/plugins/subscribe-to-comments-reloaded/wp_subscribe_reloaded.php on line 1540

**Comment by BobaWebDev** [comment]
Can you visit `StCR -> Options` section and just save the changes and see if that helps you to resolve this issue?

**Comment by ThisHealthyKitchen** [comment]
Deactivating the plugin and reactivating it corrected the layout issues.

However, now the check box to subscribe to replies is gone. I tried deselecting in the options and saving. Then selecting again and saving. This hasn't corrected the issue.

**Comment by ThisHealthyKitchen** [comment]
Nevermind! Clearing the cache resolved this issue as well.
