### ISSUE TITLE
Default subscription type isn't respected when Advanced subscriptions is enabled

### ISSUE THREAD

**Issue by rghedin** [stcr/subscribe-to-comments-reloaded#708]
I just enabled Advanced subscriptions in [my site](https://manualdousuario.net/), and selected “Only replies to my comments” as the default option, but in comment form it shows “Do not subscribe” as default.

I'm running WordPress 5.9.3 and StCR 220502.

**Comment by AndreiSPBR** [comment]
Same here, but we are running WordPress 6.0 and Subscribe to Comments Reloaded 220523. Could you help us, please?

**Comment by rghedin** [comment]
> Same here, but we are running WordPress 6.0 and Subscribe to Comments Reloaded 220523. Could you help us, please?

Do you have any cache in place? It took some time, but eventually the form was updated accordingly to my configuration.
