### ISSUE TITLE
who sends a comment does not receive an email

### ISSUE THREAD

**Issue by taamu** [stcr/subscribe-to-comments-reloaded#715]
Hello
I installed a plugin, but for some reason anyone who sends a comment does not receive an email.
[I as a manager, have always received an email when a comment was written in a post, and I still continue to receive, the problem being that the commenter does not receive an email].
Thanks

**Comment by mebishalnapit** [comment]
Could you install the plugin [WP Mail Logging](https://wordpress.org/plugins/wp-mail-logging/), which can catch all outgoing emails and with their status. That way we'll know if an error has occurred on sending the email, or if it was sent successfully but for some reason it was stopped by your server.

After the plugin is activated, you can make a test comment to one of the subscribers and then check the mail log to see if it's in there and if it shows any error.

**Comment by taamu** [comment]
Thanks, I got along
