### ISSUE TITLE
Manage Subscriptions Links Overwriting Sidebar Links

### ISSUE THREAD

**Issue by labsrc** [stcr/subscribe-to-comments-reloaded#723]
I noticed that multiple Manage Subscriptions links are overwriting widget links I have in my sidebar.  This happens on the comment-subscription page.  Is there a way to prevent this behavior.

**Comment by mebishalnapit** [comment]
This issue might be caused due to the `Virtual Management Page` enabled for comment subscriptions management page. So, please give a try to the solution mentioned here: https://github.com/stcr/subscribe-to-comments-reloaded/issues/681 and see if that helps.

**Comment by labsrc** [comment]
Thanks for the help.  Turning off the Virtual Management Page and creating a static subscriptions page has fixed the issue.
