### ISSUE TITLE
Google reCaptcha Not Working

### ISSUE THREAD

**Issue by labsrc** [stcr/subscribe-to-comments-reloaded#724]
I tried enabling the Google reCaptcha v3 option, but I'm getting an Invalid Key Type error.  When inspecting the page, I noticed an error with the script that's being used which has unnecessary paragraph and line break tags included.

I've already tried removing them by adding `remove_filter( 'the_content', 'wpautop' );` to my functions.php, but this seems to have no effect and the tags are still there.  I'm not sure if this is the cause of the reCaptcha error, but all signs seem to point to it.

**Comment by mebishalnapit** [comment]
We will be fixing this issue in the upcoming version update of the plugin. However, if you want it to get solved now then, try this solution: https://github.com/stcr/subscribe-to-comments-reloaded/pull/726 and see if it helps.

**Comment by labsrc** [comment]
I tested out the fix and it appears to work.  I'm no longer getting a reCaptcha error on the page.
