### ISSUE TITLE
Subscription Page is Indexed on Google

### ISSUE THREAD

**Issue by brianbillopiyo** [stcr/subscribe-to-comments-reloaded#735]
I'm very frustrated to see [comment page](https://opwellforex.org/comment-subscriptions) appear on Google search even though code <meta name='robots' content='noindex,nofollow'> is added to the header.

I cannot edit the page traditional because it's a virtual page. How do I prevent search engines from indexing this page?

**Comment by BobaWebDev** [comment]
Hi @brianbillopiyo 

Sorry about that and thanks for reporting the issue.

We'll release an update (today or tomorrow) to resolve the issue.

**Comment by brianbillopiyo** [comment]
Thank you for the update.
