### ISSUE TITLE
Bulk email generated when site gets scraped by a bot

### ISSUE THREAD

**Issue by Tyler-Ward** [stcr/subscribe-to-comments-reloaded#745]
I have had the situation a few times where the plugin generates large volumes of email (in the most recent case over 1500 emails). This looks to be due to some bot (which appears to be deliberately malicious based on the SQL fragments in its one other request that wasn't just a post to the /comment-subscriptions/ url) performing bulk posts to the /comment-subscriptions page. Previously recapture wasn't enabled but this has been enabled after the last time and was in place when the issue occurred this time.

The emails generated by this issue look to be only being sent to the wordpress admin email and not to any other locations. Also of note is that the to field is blank. In addition the url in the email looks to be missing some of the parameters that are present in a normal email when I tried testing it normally, the srek field is empty and the post_permalink field is missing.

Access Log reports from the container running wordpress

```
wordpress_1  | ***.***.***.*** - - [06/Nov/2022:22:35:57 +0000] "POST /comment-subscriptions/ HTTP/1.1" 200 9231 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/534.24 (KHTML, like Gecko) Ubuntu/10.10 Chromium/12.0.703.0 Chrome/12.0.703.0 Safari/534.24"
```

Le me know if there is any other information I can provide that will assist in locating what is going wrong here.

**Comment by BobaWebDev** [comment]
Hi @Tyler-Ward 

Which of the notification emails are you getting? 

By default just the `/comment-subscriptions/` shows a form for requesting a link (to be sent to the email address) to manage subscriptions. Are those the emails you are getting?

By default it's just a form and bots can submit it, but there are option to turn on Google reCAPTCHA or add a challenge questions/answer if you prefer not to use reCAPTCHA.

The options are in WP admin > StCR > Options. 

![image](https://user-images.githubusercontent.com/4485586/200278096-1996e8a4-026d-4e67-ae27-67124012a897.png)

**Comment by Tyler-Ward** [comment]
I am getting the following content in the email. have blanked out the srk value as I am not sure if that contains anything sensitive

```
You have requested to manage your subscriptions to the articles on The blog of Tyler Ward (aka scorpia). Follow this link to access your personal page:
https://www.scorpia.co.uk/comment-subscriptions/?srek=&srk=****************************&srsrc=e
```

My settings are as follows

![image](https://user-images.githubusercontent.com/3390465/200396259-7be29152-b20e-405e-bd47-c0b055be0d66.png)

The emails don't seem to have a to address and are missing some of the URL values so I assume they are not submitting the usual expected form contents.

**Comment by Tyler-Ward** [comment]
I have had a look and I don't see any emails generated since my previous tests. Also sent myself a valid subscription management link so emails are being generated correctly. (Note: Currently emails are being held on the server using the mailhog tool so don't automatically send outbound)

**Comment by BobaWebDev** [comment]
Hi @Tyler-Ward 

The "To" is empty and you are receiving the email as the "BCC", right? You have the "BCC admin on notifications" setting enabled (WP admin > StCR > Options)?

So whatever is being put into the form as the email address passes the email validation check and the check if the email address is a subscriber, but somehow ends up blank.

There's some additional sanitization done on the email address when the generation of the email contents is done. That must be where the value supplied is caught being incorrect and the email ends up with a blank "To".

We'll move that sanitization to be done a bit earlier so it gets caught before the system decides whether it should be sending an email.

We'll release an update this week.

How often does the bulk email issue happen?

**Comment by Tyler-Ward** [comment]
Thanks for looking into this.

That is correct I have the "BCC admin on notifications" setting enabled. That explanation sounds like a likely explanation.

Regarding timings It is fairly infrequent with the issue having been triggered on the following dates.
- 2022-02-26
- 2022-03-10
- 2022-06-23 (After this one I enabled recaptcha)
- 2022-11-06

Also for info I had a look at the recaptcha stats in the google dashboard and it shows very little activity on that day (most likely from my testing), not sure if that is useful info or not.

**Comment by BobaWebDev** [comment]
You're welcome and thank you.

Yeah, the recaptcha part is a bit weird, not entirely sure how that did not stop it, will look into that as well.

The update will be released this week but it might take a while until we know if it's working since there's such a big gap between the dates when the issue happened. And I'm not really sure how to replicate the behavior myself, but will try to figure it out.

**Comment by Tyler-Ward** [comment]
I have had a quick look at the captcha issue and spotted how it was being skipped. I have put the fix I found in #755.

**Comment by BobaWebDev** [comment]
Hi @Tyler-Ward 

At first look that does seem to be correct, thanks.

I'll test it out to confirm and the fix will be added in the next update.

**Comment by Tyler-Ward** [comment]
Just notied this was fixed in the 240119 release, Thanks for resolving, will also close the linked pull request
