### ISSUE TITLE
Version 150207 - links showing up on screen as html code 

### ISSUE THREAD

**Issue by Nickxyz** [stcr/subscribe-to-comments-reloaded#75]
I just updated to version 150207 and now all of the links (driven by shortcodes) are appearing on screen as html code, and are not clickable. 

Example (this is what the user sees on screen): 

<a href='http://www.mywebsite.com/comment-subscriptions/?srp=6710&srk='>manage the subscriptions</a> of this post.

**Comment by Reedyseth** [comment]
Can you share the link of your site please?

**Comment by Reedyseth** [comment]
By the way, @Nickxyz Can you go to the Settings and update the settings by clicking on each of the panels please. This is to clean what is store in you database.

**Comment by Nickxyz** [comment]
Hi Israel - The site is http://www.gettingtotruelove.com/

**Comment by Nickxyz** [comment]
Thanks Israel - I just went to each tab and clicked "update" or "save" and
it looks like it's now working great. That must have been the problem

Thanks for your help!

- Nick

**Comment by Reedyseth** [comment]
> Thanks Israel - I just went to each tab and clicked "update" or "save" and
> it looks like it's now working great. That must have been the problem
> 
> Thanks for your help!

No problem.
