### ISSUE TITLE
Error: Please fill in the correct answer to the security question!

### ISSUE THREAD

**Issue by johnric** [stcr/subscribe-to-comments-reloaded#757]
I have received a report from a regular commenter that his attempts to submit a comment have begun producing a pop-up with the following message:

Error: Please fill in the correct answer to the security question!
[Go Back]

A response to my [request on the WordPress forum](https://wordpress.org/support/topic/error-please-fill-in-the-correct-answer-to-the-security-question/) suggests that StCR is the origin of this message. My active plugins are listed in my request, as is the site in question.

I don't have challenge question or Google reCAPTCHA enabled.

Any advice or response will be appreciated.

**Comment by johnric** [comment]
This has turned out to be a problem with the No-Bot Registration plugin:
[https://wordpress.org/support/topic/a-lot-of-issues-suddenly/](https://wordpress.org/support/topic/a-lot-of-issues-suddenly/)

Sorry for the noise.

**Comment by BobaWebDev** [comment]
Hi @johnric 

Happy to hear you found the issue.
