### ISSUE TITLE
Haven't been getting email notifications for a while

### ISSUE THREAD

**Issue by podfeet** [stcr/subscribe-to-comments-reloaded#760]
Hi - I'm trying to figure out why I'm not getting notifications on my posts. I've always had the setting on to send emails to authors for all posts. I'm not sure when it quit working (maybe even six months?) I've even manually checked the box on a post to be notified of new posts and comments and still no emails.

I'm on WordPress 6.1.1 running Site Origin North as my theme.

I've checked spam/junk (boy I hate even looking at the titles in there!) and don't see anything.

I'll do any experiments you suggest. (btw, used the awesome CleanShot X to capture a scrolling screenshot)

![Allison subscribe to comments reloaded settings](https://user-images.githubusercontent.com/12651464/211207972-07c33399-7653-480d-961a-9c1e01981d6a.png)

**Comment by BobaWebDev** [comment]
Hi @podfeet 

Can you install [WP Mail Logging](https://wordpress.org/plugins/wp-mail-logging/) plugin.

It stores all the email requests your WordPress site processed.

Then make a test comment (one that should trigger a notification email) and check if it shows up there.

If it doesn't show up it means WP hasn't received the request from the plugin to send an email.

If it shows up but also shows an error, let me know what that error is.

If it shows up and no errors are shown then it was processed but something went wrong after that.

Let me know which one of those 3 happens and we'll figure out how to proceed.

**Comment by BobaWebDev** [comment]
Hi @podfeet 

No worries. Happy to hear you figured it out.

If you're getting "Could not instantiate mail function" then most likely (99.99%) no emails sent through WordPress would work, so it's not specific to our plugin.

The best approach would be to contact the hosting provider and ask why you are getting the error.

**Comment by podfeet** [comment]
> Hi @podfeet 
> 
> 
> 
> No worries. Happy to hear you figured it out.
> 
> 
> 
> If you're getting "Could not instantiate mail function" then most likely (99.99%) no emails sent through WordPress would work, so it's not specific to our plugin.
> 
> 
> 
> The best approach would be to contact the hosting provider and ask why you are getting the error.

Thanks so much for getting back to me, Bob. Again my huge apologies for my slow response to your awesome support. You can close this one out.

**Comment by BobaWebDev** [comment]
You're welcome Allison.
