### ISSUE TITLE
Where is “subscribe without comment” form?

### ISSUE THREAD

**Issue by rghedin** [stcr/subscribe-to-comments-reloaded#767]
Hi!

I activated the `Allow "Subscribe Without Comment"` option in StCR, but can't see this form whatsoever on [my blog](https://manualdousuario.net/).

Do I need to do some code change in my template to expose subscribe without comment in front-end?

**Comment by rghedin** [comment]
Thanks! I found this option right after posting this issue and forgot to update it 😬😄

**Comment by BobaWebDev** [comment]
You're welcome :)
