### ISSUE TITLE
“Don't subscribe” is defaulted even when other option is selected

### ISSUE THREAD

**Issue by rghedin** [stcr/subscribe-to-comments-reloaded#769]
Hi! It seems a bug made into StCR recently.

In [my blog](https://manualdousuario.net/), I allow advanced subscription and defaults it to “only replies to my comments” (it's in pt_BR, but I guess you can understand):

![Captura de Tela 2023-04-05 às 07 42 03](https://user-images.githubusercontent.com/19216581/230058491-bec53e4c-3ede-4f8e-b221-2cd5cfa7cbfc.png)

However, on front-end, comment form doesn't respect that default and shows “Don't subscribe” as the true default:

![Captura de Tela 2023-04-05 às 07 43 17](https://user-images.githubusercontent.com/19216581/230058609-47d530e1-3dbc-4f6b-bcb3-fd7b221cc5c9.png)

I haven't made any changes on options/config; a reader noticed and alerted me. Am I doing something wrong? Is this a bug?

**Comment by BobaWebDev** [comment]
Hi,

Managed to figure out how to replicate the issue.

If the "StCR Position" option is enabled it loses the default value.

![image](https://user-images.githubusercontent.com/4485586/230448371-e1b2b237-5004-4467-821d-59c58e4a8f2b.png)

We'll get that sorted out in the next update.

But that option is only meant to be used on older themes that don't handle the comments form in the standard way, can you try disabling it?

**Comment by rghedin** [comment]
That's it, @BobaWebDev! I have no idea why or when I enabled this option, but disabling it fixed the issue. Thanks!

**Comment by BobaWebDev** [comment]
You're welcome.
