### ISSUE TITLE
Exceptions for author's auto subscription 

### ISSUE THREAD

**Issue by rghedin** [stcr/subscribe-to-comments-reloaded#770]
Hi! In my blog, readers can publish posts alongside me. For this reason, I turned on that option that automatically subscribe authors to receive comments. It's great!

However, I (admin and the person who publishes the most) don't need it. Actually, I'd like to not receive email notifications at all, since it's unnecessary for me and it increases email costs quite a bit.

So I was wondering if would be possible to add exceptions to this “automatically subscribe authors”, since I do want to keep it for readers that publish, but not for myself.

Is it possible? Or is this option on your roadmap?

**Comment by BobaWebDev** [comment]
Hi @rghedin 

It's not possible at the moment, but a feature that lets you set a list of email addresses that will not receive notifications would be a good addition. 

I've added that to the to do list.

In the meantime, if you have some experience with editing code, I can tell you what to modify to make it skip your email address.

**Comment by rghedin** [comment]
Thanks, @BobaWebDev! I do have some experiencing, and I'd love to know that code.

**Comment by BobaWebDev** [comment]
Hi @rghedin 

In `wp_subscribe_realoded.php` on line 1459 starts the function called `notify_user`

That function handles sending the notification emails.

Line 1488 is this:

`$clean_email     = $this->utils->clean_email( $_email );`

After that we can check for a specific email address and stop executing the function if it matches the address.

So the code would look like this:

`$clean_email     = $this->utils->clean_email( $_email );
if ( $clean_email == 'name@example.com' ) return;`

Just replace the `name@example.com` with your email address.

**Comment by rghedin** [comment]
Great, @BobaWebDev! I just added the code. Thanks a lot!

**Comment by rghedin** [comment]
@BobaWebDev, I noticed that although your code stops StCR to send email notifications to the email informed, it's still registered (see image below).

I was wondering: if I make the same change in the function `add_subscription`, will it work? I mean, will the informed email stops being auto registered in StCR?

<img width="1133" alt="image" src="https://user-images.githubusercontent.com/19216581/231302974-ed4cf8cd-0f1d-4062-863e-d4f36c9d2b28.png">

**Comment by BobaWebDev** [comment]
Hi @rghedin 

Well this is interesting.

Went to check the code for the function that adds the subscriptions and saw this at the top:

`$has_blacklist_email = $this->utils->blacklisted_emails( $_email );`

So there is already an option to blacklist specific emails from being subscribed. I forgot we had that.

It won't stop the notifications if the email address has subscribed before being added to the list but it will stop future subscriptions.

In WP admin > StCR > Options, at the bottom is "Blacklisted emails" options. Add your email in there.

**Comment by rghedin** [comment]
Awesome, @BobaWebDev! Just added my email in Blacklisted field.

Thanks!

**Comment by BobaWebDev** [comment]
You're welcome @rghedin
