### ISSUE TITLE
Protocol error in management links

### ISSUE THREAD

**Issue by heikohaensge** [stcr/subscribe-to-comments-reloaded#778]
The automatically generated links under the comment form to manage subscriptions are missing the “:” in the protocol part. So the links look like `https//` instead of `https://`
How to get this working?

We are using Astra Theme and Elementor page builder, and Elementor’s comment widget.
Thanks in advance.

**Comment by BobaWebDev** [comment]
Hi @heikohaensge 

That part of the URL (the full `https://example.com/` part of the URL) is based on the URL you have set in **WP admin > Settings > General** for the **Site Address** option

Can you check that option, is everything ok there?

If it is, can you do a "request management link" and check if the URL that you receive via email is correct and let me know, that'll help me figure out how to proceed with the debugging process.

**Comment by heikohaensge** [comment]
Hi @BobaWebDev 
I checked the URL in WP admin > Settings > General for the Site Address option. It's set correctly.

So I wrote a test comment and subscribed for notifications checking the checkbox. After subscribing I get two links beneath the comment box. 
The link to 'edit my subscription' is correct. But the link to 'edit all subscriptions for this post' is wrong. The latter looks like this in HTML code: `http://https://example.com/comment-subscriptions/?srp=xxx&srk=xxx`
Same goes for the link to 'subscribe without posting a comment' if I didn't subscribe yet. Here too the link looks like this in the HTML code: `http://https://example.com/?srp=xxx&srk=xxx`

So I was not correctly reporting the issue in the first place. There is no missing “:” in the protocol part, but an additional prefix `http://` added to some links. 
I hope this helps. 
Regards

**Comment by heikohaensge** [comment]
Hi @BobaWebDev ,
already any ideas why the protocol of the links are changed into `http://https://` ?
Or how this bug could be traced down?
Regards

**Comment by heikohaensge** [comment]
Hi @BobaWebDev ,
finally I could find out why the protocol in some links appeared wrong!
In the "Messages for your visitors" section of the "Comment Form" plugin options page some links were set like this: 
<a href="http://[subscribe_link]">
or
<a href="http://[manager_link]">
This is only visible in TEXT mode of the editor fields, but not in their VISUAL mode. Argh!
Regards
