### ISSUE TITLE
Google claims personally identifiable information is being passed on

### ISSUE THREAD

**Issue by BackdoorSurvival** [stcr/subscribe-to-comments-reloaded#79]
I have just been informed that the "Subscribe to Comments" plugin is in violation of Google terms because it passes identifiable info to the Google Ad Network. Basically, I must change to something else or they will disable my ads. 

Is there some way to mask the email address of the subscriber?

**Comment by raamdev** [comment]
@BackdoorSurvival I've never heard of this before now. Do you have a copy of the notice from Google? I'd like to know exactly what they are referring to as being personally identifiable. 

The Subscribe to Comments Reloaded plugin just uses the existing WordPress commenting system to allow commenters to choose to receive notifications when a reply to their comment is made. The plugin doesn't expose any email addresses.

Some more information on what Google is indicating the problem is would be helpful.

**Comment by Reedyseth** [comment]
> I have just been informed that the "Subscribe to Comments" plugin is in violation of Google terms

Hello @BackdoorSurvival , Just to make sure, you mentioned `Subscribe to Comments` but our plugin is Subscribe to Comments **Reloaded**. Are we talking about the same plugin ?

**Comment by BackdoorSurvival** [comment]
Yes, sorry.  Subscribe to Comments Reloaded is what I use.

I can send you the email but I prefer to not to make it public.  Can I email it to you?

**Comment by BackdoorSurvival** [comment]
Also, the notice came from The Blogger Network.  They place Google Network Ads on my site,  Here is a screen shot.  They are claiming the email address is being passed on to the Google Ad Network.
![image](https://cloud.githubusercontent.com/assets/11183485/6360690/ef13179a-bc30-11e4-9e9c-0df1498805d3.png)

**Comment by Reedyseth** [comment]
@BackdoorSurvival To avoid using email address here use the folllowing contact form:

http://behstant.com/negocio/contact.php

**Comment by BackdoorSurvival** [comment]
I just cut and paste the email onto your contacts page.

**Comment by BackdoorSurvival** [comment]
Update: I went through the options again and saw that I could generate a security key.  I then had my ad network test and that appears to have solved the issue.

Thank you for responding so quickly.  I hope this will help someone else.

**Comment by Reedyseth** [comment]
@BackdoorSurvival I just read your email and although It seems to work you email address is pass on the URL, and this is what Google guys call **PII**, I will work to created a UUID instead of the email because this is threatening the user privacy.

Thank you for reporting it.

**Comment by BackdoorSurvival** [comment]
I just received another notice from Goggle.  Do you happen to know when this will be resolved?

**Comment by Reedyseth** [comment]
@BackdoorSurvival 

Since the creation of the plugin this was not an issue, but now that Google improve they privacy scanners they have this policy that you cannot have sensitive data on a link.

The main issue is that the email address is on the query string.

I am going to work on this to get the bug fix ASAP.

**Comment by foliovision** [comment]
Hi Seth,

We use your plugin on many sites and we need this fix very urgently as well. We'll take a look and see if we don't have some suggestions for you. Great that you have Subscribe to Comments Reloaded on GitHub.

Alec Kinnear

**Comment by Reedyseth** [comment]
Hello @foliovision ,

I am working on this fix, but it will require to change the structure of the plugin a bit, but this week it will be ready, I will notify here on the issue.

**Comment by solhuebner** [comment]
:+1:

**Comment by Reedyseth** [comment]
This fix is almost done, but before I release it I would like more users to test it, so please use the form on the following link to subscribe to the mailing list and be notify of the pre-release version.

http://eepurl.com/biCk1b

**Comment by dabesa** [comment]
@Reedyseth do you have any news on the fix?
I joined the newsletter but I didn't get any version to try.
Thanks!

**Comment by Reedyseth** [comment]
Hello @dabesa 

I am finishing some debugs on my code before you can start spotting more issues in the usage. If you want I can share the latest changes.
