### ISSUE TITLE
Management Page /?page_id=99999  NOT FOUND

### ISSUE THREAD

**Issue by Joaquim3** [stcr/subscribe-to-comments-reloaded#795]
Hello,

Thanks for this nice piece of work.

**My System :**

- WordPress Version -> 6.4.3
- STCR Version	by [WPKube] –> 240119

**My Issue :** 

- A user receives an email containing the following message : 
Please confirm your request by clicking on this link:
_https://mywebsite.com/?page_id=99999&srek=123&srk=456&srp=3640&sra=c&srsrc=e&confirmation_email=y&post_permalink=https://mywebsite.com/?p=3640_

But when the User clicks on the link There is a PAGE NOT FOUND.

**My Settings :**

- /Management Page /Virtual Page Management = Yes

Could you please give me some guidelines.
Kind Regards,🙂

**Comment by Joaquim3** [comment]
I found the answer here from WPKube 🙂🙂: **https://wordpress.org/support/topic/php-8-0-problem/**

1. Go to WP Admin > StCR > Management Page
2. Set “Virtual management page” to “No” and save changes
3. Go to WP admin > Pages > Add New and create a page called “Comment subscriptions”, the permalink should be comment-subscriptions
4. For the content of the page add [stcr_management_page]
5. In /Virtual Page Management/ change page_id=9999 by the ID of the new page
6. Don't forget to hide the page from the menus
🙂

**Comment by BobaWebDev** [comment]
Hi @Joaquim3 

Happy to hear you found the solution.

**Comment by pled** [comment]
Thank you for this ! it works fine.
