### ISSUE TITLE
Comment Subscription Confirmation Email Sends Errored Hyperlink

### ISSUE THREAD

**Issue by benoitellisclement** [stcr/subscribe-to-comments-reloaded#80]
One of my readers submitted screenshots to me from his mobile phone.

He had requested to receive email notification for replies to the comments on a particular post, and when he received the confirmation email asking him to click on the hyperlink to confirm, it created a "Cannot find page" error.

https://mail.google.com/mail/u/0/?ui=2&ik=87cc19e667&view=att&th=14bc74dc8aa6179c&attid=0.1&disp=safe&realattid=1494197617764577450-local0&zw

https://mail.google.com/mail/u/0/?ui=2&ik=87cc19e667&view=att&th=14bc74dc8aa6179c&attid=0.2&disp=safe&realattid=1494197617764577450-local1&zw

**Comment by Reedyseth** [comment]
Hello @benoitellisclement 

I think the links are only available on your account:

![image](https://cloud.githubusercontent.com/assets/1228711/6401448/b31867d4-bdbd-11e4-8757-049d0f29dbc5.png)

Can you share the screenshot here on the issue?

**Comment by benoitellisclement** [comment]
![screenshot_2015-02-26-13-59-10 1](https://cloud.githubusercontent.com/assets/11217768/6413787/bceb42f6-be60-11e4-9527-44e9b12145c9.png)
![screenshot_2015-02-26-13-59-17](https://cloud.githubusercontent.com/assets/11217768/6413788/bced72e2-be60-11e4-9497-cf95a0fd051b.png)

**Comment by Reedyseth** [comment]
@benoitellisclement 

Also, can you share your WordPress permalink setup on the `general > permalinks` settings as well as the ***Management URL*** of the Management Page tab of the plugin?

**Comment by benoitellisclement** [comment]
![permalink settings](https://cloud.githubusercontent.com/assets/11217768/6603460/b2d58e6a-c7f8-11e4-94e3-3680cc9d6984.png)
![screen shot 2015-03-11 at 2 12 03 pm](https://cloud.githubusercontent.com/assets/11217768/6603461/b2d69f4e-c7f8-11e4-86b4-01bfd23eb097.png)

**Comment by Reedyseth** [comment]
@benoitellisclement 

I see now, I recreated your permalink structure and `Management URL`. Please disable the `Virtual Management Page` and it should work.
