### ISSUE TITLE
I can manage subscribtions of anyone... Bug or feature?

### ISSUE THREAD

**Issue by Reedyseth** [stcr/subscribe-to-comments-reloaded#81]
Hello,

I'm using this great plugin but I'm wondering... why is it possible that I can manage any subscriber's subscriptions?

When I go to the manage page to request the management URL, I get a screen with the link to manage page immediately. Also an email is sent with the exact same message.

How is it possible that the URL to the manage page shows up whatever email (of an existing) subscriber I use? The link should only be sent by email so access is given exclusively by clicking on that link in the email.

Is this a bug or a feature?

Rick

Reported here: https://wordpress.org/support/topic/i-can-manage-subscribtions-of-anyone-bug-or-feature?replies=9

**Comment by ricksportel** [comment]
Thank you for moving my reported bug to GitHub.

**Comment by ricksportel** [comment]
Will it be solved in the next release?

**Comment by Reedyseth** [comment]
Yes, it is ready for the next release a6fcd41790fbe55fe40387cc614f577b63db5f73, some users are evaluating (https://github.com/stcr/subscribe-to-comments-reloaded/issues/79#issuecomment-88353228) all the changes before I release it next week.
