### ISSUE TITLE
Searching for subscriptions on the Manage Subscriptions page

### ISSUE THREAD

**Issue by antipole2** [stcr/subscribe-to-comments-reloaded#82]
The Manage Subscriptions page allows one to find subscriptions by email address with various matching criteria.

This works in most cases, but I find that if I use the _starts with_ criterion, it matches all records.  Bug?

Thanks for the good work.

**Comment by Reedyseth** [comment]
Hello @antipole2 ,

Let me check it out, I will try to reproduce that behavior !

**Comment by Reedyseth** [comment]
@antipole2 

FYI, I have found the bug and I am working on it.

**Comment by Reedyseth** [comment]
@antipole2 

I have solve the issue on this commit 5b74f00c280277c16ecfb146b5773b1c42cfe267. This will be available on the next release. Thank you for reporting it.
