### ISSUE TITLE
404 error Comment Subscriptions Error - Google Webmasters

### ISSUE THREAD

**Issue by benoitellisclement** [stcr/subscribe-to-comments-reloaded#83]
I'm curious to know if the 404 errors I'm receiving, might be correlated to the plugin. I've got over 100 crawl errors.

I've reported a previous issue about a possibly-related issue just recently.

![google webmasters crawl error screenshot](https://cloud.githubusercontent.com/assets/11217768/6603547/3917b174-c7f9-11e4-86b1-445ca5a2e558.png)

**Comment by Reedyseth** [comment]
@benoitellisclement 

At first sight what I see is that 404 error are to pages not found, so if Google indexed one of your pages using the srk value once that you regenerate a new unique key that reference will be lost.

You can verify that by going to those links. Check it out. If after validating those links you find a issue you can let me know.
