### ISSUE TITLE
Translation to cs_CZ 

### ISSUE THREAD

**Issue by danekee** [stcr/subscribe-to-comments-reloaded#85]
Hi!
I translated this plugin to cs_CZ and this is actulal release with few bugs in traslation fixed.
Heres the link (90 days from now it will work): http://wikisend.com/download/251660/translation-cs_CZ-subscribe-to-comments-reloaded.rar

**Comment by raamdev** [comment]
@danekee Thank you for contributing! I tried to download the file, but my computer says it's malicious. Could you create a zip file and upload it to https://cloudup.com instead?

**Comment by danekee** [comment]
Malicious? maybe on wiki something I google it for sharing... OK, cloud up tells me that they have limited users so i uploaded to http://uloz.to/xmX9QsDi/subscribe-reloaded-cs-cz-rar finally its stored till 30.april

**Comment by Reedyseth** [comment]
Hello @danekee ,

That link worked, you translation is now into StCR (70a64ce), thank you for your time and contribution.
