### ISSUE TITLE
Optimizing get_option calls

### ISSUE THREAD

**Issue by foliovision** [stcr/subscribe-to-comments-reloaded#86]
Hello,

is there any reason why this plugin initializes the wp_options rows with the autoload field set to "no"? It's in the _activate() function.

This means that when loading a single post there are around 8 SQL queries caused by this plugin. If it would use autoload, these options would load automatically during WP init.

Could you please adjust that and perhaps fix the autoload setting on plugin upgrade?

Thanks,
Martin

**Comment by Reedyseth** [comment]
Great Martin,

Thank you for dropping that issue here.

Regards.!!

**Comment by Reedyseth** [comment]
This issue is solved and it will be on the next release, see 4ef2465275dbc32dd580bc48dd78b81b0cd4a2bb.
