### ISSUE TITLE
Default subscribe checkbox doesn't show on site

### ISSUE THREAD

**Issue by protoolreviews** [stcr/subscribe-to-comments-reloaded#89]
After enabling the plugin with the "Enable default checkbox" selected and "Advanced subscription" set to 'No' I don't see an actual checkbox allowing me to subscribe to the comments.

Sample page:
http://www.protoolreviews.com/tools/outdoor-equipment/kobalt-40v-string-trimmer-hedge-trimmer/10872/

I've attached images below as well. 

I'm guessing it's a theme issue, but if it is, can you please help me in how to specifically word a request to my theme developer requesting an adjustment that will fix the problem? Hopefully this can help others who may have this issue or even result in a  more flexible way to code the plugin. I am using the Powermag theme by djwd.
![no subscription checkbox](https://cloud.githubusercontent.com/assets/5340139/7273996/164af55e-e8c7-11e4-97aa-befa4d06a57f.png)
![subscription management page](https://cloud.githubusercontent.com/assets/5340139/7273998/19492d7a-e8c7-11e4-8dab-77891ce1d3ef.png)

**Comment by Reedyseth** [comment]
Hello @protoolreviews 
Can you enable the plugin again?, looks like the html is broken.

**Comment by protoolreviews** [comment]
I just deactivated and reactivated it and it appears to be the same.
--
Clint DeBoer

**Comment by Reedyseth** [comment]
The problem is that if you don't enable it I can do much.

**Comment by protoolreviews** [comment]
It is completely enabled. That’s the problem. Though it is enabled, it’s not showing up.
--
Clint DeBoer

**Comment by Reedyseth** [comment]
@protoolreviews 

The issue is not part of the plugin, it is issues with your theme. You wrapped the plugin text with a label tag and the theme is displaying none to the labels.

![image](https://cloud.githubusercontent.com/assets/1228711/7277050/dd43ec8a-e8ca-11e4-9339-52e1ec9496ac.png)

**Comment by protoolreviews** [comment]
Israel,

My theme developer stated that per best practices, your plugin markup may be semantically wrong—the label tag should not wrap the input element. This is what’s causing the problem on our end with ti not showing up, thought it’s activated.

Is this something that might help you be more compatible with a greater number of themes?
--
Clint Everett DeBoer
www.ProToolReviews.com <http://www.protoolreviews.com/>

Professional tool reviews for the Average Pro!

Check us out on Facebook <http://www.facebook.com/protoolreviews> 
Follow us <http://twitter.com/#!/ProToolReviews> on Twitter



All information contained within this email is proprietary and confidential.

**Comment by Reedyseth** [comment]
Hello Clint,

The plugin does not wrap the input element into a label, this might be something in your **comment form** settings

![image](https://cloud.githubusercontent.com/assets/1228711/7322979/bc753924-ea68-11e4-926a-b0243f52c792.png)

Can you screenshot your **Comment Form** settings?
