### ISSUE TITLE
New database "subscribers' doesn't exist" errors from StCR Version 150422

### ISSUE THREAD

**Issue by antipole2** [stcr/subscribe-to-comments-reloaded#92]
Hi...

Suddenly getting database errors from StCR.  Site is http://mg30.antipole.co.uk with WordPress 4.1.3 running Attitude theme multisite.  Any help appreciated.

Tony

Edited to keep data safe.

**Comment by Reedyseth** [comment]
Hello Tony,

I have edited your message since it contains information about your database.

Some how the table wp_12_subscribe_reloaded_subscribers was not created on the update.

Can you deactivate and activate the plugin again ?"Make sure that your database user have permission to create tables.

**Comment by antipole2** [comment]
Thanks for responding.

StCR is not network activated, so I deactivated and reactivated at site level.  I have used phpMyAdmin to look for the table wp_12_subscribe_reloaded_subscribers and it does now exist and contains one entry for each different subscriber and has an add_date time stamp of when I reactivated the plugin.

So this looks OK?  I will wait and see if any further errors logged.

**Comment by Reedyseth** [comment]
Yes, the main problem was that when StCR was trying to run a query the table on database MySQL threw the error, so if the table is created you shouldn't face this error.

Now everything should be OK
